### ISSUE TITLE
感谢贤心

### ISSUE THREAD

**Issue by LouisYZK** [layui/layui#1002]
近日项目中想再用到layui时，搜索引擎已经找不到她，随后惊闻官网不再维护的消息。
去年此时，我还是一个实习生的时候，用layui完成了我六个月实习的总结。
那是一个涵盖数据表格、地图路线、实验交互的算法分析平台，大家纷纷惊讶于这样复杂繁多的功能如何在两周搞定。
一切都只因这个为后端选手使用的前端框架。第一次让我体会到了一个陌生的框架可以设计的如此得心应手。
感谢作者贤心，我早已在知乎的问题表达过支持，对不能维持的官网深感遗憾。江湖再见~

**Comment by Anryliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
