### ISSUE TITLE
如何使两个col自动同高？

### ISSUE THREAD

**Issue by cha0ran** [layui/layui#1005]
不知是有意为之还是bug，特来请教。

先上伪代码
```html
<div class="layui-row">
    <div class="layui-col-xs8">
        <p>111111</p>
        <p>222222</p>
    </div>
    <div class="layui-col-xs4">
        <p>333333</p>
    </div>
</div>
```

我的预期是当左侧col两行时，右侧的高度也会随左侧变成同样的高度，然后右侧内容使用 `vertical-align: middle;` 保持垂直居中，但现实中是右侧仅只有一行的高度，且尝试了各种方法都没办法让右侧高度随左侧相同。

还望指教，是我使用不对吗？

**Comment by richex-cn** [comment]
You can hug CSS flex layout.
