### ISSUE TITLE
数据表格点击禁用的单选框，依然可以取到值

### ISSUE THREAD

**Issue by imouze** [layui/layui#1008]
done:function(res,` curr, count){
    var data = res.data
    $.each(data, function (index, item) {
        if(!item.enable) {
            $('tr[data-index="' + index + '"] input[type=radio]').prop('disabled', 'disabled')
            $('tr[data-index="' + index + '"] input[type=radio]').next().addClass('layui-radio-disbaled layui-disabled');
        }
    })
}

表格渲染后，执行这个done，把表格中的单元格设置disabled
查看源码是
`//单选框选择
    that.elem.on('click', 'input[lay-type="layTableRadio"]+', function(){
      var radio = $(this).prev()
      ,checked = radio[0].checked
      ,thisData = table.cache[that.key]
      ,index = radio.parents('tr').eq(0).data('index');
      
      //重置数据单选属性
      layui.each(thisData, function(i, item){
        if(index === i){
          item[options.checkName] = true;
        } else {
          delete item[options.checkName];
        }
      });
      that.setThisRowChecked(index);
      
      layui.event.call(this, MOD_NAME, 'radio('+ filter +')', commonMember.call(this, {
        checked: checked
      }));
    });`

是不是没处理disabled的情况呢？还是需要在哪里设置呢？

**Comment by sentsim** [comment]
可使用 2.7.x 新增的 `LAY_DISABLED` 来控制单选框是否禁用。
参考：https://layui.gitee.io/v2/docs/modules/table.html#specific-field
