### ISSUE TITLE
Layui table動態合併單元格后，如何實現保持頁面效果的情況下導出excel？

### ISSUE THREAD

**Issue by 8337009** [layui/layui#1011]
Layui table動態合併單元格后，如何實現保持頁面效果的情況下導出excel？
引入第三方插件，手動實現？還是有更好的方案？

**Comment by sentsim** [comment]
可尝试用 2.6.9 版本推出的 exportTemplet 函数来控制导出内容，虽然不知能够实现您所需要的效果，但可以试试看
参考文档：https://layui.gitee.io/v2/docs/modules/table.html#exportTemplet
