### ISSUE TITLE
多级表头colspan=1出现异常

### ISSUE THREAD

**Issue by garyelephant** [layui/layui#103]
数据表格中，我想实现多级表头，第一级表头是中文（只有1列），第二级表头对应的是英文（也是只有1列），因此需要指定colspan=1，但是数据表格渲染出来后，会出现表头和数据错位的情况，无法使用。

**Comment by sentsin** [comment]
建议第一级设置 colspan="2"，因为只有＞1，table 才会认为是一个多级表头。
