### ISSUE TITLE
数据表格 开启 左侧固定 fixed  + totalRow合计行 ，出现行错乱

### ISSUE THREAD

**Issue by netyjq** [layui/layui#1032]
数据表格table 在开启了 左侧固定 + 合计行的时候，会出现样式行错乱，大佬啥时候抽空解决下？
![fixed](https://user-images.githubusercontent.com/13848223/172346591-e37113b2-2457-440a-881f-07938d4cfd49.jpeg)
![unfixed](https://user-images.githubusercontent.com/13848223/172346600-4d05e1a3-76fd-4511-9194-93b13c974b1b.jpeg)

**Comment by sunxiaobin89** [comment]
经过测试没有出现你提到的现象哦，我觉得关键要看你的目前行高是怎么处理的，从截图看出来你的行高应该是做了一些处理，表格默认是单行显示的且高度没有这么高，所以导致这个问题可能跟你表体中的内容高度处理有关系

**Comment by sunxiaobin89** [comment]
恩恩，关键的问题就在于你的layui-table-cell高度是auto，目前layui的固定列其实是依附于一个固定内容高度去达到高度一致一一对应的，所以如果你固定列中的内容，没有表体中其他的列内容一样高的时候就会出现你提到的现象，因为layui目前的机制就是如此，不支持内容任意高度且能锁定列，如果想要这个效果，需要自己做一些额外的处理，多一些额外的开销如下：
`//执行一个 table 实例
  table.render({
    elem: '#demo'
    ,height: 420
    ,url: '/static/json/table/user.json' //数据接口（此处为静态数据，仅作演示）
    ,title: '用户表'
    ,page: true //开启分页
    ,toolbar: 'default' //开启工具栏，此处显示默认图标，可以自定义模板，详见文档
    ,totalRow: true //开启合计行
    ,cols: [[ //表头
      {type: 'checkbox', fixed: 'left'}
      ,{field: 'id', title: 'ID', width:80, sort: true, fixed: 'left', totalRowText: '合计：'}
      ,{field: 'username', title: '用户名', width:80, templet: '<div>{{d.username}}<br>{{d.username}}</div>'}
      ,{field: 'experience', title: '积分', width: 90, sort: true, totalRow: true}
      ,{field: 'sex', title: '性别', width:80, sort: true}
      ,{field: 'score', title: '评分', width: 80, sort: true, totalRow: '{{ parseInt(d.TOTAL_NUMS) }} 分'}
      ,{field: 'city', title: '城市', width:150} 
      ,{field: 'sign', title: '签名', width: 200}
      ,{field: 'classify', title: '职业', width: 100}
      ,{field: 'wealth', title: '财富', width: 135, sort: true, totalRow: true}
      ,{fixed: 'right', width: 150, align:'center', toolbar: '#barDemo'}
    ]],
done: function () {
  var tableView = this.elem.next();
  layui.each(tableView.find('.layui-table-fixed tr'),   function(index, trElem) {
  debugger
  trElem = layui.$(trElem);
console.log(trElem, tableView.find('.layui-table-body tr[data-index="'+trElem.data('index')+'"]') + 'px', trElem.css('height'));
  trElem.css({
    height: tableView.find('.layui-table-body tr[data-index="'+trElem.data('index')+'"]').height() + 'px'
  })
})
}
  });`
写了一个简单的例子给你参考一下，核心的思路就是在渲染完成之后遍历固定列的行，同步他们的高度与实际的tr一致，另外如果开启了统计行，不建议你样式设置的这么粗额，..layui-table-cell也会影响到统计行，如果你统计行也需要高度自动的话那就可以哈，如果不是建议样式设置如下：
`.layui-table-body .layui-table-cell {
height: auto;
overflow: visible;
text-overflow: inherit;
padding: 0 15px;
white-space:normal;
word-wrap:break-word;
word-break:break-all;
}`
只设置表体中的tr；
最后tips: 例子只是简单的在done处理，但是实际应用中，因为你的高度设置是自动的，那么如果窗口大小变化，或者拖动了列宽，内容发生变化高度可能变化的情况下，需要再同步一下固定列的高度，所以可以自己进一步优化处理一下额。

**Comment by netyjq** [comment]
我发现问题出在 开启合计后，固定div少了 total这个div
<img width="590" alt="image" src="https://user-images.githubusercontent.com/13848223/172583605-860e7602-087a-457f-8e27-4131ecf49a37.png">

**Comment by sunxiaobin89** [comment]
固定列本来就没有带统计列的哈，再看了一下你的表格，应该是做了一些针对性的调整，我看你的统计是在顶部的，默认是在底部，所以不会造成错列的问题，只要他们高度一致，如果你做了调整提到上面去了固定列缺少统计行确实就会这样错开

**Comment by netyjq** [comment]
针对我提的这个场景，考虑在新版本做下支持吗？

1、汇总支持放在首行或者末尾，开启合计行后能够正常展示
2、单元格支持多行内容，且高度自动垂直居中

**Comment by sentsim** [comment]
1. 若汇总放在行首，又得多增加一个参数，不建议这么做。
2. 从 2.7.0 开始，已经可以通过 lineStyle 参数任意定义单元格的高度，即支持多行内容。
