### ISSUE TITLE
【BUG？】table的一个问题。

### ISSUE THREAD

**Issue by q8018414** [layui/layui#1038]
done的渲染回调时,轮询每行设备状态,在后端未全部返回数据前,点击表头排序,必然会导致后续状态数据无法更新.必须手动点击事件更新.
![QQ图片20220612112430](https://user-images.githubusercontent.com/70793915/173213011-5dfb407a-5b08-49fa-8ceb-74738ea515fa.png)
done代码截图如上，请各位大佬指教。
![QQ图片20220612112632](https://user-images.githubusercontent.com/70793915/173213058-02f7445a-4985-47ff-803f-b80ce712762a.png)
利用行点击事件，手动更新状态代码如上。

**Comment by sentsim** [comment]
从截图中无法判断您所说的「点击表头排序」导致的问题，最好直接在 codepen 提供一个在线示例呢。

**Comment by q8018414** [comment]
> 从截图中无法判断您所说的「点击表头排序」导致的问题，最好直接在 codepen 提供一个在线示例呢。

这是两个事件，第一个事件，是首次加载数据表格后的done的渲染回调，回调时进行了后台查询动作。

第二个事件，是这个回调渲染后，点击表头排序。如果正常回调完成后，点击排序没有问题。但是如果回调的动作没有完成。就点击排序。就会导致回调的数据查询动作中断。且之前已经完成的部分查询也会恢复至回调前的状态。

**Comment by q8018414** [comment]
> 从截图中无法判断您所说的「点击表头排序」导致的问题，最好直接在 codepen 提供一个在线示例呢。

可能表述不太清楚。录了一个实际操作的。。
![QQ录屏20220731215018](https://user-images.githubusercontent.com/70793915/182029801-2c5f123d-b9dd-40d5-bac4-80adbc03da42.gif)
