### ISSUE TITLE
【建议】table的另一个问题。

### ISSUE THREAD

**Issue by q8018414** [layui/layui#1039]
在列比较少的时候，左边有复选列，右边有操作列，中间自动列宽，会出现横向滚动条。
![QQ图片20220612122000](https://user-images.githubusercontent.com/70793915/173214279-021322e7-e7bc-404f-b97a-775f307332ed.png)
效果如上
![QQ图片20220612122141](https://user-images.githubusercontent.com/70793915/173214329-01e2753c-5533-4ef9-8981-2e719a50fb48.png)
代码如上

**Comment by sentsim** [comment]
有可能是图片那一列的 width: '15%' 导致，尝试去掉，改成 `minWidth: 200`

**Comment by q8018414** [comment]
> 有可能是图片那一列的 width: '15%' 导致，尝试去掉，改成 `minWidth: 200`

测试过了。没有定义15%。也会出现这个情况。只要数据列过少，不足填充都会出现下面的横向滚动条。
![image](https://user-images.githubusercontent.com/70793915/182029342-831e10d1-bc19-4798-9d18-a6e755b5424e.png)
![image](https://user-images.githubusercontent.com/70793915/182029366-8ed6a761-9e99-458c-a1d4-6920bf76fe78.png)

**Comment by sentsim** [comment]
> > 有可能是图片那一列的 width: '15%' 导致，尝试去掉，改成 `minWidth: 200`
> 
> 测试过了。没有定义15%。也会出现这个情况。只要数据列过少，不足填充都会出现下面的横向滚动条。 ![image](https://user-images.githubusercontent.com/70793915/182029342-831e10d1-bc19-4798-9d18-a6e755b5424e.png) ![image](https://user-images.githubusercontent.com/70793915/182029366-8ed6a761-9e99-458c-a1d4-6920bf76fe78.png)

这个不大应该。您看看你当前用的 Layui  是什么版本，如果版本太老，尝试升级到最新版看看

**Comment by q8018414** [comment]
> 这个不大应该。您看看你当前用的 Layui 是什么版本，如果版本太老，尝试升级到最新版看看

最新版本。一直有追更新。一个新项目。前端还没完全定板。

**Comment by sentsim** [comment]
> 最新版本。一直有追更新。一个新项目。前端还没完全定板。

我这边按照您的配置方式在 codepen 写了个示例：https://codepen.io/sentsim/pen/OJvzjRB
未发现横向滚动条问题。

**Comment by q8018414** [comment]
> > 最新版本。一直有追更新。一个新项目。前端还没完全定板。
> 
> 我这边按照您的配置方式在 codepen 写了个示例：https://codepen.io/sentsim/pen/OJvzjRB 未发现横向滚动条问题。

找到问题了。外围没有给padding；哪怕给个1px都不会出现这个问题。。

**Comment by q8018414** [comment]
![image](https://user-images.githubusercontent.com/70793915/182031278-d70bad87-3d80-4d85-8f1c-51381c381d1b.png)
只要给个1px就行。。

**Comment by q8018414** [comment]
> > 最新版本。一直有追更新。一个新项目。前端还没完全定板。
> 
> 我这边按照您的配置方式在 codepen 写了个示例：https://codepen.io/sentsim/pen/OJvzjRB 未发现横向滚动条问题。

看看贤心大佬，认为这个问题需不需改改吧。我先关闭issuele了。

**Comment by sentsim** [comment]
好的，我们后续关注一下是否由 `padding` 的影响所致

**Comment by sentsim** [comment]
好的，我们后续再具体关注一下是否由 padding 的影响所致。
不过上面我提供的示例中，将 padding 设为 0 也并没有发现有横向滚动条的。
所以建议先优先检查一下是否受到您页面本身的外部元素（如父节点）的影响

**Comment by q8018414** [comment]
感谢大佬的帮助，确实我愚了。。实际是因为父节点有layui-col-space10，导致margin给定-5PX导致的。之前没有详细检查父节点情况。忽略了中间的div。把父节点认为是body.没有发现中间div的class上出现了问题。
![image](https://user-images.githubusercontent.com/70793915/182132687-7edb8d49-ea62-42dc-b5bf-6502df06603f.png)
