### ISSUE TITLE
 layer.open的页面渲染问题

### ISSUE THREAD

**Issue by niuzhi** [layui/layui#1050]
你好，我使用layer.open弹出一个页面，发现页面里面使用代码高亮插件prism不起作用，渲染不了，请问如何设置？pre和code没有起作用
![image](https://user-images.githubusercontent.com/33443724/175020375-0c434c8f-e7da-4321-8b35-4118d446ac79.png)

![image](https://user-images.githubusercontent.com/33443724/175020474-f8da296f-0819-4b3d-927a-c892e1ae7fa9.png)

**Comment by sentsim** [comment]
prism 默认是当页面 load 完成之后自动渲染一次，你用 layer 来弹出，content 指向的是动态生成的新元素，prism 识别不到。按照以下两种**任意一种**方式来解决：
1. content 参数后面的 `.html()` 去掉，但是 editDialog 所在元素需要在 body 根节点下。
2. 在 layer 的 success 回调执行 `prism.highlightAll();` 或 `prism.highlight(code, options);` 方法来重新对代码区域进行高亮渲染

**Comment by niuzhi** [comment]
> prism 默认是当页面 load 完成之后自动渲染一次，你用 layer 来弹出，content 指向的是动态生成的新元素，prism 识别不到。按照以下**任意一种**方式来解决：
> 
> 1. content 参数后面的 `.html()` 去掉，但是 editDialog 所在元素需要在 body 根节点下。
> 2. 在 layer 的 success 回调执行 `Prism.highlightAll()` 或 `Prism.highlight(code, grammar)` 来重新对代码区域进行高亮渲染

非常感谢！

**Comment by niuzhi** [comment]
@sentsim 大神，再问一个问题，面可以实现高亮，但是发现最后被回显值覆盖。
比如如下代码：

![image](https://user-images.githubusercontent.com/33443724/175209616-b393f2ce-bce0-41fc-9119-00af300e7ec5.png)

![image](https://user-images.githubusercontent.com/33443724/175209538-7c2c5b46-4d4a-4250-885d-f2970e0dab30.png)

效果显示为：
![image](https://user-images.githubusercontent.com/33443724/175209714-af80b744-8fde-4fa8-84d5-487bca0f49ad.png)
但是如果把值放在
<textarea id="File" name="File" rows="100" cols="500" >代码</textarea>则高亮正常，请问这块如何设置？期待你的恢复

**Comment by sentsim** [comment]
给你的 `Prism.hightlightAll()` 延迟 100ms 执行，或者在前面先进行 `data.File = Prism.hightlight(data.File, grammar)` 的处理
