### ISSUE TITLE
table组件列在使用templet时，回调函数中是否能返回当前列的数据？

### ISSUE THREAD

**Issue by MartinLongYW** [layui/layui#1057]
如题，因为目前只返回一个d，即rowData，每次处理的时候，都需要通过d.字段去访问，有一些不方便。
是否能像下面代码所示：
`
templet:function(data,rowData){
     // data为当前列数据，rowData为当前行数据。
}`

**Comment by sentsim** [comment]
没必要再返回一个 rowData 参数的，可以通过 `this` 获取到当前表头的信息
 ```
templet: function(data){
  console.log(this); // 当前表头信息
  console.log(this.field); // 当前表头字段名
}
```
