### ISSUE TITLE
form.js里面verify问题，建议除了required，其它都应该不是必填的

### ISSUE THREAD

**Issue by MonsterUncle** [layui/layui#1082]

**Comment by sentsim** [comment]
这个要考虑到向下兼容问题，不能直接这样调整了。因为很多人早前一步到位，并没有设置 `required`，而是直接通过类似于 lay-verify="phone" 的形式，既包含了必填项，又包含了手机号规则。所以 2.x 只能按照现有的规则保持下去。

若要实现你说的需求，其实也不难，可通过 form.verify 方法对默认的校验规则重置即可。
