### ISSUE TITLE
😊 请将 Issue 统一发表在 Gitee

### ISSUE THREAD

**Issue by sentsim** [layui/layui#1084]
目前平台的处理方式如下：
- Issue 在 Gitee 提： [**Issues**](https://gitee.com/layui/layui/issues) （因 Gitee 在 Issue 交流时访问速度占优）
- PR 在 Github 提： [**Pull requests**](https://github.com/layui/layui/pulls) （因 Layui 在 Gitee 的仓库是从 Github 同步而来）
> **Gitee Issues:** https://gitee.com/layui/layui/issues

**Comment by LuoCore** [comment]
能搞个qq群？

**Comment by q8018414** [comment]
期望交流群

**Comment by sentsim** [comment]
@q8018414 @LuoCore 
https://gitee.com/layui/layui/issues/I5JMUT#note_12019725_link

**Comment by ByYogi** [comment]
风水轮流, 哈哈
[重要调整：Layui Issues 请统一在 Github 提交](https://gitee.com/layui/layui/issues/I8OVIB)
