### ISSUE TITLE
在template中修改了this的属性值后不能渲染

### ISSUE THREAD

**Issue by yangmingtao** [layui/layui#1151]
this.edit="text"

根据data的值动态设置当前列是否可编辑，下面图片设置了this的属性值，但是页面好像没有渲染
![Y9~DA1 NS7TTJME%VCW9G71](https://user-images.githubusercontent.com/8136462/196112330-5bf33615-1fd8-4436-8ef4-08e86ff71ad4.png)

**Comment by yangmingtao** [comment]
就像图片展示的那样

**Comment by sentsim** [comment]
无法在 `templet` 函数中设置 edit 属性，建议您升级到 2.7 最新版：https://layui.gitee.io/v2/
并采用 edit 新增的函数写法处理即可，如：
```
edit: function(d){ // v2.7.5 加强支持函数写法，用于更灵活地开启单元格的编辑权限
  if(d.datasource === '存货编码'){
    return 'text'; // 给满足条件的字段开启编辑
  }
}
```

**Comment by yangmingtao** [comment]
谢谢大佬

**Comment by yangmingtao** [comment]
谢谢大佬
