### ISSUE TITLE
form表单 select组件，渲染的时候空格没有生效，以前版本可以的

### ISSUE THREAD

**Issue by MonsterUncle** [layui/layui#1154]
![image](https://user-images.githubusercontent.com/23304366/197095928-16e1fac5-fa08-4287-83ff-74c80545de5e.png)
![image](https://user-images.githubusercontent.com/23304366/197095954-c4da61bc-8958-4f11-b571-564953e9e2f2.png)

**Comment by MonsterUncle** [comment]
我看示例中也不行

**Comment by sentsim** [comment]
见：https://gitee.com/layui/layui/issues/I5Y9NS
