### ISSUE TITLE
同样的参数，layer.photos可以正常使用，但是top.layer.photos没反应

### ISSUE THREAD

**Issue by Rebuilding127** [layui/layui#117]
实际需求：先layer.open打开一个help弹窗，再从help弹窗中显示一些图片示例。但是由于会自动基于父窗口缩略，所以要设置基于顶层显示。 图片参数固定，如：
```
{
    "title": "",
    "id": 1,
    "start": 0,
    "data": [
        {
            "alt": "图1",
            "pid": 1,
            "src": "resources/img/操作演示.gif",
            "thumb": ""
        }
    ]
}
```
一样的参数，一开始 `layer.photos` 使用的时候没问题，但是不符合实际需求。改成 `top.layer.photos` 后无效。

调试发现，参数传入layer后进行判断（源码`1071`行）
`var type = options.photos.constructor === Object;`
该判断在默认情况下得到结果是true，但是在`top.`调用的时候却一直得到结果为false，甚至在上面定义photo参数的时候加入` constructor: Object `都没有用。 但是调试时分析参数应该是object没问题，不知为何会导致这种情况。

另外，使用 `top.layer.open` 打开弹窗是正常可以使用的

**Comment by jiaokai** [comment]
2018年的还没解决啊

**Comment by sentsim** [comment]
> 2018年的还没解决啊

这个早就在后面的某一个版本中修复了。

**Comment by artisancn** [comment]
挖祖坟咯~~2.9.10版，top.layer.photos 无效。
