### ISSUE TITLE
layui.all.js:2 Laytpl Error：EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

### ISSUE THREAD

**Issue by jichangfeng** [layui/layui#1176]
客户安全部门要求 CSP 标头里不能加 'unsafe-eval'，导致 layui 用不起来，有什么解法吗？

**Comment by sentsim** [comment]
这个报错应该是您模板里面的语句所致，查找 `unsafe-eval` 段落处进行修正。
至于 laytpl 自身是不会用到这个的，它只是一个模板解析模块。

另外，layui.all.js 是 Layui 低版本才有的，从 2.6.0 开始就已经取消该文件了。

**Comment by jichangfeng** [comment]
@sentsim 检查了代码没有使用 eval，下面是代码片段和错误，有空的时候帮忙分析下吧？

源代码 - HTML片段：
```
<table class="layui-hide" id="datagrid" lay-filter="datagrid"></table>
<link rel="stylesheet" href="../public/css/layui.css">
<script src="../public/js/jquery.min.js"></script>
<script src="../public/layui.all.js"></script>
<script src="../public/js/store.js"></script>
```

源代码 - ../public/js/store.js：
```
var tableIns = layui.table.render({
	elem: '#datagrid'
	,height: 'full-70'
	,cellMinWidth: 80
	,cols: [[
		{
			field: 'sid',
			title: '门店编号'
		},{
			field: 'store_code',
			title: '门店编码'
		},{
			field: 'store_name',
			title: '门店名称'
		},{
			field: 'store_province',
			title: '所属省份'
		},{
			field: 'store_city',
			title: '所属城市'
		}
	]]
	,page: true
	,url: '/api/store/index'
	,request: {
		pageName: 'cur_page'
		,limitName: 'per_page'
	}
	,parseData: function(res){
		layer.closeAll();
		return {
			"code": 0,
			"msg": "",
			"count": res.pagination.total_rows,
			"data": res.datas
		};
	}
});
```

报错截图：
![image](https://user-images.githubusercontent.com/34360195/206099338-02449d1c-5cd2-4140-8ff4-d708240bbcbc.png)

**Comment by richex-cn** [comment]
看起来是 jQuery 用到了 eval 的问题，最新版的 jQuery 没有用到 eval 可以试试。

**Comment by jichangfeng** [comment]
@richex-cn 谢谢您的解答。
用的 jQuery v3.6.1 最新版本，而且 jQuery 其他操作没问题，就是渲染 layui.table 的时候才会有这个错误。
上面用的 layui 2.5.4，我换成 layui 2.7.6 后，也是报类似的错误，错误如下图
![image](https://user-images.githubusercontent.com/34360195/206102259-01677c47-1205-4796-bfd8-8e667e3d682a.png)

**Comment by jichangfeng** [comment]
@sentsim @richex-cn 补充下 CSP 配置，还请帮忙分析，不胜感激。

未加 'unsafe-eval' 指令的 CSP 配置，就会有上面的错误。
```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'";
```

加上 'unsafe-eval' 指令的 CSP 配置，就不会有问题了
```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'";
```

但是客户方要求不能存在 unsafe-inline、unsafe-eval 这些不安全指令，
unsafe-inline 只需要把 JavaScript/CSS 代码均移入单独文件可以解决，
而 unsafe-eval 是目前遇到的问题，渲染 layui.table 就会报错。

**Comment by richex-cn** [comment]
是不是因为这里 @sentsim 

https://github.com/layui/layui/blob/b80f7d60b9a42db6d21d78cdccd9a17e392d2b3c/src/modules/laytpl.js#L95

**Comment by richex-cn** [comment]
参考：
https://web.dev/csp/#eval-too
https://security.stackexchange.com/questions/88610/problem-in-underscore-js-with-new-function-when-csp-header-is-set

**Comment by jichangfeng** [comment]
@richex-cn 感谢感谢，确实是 new Function() 导致的，有解决思路了。

**Comment by fan-zibang** [comment]
@jichangfeng 我也遇到了同样的难题，可以将你的解决思路分享一下吗？

**Comment by anna647** [comment]
> @richex-cn 感谢感谢，确实是 new Function() 导致的，有解决思路了。

网上提供的new Function追加元素也被拦截了，请问下你是怎么解决的呀？

**Comment by boatingPear** [comment]
@jichangfeng 我也遇到了同样的难题，可以将你的解决思路分享一下吗？
怎么解决的大佬能分享一下吗
