### ISSUE TITLE
关于树形表格的需求

### ISSUE THREAD

**Issue by linjifu** [layui/layui#1204]
最近项目需求中碰到很多需要树形表格并且排序的功能，发现数据表格暂无这个功能，而基于layui的第三方树形表格又会出现无法排序或者排序错乱的BUG，最后迫于无奈只能选择elementUI嵌套进来写，想问问大佬是否有扩展数据表格为树形表格的想法哈哈~

**Comment by sentsim** [comment]
见：[关于 `treeTable` 组件的计划](https://gitee.com/layui/layui/issues/I6H8EJ)
