### ISSUE TITLE
表格导出问题

### ISSUE THREAD

**Issue by lhd1111** [layui/layui#1214]
### 说明

- 版本：layui-v2.8.0-rc.6
- 描述：
    自2.8.0rc6版本开始，数据表格的导出已经修复卡顿的bug，但是导出的数据excel的公式并不认可，不能参与运算，包括简单的excel单元格中的数字计算

### 代码

系统自带的表格导出，并无额外的代码

### 补充
经测试：
layui-v2.8.0-rc.5除了表格导出卡顿一会，导出后的表格使用无问题
layui-v2.8.0-rc.6、rc7、rc10、rc13都测过
开始多选框的风格变了，
表格导出卡顿的问题解决，但是表格无法二次运算

**Comment by sentsim** [comment]
Gitee 已经有重复提问，Issue 发在那边即可：https://gitee.com/layui/layui/issues/I6OEQF
