### ISSUE TITLE
layui又回来了

### ISSUE THREAD

**Issue by kiss758** [layui/layui#1231]

**Comment by zhixu369** [comment]
当初就不该有那个公告，好不容易积累的口碑和人气，只要当初的官网在，人气就在、流量就在，就有很多办法可以维持那个官网的生存，甚至盈利。我是一名创业者，虽然多年来仍在路上，但只要还继续创业下去，服务器肯定不会关停。既然这次回来了，我也想啰嗦一下，前后端分离的大趋势下，还是要顺大势，还是让layui底层采取主流框架vue或者react为好，如果担心基于vue和react的UI框架已经有很多成熟的了，这个担心肯定多余了，我当初用layui，看重的仅仅只是layui的UI视觉效果和体验，layui的JS模块化写法，我相信大家只会吐槽的，所以新官网上线，希望layui拥抱vue或react，把优势往视觉和体验上靠拢，否则真没啥竞争力

**Comment by Ken-Sinn** [comment]
> 当初就不该有那个公告，好不容易积累的口碑和人气，只要当初的官网在，人气就在、流量就在，就有很多办法可以维系那个官网的存在，甚是凪业者，虽然多年以后还在路上，但只要继续创业下去，服务器肯定不会关停。但无论如何这一次回来了，我想哒哒一下，前后端分离开的大势，以后端分离开的大势还是让layui底层采集主流框架vue或者react为好，如果依赖于vue和react的UI框架已经有很多成熟的了，这个担心确定了很多余了，我当初用layui，看现在的UI布局是ui效果和体验，至于layui的JS模型块化写法，我相信大家只会吐槽的，所以以新官网上线，希望layui抱抱vue或react，把优势趋向视觉和体验上靠拢，否则真的没有乞丐

其实我觉还有一种方式，就是既然大家喜欢的是layui的样式，可以考虑走css组件的方向。类似：https://github.com/weilanwl/coloruicss

**Comment by thomasgolden** [comment]
https://www.npmjs.com/package/@types/layui-src
希望ts 定义文件可以更新一下。

**Comment by sentsim** [comment]
准确地说，是「文档站」回来了。😅
