### ISSUE TITLE
upload的error回调，能否把res也带回来

### ISSUE THREAD

**Issue by shenzhe** [layui/layui#1245]
原因：
有一些系统，一些业务错误，返回的http code也是非200，比如500，然后response body里再带有具体的错误信息

现在的error回调里，是拿不到response信息

**Comment by sentsim** [comment]
业务型状态码建议正常返回即可，在 `done` 回调中进行判断处理。 `error` 是在网络异常和服务端异常时才触发的。
另外， `Issue` 最好还是发在 Gitee 哈，见：#1084
