### ISSUE TITLE
laydate的分隔符两边会自动加两个空格，能否去掉？

### ISSUE THREAD

**Issue by KuoKongQingYun** [layui/layui#127]
laydate的分隔符两边会自动加两个空格，能否去掉？
我分隔符设置为- ，但是-两边却有空格，会影响后端解析

**Comment by sentsim** [comment]
日期范围的分隔符带空格就是为了便于分割，比如类似于 `2018-06-18-2022-06-18` 若中间不加空格，会更为不妥。
