### ISSUE TITLE
自定义表格的response数据格式，不支持多层嵌套

### ISSUE THREAD

**Issue by zhou-hao** [layui/layui#131]
如调用的 res[response.countName]，如果countName是多层的属性如: result.total 则无法获取
https://github.com/sentsin/layui/blob/ce3a0e74783accd0a5e756ae5c68e6f7e56eb5ea/src/lay/modules/table.js#L421-L429

**Comment by ellermister** [comment]
同问，这个问题很BUG，希望尽快修复。

**Comment by zhou-hao** [comment]
@ellermister 通过自己修改table.js解决了。参考  https://github.com/sentsin/layui/pull/90

**Comment by slimina** [comment]
同问，建议增加个res数据预处理函数

**Comment by l511407563** [comment]
#235
