### ISSUE TITLE
如何开始运行该项目？

### ISSUE THREAD

**Issue by rushChen131** [layui/layui#133]
我现在的一个项目有用到该框架，需要个新功能点击表格内tr 元素做到该行的checkbox选中并且变色 点击其他tr元素原先那行tr的checkbox取消选中并取消变色 我写了这个需求后发现一些bug 我想把这个项目跑起来运行测试编写这个功能，请教下怎么启动 ？ 

                                                                                                                                               一个java小菜鸡

**Comment by Yurunsoft** [comment]
1. 安装Node.js
2. 执行`npm install`
3. 改src里的代码
4. 项目目录中执行`gulp all --open`
5. dist目录里就是编译后的文件

**Comment by Mgzu** [comment]
Java Web项目，可以直接下载官方最新版本，放在Webapp（或Webroot）目录下，引用layui.js，实现相应功能，使用Tomcat去发布项目，然后去调试
