### ISSUE TITLE
🌐 Layui 唯一官方文档网址声明：https://layui.dev

### ISSUE THREAD

**Issue by sentsim** [layui/layui#1377]
# Layui 官网以 Github 和 Gitee 公布的域名为准，其他第三方搭建的文档镜像站与 Layui 官方没有任何关联，请务必仔细辨别。

🌐 Layui 官网文档：https://layui.dev

### Github 公布的 Website ：
![image](https://github.com/layui/layui/assets/3277200/eca74237-8348-46e1-a44d-af610b5daba3)
截图来自：https://github.com/layui/layui/

### Gitee 公布的 Website ：
![image](https://github.com/layui/layui/assets/3277200/e39fe98c-e4f6-4101-81dd-adefc262d33c)
截图来自：https://gitee.com/layui/layui/

**Comment by xinconan** [comment]
之前是老用户，现在网站好像变了，登录不了

**Comment by sentsim** [comment]
> 之前是老用户，现在网站好像变了，登录不了

主题吗？https://dev.layuion.com/themes/

**Comment by AppSkyBoy** [comment]
为什么不搞一个layui of svelte 呢？

**Comment by LuJinSehng** [comment]
@sentsim 贤姐，救命！请问官网的“在线测试”组件是什么？我在layuiAdmin-v2.3.2框架中，没有找到这个组件，这是第三方组件吗？最近有个账单扎帐快照功能，需要支持html在线编辑调整。
![Uploading 1.png…]()
