### ISSUE TITLE
弹出层msg能否加一个自动定位功能？销毁msg后，其他msg自动重新调整位置

### ISSUE THREAD

**Issue by wdk589** [layui/layui#1393]
### 议题条件

- [X] 我确认已查看官方使用文档：**https://layui.dev** ，但没有找到相关解决方案。
- [X] 我确认已在 **Issues** 中搜索过类似的问题，但没有找到相关解决方案。

### 版本号

2.817

### 浏览器

edge

### 问题类型

功能困惑

### 问题描述

类似饿了么ui的消息提示的效果

### 业务代码

```auto
弹出层msg能否加一个自动定位功能？销毁msg后，其他msg自动重新调整位置
```

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
该功能可以用 `type:1` 页面层自主实现。 `msg` 层的逻辑是同时只能显示一个。

**Comment by wdk589** [comment]
> 该功能可以用 页面层自主实现。 层的逻辑是同时只能显示一个。`type:1``msg`

嗯，已经修改成type:1了。但是它的位置是固定的，而且到时间销毁之后，也不会自动重新给其他的msg修改定位。

**Comment by sentsim** [comment]
> > 该功能可以用 页面层自主实现。 层的逻辑是同时只能显示一个。`` type:1``msg ``
> 
> 嗯，已经修改成type:1了。但是它的位置是固定的，而且到时间销毁之后，也不会自动重新给其他的msg修改定位。

位置是需要单独处理一下的，即 offset 始终动态计算。
