### ISSUE TITLE
当输入框使用了时间控件，并加上了lay-affix="clear"的bug

### ISSUE THREAD

**Issue by douno23** [layui/layui#1394]
### 议题条件

- [X] 我确认已查看官方使用文档：**https://layui.dev** ，但没有找到相关解决方案。
- [X] 我确认已在 **Issues** 中搜索过类似的问题，但没有找到相关解决方案。

### 版本号

2.8.17

### 浏览器

117.0.5938.150

### 问题类型

疑是 BUG

### 问题描述

当输入框使用了时间控件，并加上了lay-affix="clear"的bug

如果输入框有值，会显示清楚图标，当点击清空图标后，即使再输入也无法显示图标

### 业务代码

```auto
见描述
```

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
input 的 `clear` 图标只有在初始状态和发生输入事件（`input`） 时才会显示或隐藏，如果是外部赋值，如 laydate 选择日期赋值，则不属于输入事件，此时需要在 laydate 的 `done` 中手动触发一下 `input` 事件，如：

```
done: function() {
  $(this.elem).trigger('input');
}
```

**Comment by douno23** [comment]
感谢解答
