### ISSUE TITLE
数据表格重载有问题，会有重复的列

### ISSUE THREAD

**Issue by ghost** [layui/layui#144]
![tim 20180124165811](https://user-images.githubusercontent.com/25221782/35323352-234c600e-0128-11e8-87a8-16a95317d783.png)
用 table.reload 重载，会有重复的列，而且这个重载会自动增加容器的宽度，出现横向滚动条，能像table.render一样，不管列怎么变动，不出现横向滚动，自动适应，让列变窄吗？。
![tim 20180124165631](https://user-images.githubusercontent.com/25221782/35323347-1da60858-0128-11e8-85b7-4a82e73066ed.png)

**Comment by jilingling** [comment]
我也遇到这个问题了
