### ISSUE TITLE
设置自动行高时，复选框错位

### ISSUE THREAD

**Issue by douno23** [layui/layui#1448]
### 议题条件

- [X] 我确认已查看官方使用文档：**https://layui.dev** ，但没有找到相关解决方案。
- [X] 我确认已在 **Issues** 中搜索过类似的问题，但没有找到相关解决方案。

### 版本号

2.9

### 浏览器

120.0.6099.71 

### 问题类型

疑是 BUG

### 问题描述

数据表格问题及建议
1. 在设定表格样式后，会错位，比如复选框
2. 希望增加参数让单元格高度自适应，目前的点击展开按钮展示效果不太好阅读
3. 设定列宽后，会发现表格主体和表头不能精准对齐

### 业务代码

```auto
数据表格复选框错位



        .layui-table-cell {
            height: auto !important;
            line-height: 25px !important;
        }
```

### 截图补充

![复选框错位](https://github.com/layui/layui/assets/147586793/a56f92cb-2d86-4934-96f1-d7f2754c0a04)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
因为你对 `.layui-table-cell` 自定义了样式，尽量不要做这件设置。建议通过 `lineStyle` 来定义行样式。
相关参考：
https://layui.dev/docs/2/table/#options-intro
https://layui.dev/docs/2/table/#demo-css

**Comment by douno23** [comment]
> 因为你对 `.layui-table-cell` 自定义了样式，尽量不要做这种影响原有样式结构的设置。 建议通过 `lineStyle` 来定义行样式。相关参考： https://layui.dev/docs/2/table/#options-intro https://layui.dev/docs/2/table/#demo-css

可是内容的长度是不确定的，设定 lineStyle 会导致所有行都变更，并不是自适应啊

**Comment by Sight-wcg** [comment]
> > 因为你对 `.layui-table-cell` 自定义了样式，尽量不要做这种影响原有样式结构的设置。 建议通过 `lineStyle` 来定义行样式。相关参考： https://layui.dev/docs/2/table/#options-intro https://layui.dev/docs/2/table/#demo-css
> 
> 可是内容的长度是不确定的，设定 lineStyle 会导致所有行都变更，并不是自适应啊

更改 .layui-table-cell 也是所有的单元格生效，lineStyle 只是设置行样式，是否自适应高度，取决于你设置的样式，table-cell 怎么改的，lineStyle 就怎么设置。

**Comment by Sight-wcg** [comment]
> > > > 因为你对 `.layui-table-cell` 自定义了样式，尽量不要做这种影响原有样式结构的设置。 建议通过 `lineStyle` 来定义行样式。相关参考： https://layui.dev/docs/2/table/#options-intro https://layui.dev/docs/2/table/#demo-css
> > > 
> > > 
> > > 可是内容的长度是不确定的，设定 lineStyle 会导致所有行都变更，并不是自适应啊
> > 
> > 更改 .layui-table-cell 也是所有的单元格生效，lineStyle 只是设置行样式，是否自适应高度，取决于你设置的样式，table-cell 怎么改的，lineStyle 就怎么设置。
> 
> lineStyle也会导致错位...

lineStyle 设置自动行高，不能和固定列同时使用
