### ISSUE TITLE
【bug】当页面含有滚动条时，layer弹出固定滚动条，会导致鼠标悬浮弹出框内容的时元素偏移（附最小复现、演示地址）

### ISSUE THREAD

**Issue by cvpv** [layui/layui#1471]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.2

### 问题描述

当页面有滚动条的时候，layer弹出框在弹出后隐藏滚动条。

必要条件：

1. 页面含有滚动条
2. layer 设置`scrollbar: false`
3. 页面屏幕宽度位于一定值之间，太小太宽都无法复现。（大概1000px可以复现）

**部分浏览器始终无法复现，需要chromium内核的浏览器才能复现**

这时候，悬浮layer内部的部分元素，会出现诡异的文字向左偏移1px！！！

见下面的最小复现

### 业务代码

[最小复现](https://github.com/cvpv/issue-layui-bug/tree/master)

### 截图补充

![Snipaste_2023-12-19_12-41-25](https://github.com/layui/layui/assets/84720311/e9f6a586-a2b2-4392-ad0b-0d5347f3f846)

### 浏览器

chrome119

### 演示地址

[点击访问](https://tool.cvpvp.com/issue-layui-1471/)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by cvpv** [comment]
真的无语了，怀疑人生。

**Comment by sentsim** [comment]
@cvpv 小伙子不要慌，标题取得有点长。
`anim: 5` 可以秒解你的困惑。

**Comment by cvpv** [comment]
> @cvpv 小伙子不要慌，标题取得有点长。 `anim: 5` 可以秒解你的困惑。

请问你那边能复现吗？演示地址发了

**Comment by cvpv** [comment]
有的电脑能复现有的电脑不能复现，关闭动画后（设置`anim: 5`）就没有这个问题了

**Comment by cvpv** [comment]
学习css三年，我还是搞不清楚原理是什么

**Comment by cvpv** [comment]
> 有的电脑能复现有的电脑不能复现，关闭动画后（设置`anim: 5`）就没有这个问题了

似乎要屏幕宽度小于一定值才能复现，大概屏幕宽度1000px可以稳定复现

**Comment by sentsim** [comment]
跟不同终端 CSS 动画渲染后的差异有关，我这里即便不更改动画，也无法重现你说的文本偏移。
后续建议通过 stackblitz 创建在线示例，会更方便一些： https://stackblitz.com/edit/orsrjb?file=index.html

**Comment by cvpv** [comment]
是的，我本机也只有chrome内核的浏览器能复现，filefox一切正常。
https://stackblitz.com/edit/orsrjb-cmerp9?file=index.html

**Comment by bxjt123** [comment]
> @cvpv 小伙子不要慌，标题取得有点长。 `anim: 5` 可以秒解你的困惑。

我有个`layer.msg`里加了`<br>`，每次选中内容就会向上偏移一点，还以为是换行的问题也没管他，加了这`anim: 5`果然不偏了

**Comment by LSL1618** [comment]
这么小的差异都能发现！眼神真好！

**Comment by cvpv** [comment]
> 这么小的差异都能发现！眼神真好！

你这边能复现吗？是ui发现的。。。验收不合格

**Comment by bxjt123** [comment]
> > > @cvpv 小伙子不要慌，标题取得有点长。 `anim: 5` 可以秒解你的困惑。
> > 
> > 
> > 我有个`layer.msg`里加了`<br>`，每次选中内容就会向上偏移一点，还以为是换行的问题也没管他，加了这`anim: 5`果然不偏了
> 
> 是否是浏览器兼容性不到位，这个问题我在全文都没有搜到相似的，去chromium issue也没有搜到相似内容

我不确定，其实我只是后端，我这个是页面有滚动条（没设置 `scrollbar `页面宽度不限）选中内容就会上偏，如果页面无滚动条就没事，奇怪的很

**Comment by LSL1618** [comment]
> > 这么小的差异都能发现！眼神真好！
> 
> 你这边能复现吗？是ui发现的。。。验收不合格

我看不出来有存在偏差！你们UI的眼神好犀利！

**Comment by Sight-wcg** [comment]
#### 解决方案
目前可以在 layer 应用动画的元素上添加 `will-change：transform` 来修复此问题。但是，由于 will-change 的一些限制，可能不能将其添加到 layui 中。
> Also, some properties can lead to the creation of a containing block for fixed-position elements. For example, a [transformed element creates a containing block for all its positioned descendants](http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/), even those that have been set to position: fixed. So, if a property leads to the creation of a containing block, then specifying it as a value for will-change will also lead to the generation of a containing block for fixed-position elements.

参考 https://dev.opera.com/articles/css-will-change-property 

简而言之，在 `.layui-layer` 添加 `will-change：transform` 之后，其后代元素中，fixed 定位的元素行为将和 absolute 定位类似，这会**影响 layer.photo 的布局**，或者其他使用类似方法扩展 layer 的程序，估计影响比较小。

解决方案来自： 
https://stackoverflow.com/questions/38896584/css3-transition-shifts-rotated-element-by-1px-in-safari?rq=3
https://stackoverflow.com/questions/14729492/css3-transform-rotate-causing-1px-shift-in-chrome

#### 调查原因
进一步调查之后，发现这可能是浏览器的 BUG，可能相关的问题，chromium 团队表示预计 2024 年修复：
https://bugs.chromium.org/p/chromium/issues/detail?id=600120&q=transform%201px&can=2
https://groups.google.com/a/chromium.org/g/blink-dev/c/Ufwrhx_iZ7U

使用 chromium issues 中类似的最小重现方法，将 .layui-layer 设置为黑色背景，对比 anim: 0  和 anim: 5 的布局，弹层底部多 1px 的线条。如果鼠标悬停时，元素向上偏移，底部多 1px，向左偏，右边多 1px。可能会受到浏览器缩放，屏幕缩放，分辨率等因素影响。
anim0
![cuo](https://github.com/layui/layui/assets/26325820/4edb1478-dbb0-478f-a9a3-c75e9363d770)

anim5
![zh](https://github.com/layui/layui/assets/26325820/496f98c0-a68c-48f2-a91c-c537a0cb8d90)


只是一个初步的调查，后续如果有好的解决方案再跟进。

**Comment by sentsim** [comment]
@Sight-wcg  我最早排查到的也是「动画缩放」所致，但没有继续深入研究下去，潜意识把它归结为浏览器导致的小瑕疵 😅
晨星的这种对技术的每一个细节不断深究的态度，太值得我们学习 🎉。

**Comment by Sight-wcg** [comment]
只是使用信息检索找到类似的问题，这个问题我也很早就注意到了，如果没有前面关于动画因素的评论，我就无法确定检索关键词。

**Comment by cvpv** [comment]
我注意到PR[1492](https://github.com/layui/layui/pull/1492)被关闭了，除了手动设置anime5，开发者还有什么方法可以解决吗？

1. 按照该PR修改源码
2. 由使用者主动在 success 回调(动画之前)执行
```JavaScript
success: function(layero){
  layero.css({ willChange: 'transform, top, left'})
}
```

**Comment by Sight-wcg** [comment]
#### 临时的解决方案

在 layer 中使用 fixed 定位的元素的场景应该很少，所以可以在项目的公共样式中添加 `will-change`
```
.layui-layer:not(.layui-layer-photos) {
  will-change: transform, top, left;
}
```
如果某些场景因为包含块影响了布局，可以在 success 回调(此回调在动画之前执行)中修改 `will-change` 属性的值为 `unset`
```
success: function(layero){
  layero.css({ willChange: 'unset'})
}
```
