### ISSUE TITLE
layui 的table导致网页崩溃

### ISSUE THREAD

**Issue by shijunpeng15** [layui/layui#1473]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.2,v2.7.6,v2.80

### 问题描述

当页面存在**table**时，打开浏览器控制台，选中获取元素的箭头后，鼠标在网页上点击查看元素的情况下，在尝试过 v2.9.2, v2.7.6, v2.80 这几个版本后，均存在图片中问题，浏览器崩溃，显示 **错误代码: STATUS_BREAKPOINT**。测试过edge,google和火狐三个浏览器，其中火狐浏览器是正常的。其他两个都崩溃。
edge版本：120.0.2210.77 (正式版本) (64 位)，Google Chrome：120.0.6099.110（正式版本） （64 位），
![PixPin_2023-12-19_17-28-17](https://github.com/layui/layui/assets/46516257/cb712580-6f8d-401b-bd5c-3b36b452eb43)
![PixPin_2023-12-19_17-36-42](https://github.com/layui/layui/assets/46516257/975e594f-d46c-4b59-b3ab-4bd09c50181b)

### 业务代码

```auto
// 引用layui  js和css ,就是如下简单的一个table渲染
<div class="layui-card">
  
    <div class="layui-card-body">
        <table class="layui-hide" id="dataTable" lay-filter="dataTable"></table>
    </div>
</div>

// 以下是js
 table.render({
     elem: '#dataTable',
     data: [],
     page: true,
     height: "full-270",
     cols: [[
         { field: 'name', title: '文件名称' },
         { field: 'size', title: '大小' },
         { field: 'extension', title: '文件格式' }
     ]]
 });
```

### 浏览器

edge版本：120.0.2210.77 (正式版本) (64 位)，Google Chrome：120.0.6099.110（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
还真是，不过不是每次都能触发，时好时坏！也不一定是table的问题。

**Comment by shijunpeng15** [comment]
我就测试了一个table,因为我这页面调试时发现的，这个页面就一个table。也可能是其他引起的，没试过其他组件是否也存在这样的问题。以前没这样的问题，今天升级了一下浏览器就出现了这个问题。

**Comment by Sight-wcg** [comment]
关联 https://gitee.com/layui/layui/issues/I8N08M

**Comment by shijunpeng15** [comment]
这个问题可以关闭了，等待后续更新

**Comment by cvpv** [comment]
> 这个问题可以关闭了，等待后续更新

请问已经修复了吗？老版本目前也受到影响，版本号2.5.5，老项目年久失修无人维护升级困难

**Comment by shijunpeng15** [comment]
> > 这个问题可以关闭了，等待后续更新
> 
> 请问已经修复了吗？老版本目前也受到影响，版本号2.5.5，老项目年久失修无人维护升级困难

并没有，这个是浏览器内核的问题，详情关注 https://gitee.com/layui/layui/issues/I8N08M
