### ISSUE TITLE
表格组件的导出接口

### ISSUE THREAD

**Issue by wmathor** [layui/layui#1476]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.2

### 问题描述

导出CSV我可以理解，但是为什么现在都2023年了，导出的居然默认还是xls格式？应该修改成默认导出xlsx格式

### 业务代码

```auto
无
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
估计是xlsx文件相对更复杂，没有多余的精力去处理，xlsx文件推荐使用第三方导出插件比如 [ExcelJS](https://github.com/exceljs/exceljs) [SheetJS](https://docs.sheetjs.com/docs/)。

**Comment by Sight-wcg** [comment]
也许将来可以实现一个获取导出数据的方法，具体导出什么文件由使用者在外部实现。

**Comment by xxcniao** [comment]
自己加一下在layui.js中，增加一个mate项就行了
![image](https://github.com/layui/layui/assets/165743395/9139f389-bfc3-4172-be5c-50bd86d21e4a)

**Comment by LSL1618** [comment]
> 自己加一下在layui.js中，增加一个mate项就行了 ![image](https://private-user-images.githubusercontent.com/165743395/318621050-9139f389-bfc3-4172-be5c-50bd86d21e4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjg0NjAsIm5iZiI6MTcxMjEyODE2MCwicGF0aCI6Ii8xNjU3NDMzOTUvMzE4NjIxMDUwLTkxMzlmMzg5LWJmYzMtNDE3Mi1iZTVjLTUwYmQ4NmQyMWU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwNzA5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTBjOGVhY2U1Y2Q0ZmEwZjZjMWUxZmI1ZTFmMjg3NDEzNjAzOTVmMGE5OGMwNDIxYWZhM2E4NTBkZWNjYzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.noq7oO3KdvgRisgCrs1FWjbRilfVjpU36Tp8xkV2Kuc)

光增加选项没啥用，还需要加上具体实现方法，而layui内部本质上只支持导出csv文件，还不如直接加个“导出”按钮，用ExcelJS实现导出xlsx文件。

**Comment by JiangYuSong** [comment]
@xxcniao 这个是怎么出来的，扩展

**Comment by LSL1618** [comment]
@JiangYuSong 看这里 **[https://github.com/layui/layui/issues/1827](https://github.com/layui/layui/issues/1827)**

**Comment by sentsim** [comment]
我们在 v2.9.13 版本中重构了 `defaultToolbar` 选项，这意味着可以自由扩展导出。
详见：https://layui.dev/docs/2/table/#options.defaultToolbar
