### ISSUE TITLE
数据表格中点击分页不出现加载条的bug

### ISSUE THREAD

**Issue by mrliuyin1204** [layui/layui#1480]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.6.8

### 问题描述

已经设置了loading为true
1、如果设置了limit和limits参数，在数据表格中点击分页不会出现加载条
2、不设置limit和limits参数，但是更改了每页显示的数量，点击分页也不会出现加载条

### 业务代码

```auto
table.render({
                elem: '#info-table'
                ,id:'info'
                , url:'myUrl' //数据接口
                , title: '用户列表'
                , page: true //开启分页
                ,loading:true
                , limit: 50
                , limits: [50,100,150,200,250,300,350]
```

### 浏览器

edge

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
无法重新

**Comment by bxjt123** [comment]
2.6.8无法复现，有没有一个可能是网太快了看不到，F12调整网络试试
![1](https://github.com/layui/layui/assets/33601030/d079774b-cc77-4f7e-a9f4-c0cb5e73f1b4)

**Comment by mrliuyin1204** [comment]
> 2.6.8无法复现，有没有一个可能是网太快了看不到，F12调整网络试试 ![1](https://private-user-images.githubusercontent.com/33601030/291859298-d079774b-cc77-4f7e-a9f4-c0cb5e73f1b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjAxNjYsIm5iZiI6MTcwMzExOTg2NiwicGF0aCI6Ii8zMzYwMTAzMC8yOTE4NTkyOTgtZDA3OTc3NGItY2M3Ny00ZjdlLWE5ZjQtYzBjYjVlNzNmMWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAwNTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NTBkN2MzNWVmNDNmN2FmMTlkMzRjZWE1MTcyYmY4ZDRkNTA0YTIyZjk0YjcwYWU5OWJlMDFjZjlkZDFiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_DNZVnTniyt-LIsDe3NpjP0e0lvUjliq29tPC8pNWs)

没有太快，我的数据比较大，要等3秒左右呢
