### ISSUE TITLE
table组件 能否增加  单独获取及更新某个单元格数据的功能。

### ISSUE THREAD

**Issue by chenxiaobozhang** [layui/layui#1483]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.2

### 问题描述

业务需求：频繁更新某一行某一个单元格数据。
目前遇到问题：只能重载数据，会把整个表格数据重载（包括重新渲染按钮？）
功能请求：能否 加一个 table.getCell(x,y)方法，指定获取某一单元格的值，table.updateCell(x,y,value)方法，指定修改某一单元格的值

### 业务代码

```auto
目前只能  table.reloadData(id, options, deep); 重载整个表格数据
```

### 截图补充

![8A}Q1$G DUL CQLRA JTI5S](https://github.com/layui/layui/assets/23134309/ed9948b8-6456-445c-9f2b-e7ea53b4d78e)

### 浏览器

Chrome浏览器最新版本

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by chenxiaobozhang** [comment]
或者有没有其他好的方法，解决这种频繁修改某一个单元格的问题。

**Comment by sentsim** [comment]
更新单行见 `tool` 事件中的 `obj.update()`：https://layui.dev/docs/2/table/#on-tool

**Comment by Adair1990123** [comment]
> 更新单行见 `tool` 事件中的 `obj.update()`：https://layui.dev/docs/2/table/#on-tool

有没有办法在不使用tool的情况下更新单元格/行数据？有些情况没使用tool，但也需要更新单元格/行数据

**Comment by chenxiaobozhang** [comment]
同问：有没有办法在不使用tool的情况下更新单元格/行数据？
我的需求 是websocket 有数据改动，直接反应到table单元格数据变动，而不是 去点击按钮改动
或者 有没有 类似 jquery的trigger 函数，直接触发 tool事件。
