### ISSUE TITLE
table组件好像和 最新版谷歌浏览器有冲突，导致浏览器崩溃

### ISSUE THREAD

**Issue by chenzuijianghu** [layui/layui#1486]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v 2.9.2

### 问题描述

使用最新版谷歌浏览器，在 https://layui.dev/docs/2/table/ **表格组件**
使用代码检查时，会导致浏览器崩溃，不确定是什么原因
mac ，和Windows电脑都有这种问题

### 业务代码

```auto
无
```

### 截图补充

![1703127615668](https://github.com/layui/layui/assets/35945559/cdb693c4-d6cd-4c58-b202-d84ffbff7fc0)
![WX20231221-110540@2x](https://github.com/layui/layui/assets/35945559/07df58e6-e769-46a2-9c6f-71e3bae457d5)

### 浏览器

Chrome 最新版本 版本 120.0.6099.129 | mac /windows

### 演示地址

https://layui.dev/docs/2/table/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
# 1473

**Comment by sentsim** [comment]
> - [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。

关联 #1473
