### ISSUE TITLE
layer.load组件会显示两个加载样式

### ISSUE THREAD

**Issue by aze999** [layui/layui#1488]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.8.18

### 问题描述

直接使用一次layer.load加载了两个样式，在官网也是一样，https://layui.dev/docs/2/layer/#demo-load

### 业务代码

```auto
layer.load(2,{shade: [0.3,'#000']})
```

### 截图补充

![image](https://github.com/layui/layui/assets/54434237/b5390b12-5ced-4f9f-a634-1d62e5751468)

### 浏览器

Chrome 119.0.6045.200（正式版本） （64 位）

### 演示地址

https://layui.dev/docs/2/layer/#demo-load

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
类似的问题在 gitee 那边有三四次报告，但是始终无法重现，也没有任何是否解决的回应。
盲猜是同时引入不同版本的 layui, 或者独立版 layer 所致。
