### ISSUE TITLE
有关于上传组件上传的文件格式的错误提示

### ISSUE THREAD

**Issue by 2598625281** [layui/layui#1490]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.2

### 问题描述

我明明都指明了
acceptMime: 'video/*',
ext: 'mp4',
但是还是提示不支持该类型的文件上传

### 业务代码

```auto
// 视频文件上传
    var videoUpload = upload.render({
        elem: '#UploadVideo',
        url: '/Api/FileUpload.aspx', // 后端API的URL地址
        method: 'POST',
        field: 'videoFile',
        acceptMime: 'video/*',
        ext: 'mp4',
        done: function (res) {
            console.log(res); // 在控制台输出响应数据
        },
        error: function (index, upload) {
            console.log(upload);
        }
    });

    // // 图片文件上传
    // var imageUpload = upload.render({
    //     elem: '#UploadVideoImg',
    //     url: '/Api/FileUpload.aspx', // 后端API的URL地址
    //     method: 'POST',
    //     field: 'imageFile',
    //     accept: 'image/*',
    //     done: function (res) {
    //         console.log(res); // 在控制台输出响应数据
    //     },
    //     error: function (index, upload) {
    //         console.log(upload);
    //     }
    // });
```

### 浏览器

Edge

### 演示地址

内网，发不了

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by 2598625281** [comment]
选择文件后，并没有提交，疑似被阻止前端代码阻止了该请求

**Comment by Sight-wcg** [comment]
accept指定允许上传时校验的文件类型
acceptMime规定打开系统的文件选择框时，筛选出的文件类型
exts允许上传的文件后缀

关闭，因为这并不是 BUG。对于限制文件类型的参数，文档中有明确的描述。该问题属于没有阅读文档，或者错误使用参数。
