### ISSUE TITLE
laydate开启rangeLinked问题

### ISSUE THREAD

**Issue by xw921211** [layui/layui#1501]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.8.12

### 问题描述

laydate开启rangeLinked模式后，选同一个时间，点击两次，然后开始时间和结束时间是反的

### 业务代码

```auto
laydate.render({
            elem: '#datetime_period',
            type: 'datetime',
            range: '~',
            rangeLinked: true,
            format: 'yyyy-MM-dd HH:mm',
            min: '<?= date('Y-m-d H:i:s'); ?>',
            btns: ['clear', 'confirm']
        });
```

### 截图补充

![企业微信截图_20231225140029](https://github.com/layui/layui/assets/68523448/b63632f5-1f74-475a-87a9-08662da3d90b)
![企业微信截图_17034840577817](https://github.com/layui/layui/assets/68523448/ce735dae-d2bb-45d3-beec-397d59a2ba68)

### 浏览器

120.0.6099.110

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sunxiaobin89** [comment]
这个问题在后面的版本已经修复，建议升级到最新稳定版

**Comment by xw921211** [comment]
好的

**Comment by xw921211** [comment]
![企业微信截图_17035935647834](https://github.com/layui/layui/assets/68523448/75fcaa74-7ef5-4b66-a614-531b991bed9f)
最新版也是有问题，在设置了最小时间后，点击最小天日期两次，还是会开始时间和结束时间反过来

**Comment by xw921211** [comment]
> 这个问题在后面的版本已经修复，建议升级到最新稳定版

是还没上线的版本吗，官网最新的也是有这个问题
