### ISSUE TITLE
能够弄一个comboxtree插件，也就是treeSelect，selectTree， 也就是树形的下拉选择控件

### ISSUE THREAD

**Issue by wycto** [layui/layui#1505]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.0

### 问题描述

需要一个树形的下拉选择组建，这个还是比较常用的，下图和代码是我写的一个比较简单的扩展

### 业务代码

```auto
layui.define(function(exports){
    // do something
    const treeSelect = {
        render: function (elem,data,level=1,selectedVal=0) {
            let levelPrefix = '';
            for (let i = 2; i <= level; i++) {
                levelPrefix += '...';
            }

            if(level>1){
                levelPrefix = levelPrefix + "├ "
            }

            for (const element of data) {
                const option = document.createElement('option');
                option.value = element.id;
                option.text = levelPrefix + element.name;

                //给option增加选中属性
                if(element.id == selectedVal){
                    option.selected = true;
                }

                layui.$(elem).append(option);

                if(element.children.length > 0){
                    treeSelect.render(elem,element.children,level+1,selectedVal);
                }
            }
        }
    };

    // 输出 demo 模块
    exports('treeSelect', {
        render: function(options){
            console.log(options);
            treeSelect.render(options.elem,options.data,1,options.selectedVal);
            layui.form.render(layui.$(options.elem));
        }
    });
});
```

### 截图补充

![image](https://github.com/layui/layui/assets/16209943/5a90558c-a8be-40db-b008-26df727e35b6)

### 浏览器

Chrome 已是最新版本 版本 120.0.6099.129（正式版本） (arm64)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sunxiaobin89** [comment]
个人建议可以利用下拉菜单的自定义内容来实现这个功能，[https://layui.dev/docs/2/dropdown/#demo-content](https://layui.dev/docs/2/dropdown/#demo-content)

**Comment by sentsim** [comment]
> 个人建议可以利用下拉菜单的自定义内容来实现这个功能，https://layui.dev/docs/2/dropdown/#demo-content

岁月所言甚是。

**Comment by wycto** [comment]
> 个人建议可以利用下拉菜单的自定义内容来实现这个功能，https://layui.dev/docs/2/dropdown/#demo-content

看了下，也阔以，谢谢

**Comment by wycto** [comment]
> > 个人建议可以利用下拉菜单的自定义内容来实现这个功能，https://layui.dev/docs/2/dropdown/#demo-content
> 
> 岁月所言甚是。

好的，先用用这个

**Comment by jichuanan** [comment]
如果只是想使用一下，可以用第三方开发的layui树形组件，比如：
https://gitee.com/honestno1/combotree
