### ISSUE TITLE
希望table在 利用function来渲染一列数据时， templet 是function时，支持返回jquery对象

### ISSUE THREAD

**Issue by terry2870** [layui/layui#1506]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.8.18

### 问题描述

目前table自定义渲染一列数据时，使用templet，并且templet是一个function时。目前好像该函数只能返回字符串。
希望能支持返回一个jquer对象，这样可以对这个jquery对象进行很多事件绑定，属性绑定等等的操作

### 业务代码

```auto
{field:"demandInfoList",title:"需求",align:"left",templet: function(d) {
    //return layui.$("<div>").html("内容");  // 希望能够支持这样写
    //return "<div>内容</div>";                    // 目前只支持这些
}}；
这样写的好处就是，我在这里可以直接对这个jquery对象设置data，事件，属性。如果只能返回字符串的话，我要对这里的div设置点击事件的话，还要在别处设置一个事件监听才行，比较麻烦
{field:"demandInfoList",title:"需求",align:"left",templet: function(d) {
    let div = layui.$("<div>").html("内容");
    div.data("data", 一些数据);
    div.click(function() {
        alert(123);
    });
    return div;
}};
```

### 浏览器

chrome 119

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by shengxiadexiyang** [comment]
或许可以尝试下templet的【设置模版选择器】的方式
1.首先设置templet
`<th lay-data="{field:'', align:'center', width:120, templet: '#AddSubTpl1'}" rowspan="2">姓名</th>`
2.写模板
`<script type="text/html" id="AddSubTpl1">
    <a class="" lay-event="openSub1" style='width:100%;height: 100%;display: block;'>{{d.name}}</a>
</script>`
3.使用事件
`table.on("tool(MianTable)", function (obj) {
            var data = obj.data,
                layEvent = obj.event;
            switch (layEvent) {
                case "openSub1":
                    openSub1(obj);
                    break;
                default:
            }
        });`

**Comment by sentsim** [comment]
返回 jQuery 对象的用意是什么呢？模板对应的通常是一段字符，而非对象。

另外，类似的 issue 好像在 Gitee 提过吧：https://gitee.com/layui/layui/issues/I8K95Y
尽量不要重复提 issue。
