### ISSUE TITLE
table组件希望能够提供合并行和单元格的api方法

### ISSUE THREAD

**Issue by terry2870** [layui/layui#1507]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.8.18

### 问题描述

系统table组件能够提供一个合并行或单元格的api方法。因为哪些行需要合并是根据后台返回的数据决定的
有的需要两行合并，有的需要三行合并。这个时候就需要在done方法里面去做合并的操作。但是目前还没有合并的行或单元格的方法。这个能不能加一下呢

### 业务代码

```auto
无
```

### 浏览器

chrome 119

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
提 Issue 时，**议题类型**尽量要选择对应的，该 issue 的类型的应该是“功能请求”
