### ISSUE TITLE
table组件优化 update()

### ISSUE THREAD

**Issue by qq303373989** [layui/layui#1511]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.2

### 问题描述

update 的更新行数据，如果表格使用的是字段直接输出内容的话，可以正常更新，如果使用的是模板templet，则模板内容无法更新
如果是简单的模板，模板直接输出的只有对应字段 field 的值，那么模板依然可以更新，但是如果模板输出的，包含行数据的多个值，那么模板数据里面，只会更新field  对应的值。

### 业务代码

```auto
// 更新当前缓存数据
  var update = {};
  update[field] = value;
  obj.update(update, true); // 参数 true 为 v2.7 新增功能，即同步更新其他包含自定义模板并可能存在关联的列视图
```

### 浏览器

所有浏览器

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
无法重现

**Comment by qq303373989** [comment]
模板一      
<script type="text/html" id="table-sp_businessitemtype-content">
                                   {{-d.bi_content.replace(/(?:\r\n|\r|\n)/g, '<br>')}}
                                                </script>
模板二
 <script type="text/html" id="table-sp_businessitemtype-yewu">
                <div class="table-td-contentbox">
                    {{#
                  
                        if(d.bi_fromid==0){}}
                        {{#if(d.bi_classid==1){}}
                        <p>{{d.s_title}}</p>
                        <p>{{d.s_os}} {{d.s_cpu_cores}}核 {{d.s_ram}}G</p>
                        <p>公网IP：{{d.s_ip}} &nbsp; &nbsp; 内网IP：{{d.s_pip}}</p>


                        {{#}else if(d.bi_classid==2){}}
                        <p>{{d.d_domain}}</p>
                        {{#}}}


                    {{#}else{}}

                        {{#if(d.bi_classid==1){}}
                        {{#if(d.s_domain){}}
                        <p>{{-d.s_domain?d.s_domain.map(JSON.stringify).join('&nbsp; &nbsp;').replace(/"/g, ''):''}}</p>
                        {{#}}}
                        <p>{{d.s_os}} {{d.s_cpu_cores}}核 {{d.s_ram}}G</p>
                        <p>公网IP：{{d.s_ip}} &nbsp; &nbsp; 内网IP：{{d.s_pip}}</p>


                        {{#}else if(d.bi_classid==2){}}
                        <p>{{d.d_domain}}</p>
                        {{#}}}


                    {{#}}}
                </div>
            </script>
模板一这种是可以更新的，模板二这种多个字段的就无法更新

**Comment by Sight-wcg** [comment]
不，这不是重现，请提供完整的，可运行的，可重现问题的代码。
我在本地无法重现这个问题。
