### ISSUE TITLE
表格使用 table.setRowChecked(id, opts)  api设置单选框选中状态后，没有触发单选框事件

### ISSUE THREAD

**Issue by ning-ll** [layui/layui#1516]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.1

### 问题描述

表格使用 table.setRowChecked(id, opts)  api设置单选框选中状态后，没有触发表格的单选框事件。

### 业务代码

```auto
table.on('row(RisList)', function (obj) {

        var index = obj.index; // 得到当前行索引

        table.setRowChecked('RisList', { type: 'radio', index: index, checked:true });


    });
```

### 浏览器

Chrome 120.0.6099.111

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
需要点击单选框才能触发
![1](https://github.com/layui/layui/assets/33601030/4289302b-b80c-492f-93f9-6ef8bdd1ed06)

**Comment by ning-ll** [comment]
我还尝试了另一种方式，在行单击的时候，直接调用封装的触发函数。

    table.on('row(RisList)', function (obj) {

        var index = obj.index; // 得到当前行索引

        table.setRowChecked('RisList', { type: 'radio', index: index, checked:true });

        var data = table.cache['RisList'] || {};
        var onlyId = '';

        for (var i = 0; i < data.length; i++)
        {
            if (data[i].LAY_CHECKED)
            {
                onlyId = data[i].onlyId;
                break;
            }
        }
        
        if (onlyId != '') GetRisResult(onlyId);   //调用封装的函数
    });

**Comment by ning-ll** [comment]
还有另一种思路，在行点击事件中直接调用我的函数。

       `table.on('row(RisList)', function (obj) {

        var index = obj.index; // 得到当前行索引

        table.setRowChecked('RisList', { type: 'radio', index: index, checked:true });

        var data = table.cache['RisList'] || {};
        var onlyId = '';

        for (var i = 0; i < data.length; i++)
        {
            if (data[i].LAY_CHECKED)
            {
                onlyId = data[i].onlyId;
                break;
            }
        }

        if (onlyId != '') GetRisResult(onlyId);  //调用封装的函数
    });`
