### ISSUE TITLE
官网下载好像还是2.9.2

### ISSUE THREAD

**Issue by ken678** [layui/layui#1531]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.3

### 问题描述

![image](https://github.com/layui/layui/assets/15792472/ae4ab11a-be68-49d6-8665-36549232a3dd)
![image](https://github.com/layui/layui/assets/15792472/e3ee65cc-bec4-4325-ac37-e9b98311f314)

### 业务代码

```auto
无
```

### 浏览器

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by isfk** [comment]
https://layui.dev/docs/2/versions.html#v2.9.3 去这里下

**Comment by sentsim** [comment]
确实忘了更新下载链接，已经改好了。
