### ISSUE TITLE
日期与时间选择器 laydate中的时间选择在移动端几乎无法操作

### ISSUE THREAD

**Issue by artrogue** [layui/layui#1533]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.3

### 问题描述

日期与时间选择器 laydate中的时间选择在移动端几乎无法操作，建议适当改进以提高该组件在移动端的可操作性

### 业务代码

```auto
laydate.render({
  elem: '#choosetime',
  type: 'time',
  format: 'H:m'
});
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
无法操作是指怎样的操作？
你做了什么操作，日期选择器表现出什么样的效果？期望的效果是什么？

**Comment by artrogue** [comment]
> 无法操作是指怎样的操作？ 你做了什么操作，日期选择器表现出什么样的效果？期望的效果是什么？

移动端表现上无法使用手指滑动 小时/分钟/秒 的数字栏
必须先点选一个小时/分钟/秒的数字后，再尝试向下滑动，才可能选择的到对应的小时/分钟/秒 数字

**Comment by Sight-wcg** [comment]
> > 无法操作是指怎样的操作？ 你做了什么操作，日期选择器表现出什么样的效果？期望的效果是什么？
> 
> 移动端表现上无法使用手指滑动 小时/分钟/秒 的数字栏
> 必须先点选一个小时/分钟/秒的数字后，再尝试向下滑动，才可能选择的到对应的小时/分钟/秒 数字

移动端 Chromium 73, 112 无法重现

**Comment by artrogue** [comment]
微信内置浏览器
IOS17.2.1 微信8.0.45

**Comment by artrogue** [comment]
或者微信开发者工具 也可以重现，我用的版本是windowns版  stable 1.06.2308310

**Comment by bxjt123** [comment]
> > 无法操作是指怎样的操作？ 你做了什么操作，日期选择器表现出什么样的效果？期望的效果是什么？
> 
> 移动端表现上无法使用手指滑动 小时/分钟/秒 的数字栏 必须先点选一个小时/分钟/秒的数字后，再尝试向下滑动，才可能选择的到对应的小时/分钟/秒 数字

这个应该是正常的，移动端没有鼠标可以判断位置，默认滑动是页面滚动，你要点了时/分/秒将焦点切到对应列表，用手指滑动的才是时间列表
