### ISSUE TITLE
number 输入框 可以输入两个减号--   ，并且位置 可以在两个数字之间

### ISSUE THREAD

**Issue by wtta1812** [layui/layui#1534]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.13

### 问题描述

number 输入框 可以输入两个减号--   ，并且位置 可以在两个数字之间
![image](https://github.com/layui/layui/assets/34429383/7c6d402c-f65f-4014-b59b-f4f6eef3fe70)

### 业务代码

```auto
无
```

### 浏览器

谷歌

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
Layui 对 `< input type="number">` 的字符格式没有做相关限制，浏览器允许对 `number` 框输入正负数值，即诸如 `-` `+`这些字符都是被许可的，如 `-11`。但是，考虑到 `number` 框同时还支持浮点型和科学计数法，除了 `-` `+`，还会涉及到 `.` `e` 等字符，如 `1.1e-11`，格式的判断可谓纷繁复杂。因此我建议，如果业务对数据类型敏感，直接对 `<input>` 设置 `readonly` 可能会更好。

**Comment by Sight-wcg** [comment]
`<input type="number">` 目前只是对原生 input number 的美化，行为和原生基本一致，2.x 暂不考虑做调整。

**Comment by Sight-wcg** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398528
