### ISSUE TITLE
有没有不通过tool事件，直接更新table单元格/单行数据的方法

### ISSUE THREAD

**Issue by chenxiaobozhang** [layui/layui#1538]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.2

### 问题描述

业务场景：websocket获取数据，需要频繁更新talbe的“状态”列，其他列不需要更新；这种情况需要直接更新单元格数据，而不能使用tool事件！
业务需求：有没有办法直接更新单元格数据 ，或者类似jquery的trigger方法直接触发某一行的tool事件来更新数据

### 业务代码

```auto
目前我只能  table.reloadData(id, options, deep); 重载整个表格数据
```

### 截图补充

![760ec59ac999e26c75c2a3a55831dee](https://github.com/layui/layui/assets/23134309/442f8642-3b90-4f6e-87d0-361b8b9e4cbe)

### 浏览器

Chrome浏览器最新版本

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
目前为止只能使用`reload()`重载方法，未来可能会有`getRow()、setRow()`之类的更新行方法。

**Comment by chenxiaobozhang** [comment]
我有100行数据，每行数据后面有10个按钮，每个按钮都绑定了事件，而状态列每秒更新一次，难道只能每秒reload一次么?
肯定是类似tool事件的update方法效率更高啊，但是又没法使用tool事件，好难受

**Comment by bxjt123** [comment]
`trigger`实际上也可以，隐藏操作栏按钮即可，以下仅供参考
```
<table class="layui-hide" id="ID-test-table"></table>
<script type="text/html" id="ID-demo-table-tool">
  <a class="layui-btn layui-btn-primary layui-btn-xs layui-hide" lay-event="edit">编辑</a>
  <!--其他按钮-->
</script>

table.render({
  elem: '#ID-test-table',
  //其他属性
  cols: [[
    //其他列
    {field: 'city', title: '城市'},
    {title: '操作', toolbar: '#ID-demo-table-tool'}
  ]]
});
table.on('tool(ID-test-table)', function(obj) {
  var data = obj.data;
  var layEvent = obj.event;
  if (layEvent === 'edit') {
    obj.update({city:"更新"+data.id}); //更新某个单元格
  }
});
//以下放在需要更新的地方 layui-table-main限定主表格 防止右固定列重复执行
$(".layui-table-main .layui-table-cell>a[lay-event=edit]").trigger("click");
```
![1](https://github.com/layui/layui/assets/33601030/d74a02f8-8714-41d9-b18e-6584a6a2ce54)

**Comment by Sight-wcg** [comment]
duplicate #1483

**Comment by chenxiaobozhang** [comment]
感谢大佬新增的方法，完美解决我的问题！超级点赞！
