### ISSUE TITLE
talbe 分页搜索时点击其他页面的请求参数该如何重置

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#1542]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.3

### 问题描述

在使用table 外部搜索功能时，有一个下拉框是控制本地数据搜索或者外部采集的，后端逻辑是如果选择外部采集则先采集数据保存到本地再搜索本地数据返回到前端，再通过js代码将下拉框的值重置为了本地，但是切换到第二页时下拉框的请求参数仍然是第一次搜索的值，这我该如何控制页面切换时使用新的下拉框值呢

### 业务代码

```auto
form.on('submit(本地查询)', function (data) {
            var field = data.field; // 获得表单字段
            field.action = "list"
            // 执行搜索重载
            table.reload('demo', {
                page: {
                    curr: 1 // 重新从第 1 页开始
                },
                where: field, // 搜索的字段,
                complete: function (xhr, ts) {
                    // 重新渲染
                    $("#接口").val("本地");
                    form.render('select');
                }
            });
            return false; // 阻止默认 form 跳转
        });
```

### 截图补充

这是第一次请求，下拉框接口选择外部的
![image](https://github.com/layui/layui/assets/112995594/8c04ebcd-3ce0-488d-acf6-7c2b6d9206f7)
通过上述js实现请求完成后重置下拉框的值
此时下拉框的值已经修改为本地，当我点击分页时发现请求参数中接口值还是外部的
![image](https://github.com/layui/layui/assets/112995594/ded08a62-294e-4dc6-8800-c0d3e6a50a71)

### 浏览器

edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
额，下拉框和表格又没有什么关联，改变了下拉框的值，不用点按钮重新搜索重载表格数据吗？

**Comment by bxjt123** [comment]
重载时用的`where`条件还是旧的，并且`complete`后才改变下拉框，本质上表格翻页搜索的还是旧条件。
改变下拉框值后，可以用新条件重载表格数据。

**Comment by wwsuixin** [comment]
> 重载时用的`where`条件还是旧的，并且`complete`后才改变下拉框，本质上表格翻页搜索的还是旧条件。 建议先改变下拉框值后，再重载表格。

我的业务需求是第一次使用的搜索条件与选择第二页所使用的搜索条件中 有一个参数是不一样的，看起来只能把这个需求拆分成两个按钮去实现了
