### ISSUE TITLE
建议改进button事件机制

### ISSUE THREAD

**Issue by netmou** [layui/layui#1544]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.3

### 问题描述

button  文档中压根就没提事件处理是不是过分了，button  肯定是跟事件结合的吗，不然页面上放按钮干什么，现在还要以来jquery作事件监听？？能否给个demo展示下layui  页面按钮如何加事件

### 业务代码

```auto
无
```

### 截图补充

无

### 浏览器

chrome 119

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by corededitor** [comment]
兄弟你是不是对“过分”一词有什么误解，有这么盛气凌人提建议的吗？

**Comment by Sight-wcg** [comment]
按钮是否添加事件，取决于业务需求。组件库的文档编写时，我们假设您已经掌握了 HTML，JavaScript 和 CSS 。如果没有，直接使用组件库可能不是一个好的开始，建议先掌握前置技术。

如果不想使用 jQuery，可以参考 MDN https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener

关闭，因为这不是 BUG。
