### ISSUE TITLE
数字输入框输入小数在提交表单时会报错,导致无法提交

### ISSUE THREAD

**Issue by DukeJin-Dev** [layui/layui#1551]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.8.18

### 问题描述

数字输入框如果输入小数在提交表单时会报错,导致无法提交
![Capture](https://github.com/layui/layui/assets/85550799/ab8cd7a2-ff1e-409b-98ff-6bb2e5c2459e)

### 业务代码

```auto
<form method="post" id="ListForm" class="layui-form" action="xxxxxx">
    <div class="layui-row">
        <div class="layui-form-item layui-col-md3">
            <div class="layui-input-block">
                <input type="number" lay-affix="number" placeholder="" value="0" class="layui-input">
            </div>
        </div>
        <button type="submit" name="export-xlsx" value="export-xlsx" class="layui-btn layui-btn-sm pull-right margin-l-10" id="Export">@T("Export")</button>
    </div>
</form>
```

### 截图补充

![image](https://github.com/layui/layui/assets/85550799/3ce5013c-98d5-48f4-a179-78305ea5456b)

### 浏览器

Chrome Version 120.0.6099.200 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这是预期的行为，不是 Bug。以下仅供参考
1. 参考 MDN 
如果要输入一个需要小数的值，则需要修改 step 值（例如，step="0.01" 以允许 2 位小数）
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/number#%E5%85%81%E8%AE%B8%E5%B0%8F%E6%95%B0%E5%80%BC

2. 参考 layui 文档，在 submit 事件回调中返回 false, 使用 ajax 提交表单
https://layui.dev/docs/2/form/#submit
