### ISSUE TITLE
table 多行模式列超文本没有格式

### ISSUE THREAD

**Issue by liusongzhou** [layui/layui#1553]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.0

### 问题描述

        table 某列的文本很多且有格式（缩进、段落、空格等）。用多行模式显示，显示的是没有格式的文本，本人修改了一下列样式，允许有格式呈现，是可以显示有格式的文本。但切换成单行模式后，也把修改的样式还原成初始值，原有的单行显示效果就没有了，出现列横向、纵向滚动条。自己能力有限，特地将此问题向上反馈，希望在下一个版本，能有所优化。谢谢！

在此向您们致敬！

### 业务代码

```auto
// 行模式
      dropdown.render({
        elem: '#rowMode',
        data: [{
          id: 'default-row',
          title: '单行模式（默认）'
        },{
          id: 'multi-row',
          title: '多行模式'
        }],
        // 菜单被点击的事件
        click: function(obj){
          var checkStatus = table.checkStatus(id)
          var data = checkStatus.data; // 获取选中的数据
          switch(obj.id){
            case 'default-row':
              table.reload('test', {
                lineStyle: null // 恢复单行
              });
              layer.msg('已设为单行');
            break;
            case 'multi-row':
              table.reload('test', {
                // 设置行样式，此处以设置多行高度为例。若为单行，则没必要设置改参数 - 注：v2.7.0 新增
                lineStyle: 'height: 95px;' 
              });
              layer.msg('即通过设置 lineStyle 参数可开启多行');
            break;
          }
        }
      });
```

### 浏览器

chrome 88.0.4324.104

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
没有格式是指什么，是否直接输出了 HTML 原字符，尝试在 table 的文档查找 `escape` 属性去解决问题。
最好提供完整的示例和截图。

**Comment by liusongzhou** [comment]
您好！
1.添加有格式的文本
2.在多行模式显示如图…227.jpg
3.应显示如图 …252.jpg




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 下午2:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [layui/layui] table 多行模式列超文本没有格式 (Issue #1553)




 
@liusongzhou 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
  
产生问题的详细步骤
 
与问题相关的完整代码
 
在线 Demo (推荐通过 stackblitz 或 codepen 创建)
   
详见：🍀 Layui Issue 贡献指南
 延伸：👉 为什么要提供最小化重现？

**Comment by liusongzhou** [comment]
1.列文本过多时通过下拉箭头展开，原始显示效果：如qq邮件中的图…227.jpg；后来将样式中的.layui-table-cell{white-space: nowrap;}修改成.layui-table-cell{white-space: break-spaces;}后，显示的效果如…252.jpg；
2.后来想若每行都有超文本列需要通过点击下拉箭头展开，很频繁。为了操作简单，就采用多行模式来显示。结果没有格式，如是按照修改样式.layui-table-cell的方法去修改，结果效果达到了，有格式。但切换到单行模式时，列就有横向滚动条、纵向滚动条，下拉箭头也没有了。由于是一个星期前发现的问题，当时没有及时反馈，造成现在无法提供代码给您，很抱歉！

**Comment by liusongzhou** [comment]
补充一下：
1.列文本过多时通过下拉箭头展开，原始显示效果：如qq邮件中的图…227.jpg；后来将样式中的.layui-table-expanded .layui-table-cell{white-space: nowrap;}修改成.layui-table-expanded .layui-table-cell{white-space: break-spaces;}后，显示的效果如…252.jpg；

**Comment by sentsim** [comment]
看不到图片，不要在邮件中回复 Issue。

**Comment by liusongzhou** [comment]
公司电脑受限制了，暂时传不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [layui/layui] table 多行模式列超文本没有格式 (Issue #1553)




 
看不到图片，不要在邮件中回复 Issue。

**Comment by liusongzhou** [comment]
我已单独发邮件（含图片、附件）给notifications@github.com，麻烦notifications大佬查看一下，谢谢！

**Comment by sentsim** [comment]
> 我已单独发邮件（含图片、附件）给[notifications@github.com](mailto:notifications@github.com)，麻烦notifications大佬查看一下，谢谢！

notifications大佬是谁？Notifications 是 Github 官方的系统邮箱啊亲………  😥

几点建议：
1. 把 Chrome 升级一下（ Chrome 88.0 还是多少年前的版本）
2. 不要在 Github 推送的邮件中进行回复，前面已经强调了
3. 如果公司的网络无法登录 Github，那么可再下班后，在家里的电脑登录将 Issue 好好描述下。

**Comment by liusongzhou** [comment]
不好意思，下次注意，接受您的建议，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月12日(周五) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [layui/layui] table 多行模式列超文本没有格式 (Issue #1553)




  
***@***.***，麻烦notifications大佬查看一下，谢谢！
  
notifications大佬是谁？Notifications 是 Github 官方的系统邮箱啊亲………  😥
 
几点建议：
  
把 Chrome 升级一下（ Chrome 88.0 还是多少年前的版本）
 
不要在 Github 推送的邮件中进行回复，前面已经强调了
 
如果公司的网络无法登录 Github，那么可再下班后，在家里的电脑登录将 Issue 好好描述下。

**Comment by liusongzhou** [comment]
听从建议，把 Chrome 升级到最新版，多文本模式显示的文本有格式。谢谢！，申请该问题关闭，谢谢！
