### ISSUE TITLE
关于上传组件

### ISSUE THREAD

**Issue by wangda2000** [layui/layui#1564]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.3

### 问题描述

请问如何获得当前的上传实例对象呢，
![image](https://github.com/layui/layui/assets/123173907/96b33b00-31af-40ba-a135-1f2ba4e7e38c)
我这个是多实例上传，之前的2.7版本我在done回调中我直接uploadInst.reload了下url，在调用uploadInst.upload()是没问题的，现在升级2.9.3版本，代码没变的情况下，报错了
![image](https://github.com/layui/layui/assets/123173907/78cb98bf-bfea-45c9-96db-e771179d95fe)

### 业务代码

```auto
uploadInst.reload({url: 'xxxx'});
uploadInst.upload();
```

### 浏览器

120.0.6099.217（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by wangda2000** [comment]
https://stackblitz.com/edit/web-platform-jx8gnq?file=2.8test.html,2.9test.html

**Comment by wangda2000** [comment]
> @wangda2000好的，请提供一个最小化的拆卸，以便我们为您协助排查问题。好的拆卸应该包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线演示（推荐通过[stackblitz](https://stackblitz.com/)或[codepen](https://codepen.io/)创建）
> 
> > 请参阅：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉[为什么要提供最小化隐藏？](https://antfu.me/posts/why-reproductions-are-required-zh)

重现地址 https://stackblitz.com/edit/web-platform-jx8gnq?file=2.8test.html,2.9test.html

**Comment by wangda2000** [comment]
https://github.com/layui/layui/issues/1566#issuecomment-1892400340 大佬，已经提供重现

**Comment by wangda2000** [comment]
@Sight-wcg  您好 重现地址为https://stackblitz.com/edit/web-platform-jx8gnq?file=2.8test.html,2.9test.html

**Comment by LSL1618** [comment]
你这个是不是应该用`id`去绑定实例，而不是用`class`，这样每个实例对应各自独立唯一的`id`就不会乱套报错了。

**Comment by wangda2000** [comment]
> 你这个不是应该`id`用去绑定实例，而不是用`class`，这样每个实例对应各自独立唯一的`id`就不会乱套报错了。

 我这个是个文件上传列表组件，id是无法确定的，之前的版本每次上传后都能拿到当前上传的实例，现在的版本却不行了
