### ISSUE TITLE
树组件增加搜索功能

### ISSUE THREAD

**Issue by JasonZhuAtamation** [layui/layui#1566]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.3

### 问题描述

树组件，缺少搜索功能，并且被搜索到的内容的颜色最好可以支持自定义

### 业务代码

```auto
新功能特征
```

### 浏览器

常用浏览器

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
tree 组件的功能增加不在当前 2.x 版本计划之内，复杂的树形菜单需求，建议采用更成熟的同类组件替代。

**Comment by JasonZhuAtamation** [comment]
好的，谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 晚上11:40
收件人: ***@***.***&gt;;
抄送: "jason ***@***.******@***.***&gt;;
主题: Re: [layui/layui] 树组件增加搜索功能 (Issue #1566)




 
tree 组件的功能增加不在当前 2.x 版本计划之内，复杂的树形菜单需求，建议采用更成熟的同类组件替代。
