### ISSUE TITLE
表格列不设置，右侧有空白

### ISSUE THREAD

**Issue by quliting** [layui/layui#1568]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.3

### 问题描述

![image](https://github.com/layui/layui/assets/14035957/74e80687-a7f8-43cf-8617-2bd43e9d8b35)
width 不设置。最右侧出现这个；

### 业务代码

```auto
{type: "numbers", title: "序号", },
{ field: "Name", title: "" },
{ field: "MakeOrChange", title: "",  },
{ field: "StandardCode", title: "",  },
{ field: "ApplyPerson", title: "联系人",  },
{ field: "GeneralPhone", title: "联系电话",  },
{ field: "DepartmentName", title: "",  },
{ field: "ApplyDate", title: "",  },
部门title 删除了，
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by quliting** [comment]
是吗？？？

**Comment by quliting** [comment]
请问，哪个版本算是稳定，因为我着急交付项目

**Comment by LSL1618** [comment]
试试将空的`title`给个占位符，比如`-、_、/、\`

**Comment by sunxiaobin89** [comment]
不确定你都做了什么操作才出现这种情况，出现这种情况的时候可以试试执行一下table.resize();试一下是否可以通过重新调整大小来修正，从截图看像是残留了一个滚动条补丁的位置，但是不确定是做了什么操作执行了什么出现这个现象的所以无法判断原因是什么

**Comment by quliting** [comment]
> 不确定你都做了什么操作才出现这种情况，出现这种情况的时候可以试试执行一下table.resize();试一下是否可以通过重新调整大小来修正，从截图看像是残留了一个滚动条补丁的位置，但是不确定是做了什么操作执行了什么出现这个现象的所以无法判断原因是什么

我用这个版本做一个demo；

**Comment by quliting** [comment]
> 不好意思，这个问题很难解决，暂时搁置。

是吗？

**Comment by sentsim** [comment]
由于始终没有收到问题重现的 Demo，该问题暂时关闭。
