### ISSUE TITLE
laydate如何设置结束时间不能小于开始时间

### ISSUE THREAD

**Issue by Orange8** [layui/layui#157]
```
        //年月选择器
	var start = {
	  elem: '#test1',
	  type: 'month',
	  done: function(value, date, endDate){
	  	end.min = date.year+'-'+date.month+'-'+date.date; //开始日选好后，重置结束日的最小日期
	  	contractMonthStart = value;
	  	// ajaxReport(contractMonthStart, contractMonthEnd, orgNo);
	  }
	};
	var end = {
	  elem: '#test2',
	  type: 'month',
	  done: function(value, date, endDate){
	  	start.max = date.year+'-'+date.month+'-'+date.date; //结束日选好后，重置开始日的最大日期
	  	contractMonthEnd = value;
	  	// ajaxReport(contractMonthStart, contractMonthEnd, orgNo);
	  }
	};
	laydate.render(start);
	laydate.render(end);
```

**Comment by getElementByClass** [comment]
var stValue = new Date(new Date() - 24 * 60 * 60 * 1000).getFullYear() + '-' + ((new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1) < 10 ? '0' + (new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1) : (new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1)) + '-01';
        var maxValue = new Date(new Date() - 24 * 60 * 60 * 1000).getFullYear() + '-' + ((new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1) < 10 ? '0' + (new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1) : (new Date(new Date() - 24 * 60 * 60 * 1000).getMonth() + 1)) + '-' + (new Date(new Date() - 24 * 60 * 60 * 1000).getDate() < 10 ? '0' + new Date(new Date() - 24 * 60 * 60 * 1000).getDate() : new Date(new Date() - 24 * 60 * 60 * 1000).getDate());    
        var StChoose = laydate.render({
            elem: '#incomeInput1', //指定元素
            value: stValue,
            max: maxValue,
            showBottom: false,
            done: function(value, date, endDate) {
                $('#incomeInput2').val('');
                EdChoose.config.min = {
                    year: date.year,
                    month: date.month - 1,
                    date: date.date + 1,
                    hours: date.hours,
                    minutes: date.minutes,
                    seconds: date.seconds
                };
                EdChoose.config.max = {
                    year: date.year,
                    month: date.month + 2,
                    date: date.date - 1,
                    hours: date.hours,
                    minutes: date.minutes,
                    seconds: date.seconds
                };
            },
        });
        var EdChoose = laydate.render({
            elem: '#incomeInput2', //指定元素
            min: get3MonthBefor(),
            max: maxValue,
            value: maxValue,
            showBottom: false,
        });

**Comment by davinma** [comment]
需要在 `layui.use()` 中引入 `laydate` 和 `util` 模块，大致这么写：

`````
    var timeNow = util.toDateString(new Date());

    // 渲染开始发送时间组件
    laydate.render({
        elem: '#LAY-time-start',
        type: 'datetime',
        value: timeNow,
        min: timeNow,
        format: 'yyyy-MM-dd HH:mm:ss'
    });

    // 渲染结束发送时间组件
    laydate.render({
        elem: '#LAY-time-end',
        type: 'datetime',
        min: timeNow,
        format: 'yyyy-MM-dd HH:mm:ss'
    });
`````
