### ISSUE TITLE
希望 去掉 或 可配置 dropdown，[type: '-']分割线的上下填充，保持选项的高度一致。

### ISSUE THREAD

**Issue by pkkgu** [layui/layui#1573]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.4

### 问题描述

希望去掉或可配置dropdown，[type: '-']分割线的上下填充，保持高度一致。

### 业务代码

```auto
dropdown.render({
    elem: '.demo-dropdown-base', // 绑定元素选择器，此处指向 class 可同时绑定多个元素
    data: [{
      title: 'menu item 1',
      id: 100
    }, {
      type: '-' // 分割线
    },{
      title: 'menu item 2',
      id: 101
    },{
      title: 'menu item 3',
      id: 102
    }],
    click: function(obj){
      this.elem.find('span').text(obj.title);
    }
  });
```

### 浏览器

遨游 7.1.7.8800

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
尝试借助 `className` 属性去自定义样式来实现重置分割线边距
docs: https://layui.dev/docs/2/dropdown/#options

**Comment by pkkgu** [comment]
OK
