### ISSUE TITLE
Table组件增加按列筛选功能

### ISSUE THREAD

**Issue by antgogogo** [layui/layui#1576]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.4

### 问题描述

建议在Table组件中新增按列筛选当前页数据的功能，类似excel那样。
或者在表头下新增一行筛选行，可以按每列进行筛选。
具体请看图片展示。
![图片](https://github.com/layui/layui/assets/19969432/04ff7130-1a21-4405-82af-6a48d5d417de)

### 业务代码

```auto
无
```

### 浏览器

Microsoft Edge 版本 119.0.2151.72 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #1556

**Comment by bxjt123** [comment]
或许可以试试[layui-soul-table](https://yelog.org/layui-soul-table/#/zh-CN)
