### ISSUE TITLE
treeTable 添加支持自定义code

### ISSUE THREAD

**Issue by aveyuan** [layui/layui#1579]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.4

### 问题描述

树型表格考虑下像表格那样支持自定义code状态码，而不是写死。扩展性有点差

### 业务代码

```auto
无
```

### 浏览器

edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
table 组件的所有 API 均适用于 treeTable 组件。可以使用 parseData 回调函数将数据解析并转换为默认规定的格式。

**Comment by aveyuan** [comment]
> table 组件的所有 API 均适用于 treeTable 组件。可以使用 parseData 回调函数将数据解析并转换为默认规定的格式。

table提供了code属性，treeTable也提供code相关属性，对齐岂不是更好？
