### ISSUE TITLE
V2.9.4移动端Table组件BUG反馈

### ISSUE THREAD

**Issue by LuckyMoke** [layui/layui#1580]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.4

### 问题描述

2.9.4版本中table组件本地更新增加的修复代码，疑似在移动端造成BUG。

- 安卓端（Alook浏览）：造成输入法疯狂弹出闪动
- IOS端（Safari浏览器）：造成页面直接跳到最底部

疑似input相关造成的，2.9.3版本无此问题。

![PixPin_2024-01-22_11-36-01](https://github.com/layui/layui/assets/14307269/17825e44-51b3-4d3a-9651-595e3e71beef)

### 业务代码

```auto
直接使用的官网演示代码。
```

### 截图补充

演示视频：

https://github.com/layui/layui/assets/14307269/71d46171-8fb3-47f6-9a1b-17d3501dba51

### 浏览器

Alook

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
我在wide Android 机测试未复现该问题。由于没有 Apple 机，IOS 尚未测试。

**Comment by LuckyMoke** [comment]
完整的使用官网文档里的代码演示，2.9.3版本没有问题，2.9.4版本疯狂弹输入法。

https://github.com/layui/layui/assets/14307269/92b8d687-d165-4045-88f0-a4519fe2acb3

手机浏览器内核UA。

Mozilla/5.0 (Linux; Android 12; TFY-AN00 Build/HONORTFY-AN00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36
