### ISSUE TITLE
希望能提供可编辑的下拉框控件

### ISSUE THREAD

**Issue by jianhao84** [layui/layui#1581]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.8.17

### 问题描述

希望能提供可编辑的下拉框控件

### 业务代码

```auto
无
```

### 浏览器

chrome115.0.5790.171

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sinbh** [comment]
是的，有些不太严格的场景下，是可以允许用户输入或选择的，或者某些场景选择的值来自用户的输入累积，当第一个用户使用时他必然要输入，虽然可以通过dropdown来实现这个需求，但还是希望下拉框有个属性能开放用户输入，这样使用上更方便些。

**Comment by LSL1618** [comment]
> 是的，有些不太严格的场景下，是可以允许用户输入或选择的，或者某些场景选择的值来自用户的输入累积，当第一个用户使用时他必然要输入，虽然可以通过dropdown来实现这个需求，但还是希望下拉框有个属性能开放用户输入，这样使用上更方便些。

有一点不好区分，输入内容是用于检索已有选项呢，还是用于创建新选项并作为选中项呢！

**Comment by bxjt123** [comment]
或许可以试试[xm-select](https://maplemei.gitee.io/xm-select/#/)

**Comment by itbencn** [comment]
这个提议非常棒,目前刚好遇到这个场景,暂时只能用dropdown
但是dropdown没有检索功能不太方便

**Comment by jianhao84** [comment]
是用的这个，但是最好框架支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 青崖 ***@***.***&gt;
发送时间: 2024年1月23日 19:45
收件人: layui/layui ***@***.***&gt;
抄送: jianhao84 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [layui/layui] 希望能提供可编辑的下拉框控件 (Issue #1581)





 
或许可以试试xm-select
