### ISSUE TITLE
layui.slider 能否支持小数步进？

### ISSUE THREAD

**Issue by caocos** [layui/layui#1582]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.4

### 问题描述

无论 range 是否为 true 时，都希望能支持 step 以小数步进，代码见业务代码部分

### 业务代码

```auto
以下代码无法如期望运行，希望贤心能看到这里
slider.render({
    elem: '#slider-so-range',
    step: 0.001,
    value: [1.05, 3.1],
    range: true,
    done: function(value){
        console.log(value);
    }
});
```

### 浏览器

> 0.5%

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
你可以试试把小数放大倍数转成整数，不一定非得用小数。
