### ISSUE TITLE
chrome devtools检视iframe中table崩溃问题已经解决了

### ISSUE THREAD

**Issue by yhl452493373** [layui/layui#1583]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.4

### 问题描述

之前chrome检视iframe中的table会导致页面崩溃，2.9.4中提了个pr临时修复，但是这个pr会导致开了chrome devtools时，iframe中表格宽度不正确。今天macos下chrome更新到121.0.6167.85，用2.9.3测试，已经不会再崩溃了。

### 业务代码

```auto
无
```

### 浏览器

121.0.6167.85

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
看上去 #1571 的补丁确实造成了较大困扰，目前在 MacOS 之外的系统尚未检测到 Chrome 121 的更新。如果确认 DevTools 已经修复该问题，该实验性的补丁将会在第一时间剔除，以尽量减少影响面。

**Comment by Herney123** [comment]
更新之后部分电脑input聚焦有问题，input.focus();失效了
