### ISSUE TITLE
更新2.9.4之后部分电脑input聚焦有问题，input.focus();失效了

### ISSUE THREAD

**Issue by Herney123** [layui/layui#1585]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.4

### 问题描述

更新2.9.4之后部分电脑input自动聚焦有问题，input.focus();失效了

### 业务代码

```auto
const $shop_input= $("#shop_input");
$shop_input.focus();
```

### 浏览器

Chrome 121.0.6167.86（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
已有类似的 Issue，不要重复提。
