### ISSUE TITLE
低版本浏览器模板无法运行 js方法 

### ISSUE THREAD

**Issue by wlf2r** [layui/layui#1596]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.96

### 问题描述

目前测试 搜狗浏览器8.6.0.30561版本的 模板无法运行js方法
![image](https://github.com/layui/layui/assets/13636275/29520908-5550-46b7-9cab-c7fc4d07f197)
 

### 业务代码

```auto
{{# var rs = _cDom.showDom(d.data[index]) }} 与
{{- _cDom.showDom(d.data[index]) }}

运行报
ypeError: template[o].replaceAll is not a function
```

### 浏览器

 搜狗浏览器8.6.0.30561

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
replaceAll 是 ES2021 添加的，低版本浏览器不支持。建议使用 replace 或者添加replaceAll 的 Polyfill。

**Comment by wlf2r** [comment]
整个layui.js 搜索去掉replaceAll 还是报此错，_cDom.sowDom 此方法只是返回字符串
