### ISSUE TITLE
关于火狐浏览器使用Layui 拖拽上传 文件会被浏览器打开BUG及解决方案

### ISSUE THREAD

**Issue by FEJackFly** [layui/layui#160]
在火狐48.0b7版本中使用拖拽上传时 上传文件依然可以打开，解决方案如图

**Comment by JackFlyL** [comment]
![image](https://user-images.githubusercontent.com/24688308/35796785-931a35ea-0a98-11e8-9075-0328ae06eb4b.png)

**Comment by JackFlyL** [comment]
如果看到请在下个版本能修复
