### ISSUE TITLE
动态点缀无法设置多项

### ISSUE THREAD

**Issue by 36Dyyds** [layui/layui#1602]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.6

### 问题描述

密码框显隐和内容清除无法同时使用

### 业务代码

```auto
lay-affix="eye"
lay-affix="clear"
```

### 浏览器

火狐浏览器最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
暂无计划支持
