### ISSUE TITLE
修复 Chrome DevTools 审查 iframe srcdoc 中的 table 元素时导致页面崩溃的问题  目前依然崩溃

### ISSUE THREAD

**Issue by yz8943** [layui/layui#1608]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.6

### 问题描述

升级到v2.9.6版本 iframe 的table 元素依然导致崩溃 出现STATUS_STACK_OVERFLOW

### 业务代码

```auto
就是普通的代码之前都可以。
```

### 截图补充

![image](https://github.com/layui/layui/assets/10083920/a8f88389-362c-4a2c-960e-18fc05254dc5)

### 浏览器

121.0.6167.86（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
ref: https://github.com/layui/layui/pull/1571#issuecomment-1911304298

**Comment by Sight-wcg** [comment]
我这边暂时不能重现，你在项目中分别测试一下 2.9.3 和 2.9.4 是否会崩溃，以判断 2.9.4  的补丁能否修复此问题。
此问题的错误码和之前的同类问题不同。

**Comment by yz8943** [comment]
2.9.3 版本依然是崩溃的 还是出现  STATUS_STACK_OVERFLOW

**Comment by Sight-wcg** [comment]
> 2.9.3 版本依然是崩溃的 还是出现  STATUS_STACK_OVERFLOW 

2.9.4 会崩溃吗？

**Comment by yz8943** [comment]
目前官网的2.9.4版本没有下载入口了。没有测

**Comment by yz8943** [comment]
刚找了下2.9.4 依然是崩溃的

**Comment by yz8943** [comment]
是不是要加上这段代码才可以 ，目前好像删除了这段代码
https://github.com/layui/layui/commit/a5502f63728a9a8c956e90b6a67941345ec0e7a9

**Comment by yz8943** [comment]
![image](https://github.com/layui/layui/assets/10083920/e8c005b4-d8c6-423e-bfba-03eb56f74939)
目前最新版本2.9.4  确实删除了这个Chrome的补丁是不是要加上才可以、我这边的浏览器就是图上说的版本。依然没有修复

**Comment by yz8943** [comment]
刚刚更新一个Chrome最新版本
![image](https://github.com/layui/layui/assets/10083920/075375a2-ee43-4bdf-ac89-92df8caf2abf)
居然可以用2.9.6 版本了 不崩溃了

**Comment by Sight-wcg** [comment]
> 是不是要加上这段代码才可以 ，目前好像删除了这段代码
> https://github.com/layui/layui/commit/a5502f63728a9a8c956e90b6a67941345ec0e7a9

2.9.4 中包含这段代码，仍然崩溃说明这个补丁不能修复该问题。

**Comment by Sight-wcg** [comment]
> 刚刚更新一个Chrome最新版本
> ![image](https://github.com/layui/layui/assets/10083920/075375a2-ee43-4bdf-ac89-92df8caf2abf)
> 居然可以用2.9.6 版本了 不崩溃了

好的，解决了就好。

**Comment by yz8943** [comment]
![image](https://github.com/layui/layui/assets/10083920/a4e85167-6861-4f45-b04b-4dd501434ad1)
依然崩溃

**Comment by Sight-wcg** [comment]
> ![image](https://private-user-images.githubusercontent.com/10083920/306127509-a4e85167-6861-4f45-b04b-4dd501434ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTg1MjMsIm5iZiI6MTcwODQ5ODIyMywicGF0aCI6Ii8xMDA4MzkyMC8zMDYxMjc1MDktYTRlODUxNjctNjg2MS00ZjQ1LWIwNGItNGRkNTAxNDM0YWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2NTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzdhN2YwZjkxNjU4ODcwY2YyY2M5NGE3OGE2ODg2MTBhMjhhYjllOWY2NTMwZWYzY2E2ZGZlOTE2MTJmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GeCeXMAvLHv1DYdAEBxarY1peWhiHqw9fGJJe8pPSHU) 依然崩溃

这个问题，只能等浏览器厂商修复。
