### ISSUE TITLE
table 单元格支持右侧down箭头固定显示

### ISSUE THREAD

**Issue by itbencn** [layui/layui#1609]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.6

### 问题描述

需要实现不管列宽多少/内容实际宽度多少,右侧down箭头固定可视
目前情况是设置width或minWidth后 或当内容长度不足时就不会显示

建议增加一个表头属性控制

### 业务代码

```auto
layui-table-grid-down
```

### 浏览器

Edge 121.0.2277.83 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
暂不考虑添加这个功能，只是一个很小众的需求。
