### ISSUE TITLE
table.resize(id) 重置table height 无效

### ISSUE THREAD

**Issue by lanbohello163** [layui/layui#1614]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.6

### 问题描述

表格使用的2.9.1新增的height高度设置方式，查询区域高度动态变化时，table.resize(id) 未能改变表格高度。
期望不发起请求情况下刷新表格高度，目前发现只有完整重载才能改变高度，发起请求刷新表格用户体验较差。

### 业务代码

```auto
height: function(){
  var otherHeight = $('#search-content').outerHeight(); // 自定义其他区域的高度
  return $(window).height() - otherHeight; // 返回 number 类型
}
```

### 截图补充

![image](https://github.com/layui/layui/assets/26701566/d3be7bab-532d-4188-bfb2-e73549a61268)

### 浏览器

Chrome版本 121.0.6167.86（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
从源码来看如果`height`属性是函数类型的话是会生效的
![image](https://github.com/layui/layui/assets/10653427/39d8e916-e69e-49b1-978c-c2e7f1c4bec8)

**Comment by lanbohello163** [comment]
![image](https://github.com/layui/layui/assets/26701566/8bd8905a-032e-4388-b7dd-81c7e6a85e7b)
是我的写法有问题， 感谢。
