### ISSUE TITLE
设置表格type属性为“checkbox ”或者“radio”不会垂直居中

### ISSUE THREAD

**Issue by Tengxunqq** [layui/layui#1615]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.4

### 问题描述

设置表格type属性为“checkbox ”或者“radio”不会垂直居中

### 业务代码

```auto
cols: [[ //表头
                {type: 'checkbox'}
```

### 截图补充

![1706773733456](https://github.com/layui/layui/assets/30361764/6c08cbeb-84a2-4aef-afa6-c8783026a939)
![1706773749351](https://github.com/layui/layui/assets/30361764/a1b1bb56-910c-4ebd-a55a-f79da555e9b2)

### 浏览器

chrome 121.0.6167.86、360极速浏览器 22.1.1084.64

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of https://github.com/layui/layui/issues/1477  https://github.com/layui/layui/issues/1515

**Comment by Tengxunqq** [comment]
复现demo，chrome&nbsp;版本 121.0.6167.86（正式版本） （64 位）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "layui/layui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 下午4:58
***@***.***&gt;;
抄送:&nbsp;"ಡ ﹏ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [layui/layui] 设置表格type属性为“checkbox ”或者“radio”不会垂直居中 (Issue #1615)





 
@Tengxunqq 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
  
产生问题的详细步骤
 
与问题相关的完整代码
 
在线 Demo (推荐通过 stackblitz 或 codepen 创建)
   
详见：🍀 Layui Issue 贡献指南
 延伸：👉 为什么要提供最小化重现？

**Comment by Tengxunqq** [comment]
> Duplicate of #1477 #1515

我的情况跟这个不一样，没有任何其他样式，请看代码：
![1706780213275](https://github.com/layui/layui/assets/30361764/32ec7261-03ca-409d-b874-326ae829b609)
![1706780231332](https://github.com/layui/layui/assets/30361764/fc5a3664-57ee-4cd7-a780-d4d4079626f7)

**Comment by Tengxunqq** [comment]
> Duplicate of #1477 #1515

### **我的情况跟这个不一样，没有任何其他样式，请看代码：**
![1706780213275](https://github.com/layui/layui/assets/30361764/ac89faba-e237-41de-acb9-3766f33be6c5)
![1706780231332](https://github.com/layui/layui/assets/30361764/d3ed5cb4-67af-4b72-810b-9f4302d0d2ed)

### **效果：**
![1706780473872](https://github.com/layui/layui/assets/30361764/3c29f448-4ea0-4fb7-86b1-f7da1dfc81d7)

**Comment by Tengxunqq** [comment]
> @Tengxunqq 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)

layui-icon有时也会出现垂直不对齐问题

### **另外还发现个chrome上的表格初始加载的bug，360浏览器正常，如图：**
![1706781044302](https://github.com/layui/layui/assets/30361764/ae3a98fe-62c0-48e6-81ea-ec63fcf75ab7)
![1706781120062](https://github.com/layui/layui/assets/30361764/ff356de6-a2d8-4c59-a542-acd1ace49447)
![1706781181329](https://github.com/layui/layui/assets/30361764/5cc5475b-8965-450a-a4cd-e4abd16977fb)
![1706781222680](https://github.com/layui/layui/assets/30361764/53288b4f-b99d-4be0-90ae-61511bc5c24b)
![1706781263094](https://github.com/layui/layui/assets/30361764/723f3374-e740-4520-aea4-6e592dc2de16)

**Comment by Tengxunqq** [comment]
> @Tengxunqq 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)

### **layui-icon有时也会出现垂直不对齐问题**

### **另外还发现个chrome上的表格初始加载的bug，360浏览器正常，如图：**
![1706781549578](https://github.com/layui/layui/assets/30361764/7e7b143e-6945-41c3-9ef5-c975176d5116)
![1706781120062](https://github.com/layui/layui/assets/30361764/72daa2b3-40ba-4b0d-aa9f-5990c8169194)
![1706781181329](https://github.com/layui/layui/assets/30361764/f7cafc86-0c83-4460-9b27-e31bb1f07e50)
![1706781222680](https://github.com/layui/layui/assets/30361764/388868b0-d03c-4b9d-bb08-7563e4cf51a0)
![1706781263094](https://github.com/layui/layui/assets/30361764/1b9e265b-2205-4d1a-8df3-90eea2654585)
