### ISSUE TITLE
table.setRowChecked使用时的问题

### ISSUE THREAD

**Issue by zherose** [layui/layui#1619]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.2

### 问题描述

我想在点击表格checkbox时，触发表格复选框，并同时选择某个或多个数据相同（订单号相同）的其他行。
我写的代码可以执行，如图所示，当我点击前三行订单 RK20240126-1，会同时选中4行。
但不知道为什么点击第4行，前3行没选中。
是BUG 还是我写的代码有问题？

### 业务代码

```auto
// 触发表格复选框选择
	table.on('checkbox(Receipts)', function(obj){
		//console.log(obj)
		var data = obj.data;
		var id = data.OrderNumber;
		console.log(id)
		//var tabledata = table.cache['Receipts'] || {};
		var tabledata = table.getData('Receipts')
		var i = [];
			tabledata.forEach(function (item, index) {
				if (item.OrderNumber === id) {
					//item.LAY_CHECKED = true
					//console.log(item.OrderNumber)
					i.push(index)
		        }
		    });
		console.log(i)
		if (i.length > 1) {
			table.setRowChecked('Receipts', { index: i});
		}
	});
```

### 截图补充

![PixPin_2024-02-03_15-16-45](https://github.com/layui/layui/assets/155124208/4554f541-fe9a-4dbf-bb0e-7f18fc2da303)

### 浏览器

Chromium: 98.0.4758.139 Res: 2306.598 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
如果是需要批量选中/取消的，那么push里就不能放入选中行的下标，因为`checkbox`的`checked`默认会自动切换，选中后又执行一次会导致同样订单号的最后一行被取消选中，用`table.checkStatus(id)`获取选中行就知道了；
或者判断当前是要选中还是取消，给`checked`强制赋值也可以。
![1](https://github.com/layui/layui/assets/33601030/19677f83-ba9c-4b9a-b5b0-30b5bfc51ade)
