### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by azzahrah** [layui/layui#162]
Any support for english documentation?

**Comment by xuexb** [comment]
666

**Comment by azzahrah** [comment]
what do you mean 666? iam sorry i don't understand

**Comment by xuexb** [comment]
I am sorry, I mean very good ~

**Comment by Veepim** [comment]
@azzahrah  you can use the Google translation

**Comment by zz412000428** [comment]
@xuexb  This is very 666

**Comment by me4405801** [comment]
finally we have international friends~！
