### ISSUE TITLE
上传组件中的上传图片格式不支持webp

### ISSUE THREAD

**Issue by nyakohub** [layui/layui#1620]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.6

### 问题描述

图片格式似乎只支持jpg|png|gif|bmp|jpeg|svg几个格式，如果上传webp格式的图片会显示格式错误。
![image](https://github.com/layui/layui/assets/26781505/27dad7a7-a418-41a1-bd45-7253e58cb175)

### 业务代码

```auto
upload.render({
            elem: '#ID-upload-demo-btn',
            url: '/admin/uploadImage',
            accept:'images',
            before: obj=>obj.preview((index, file, result)=>$("#ID-upload-demo-img").attr('src', result)),
            done: res=>{
                if (res.code===0){
                    layer.msg('上传成功');
                    $("[name='imagePath']").val(res.msg);
                }
            }
        });
```

### 浏览器

Microsoft Edge 版本 121.0.2277.98 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
把`webp`格式的`mime`类型和文件后缀补上去试试
![image](https://github.com/layui/layui/assets/10653427/18a9656c-d7e6-4573-a6d6-8e6ad23773f3)

**Comment by nyakohub** [comment]
我这样写对吗？似乎还是不行，是layui没有认为webp后缀是图片格式
```
upload.render({
    elem: '#ID-upload-demo-btn',
    url: '/admin/uploadImage',
    accept:'images',
    acceptMime:'image/webp',
    // exts:'jpg|jpeg',
    before: obj=>obj.preview((index, file, result)=>$("#ID-upload-demo-img").attr('src', result)),
    done: res=>{
        if (res.code===0){
            layer.msg('上传成功');
            $("[name='imagePath']").val(res.msg);
        }
    }
});
```
![2024-02-04_11-50-30](https://github.com/layui/layui/assets/26781505/c379293a-1d2b-41bd-a25e-76b5adbc2e05)

**Comment by nyakohub** [comment]
这样写似乎是解决了，但是为啥layui不默认将webp格式认定为是图片格式?
```
upload.render({
            elem: '#ID-upload-demo-btn',
            url: '/admin/uploadImage',
            accept:'images',
            acceptMime:'image/webp',
            exts:'webp',
            before: obj=>obj.preview((index, file, result)=>$("#ID-upload-demo-img").attr('src', result)),
            done: res=>{
                if (res.code===0){
                    layer.msg('上传成功');
                    $("[name='imagePath']").val(res.msg);
                }
            }
        });
```

**Comment by LSL1618** [comment]
> 这样写似乎是解决了，但是为啥layui不默认将webp格式认定为是图片格式?
> 
> ```
> upload.render({
>             elem: '#ID-upload-demo-btn',
>             url: '/admin/uploadImage',
>             accept:'images',
>             acceptMime:'image/webp',
>             exts:'webp',
>             before: obj=>obj.preview((index, file, result)=>$("#ID-upload-demo-img").attr('src', result)),
>             done: res=>{
>                 if (res.code===0){
>                     layer.msg('上传成功');
>                     $("[name='imagePath']").val(res.msg);
>                 }
>             }
>         });
> ```

估计是webp格式相对jpg、png之类使用的不多，再说还可以自由配置，就一个默认值而已。

**Comment by sentsim** [comment]
关注：209544f
等待下个版本发布

**Comment by nyakohub** [comment]
> 关注：[[209544f](https://github.com/layui/layui/commit/209544f35167d3cfcaf9f3a36345b90480fbf8eb)] 等待下个版本发布

感谢
