### ISSUE TITLE
laydate 不支持在 INPUT 显示 周几

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1622]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.6

### 问题描述

laydate 不支持在 INPUT 显示 周几

### 业务代码

```auto
laydate 不支持在 INPUT 显示 周几
```

### 浏览器

ALL

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sunxiaobin89** [comment]
目前确实不支持，format只支出这些格式符，而且周几这个值一般是用在辅助显示用，跟目前的format不太符合，目前的format不仅仅是用作显示的格式化也作用于将input中的值解析成date的值，所以如果有一个类似getter和setter的format区分开才比较好处理，目前的建议是如果星期只是一个辅助查看星期几用的话，可以利用在回调中进行处理比如：
<img width="994" alt="date显示星期示例" src="https://github.com/layui/layui/assets/11920194/2badfcc3-3eaa-4b63-8afe-d7799c77d5d6">
```
laydate.render({
          elem: '#ID-laydate-format-1',
          format: 'yyyy年MM月dd日',
          done(value, date, endDate) {
            var datetime = new Date(date.year, date.month - 1, date.date, date.hours, date.minutes, date.seconds);
            $(this.elem[0]).parent().next('.layui-form-mid').text('星期' + '日一二三四五六'[datetime.getDay()])
          },
        });
