### ISSUE TITLE
静态表格渲染后init方法中的before配置中更改hide参数后表头不生效

### ISSUE THREAD

**Issue by JustDaWolf** [layui/layui#1629]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.6

### 问题描述

静态表格渲染init方法中通过before处理hide参数不生效，只有直接在元素的lay-data属性中配置hide才会生效，但是查看cols配置结果正常

### 业务代码

```auto
layui.use(function () {
				var table = layui.table,
					util = layui.util;

				var fieldKey = cms.urlEncode(window.location.href.split('?')[0]);
				var localData = layui.data(fieldKey);

				table.init('parse-table-demo', {
					title: '数据表',
					cellMinWidth: 100,
					toolbar: true,
					escape: false,
					before: function (options) {
						layui.each(options.cols[0], function (index, item) {
							if (!item.field) {
								item.field = fieldKey + '-' + index;
							}
							if (item.field in localData) {
								item.hide = localData[item.field];
							}
						});
					},
					done: function () {
						var that = this;
						that.elem.next().on('mousedown', 'input[lay-filter="LAY_TABLE_TOOL_COLS"]+', function () {
							var input = $(this).prev()[0];
							layui.data(fieldKey, {
								key: input.name
								, value: input.checked
							})
						});
					}

				});
			});
```

### 浏览器

qq浏览器最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sunxiaobin89** [comment]
before的定义是“数据渲染之前的回调函数”，这个阶段表头已经确定了生成了，所以在before中修改只影响到了body部分，建议采用hideCol去控制列的显示隐藏，这个方法会处理数据以及节点，包括头部的
https://layui.dev/docs/2/table/#table.hideCol

**Comment by JustDaWolf** [comment]
> before的定义是“数据渲染之前的回调函数”，这个阶段表头已经确定了生成了，所以在before中修改只影响到了body部分，建议采用hideCol去控制列的显示隐藏，这个方法会处理数据以及节点，包括头部的 https://layui.dev/docs/2/table/#table.hideCol

感谢回复，昨天通过查看layui源码已了解该情形，我的项目中暂时先重新定义了init方法进行功能适配，使相关特殊处理能在options配置阶段即生效，建议官方可以增加一个相关的处理方法，以便更加友好地兼容静态表格的渲染，即原本使用静态表格的项目可以更加简单地按实际需要进行处理渲染

**Comment by JustDaWolf** [comment]
> > before的定义是“数据渲染之前的回调函数”，这个阶段表头已经确定了生成了，所以在before中修改只影响到了body部分，建议采用hideCol去控制列的显示隐藏，这个方法会处理数据以及节点，包括头部的 https://layui.dev/docs/2/table/#table.hideCol
> 
> 感谢回复，昨天通过查看layui源码已了解该情形，我的项目中暂时先重新定义了init方法进行功能适配，使相关特殊处理能在options配置阶段即生效，建议官方可以增加一个相关的处理方法，以便更加友好地兼容静态表格的渲染，即原本使用静态表格的项目可以更加简单地按实际需要进行处理渲染

例如
`//自定义表头配置处理
								/////////
								if (!row.field) {
									row.field = 'field-' + ii;
								}
								if (th.hasClass('common-align-c')) {
									row.align = 'center';
								}
								if (row.field in localData) {
									row.hide = localData[row.field];
								}
								/////////`

**Comment by sunxiaobin89** [comment]
> > > before的定义是“数据渲染之前的回调函数”，这个阶段表头已经确定了生成了，所以在before中修改只影响到了body部分，建议采用hideCol去控制列的显示隐藏，这个方法会处理数据以及节点，包括头部的 https://layui.dev/docs/2/table/#table.hideCol
> > 
> > 
> > 感谢回复，昨天通过查看layui源码已了解该情形，我的项目中暂时先重新定义了init方法进行功能适配，使相关特殊处理能在options配置阶段即生效，建议官方可以增加一个相关的处理方法，以便更加友好地兼容静态表格的渲染，即原本使用静态表格的项目可以更加简单地按实际需要进行处理渲染
> 
> 例如 `//自定义表头配置处理 ///////// if (!row.field) { row.field = 'field-' + ii; } if (th.hasClass('common-align-c')) { row.align = 'center'; } if (row.field in localData) { row.hide = localData[row.field]; } /////////`

恩恩，后面会看看怎么添加更加合适的回调，目前因为layui2.x是基于jQuery开发的不是mvvm所以无法做到属性变化监听触发对应的函数重新渲染节点，只能通过利用插件提供的自己把控什么时候去调整，比如你提到的这个问题，实际也可以在init的时候会解析表头上的lay-data信息，比如：
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
  <link href="//unpkg.com/layui@2.9.6/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<div class="layui-btn-container">
  <button class="layui-btn" lay-on="parseTable">转换为数据表格</button>
</div>
<table lay-filter="parse-table-demo">
  <thead>
  <tr>
    <th lay-data="{field:'name', width:150, hide: layui.table.getIsHide('name')}">人物</th>
    <th lay-data="{field:'nation', width:150, hide: layui.table.getIsHide('nation')}">民族</th>
    <th lay-data="{field:'maxim', minWidth: 180, hide: layui.table.getIsHide('maxim')}">格言</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>孔子</td>
    <td>华夏</td>
    <td>有朋自远方来，不亦乐乎</td>
  </tr>
  <tr>
    <td>孟子</td>
    <td>华夏</td>
    <td>穷则独善其身，达则兼济天下</td>
  </tr>
  <tr>
    <td>庄子</td>
    <td>华夏</td>
    <td>朴素而天下莫能与之争美</td>
  </tr>
  </tbody>
</table>

<!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
<script src="//unpkg.com/layui@2.9.6/dist/layui.js"></script>
<script>
  layui.use(function () {
    var table = layui.table;
    var util = layui.util;
    var $ = layui.$;

    var fieldKey = 'layuiTable';
    var localData = layui.data(fieldKey);
    table.getIsHide = function (field) {
      return !!localData[field]
    }
    // 事件
    util.on('lay-on', {
      parseTable: function () {
        // 转化静态表格
        table.init('parse-table-demo', {
          // height: ''
          title: '数据表',
          cellMinWidth: 100,
          toolbar: true,
          escape: false,
          // before: function (options) {
          //   layui.each(options.cols[0], function (index, item) {
          //     if (!item.field) {
          //       item.field = fieldKey + '-' + index;
          //     }
          //     if (item.field in localData) {
          //       // debugger;
          //       // item.hide = localData[item.field];
          //       // table.hideCol(options.id, {
          //       //   field: item.field,
          //       //   hide: localData[item.field]
          //       // })
          //     }
          //   });
          // },
          done: function () {
            var that = this;
            that.elem.next().on('mousedown', 'input[lay-filter="LAY_TABLE_TOOL_COLS"]+', function () {
              var input = $(this).prev()[0];
              layui.data(fieldKey, {
                key: input.name
                , value: input.checked
              })
            });
          }
        });
      }
    });
  });
</script>

</body>
</html>
