### ISSUE TITLE
layer.load()偶发性的不居中

### ISSUE THREAD

**Issue by trtrtr6** [layui/layui#163]
直接初始化页面就打开一个loading：layer.load()，浏览器chrome中loading概率性不居中，火狐浏览器是一直都不居中
代码如下：
`<script type="text/javascript">
layer.load(); 
</script>
`
查看页面html样式发现。loading有个宽度导致不居中
`<div class="layui-layer layui-layer-loading" id="layui-layer1" type="loading" times="1" showtime="0" contype="string" style="z-index: 19891015; width: 360px; top: 215px; left: 460px;">`

经过测试，加一个setTimeout就又居中了
代码如下：
`<script type="text/javascript">
setTimeout(function(){
var index = layer.load(); 
},50);
</script>
`

**Comment by jiangdaxia** [comment]
尝试在document加载完成以后执行此方法。
加入你使用jquery的话，你可以尝试这样写看看。
$(function(){
 layer.load(); 
});

**Comment by trtrtr6** [comment]
@jiangdaxia 都是一样的问题

**Comment by sentsim** [comment]
使用后续的新版即可，对于初始即弹出的场景进行了优化
