### ISSUE TITLE
textarea google浏览器 Value 有值,设置和获取值正常  textarea显示不出给的默认值

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1630]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.6

### 问题描述

textarea google浏览器 Value 有值,设置和获取值正常  textarea显示不出给的默认值,input 正常

### 业务代码

```auto
<div class="layui-col-md12"><textarea type="text" name="topic" value="新年快乐" lay-affix="clear" placeholder="默认值不显示" class="layui-textarea"></textarea></div>
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
textarea 没有 value attribute。
