### ISSUE TITLE
2.9.6 表格 even 背景色建议能设置.鼠标移动过去的背景也是和其中一条一样的.方法渲染后console 没有获得任何信息.

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1635]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.6 

### 问题描述

2.9.6 表格 even 背景色建议能设置.鼠标移动过去的背景也是和其中一条一样的.方法渲染后console 没有获得任何信息.

### 业务代码

```auto
done: function(res, curr, count, origin){
        console.log(res); // 得到当前渲染的数据
	console.log(curr);  // 得到当前页码
	console.log(count); // 得到数据总量
	console.log(origin); // 回调函数所执行的来源 --- 2.8.7+
	},
error: function(e, msg) {
  console.log(e, msg)
},
complete: function(xhr, ts) {
  console.log(xhr, ts)
}
```

### 浏览器

Chrome 最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
「鼠标移动过去的背景也是和其中一条一样的」不太明白你的意思，如果是想修改背景色，可以覆盖样式
```
.layui-table-hover{
  background-color: #FFF
}
```

**Comment by aimu2000** [comment]
👌🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月21日 14:39 |
| 收件人 | layui/layui ***@***.***> |
| 抄送人 | aimu2000 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [layui/layui] 2.9.6 表格 even 背景色建议能设置.鼠标移动过去的背景也是和其中一条一样的.方法渲染后console 没有获得任何信息. (Issue #1635) |

「鼠标移动过去的背景也是和其中一条一样的」不太明白你的意思，如果是想修改背景色，可以覆盖样式

.layui-table-hover{
  background-color: #FFF
}
