### ISSUE TITLE
本地调试请求http://www.layui.com/demo/table/user时，提示跨域权访问

### ISSUE THREAD

**Issue by haoqicherish** [layui/layui#164]
本地使用表格模块时，使用table.render({url: 'http://www.layui.com/demo/table/user/)，请求数据，浏览器提示跨域无法访问，尝试在header添加meta http-equiv="Access-Control-Allow-Origin" content="*" ，未能解决问题，请提供一下解决的思路，谢谢

**Comment by trtrtr6** [comment]
跨域无外乎就那么几种解决方案，我觉得比较好的就是通过nginx反向代理处理

**Comment by luofj** [comment]
在响应头里设置允许跨域，要在服务器端设置的吧
