### ISSUE TITLE
日期范围选择面板，当设置Min,Max属性后，渲染后默认左右面板都只显示Max对应的日期

### ISSUE THREAD

**Issue by 513cat** [layui/layui#1640]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.6

### 问题描述

日期范围选择面板，当设置Min,Max属性后，渲染后默认左右面板都只显示Max对应的日期
如下代码，设置了min是2023-1-1,max是2023-10-1,
本意是左面板显示选中2023-1-1，右面板显示选中2023-10-1,
但目前是左右面板都显示选中2023-10-1

### 业务代码

```auto
var laydate = layui.laydate;
  // 日期范围 - 左右面板独立选择模式
  laydate.render({
    elem: '#ID-laydate-range',
    range: ['#ID-laydate-start-date', '#ID-laydate-end-date'],
    min:'2023-1-1',
    max:'2023-10-1'
  });
```

### 截图补充

![image](https://github.com/layui/layui/assets/16698819/1850f102-6848-45c6-994e-f81be53b4c58)

### 浏览器

Chrome 已是最新版本 版本 121.0.6167.185（正式版本） （64 位）

### 演示地址

https://r4pblm--run.stackblitz.io

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
`min`和`max`限制的是可选择的日期范围，在未选择时面板打开默认显示当月，而你设置的`min`和`max`都早于本月，面板默认显示可选择的最后一个月，也就是2023-10，你可以用2024-1-1和2024-10-1试试就会发现打开是显示2-3月了。如果需要打开默认显示可选择范围，可以再设置一个初始值`value: '2023-01-01 - 2023-10-01'`即可

**Comment by 513cat** [comment]
利有初始值来决定左右面板默认显示时，又存在可能存在另外一个问题，即强制使组件具有值，而非用户输入，且无法清除。


具有min和max限制时，是否应按限制的区间区别处理

1. min和max都早于当月，按使用习惯（左边为开始、右边为结束），默认左面板选中min,右面板选中max（或min的下一月）
2. min和max都晚于当月，按使用习惯，默认左面板选中min,右面板选中min的下一月
3. min和max都在当月，则默认左面板选中min,右面板选中max
4. min在当月，max晚于当月，则默认左面板选中min,右面板选中min的下一月
5. min早于当月，max在当月，则默认左面板选中max的上一月,右面板选中max
6. min早于当月，max晚于当月，默认左面板选中当月,右面板选中下月

或是傻瓜一点，具有min与max限制时，左面板就是min，右面板就是max，而不参考当前时间线

**Comment by bxjt123** [comment]
> 利有初始值来决定左右面板默认显示时，又存在可能存在另外一个问题，即强制使组件具有值，而非用户输入，且无法清除。
> 
> 具有min和max限制时，是否应按限制的区间区别处理
> 
> 1. min和max都早于当月，按使用习惯（左边为开始、右边为结束），默认左面板选中min,右面板选中max（或min的下一月）
> 2. min和max都晚于当月，按使用习惯，默认左面板选中min,右面板选中min的下一月
> 3. min和max都在当月，则默认左面板选中min,右面板选中max
> 4. min在当月，max晚于当月，则默认左面板选中min,右面板选中min的下一月
> 5. min早于当月，max在当月，则默认左面板选中max的上一月,右面板选中max
> 6. min早于当月，max晚于当月，默认左面板选中当月,右面板选中下月
> 
> 或是傻瓜一点，具有min与max限制时，左面板就是min，右面板就是max，而不参考当前时间线

文档要仔细看，有一个属性`isInitValue:false`，不会强制有值

**Comment by 513cat** [comment]
isInitValue:false
这个属性使用后，的确是可以将左右面板初始化在min\max设置，但是当面板渲染完成后，日期范围绑定的开始与结束Input已经被赋值，见图2.
图2仅仅是呼叫出面板，没做任何其它操作，而此时点击面板上的清除按钮，界面没有任何变化。

图1：
![image](https://github.com/layui/layui/assets/16698819/bed96f7e-a678-4b5e-a70c-fbf84a5bc809)
图2：
![image](https://github.com/layui/layui/assets/16698819/c8976a78-a1b9-4266-9d52-8d6cd021a146)

**Comment by bxjt123** [comment]
> isInitValue:false 这个属性使用后，的确是可以将左右面板初始化在min\max设置，但是当面板渲染完成后，日期范围绑定的开始与结束Input已经被赋值，见图2. 图2仅仅是呼叫出面板，没做任何其它操作，而此时点击面板上的清除按钮，界面没有任何变化。
> 
> 图1： ![image](https://private-user-images.githubusercontent.com/16698819/306179746-bed96f7e-a678-4b5e-a70c-fbf84a5bc809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjI4NjEsIm5iZiI6MTcwODQyMjU2MSwicGF0aCI6Ii8xNjY5ODgxOS8zMDYxNzk3NDYtYmVkOTZmN2UtYTY3OC00YjVlLWE3MGMtZmJmODRhNWJjODA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZTdkZDgzMTM3YjkwMzE4MDljNzg3YTRhOGI4YTg4NTAwMTA4MWE1ZGFiNzU5YTZlYWI2NjhmZjNlM2MzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yh8i1SPMJP5_IYmuNvIK1YWevh__70IQEH57wnJ6EI) 图2： ![image](https://private-user-images.githubusercontent.com/16698819/306180228-c8976a78-a1b9-4266-9d52-8d6cd021a146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjI4NjEsIm5iZiI6MTcwODQyMjU2MSwicGF0aCI6Ii8xNjY5ODgxOS8zMDYxODAyMjgtYzg5NzZhNzgtYTFiOS00MjY2LTlkNTItOGQ2Y2QwMjFhMTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmQ5NjY5N2FlNTcyM2NlNDI0ODlkOTZhYWFiYTU4NzFhMzhmMjExMjI3YjlhOTZmNTliNDJlODE4YzA2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dl5O4mZbOdE9dnB76GaXOrqEfF4-Pk6BjnDgfIVDFSY)

因为你赋的`value`初值不符合`format`默认规则（`'yyyy-MM-dd'`）会强制转换，如果你要用“2023-2-1”这种，需要配置`format: 'yyyy-M-d'`，不配置的话就得`value: '2023-02-01 - 2023-08-10'`

**Comment by 513cat** [comment]
首先感谢你的回复。

由你这里反馈信息，我已知晓format的默认规则。

但我遇到的问题是
当使用赋值给value及配合isInitValue:false 属性后，
click开始或是结束Input呼叫出面板后，未做其它操作，会出现以下两个现象
1. 系统已经将value值赋给开始与结束的Input
2. 此时面板上的清除按钮点击后，界面未有任何变动

**Comment by bxjt123** [comment]
> 首先感谢你的回复。
> 
> 由你这里反馈信息，我已知晓format的默认规则。
> 
> 但我遇到的问题是 当使用赋值给value(Value符合默认format规则)及配合isInitValue:false 属性后， click开始或是结束Input呼叫出面板后，未做其它操作，会出现以下两个现象
> 
> 1. 系统已经将value值赋给开始与结束的Input
> 2. 此时面板上的清除按钮点击后，界面未有任何变动

测试过只要代码正确并不会出现你说的两个问题，烦请提供代码以便复现问题。
![GIF](https://github.com/layui/layui/assets/33601030/0c0df7fb-2e43-463b-a5ea-ece0f55fe24f)

**Comment by 513cat** [comment]
给你添麻烦了。

目前已经找到具体的问题复现。

只要value属性在min~max之外，就会出现我上面讲的那两个问题。
已经测试value属性在min~max之间，工作很正常。

![image](https://github.com/layui/layui/assets/16698819/adbd5dc4-3521-4520-bdb8-5da93bb8af3d)
