### ISSUE TITLE
layer的非jquery版本

### ISSUE THREAD

**Issue by newyhj** [layui/layui#1641]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

3.1.1

### 问题描述

layer使用多年，非常迫切需要不依赖jquery的独立版本，请问是否有计划开发？

### 业务代码

```auto
元
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by ken678** [comment]
没有 既然作者合并了 肯定不会再单独拎出来
