### ISSUE TITLE
关于返回码 code进行自定义对齐?

### ISSUE THREAD

**Issue by youfeed** [layui/layui#1642]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.8.0

### 问题描述

组件用到 code的组件有很多地方，
code 正确用的最多的地方还是 200
与标准对其呗

### 业务代码

```auto
# code:200
```

### 浏览器

谷歌

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
2.x 考虑到兼容性，暂时不会调整状态码。

**Comment by youfeed** [comment]
是的，2.x 不应该调整 现在已经出道 2.9版本
v3.0.0版本已经快了~ 希望可以出 爱你~

**Comment by Sight-wcg** [comment]
目前只有 table 和 treeTable 中有用到 `code`, 暂时可以使用 `response.statusCode` (2.8+ 已弃用)自定义成功的状态码。

参考 https://layui.dev/2.7/docs/modules/table.html#async
