### ISSUE TITLE
table工具栏自带的导出、打印能否提供方法调用？

### ISSUE THREAD

**Issue by lanbohello163** [layui/layui#1644]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.6

### 问题描述

table工具栏自带的导出、打印能否提供方法调用？

### 业务代码

```auto
无
```

### 截图补充

无

### 浏览器

Chrome版本 121.0.6167.86（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
导出有独立方法的啊！不看文档的么？至于打印的独立方法目前确实没有，其实本质上就是用的window对象自带的打印方法`window.print()`。

**Comment by lanbohello163** [comment]
> 导出有独立方法的啊！不看文档的么？至于打印的独立方法目前确实没有，其实本质上就是用的window对象自带的打印方法`window.print()`。

window.print() 是打印...

**Comment by lanbohello163** [comment]
看到了  谢谢
