### ISSUE TITLE
遇到提示：No label associated with a form field

### ISSUE THREAD

**Issue by ChenHL-China** [layui/layui#1645]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.0

### 问题描述

使用layui的分页等功能生成的input、select元素不带name和id，于是在chrome浏览器上遇到提示：No label associated with a form field。请问如何解决

### 业务代码

```auto
<div id="laypage"></div>
<script>
layui.use(function(){
  var laypage = layui.laypage;
  laypage.render({
    elem: 'laypage',
    count: 1000,
    limit: 100,
    limits: [100, 300, 500],
    layout: ['count', 'prev', 'page', 'next', 'limit', 'refresh', 'skip'], 
    jump: function(obj){
      console.log(obj);
    }
  });
});
</script>
```

### 浏览器

Chrome 121.0.6167.185（正式版本）（64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
缺乏其他相关联的代码等信息。

**Comment by ChenHL-China** [comment]
![QQ截图20240222185123](https://github.com/layui/layui/assets/37134765/64a501e1-f033-4eb3-bdaf-e8669994101f)
以官方网站的分页控件为例，我遇到的问题已在图片中标记

**Comment by sentsim** [comment]
这个只是浏览器的象征性优化提示，可以忽略。
