### ISSUE TITLE
树形表格 ,数据段中的[icon]问题

### ISSUE THREAD

**Issue by lononan** [layui/layui#1660]
### 议题条件

- [x] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

layui-v2.9.6

### 问题描述

当前版本 树形表格中的图标设置 tree.view.data['icon']='layui-icon layui-icon-folder';
不会自动嵌入标签,导致显示不了图标
目前我自己的解决办法,layui.js搜索 layui-table-tree-iconLeaf")
![image](https://github.com/layui/layui/assets/26039221/f71557e1-f3ff-4efc-83b1-ff30e1245468)

替换成内容,添加一个[<i class=]标签头以及[></i>]结尾

`layui-table-tree-iconLeaf")+'"><i class="'+(a[c.icon]||o.icon||(a[u]?a[H]?o.iconOpen:o.iconClose:o.iconLeaf)||'')+((a[c.icon]||o.icon)?'"></i>':"")+'</div>':"",n]`
希望看到能修复下吧

### 业务代码

```auto
layui-table-tree-iconLeaf")+'"><i class="'+(a[c.icon]||o.icon||(a[u]?a[H]?o.iconOpen:o.iconClose:o.iconLeaf)||'')+((a[c.icon]||o.icon)?'"></i>':"")+'</div>':"",n]
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
图标需要设置成i标签格式，参考[这个](https://gitee.com/layui/layui/issues/I8EKAB#note_22488863_link)

**Comment by lononan** [comment]
这个不是BUG,也知道要加标签,但是从设计角度来理解的话,原始数据应该只需要图标名称,前端获得数据后方便兼容其他处理.
或者属性表格做个icon绘制回调,绘制前自己添加标签或者自定义颜色央视
这只是个建议
