### ISSUE TITLE
关于版新增 lay-creatable 属性的中文输入bug

### ISSUE THREAD

**Issue by huiyong69** [layui/layui#1666]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.7

### 问题描述

使用 lay-creatable 后，新输入英文会直接在选择框内出现，但是输入中文后，新输入的内容不会出现在选择框内，需要打个空格或者删除前一个字符才能出现在选择框内。
截图一是输入后未空格或者删除前一个字符的情况，截图二是打了个空格后的情况。

### 业务代码

```auto
<select name = "test" lay-search="" lay-creatable="" lay-filter="test-select-filter">
 <option value="">请选择或搜索（默认不区分大小写）</option>
 <option value="1">王XXX</option>
 <option value="2">齐XX</option>
 <option value="3">王xx</option>
 <option value="4">梁xxx</option>
</select>
```

### 截图补充

![企业微信截图_17091844968790](https://github.com/layui/layui/assets/54387343/930a6095-c9d1-4f2d-a4d9-d0a47b075847)
![企业微信截图_17091845316227](https://github.com/layui/layui/assets/54387343/64afbe54-53b6-4834-8848-0cea032c8a7b)

### 浏览器

firefox 123.0

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Edge 121.0.2277.128 
Firefox 123.0
无法重现

**Comment by huiyong69** [comment]
> Edge 121.0.2277.128 Firefox 123.0 无法重现，你使用的是什么输入法？切换其他输入法是否能重现？ **请提供一段重现问题的视频或 GIF。**

使用的是win11自带的微软拼音，没有安装其他输入法，我去找一个安装一下试试。

**Comment by huiyong69** [comment]
安装了QQ输入法，使用正常，微软拼音不行。

**Comment by Sight-wcg** [comment]
> 安装了QQ输入法，使用正常，微软拼音不行。

Windows 10 微软拼音无法重现，检查下是否使用了旧版微软拼音
![image](https://github.com/layui/layui/assets/26325820/4e9b8461-4678-4306-b80a-c10f71019b23)

**Comment by Cuixq123** [comment]
我靠 我还以为是我的问题，我前天发了之后就删了，跟我一样，我是微信输入法
