### ISSUE TITLE
table.reloadData中的 scrollPos 属性设置无效

### ISSUE THREAD

**Issue by 1679812625** [layui/layui#1670]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

我想在表格内进行编辑后，刷新表格数据时，滚动条位置不变。
是我用的方式不对吗？？

### 业务代码

```auto
<>
```

### 截图补充

![image](https://github.com/layui/layui/assets/68091203/d573f6fc-9897-4b56-b337-605297b4706f)

### 浏览器

122.0.6261.95

### 演示地址

https://stackblitz.com/edit/stackblitz-starters-yc4hmz?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://github.com/layui/layui/discussions/1485#discussioncomment-7915072

**Comment by 1679812625** [comment]
> #1485

好的好的，谢谢谢谢
