### ISSUE TITLE
制作多文件上传表格文件太大会导致网页崩溃

### ISSUE THREAD

**Issue by 2362400196** [layui/layui#1671]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

我的文件大小1.9g
![image](https://github.com/layui/layui/assets/63276095/77b9d22a-2427-411d-bd8f-bbb0f5212f9f)
选择过大文件会这样
![image](https://github.com/layui/layui/assets/63276095/c3f48d0e-3e1f-44f1-a8e9-8aa83c50d9ef)

### 业务代码

```auto
无
```

### 浏览器

chrome最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
尝试采用别的上传组件，采用类似的使用场景，看是否会出现页面崩溃。

**Comment by zhanyangyang2019** [comment]
我上传文件100M左右也是报500内部错误，后端采用php

**Comment by LSL1618** [comment]
> 我上传文件100M左右也是报500内部错误，后端采用php

100MB的文件大小不至于吧，上面的2GB属实有些过大。

**Comment by hulang** [comment]
@zhanyangyang2019 我也是PHP环境，

表单最大上传限制 | 2G | 文件最大上传限制 | 2G

 100M太小了，我传300-500M，随意传啊。。

**Comment by gmsjy** [comment]
1G以内我上传没什么问题，再大就太慢了容易没有响应，我就搞了大文件分片上传

**Comment by Sight-wcg** [comment]
ref: https://github.com/layui/layui/issues/1543
