### ISSUE TITLE
treeTable展开节点显示的滚动条设置 scrollPos: 'fixed' 无效

### ISSUE THREAD

**Issue by 1679812625** [layui/layui#1678]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

通过子级节点展开后出现的滚动条，属性scrollPos: 'fixed'设置没效果
有空时麻烦帮我看看，谢谢了 :rose::rose::rose::rose::rose::rose:

在线演示地址，通过变更状态列查看效果

### 业务代码

```auto
1
```

### 截图补充

![1709633496287](https://github.com/layui/layui/assets/68091203/3b788115-7b64-4268-b871-71c3a422335e)

### 浏览器

122.0.6261.95

### 演示地址

https://stackblitz.com/edit/stackblitz-starters-yc4hmz?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
该方法只对 table 有效，而对 treeTable 无效，重载涉及到子节点展开状态重置，该行为会覆盖 `scrollPos` 的动作。
另外，重载后开关未进行状态记忆，建议在开关事件中给对应行数据 LAY_CHECKED 属性赋值，且在开关模板通过 d.LAY_CHECKED 进行初始状态取值。

**Comment by 1679812625** [comment]
> 该方法只对 table 有效，而对 treeTable 无效，重载涉及到子节点展开状态重置，该行为会覆盖 `scrollPos` 的动作，暂时无解。 另外，重载后开关未进行状态记忆，建议在开关事件中给对应行数据 `LAY_CHECKED` 属性赋值，且在开关模板通过 `d.LAY_CHECKED` 进行初始状态取值。

好的 :ok_hand:

**Comment by Cuixq123** [comment]
我也遇到了，我的treeTable 进行单元格编辑 重载之后就会刷新到顶部。 希望能实现跟表格一样的效果
