### ISSUE TITLE
2.9.7的layer.msg动画为anim: 'slideUp'自动关闭后有回弹闪现问题

### ISSUE THREAD

**Issue by Linzi520** [layui/layui#1680]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

2.9.7的layer.msg动画为anim: 'slideUp'自动关闭后有回弹闪现问题

### 业务代码

```auto
layer.msg('This is an error message', {
            offset: 'b',
            anim: 'slideUp',
            area: ['100%', '50px'],
            time: 5000
        });
```

### 浏览器

Microsoft Edge 版本 122.0.2365.66 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
无法重现，最好提供个 GIF 演示

**Comment by Linzi520** [comment]
可以在官网的弹出层组件页面（[链接](https://layui.dev/docs/2/layer/)）在线测试代码区贴入以下代码测试：

`
layer.msg("Test", {
    id: 'globalErrorPromptBar',
    offset: 'b',
    anim: 'slideUp',
    skin: 'msgErrorPrompt',
    area: ['100%', '50px'],
    time: 3000,
});
`
