### ISSUE TITLE
multiSelect 无法多选，点击一项后下拉列表会收缩

### ISSUE THREAD

**Issue by jian23cn** [layui/layui#1681]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

更新到v2.9.7后原有的multiSelect 无法多选，点击一项后下拉列表会收缩

### 业务代码

```auto
Markdown
```

### 浏览器

FireFox 123.0

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
`multiSelect`这个属于第三方扩展组件的属性吧

**Comment by jian23cn** [comment]
> `multiSelect`这个属于第三方扩展组件的属性吧

是三方的，之前在2.8.18中还能正常使用

**Comment by sentsim** [comment]
建议对第三方的 multiSelect 组件进行适配，或直接使用 Layui 2.8.18 版本对该组件进行兼容。

**Comment by jian23cn** [comment]
> 建议对第三方的 multiSelect 组件进行新版本适配，或直接使用 Layui 2.8.18 版本对该组件进行兼容。

谢谢，像这种常用的使用场景官方版本能否加入此功能，避免三方组件升级不适配

**Comment by jian23cn** [comment]
目前先通过在控件click事件中增加layui.stope(e);阻止事件冒泡解决了，谢谢！
