### ISSUE TITLE
能否把layui-vue版本的一些好的组件移植过来？

### ISSUE THREAD

**Issue by hulang** [layui/layui#1683]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.6

### 问题描述

http://www.layui-vue.com/zh-CN/components/skeleton
http://www.layui-vue.com/zh-CN/components/checkcard
这2个挺好的。

### 业务代码

```auto
希望移植。。。实在不行，做出扩展也行。。。
```

### 浏览器

Microsoft Edge 版本 122.0.2365.59

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
2.x 应该不会新增组件了，skeleton 可以看看 https://shoelace.style/components/skeleton，checkcard 可以使用 lay-skin 实现。

**Comment by niusongxin** [comment]
作为一名小白，不懂那么多高深代码，希望作者能在3.0版本，增加一些多样化组件，让我们能够拿来就用，好看就行。

**Comment by niusongxin** [comment]
另外想弱弱的问一句，3.0开发进度大概百分之几了，2024年能出来不。非常期待24栅格系统和大量新奇组件。

**Comment by Sight-wcg** [comment]
由 #1686 解决， skeleton 暂无计划添加。
