### ISSUE TITLE
时间控件右边加上一个图标

### ISSUE THREAD

**Issue by melin** [layui/layui#1687]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9

### 问题描述

时间控件右边加上一个图标

### 业务代码

```auto
时间控件右边加上一个图标
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by cvpv** [comment]
什么意思？

建议用下面的格式：
为什么要加这个功能？
具体加在哪里？
增加之后解决了什么问题？

**Comment by bxjt123** [comment]
这种个性化的定制，一个[后缀](https://layui.dev/docs/2/form/input.html#pre-suf)不就解决了吗
![1](https://github.com/layui/layui/assets/33601030/a28db6af-cc0e-4aad-afaa-4715ab918458)

**Comment by sentsim** [comment]
https://layui.dev/docs/2/form/input.html#pre-suf
