### ISSUE TITLE
select下拉选择可以显示value吗？而不是option的text

### ISSUE THREAD

**Issue by wlf2r** [layui/layui#1688]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.8

### 问题描述

select下拉选择可以显示value吗？而不是option的text

### 业务代码

```auto
<select name="">
  <option value='1'>参数1</option>
  <option value='2'>参数2</option>
  <option value='3'>参数3</option>
</select>

正常是选择都显示参数1 能不能显示 value中的1
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
HTML官方定义，value是值，text是显示内容，这是硬性规则，你改成这样不就行了
```
<select name="">
  <option value='1'>1</option>
  <option value='2'>2</option>
  <option value='3'>3</option>
</select>
```

**Comment by wlf2r** [comment]
不可以，要显示完整内容描述方便选择
