### ISSUE TITLE
laydate range类型存在缺陷

### ISSUE THREAD

**Issue by douno23** [layui/layui#1689]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.1

### 问题描述

日期时间类型为范围的会使用laydate的range，该展示存在缺陷，会导致无法设定结束的时间。

### 业务代码

```auto
无需
```

### 浏览器

chrome 122.0.6261.112 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
也许由 #1569 修复
https://github.com/layui/layui/pull/1569/files#diff-345523893f7be266789b6c19574d93e5f2a084837f9122582e6ecc4f0f3b9c6dR2014
