### ISSUE TITLE
layui.dropdown 右键菜单bug

### ISSUE THREAD

**Issue by luoxing66** [layui/layui#1690]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.0

### 问题描述

使用dropdown.render渲染下拉菜单时，可以正常显示，但是当elem数量增加，新增的elem无法弹出下拉菜单，所以我调用dropdown.reload，新增的elem可以弹出下拉菜单，但之前渲染过的elem无法弹出菜单

### 业务代码

```auto
layui.dropdown.render({
    id:'test',
    elem: '.layui-layout-admin .layui-tab-title li',
    trigger: 'contextmenu',
    data: [{ id: 'refresh', title: '刷新' }, { type: '-' }]
})
当我动态增加了一个li,我需要调用
layui.dropdown.reload('test', {
    elem: '.layui-body .layui-tab-title li'
});
```

### 截图补充

![image](https://github.com/layui/layui/assets/51052831/bcdde49c-69f0-47f3-8b6a-e278ac263a31)

### 浏览器

Chrome版本 122.0.6261.112（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这不是 BUG，这种场景建议用事件委托
```
        function renderTabContextmenu(triggerEl, tabID) {
          layui.dropdown.render({
            elem: triggerEl,
            trigger: "contextmenu",
            show: true,
            data: [{ id: "refresh", title: "刷新" +  tabID}],
          });
        }

        $("body").on("contextmenu", ".layui-tab-title>li", function (event) {
          event.preventDefault();
          renderTabContextmenu(this, this.getAttribute('lay-id'));
        });
```

**Comment by luoxing66** [comment]
这种方式是能解决我的问题，但是存在效率问题，当我多次右击元素时，每次右击都会绑定一个重复的事件
![image](https://github.com/layui/layui/assets/51052831/f91b3518-46eb-4adf-addf-f88b2877e3fc)

**Comment by bxjt123** [comment]
> 这种方式是能解决我的问题，但是存在效率问题，当我多次右击元素时，每次右击都会绑定一个重复的事件 !

或许可以变通下，加个不重复判断
```
var tabID = [];
$("body").on("contextmenu", ".layui-tab-title>li", function (event) {
  event.preventDefault();
  var thisID = this.getAttribute('lay-id');
  if (!tabID.includes(thisID)) {
    tabID.push(thisID);
    renderTabContextmenu(this, thisID);
  }
});
function renderTabContextmenu(triggerEl, tabID) {
  //这个不变
}
```

**Comment by luoxing66** [comment]
这样太不优雅了🙂，还是建议dropdown组件加一个selector，可以实现事件代理

**Comment by luoxing66** [comment]
这样太不优雅了🙂，因为我的子元素还会删除，再次添加，这样做的话我还要监听子元素删除，把它从tabID中移除，否则无法触发事件，还是建议dropdown加一个selector，可以实现事件代理

**Comment by Sight-wcg** [comment]
```       
 $("body").on("contextmenu", ".layui-tab-title>li", function (event) {
          event.preventDefault();
          if (!this.__hasCtxMenu) {
            this.__hasCtxMenu = true;
            renderTabContextmenu(this, this.getAttribute('lay-id'));
          }
    });
```

**Comment by luoxing66** [comment]
> 你能提供一个重现吗？理论上内部有处理重复 render 的情况
> 
> ```
>         function renderTabContextmenu(triggerEl, tabID) {
>           layui.dropdown.render({
>             elem: triggerEl,
>             id: tabID,
>             trigger: "contextmenu",
>             show: true,
>             data: [{ id: "refresh", title: "刷新" +  tabID}, { type: "-" }],
>           });
>         }
> 
> 
>         $("body").on("contextmenu", ".layui-tab-title>li", function (event) {
>           event.preventDefault();
>           if (!this.__hasCtxMenu) {
>             this.__hasCtxMenu = true;
>             renderTabContextmenu(this, this.getAttribute('lay-id'));
>           }
>         });
> ```

这样子写没问题，但是如果不加 this.__hasCtxMenu 的话，确实会渲染多次，底层应该是没有加这个判断的

**Comment by Sight-wcg** [comment]
有处理重复渲染，不知道你这个怎么触发的。
