### ISSUE TITLE
能否添加tips功能

### ISSUE THREAD

**Issue by hanfengyangzai** [layui/layui#1691]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.7

### 问题描述

能否添加tips，鼠标移入按钮或者其他网页元素的时候显示内容，
1.可选择显示位置 上、下、左、右
2.显示内容，可写成固定的或可动态从子级或父级标签取内容

### 业务代码

```auto
无
```

### 浏览器

Google Chrome 122.0.6261.112（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://layui.dev/docs/2/layer/#demo-tips

使用 layer.tips 简单封装下，即可实现问题描述中的需求
