### ISSUE TITLE
支持侧边弹出窗口吗？

### ISSUE THREAD

**Issue by melin** [layui/layui#1694]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.7

### 问题描述

类似这个效果：https://www.jeasyui.com/demo/main/index.php?plugin=Drawer&theme=material-teal&dir=ltr&pitem=&sort=asc#

### 业务代码

```auto
无
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
1.打开 layet 文档https://layui.dev/docs/2/layer/#demo-tips
2.按下键盘 ctrl+f 组合键，在弹出的输入框中输入“抽屉”
3.使用鼠标定位到相关示例
