### ISSUE TITLE
layui-form-label的宽度能否从80更新到85或者90，以支持6个汉字

### ISSUE THREAD

**Issue by hulang** [layui/layui#1702]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.7

### 问题描述

我的项目中，几乎就layui一个css文件，没有其它CSS文件，做后端的么。。。希望官方加上，可以一劳永逸。。。

### 业务代码

```auto
~~~html
<form class="layui-form" action="">
  <div class="layui-form-item">
    <label class="layui-form-label">验证必填项</label>
    <div class="layui-input-block">
      <input type="text" name="username" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input">
    </div>
  </div>
</form>
<label class="layui-form-label">验证必填项</label>这里
~~~
~~~css
.layui-form-label {
    position: relative;
    float: left;
    display: block;
    padding: 9px 15px;
    width: 80px;// 这里的宽度
    font-weight: 400;
    line-height: 20px;
    text-align: right;
}
~~~
```

### 浏览器

Microsoft Edge 版本 122.0.2365.80 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
若 lable 宽度不够，建议采用以下方式灵活实现：
1. 采用栅格排版，不一定非要使用 form 自带的元素结构。
2. 在外部对 `class="layui-form-label"` 和 `class="layui-input-block"` 所在元素重置宽度和外边距。
3. 借助“前置后置结构”让宽度自由伸缩，这一块参考：https://layui.dev/docs/2/form/input.html#group

**Comment by hulang** [comment]
@sentsim 作者大佬，主要是习惯了这个布局，所有项目全部这样使用的哈：
```html
  <div class="layui-form-item">
    <label class="layui-form-label">验证必填项</label>
    <div class="layui-input-block">
      <input type="text" name="username" lay-verify="required" placeholder="请输入" autocomplete="off" class="layui-input">
    </div>
  </div>
```
只能自己重置了。。
