### ISSUE TITLE
树组件增加展开折叠回调函数。

### ISSUE THREAD

**Issue by swanfly** [layui/layui#1703]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.7

### 问题描述

operate、oncheck和click回调都有了，很好。但是展开状态无回调，导致无法记录最近一次树菜单的打开状态，所以树组件中能否增加展开折叠的回调函数。

### 业务代码

```auto
无
```

### 浏览器

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://github.com/layui/layui/issues/1606#issuecomment-1916536470
