### ISSUE TITLE
laydate范围选择时分秒不能选择

### ISSUE THREAD

**Issue by ALongLi** [layui/layui#172]
![image 3](https://user-images.githubusercontent.com/20749911/36624777-9e4d2066-194e-11e8-8ece-268cd48afe89.png)
![image 4](https://user-images.githubusercontent.com/20749911/36624778-9e85bad4-194e-11e8-9871-fe78d5bc036f.png)

问题： 选择日期范围后还未点确定，时分秒是禁止选择的，确定后，输入框有时间值了，再次选择时分秒才可选
期望： 初次选择时间范围后，时分秒也可以选择
```javascript
 laydate.render({
      elem: "#timeRange",
      range: true,
      type: 'datetime',
      max: 0,
}
```

**Comment by chengwubin** [comment]
对的，datetime，range为true时，时间最大值处理有bug。
比如：max=2021-03-09 10:00:00
选起始时间时，小时也只能选10点以前的，结束时间也只能选10点以前的。
当选了一次后，再选，结束时间又可以选大于10点的了
