### ISSUE TITLE
upload 组件上传阿里云 OSS 报错（不是 file 顺序的问题）

### ISSUE THREAD

**Issue by jacksonwj** [layui/layui#1720]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.7

### 问题描述

在使用 upload 组件上传到阿里云 OSS 的时候，OSS 返回的状态码可以自定义，分别有三个：200、201、204。

默认情况下，OSS 会返回 204，根据 OSS 官方文档，我把返回的状态码改为了 201，这样可以拿到返回的 XML，但是，当设置成 201 之后，upload 组件直接报错了，文件倒是上传成功了，但是直接进入了 upload 的 error 回调。

**文件已经成功上传了，但是，界面上弹出了出错的提示**

![200](https://github.com/layui/layui/assets/61455/e78c1430-0f0c-453f-813f-fbbe5bb1b147)

![201](https://github.com/layui/layui/assets/61455/7d24b42f-9a09-4176-bcff-29906d2160e2)

分别测试了三个状态值，返回结果如下：
- 200：会报错
- 201：会报错
- 204：不会报错

### 业务代码

```auto
let uploader = layui.upload.render({
    elem: '#upload-wrapper',
    url: '',
    accept: 'file',
    acceptMime: 'application/zip',
    exts: 'zip',
    auto: false,
    size: 100 * 1024,
    choose: obj => {
        obj.preview((idx, file, base64) => {
            // 其他业务代码

            $.getJSON(<获取 OSS 签名的接口>, result => {
                uploader.reload({
                    url: result.url,
                    data: {
                        key: 'demo.zip',
                        policy: result.policy,
                        success_action_status: '201',   // 默认返回 204，如果改为 200 或 201，会报错
                        Signature: result.signature,
                        OSSAccessKeyId: result.accessId
                    }
                });

                uploader.upload();
            });
        });
    },
    done: (res, idx, upload) => {
        console.log('done');   // 204 时，进入 done 回调
    },
    error: (idx, upload) => {
        console.log('error');   // 200 和 201 时，进入 error 回调
    }
});
```

### 截图补充

![OSS 官方说明](https://github.com/layui/layui/assets/61455/2838146c-97e9-45d8-8b91-6484bcad48d6)

[OSS 官方说明](https://help.aliyun.com/zh/oss/developer-reference/postobject#section-0lu-03w-2z6)

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by jacksonwj** [comment]
我分析 OSS 返回的三种码的意思：

- 200：成功，有内容，但内容是空字符串
- 201：成功，有内容，内容是 XML 字符串
- 204：成功，无内容，NoContent

应该 200 和 204 就是 "" 和 null 的区别

**Comment by Sight-wcg** [comment]
upload 的参数 dataType，即内部 jQuery ajax 的 dataType，默认值为  `"json"`。如果服务器端返回的不是 json 格式的数据，就会直接进入 error 回调。

检查 OOS 三种状态码返回的数据格式，设置对应的 dataType 类型。
