### ISSUE TITLE
表单组件能否加个lay-verify 有验证块时输入完即时验证

### ISSUE THREAD

**Issue by itfensi** [layui/layui#1744]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.7

### 问题描述

表单组件能否加个lay-verify 有验证块时输入完即时验证

### 业务代码

```auto
表单组件能否加个lay-verify 有验证块时输入完即时验证
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
建议自主绑定输入框的 `input` 事件，结合 form 提供的相关验证方法实现功能。
ref: https://layui.dev/docs/2/form/#lay-verify

**Comment by itfensi** [comment]
自主绑定，当我一个form表单添加项目较多时，input表单绑定很麻烦。

**Comment by Sight-wcg** [comment]
> 自主绑定，当我一个form表单添加项目较多时，input表单绑定很麻烦。

可以根据需求封装
