### ISSUE TITLE
 layer.open 打开页面后，页面中select 搜索不工作，输入框不能输入，选择也有问题

### ISSUE THREAD

**Issue by anke1460** [layui/layui#1746]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.8

### 问题描述

 layer.open  打开一个弹框页面，页面中放置select并设置可搜索功能，出现下拉框不能输入，搜索无效

### 业务代码

```auto
<select   lay-search="">
            <option value="">请选择或搜索（默认不区分大小写）</option>
            <option value="AAA">AAA</option>
            <option value="aaa">aaa</option>
            <option value="3">BBB</option>
            <option value="4">bbb</option>
            <option value="5">ABC</option>
            <option value="6">abc</option>
            <option value="7">AbC</option>
          </select>
```

### 浏览器

chrome 122.0.6261.129

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
在 `layer.open()` 的 `success` 中执行 `form.render('select')` 完成 `select` 组件的渲染。
要细读文档：https://layui.dev/docs/2/form/#render

**Comment by anke1460** [comment]
@sentsim   form.render('select') 或 form.render(); 都执行过，我现在版本2.8.0 弹出层也是搜索问题，然后替换成2.9.3，搜索不工作，另外下拉框选择会延迟出现上一次的选择结果

**Comment by anke1460** [comment]
找到原因了，是用了一个select扩展插件引起的search问题
