### ISSUE TITLE
laydate的mark属性问题

### ISSUE THREAD

**Issue by CNFCobra** [layui/layui#1749]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.8

### 问题描述

mark修改时无法重新渲染已删除的值

### 业务代码

```auto
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <link href="//unpkg.com/layui@2.9.8/dist/css/layui.css" rel="stylesheet">
</head>
<body class="layui-padding-3">

<div class="ws-demo-static">
  <div class="layui-inline" id="ID-laydate-static-1"></div>
</div>
<script src="//unpkg.com/layui@2.9.8/dist/layui.js"></script> 
<script>
layui.use(function(){
  var laydate = layui.laydate;
  var $ = layui.jquery;
  laydate.render({
    elem: '#ID-laydate-static-1',
    position: 'static'
    ,mark:{"2024-04-02":"aaa","2024-04-03":"bbb","2024-04-04":"ccc"}
  });
  $('#ID-laydate-static-1').html('');
  laydate.render({
    elem: '#ID-laydate-static-1',
    position: 'static'
    ,mark:{"2024-04-02":"aaa","2024-04-03":"bbb"}
  });
});
</script>
</body>
</html>
```

### 截图补充

![截图20240402222229140](https://github.com/layui/layui/assets/165807303/224378fb-55a7-474b-bf8b-14946ed815a8)

### 浏览器

所有版本

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #1735

**Comment by Sight-wcg** [comment]
临时方法 https://gitee.com/layui/layui/issues/I8HTY6
