### ISSUE TITLE
表单提交会触发两次

### ISSUE THREAD

**Issue by FelixLiuSheng** [layui/layui#175]
每次表单提交按钮事件触发都会触发两次事件

**Comment by haoqicherish** [comment]
检查下是否引用了两次layer.js，之前遇到过这个问题，我的原因是页面引用的head.ftl，且head.ftl和页面各引用了一次js。

**Comment by FelixLiuSheng** [comment]
找过，还是同样的问题，最终的解决办法，只能使用普通的button代替了
