### ISSUE TITLE
tab选项卡选中状态.layui-this:after下划线未被白色覆盖

### ISSUE THREAD

**Issue by B-wells** [layui/layui#1750]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

298

### 问题描述

选项卡除了简约风格，其他的选中状态.layui-this:after下划线未被白色覆盖
触发 ：
https://layui.dev/docs/2/tab/#default
浏览器 Google Chrome 123.0.6312.59

访问正常，在页面被缩放时会出现

### 业务代码

```auto
Markdown
```

### 截图补充

![image](https://github.com/layui/layui/assets/17328531/b9d60a83-6248-487c-bdf4-d4b31900c386)

### 浏览器

Google Chrome 123.0.6312.59 64位

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
因为 layui admin 的兼容性问题，不会修复。

**Comment by sentsim** [comment]
页面缩放比例非 100% 的情况下出现的瑕疵可先忽略。
