### ISSUE TITLE
treetable怎么将父子关系单独放到一列中

### ISSUE THREAD

**Issue by abc903349085** [layui/layui#1751]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.8

### 问题描述

现在父子关系是在一列中展示，可不可以在在多列中展示

### 业务代码

```auto
treetable
```

### 截图补充

<img width="470" alt="微信图片_20240403152833" src="https://github.com/layui/layui/assets/22519646/4de1ec4a-e981-478b-bcbc-38d80047c1f7">
<img width="254" alt="微信图片_20240403152817" src="https://github.com/layui/layui/assets/22519646/e9162ba0-3a60-4d6e-8329-dc2bae7c5e82">

### 浏览器

谷歌 eage

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
目前不支持，没有计划添加这个功能
