### ISSUE TITLE
layer.photos能否增加自定义按钮在顶部

### ISSUE THREAD

**Issue by onlycyndi** [layui/layui#1765]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.8

### 问题描述

你好，我打开了photos进行图片列表预览，类似的我想做个删除按钮，查询了Api这些没有相关的解答。

### 业务代码

```auto
layer.photos({
        photos: {
          "title": "Photos Demo",
          "start": 0,
          "data": [
            {
              "alt": "layer",
              "pid": 1,
              "src": "https://unpkg.com/outeres@0.1.1/demo/layer.png",
            },
            {
              "alt": "壁纸",
              "pid": 3,
              "src": "https://unpkg.com/outeres@0.1.1/demo/000.jpg",
            },
            {
              "alt": "浩瀚宇宙",
              "pid": 5,
              "src": "https://unpkg.com/outeres@0.1.1/demo/outer-space.jpg",
            }
          ]
        }
      });
```

### 浏览器

版本 123.0.6312.107（正式版本） (arm64)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by haodiao** [comment]
建议你复制一份 layer 代码自行修改后，再以插件的方式加载进去使用。
例如：` layui.use(['layerNew'], function () {})`  
他那个 `"thumb": "" ` 缩略图地址参数没有效果，而是直接显示  `"src"`， 所以也是自己改一下才行
