### ISSUE TITLE
Table里是否能添加类似tablePlug里的列数据筛选

### ISSUE THREAD

**Issue by cyjcxy** [layui/layui#1770]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

请求：Table里是否能添加类似tablePlug里的列数据筛选，真的很好用

### 业务代码

```auto
filter: true
```

### 截图补充

![1](https://github.com/layui/layui/assets/32184537/da5d06a3-d5a8-4447-89cd-7e04dff8349c)

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of https://github.com/layui/layui/issues/1556
