### ISSUE TITLE
Table能否实现不重载或重新渲染实现数据更新

### ISSUE THREAD

**Issue by qinggege2024** [layui/layui#1776]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.6

### 问题描述

想批量更新表格中的数据，不回写到数据库，如何实现不重载或重新渲染实现数据更新

### 业务代码

```auto
目前是把数据取出，修改后再重载表格
let data = table.getData('printTable');
				layer.prompt({
					value: '1',
					title: '请输入初始序号'
				}, function(value, index, elem){
					let xh = value;
					layui.each(data, function(i){
						data[i].xh = xh;
						xh++;
					}); 
					layer.close(index);
					table.reloadData('printTable', {data: data, initSort: {field: 'xh', type: 'asc'}});
				});
```

### 浏览器

Microsoft Edge 123.0.2420.81

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by hjingsuper** [comment]
可以看下table的updateRow方法 `table.updateRow(id, opts);`
[https://layui.dev/docs/2/table/#table.updateRow](https://layui.dev/docs/2/table/#table.updateRow)
