### ISSUE TITLE
下载发行版 windows安全中心layui.js提示木马 Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by qqzzid** [layui/layui#1780]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

<img width="361" alt="baodu" src="https://github.com/layui/layui/assets/8757312/46f0552f-56c3-45fe-b8d7-7cac6bce26f0">

### 业务代码

```auto
layui.js 提示木马 Trojan:Script/Wacatac.H!ml     windows安全中心
```

### 浏览器

Chrome123

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
好家伙，我的下载完后Windows安全中心并没有报毒。

**Comment by sentsim** [comment]
应该是误报，JS 文件都是静态资源，能有什么木马呢。
