### ISSUE TITLE
自定义选项卡只支持兄弟节点，跨父级节点不受支持

### ISSUE THREAD

**Issue by kesry** [layui/layui#1789]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

在自定义选项卡功能时，仅支持同父级节点，不支持跨父级节点，在实际业务功能中，我们大多需要在点击垂直菜单中的菜单，然后再选项卡上展示相关数据，但是菜单中的item，大多都不是兄弟节点，而是根据权限展示的菜单，对于每一个父级菜单，都需要定一个element.tab，代码就显得过于冗杂，不易管理，希望可以支持跨父级节点的自定义选项卡，谢谢。
以下为v2.9.8中element.js中定义的自定义Tab选项卡的相关代码

 // 自定义 Tab 选项卡
  Element.prototype.tab = function(options){
    options = options || {};
    dom.on('click', options.headerElem, function(e){
      var index = $(this).index();
      call.tabClick.call(this, {
        index: index,
        options: options
      });
    });
  };

### 业务代码

```auto
element.tab({
          headerElem: '#layui-nav dd',
          bodyElem: '#layui-tab-content>div'
        });
```

### 截图补充

element.tab({
          headerElem: '#layui-nav dd',
          bodyElem: '#layui-tab-content>div'
        });

### 浏览器

Chrome  正式版 123.0.6312.122

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by kesry** [comment]
这是菜单
<ul id="layui-nav" class="layui-nav layui-nav-tree layui-bg-gray" lay-filter="menu-tab">
            <li class="layui-nav-item layui-nav-itemed">
              <a href="javascript:;">xxxx</a>
              <dl class="layui-nav-child">
                <dd class="layui-this" lay-id="11"><a href="javascript:;">xxx</a></dd>
                <dd lay-id="12"><a href="javascript:;">xxx</a></dd>
                <dd lay-id="13"><a href="javascript:;">xxx</a></dd>
              </dl>
            </li>
            <li class="layui-nav-item layui-nav-itemed">
                <a href="javascript:;">xxx</a>
                <dl class="layui-nav-child">
                  <dd lay-id="14"><a href="javascript:;">zzzz</a></dd>
                  <dd lay-id="15"><a href="javascript:;">xxxx</a></dd>
                  <dd lay-id="16"><a href="javascript:;">xxxx</a></dd>
                </dl>
              </li>
            <li class="layui-nav-item">
              <dd lay-id="17"><a href="javascript:;">click menu item</a></dd>
            </li>
            <li class="layui-nav-item"><a href="javascript:;">the links</a></li>
          </ul>
这是定义的tab-body
              <div id="layui-tab-content">
                <div class="layui-tab-item" class="layui-show">内容-1</div>
                <div class="layui-tab-item">内容-2</div>
                <div class="layui-tab-item">内容-3</div>
                <div class="layui-tab-item">内容-4</div>
                <div class="layui-tab-item">内容-5</div>
                <div class="layui-tab-item">内容-6</div>
                <div class="layui-tab-item">内容-7</div>
              </div>

**Comment by kesry** [comment]
将index修复成如下代码，重新编译打包，就可以正常了。
var index = $(options.headerElem).index($(this));

**Comment by Sight-wcg** [comment]
> 将index修复成如下代码，重新编译打包，就可以正常了。
> var index = $(options.headerElem).index($(this));

欢迎 PR
