### ISSUE TITLE
重复引入layui导致layer的index初始化时为10000

### ISSUE THREAD

**Issue by buqieryul** [layui/layui#1796]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8 

### 问题描述

虽然重复引入layui.js的情况非常少，为了避免他人在此问题踩坑 

### 业务代码

```auto
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script  src="./jquery.js"></script>
    <script src="./layui.js"></script>
    <script src="./layui.js"></script>
<script>
    var layerObj;
    $(function (){
        layui.use('layer', function (){
            debugger
            layerObj = layui.layer;
        })
    });
</script>
</head>


<body>

</body>
</html>
```

### 截图补充

![微信截图_20240417100809](https://github.com/layui/layui/assets/51147864/524378ff-e454-4510-87d0-340b357b3a18)
![微信截图_20240417100834](https://github.com/layui/layui/assets/51147864/545e50f5-2f25-4b0c-b5be-cf6f5c132039)

### 浏览器

null

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这不算 BUG，不会处理这个问题，使用时应该避免重复引入 layui。
