### ISSUE TITLE
layui.flow 希望可以增加滚动到顶部后继续下拉,松手后刷新内容

### ISSUE THREAD

**Issue by 2314933036** [layui/layui#1799]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

layui.flow 希望可以增加滚动到顶部后继续下拉,松手后刷新内容,移动端需要使用这个功能

### 业务代码

```auto
flow.load({
    elem: '#ID-flow-demo', // 流加载容器
    scrollElem: '#ID-flow-demo', // 滚动条所在元素，一般不用填，此处只是演示需要。

//在这个位置增加一个属性用于开启这个功能

    done: function(page, next){ // 执行下一页的回调
      // 模拟数据插入
      setTimeout(function(){
        var lis = [];
        for(var i = 0; i < 8; i++){
          lis.push('<li>'+ ( (page-1)*8 + i + 1 ) +'</li>')
        }
        
        // 执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
        // pages 为 Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
        next(lis.join(''), page < 10); // 此处假设总页数为 10
      }, 520);
    }
  });
```

### 浏览器

chrome 122.0.6261.70 (f12手机模式)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
不好意思，layui 主要面向桌面端，不接受移动端的功能请求。
现有的功能很容易实现下拉刷新，以下代码仅供参考，请根据实际情况调整。

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
    <link href="../src/css/layui.css" href1="//unpkg.com/layui@2.8.17/dist/css/layui.css" rel="stylesheet" />
    <style>
      .flow-demo {
        height: 400px;
        overflow: auto;
        font-size: 0;
      }
      .flow-demo li {
        display: inline-block;
        margin: 0 5px;
        font-size: 14px;
        width: 48%;
        margin-bottom: 10px;
        height: 100px;
        line-height: 100px;
        text-align: center;
        background-color: #eee;
      }
    </style>
  </head>
  <body class="layui-padding-3">
    <button>reload</button>

    <div class="flow-demo" id="ID-flow-demo"></div>

    <!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
    <script src="../src/layui.js" src1="//unpkg.com/layui@2.8.17/dist/layui.js"></script>
    <script>
      layui.use(function () {
        var flow = layui.flow;
        var $ = layui.$;

        var flowOptions = {
          elem: '#ID-flow-demo', // 流加载容器
          scrollElem: '#ID-flow-demo', // 滚动条所在元素，一般不用填，此处只是演示需要。
          done: function (page, next) {
            var that = this;
            // 模拟数据插入
            setTimeout(function () {
              if(that._reload){
                that._reload = undefined;
                $(that.scrollElem).animate({marginTop: 0}, 'fast');
              }
              var lis = [];
              for (var i = 0; i < 8; i++) {
                lis.push('<li>' + ((page - 1) * 8 + i + 1) + '</li>');
              }

              // 执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
              // pages 为 Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
              next(lis.join(''), page < 3); // 此处假设总页数为 10
            }, 520);
          },
        };

        function flowRender(options){
          var el = $(options.elem);
          var scrollEl = $(options.scrollElem);
          var dampingFactor = 0.25;
          var threshold = 40;

          // 流加载实例
          flow.load(options);
          // 滑动
          lay.touchSwipe(scrollEl[0], {
            onTouchMove: function(e, state){
              if(state.direction === 'down'){
                var distance = Math.abs(state.distanceY) * dampingFactor;
                scrollEl.css({marginTop: distance})
              }
            },
            onTouchEnd: function(e, state){
              var distance = Math.abs(state.distanceY) * dampingFactor;
              // 重载并恢复位置
              if(state.direction === 'down' && distance > threshold){
                el.html('');
                scrollEl.off('scroll');
                options._reload = true;
                flow.load(options);
              }else{
                scrollEl.animate({marginTop: 0},'fast')
              }
            }
          })
        }

        flowRender(flowOptions)
      });
    </script>
  </body>
</html>

```

**Comment by 2314933036** [comment]
> 不好意思，layui 主要面向桌面端，不接受移动端的功能请求。 现有的功能很容易实现下拉刷新，以下代码仅供参考，请根据实际情况调整。
> 
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="utf-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1" />
>     <title>Demo</title>
>     
>     <link href="../src/css/layui.css" href1="//unpkg.com/layui@2.8.17/dist/css/layui.css" rel="stylesheet" />
>     <style>
>       .flow-demo {
>         height: 400px;
>         overflow: auto;
>         font-size: 0;
>       }
>       .flow-demo li {
>         display: inline-block;
>         margin: 0 5px;
>         font-size: 14px;
>         width: 48%;
>         margin-bottom: 10px;
>         height: 100px;
>         line-height: 100px;
>         text-align: center;
>         background-color: #eee;
>       }
>     </style>
>   </head>
>   <body class="layui-padding-3">
>     <button>reload</button>
> 
>     <div class="flow-demo" id="ID-flow-demo"></div>
> 
>     
>     <script src="../src/layui.js" src1="//unpkg.com/layui@2.8.17/dist/layui.js"></script>
>     <script>
>       layui.use(function () {
>         var flow = layui.flow;
>         var $ = layui.$;
> 
>         var flowOptions = {
>           elem: '#ID-flow-demo', // 流加载容器
>           scrollElem: '#ID-flow-demo', // 滚动条所在元素，一般不用填，此处只是演示需要。
>           done: function (page, next) {
>             var that = this;
>             // 模拟数据插入
>             setTimeout(function () {
>               if(that._reload){
>                 that._reload = undefined;
>                 $(that.scrollElem).animate({marginTop: 0}, 'fast');
>               }
>               var lis = [];
>               for (var i = 0; i < 8; i++) {
>                 lis.push('<li>' + ((page - 1) * 8 + i + 1) + '</li>');
>               }
> 
>               // 执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
>               // pages 为 Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
>               next(lis.join(''), page < 3); // 此处假设总页数为 10
>             }, 520);
>           },
>         };
> 
>         function flowRender(options){
>           var el = $(options.elem);
>           var scrollEl = $(options.scrollElem);
>           var dampingFactor = 0.25;
>           var threshold = 40;
> 
>           // 流加载实例
>           flow.load(options);
>           // 滑动
>           lay.touchSwipe(scrollEl[0], {
>             onTouchMove: function(e, state){
>               if(state.direction === 'down'){
>                 var distance = Math.abs(state.distanceY) * dampingFactor;
>                 scrollEl.css({marginTop: distance})
>               }
>             },
>             onTouchEnd: function(e, state){
>               var distance = Math.abs(state.distanceY) * dampingFactor;
>               // 重载并恢复位置
>               if(state.direction === 'down' && distance > threshold){
>                 el.html('');
>                 scrollEl.off('scroll');
>                 options._reload = true;
>                 flow.load(options);
>               }else{
>                 scrollEl.animate({marginTop: 0},'fast')
>               }
>             }
>           })
>         }
> 
>         flowRender(flowOptions)
>       });
>     </script>
>   </body>
> </html>
> ```

有lay.touchSwipe的文档么?我试了下这段代码flow原本的内容滑动失效了

**Comment by Sight-wcg** [comment]
> 有 lay.touchSwipe 的文档么?

https://github.com/layui/layui/blob/13b0b42528666336dff43d142c1db94324f78d52/src/modules/lay.js#L534-L553

> 我试了下这段代码flow原本的内容滑动失效了

我在设备仿真中测试的，看起来有一些差异，按照下面的步骤修改。

注意：理论上应该在滚动容 scrollTop 为 0 时才开始计算滑动距离，所以下面的代码肯定是有边缘情况的，仅供参考实现， 你可以通过回调中的参数 e (touch 事件) 重新计算滑动距离。

1.将 lay.touchSwipe 从源码中复制出来，加入到你的公共模块，并在页面中引用，去掉 onMove 回调中的 ` e.preventDefault();`
https://github.com/layui/layui/blob/13b0b42528666336dff43d142c1db94324f78d52/src/modules/lay.js#L581-L593
```diff
    var onMove = function(e){
-      e.preventDefault();
      state.pointerEnd.x = e.touches[0].clientX;
      state.pointerEnd.y = e.touches[0].clientY;
      state.distanceX = state.pointerStart.x - state.pointerEnd.x;
      state.distanceY = state.pointerStart.y - state.pointerEnd.y;
      if(Math.abs(state.distanceX) > Math.abs(state.distanceY)){
        state.direction = state.distanceX > 0 ? 'left' : 'right';
      }else{
        state.direction = state.distanceY > 0 ? 'up' : 'down';
      }
      options.onTouchMove && options.onTouchMove(e, state);
    }
```
2. 修改示例
```diff
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
    <link href="../src/css/layui.css" href1="//unpkg.com/layui@2.8.17/dist/css/layui.css" rel="stylesheet" />
    <style>
      .flow-demo {
        height: 400px;
        overflow: auto;
        font-size: 0;
      }
      .flow-demo li {
        display: inline-block;
        margin: 0 5px;
        font-size: 14px;
        width: 48%;
        margin-bottom: 10px;
        height: 100px;
        line-height: 100px;
        text-align: center;
        background-color: #eee;
      }
    </style>
  </head>
  <body class="layui-padding-3">
    <button>reload</button>

    <div class="flow-demo" id="ID-flow-demo"></div>

    <!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
    <script src="../src/layui.js" src1="//unpkg.com/layui@2.8.17/dist/layui.js"></script>
    <script>
      layui.use(function () {
        var flow = layui.flow;
        var $ = layui.$;

        var flowOptions = {
          elem: '#ID-flow-demo', // 流加载容器
          scrollElem: '#ID-flow-demo', // 滚动条所在元素，一般不用填，此处只是演示需要。
          done: function (page, next) {
            var that = this;
            // 模拟数据插入
            setTimeout(function () {
              if(that._reload){
                that._reload = undefined;
                $(that.scrollElem).animate({marginTop: 0}, 'fast');
              }
              var lis = [];
              for (var i = 0; i < 8; i++) {
                lis.push('<li>' + ((page - 1) * 8 + i + 1) + '</li>');
              }

              // 执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
              // pages 为 Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
              next(lis.join(''), page < 3); // 此处假设总页数为 10
            }, 520);
          },
        };

        function flowRender(options){
          var el = $(options.elem);
          var scrollEl = $(options.scrollElem);
          var dampingFactor = 0.25;
          var threshold = 40;

          // 流加载实例
          flow.load(options);
          // 滑动
          lay.touchSwipe(scrollEl[0], {
            onTouchMove: function(e, state){
+              if(state.direction === 'down' && scrollEl.scrollTop() === 0){
+               e.preventDefault();
                var distance = Math.abs(state.distanceY) * dampingFactor;
                scrollEl.css({marginTop: distance})
              }
            },
            onTouchEnd: function(e, state){
              var distance = Math.abs(state.distanceY) * dampingFactor;
              // 重载并恢复位置
+              if(state.direction === 'down' && scrollEl.scrollTop() === 0 && distance > threshold){
                el.html('');
                scrollEl.off('scroll');
                options._reload = true;
                flow.load(options);
              }else{
                scrollEl.animate({marginTop: 0},'fast')
              }
            }
          })
        }

        flowRender(flowOptions)
      });
    </script>
  </body>
</html>

```

**Comment by 2314933036** [comment]
可以使用了,十分感谢
