### ISSUE TITLE
layui的一些建议和意见

### ISSUE THREAD

**Issue by ydq** [layui/layui#18]
贤心您好，一直在有使用您的laytpl，最近开发一个后台项目，所以打算使用layui，使用过程中发现一些个人觉得不好的地方，在论坛有发了几个帖子不见回复，于是在这里作为建议提出来，希望您不要介意。
- laypage模块
这个模块很棒，但是目前如果我想实现包含搜索在内的全部的ajax功能，因为加入了搜索条件，所以分页的总页码数是会变化的，当前的laypage不像form模块有个重新render的功能，而且好像参数也不支持动态修改分页参数，不支持直接触发跳转到指定页的方法（当然有可能是我不会使用，还请您指出）
- form模块
这个模块很难挑出什么样的毛病，但是使用过程中发现一点疑问，第一是filter，在使用filter过滤绑定事件，但是还是会触发默认的submit事件，也就是说必须针对每个表单的submit事件单独做个处理或者绑定一个不带filter的submit时间通用的return false，不是很优雅，个人感觉filter应该放在form上，然后定制一下jquery的选择器过滤，再单独绑定事件，这样处理会不会更好一点，其次form的on方法破坏了链式操作的逻辑，比如我页面有多个表单使用filter来绑定不同的事件，本意是form().verify().on().on().on()，但是发现on之后返回的是layui对象而不是form对象。
- layer模块
layer作为一个独立惊艳的弹窗模块个人非常之喜欢，目前layer是支持多次弹窗的，而在官方文档描述说是支持传入一个id参数判断唯一性，那既然有id属性为什么不支持直接用id来关闭指定对话框呢？目前只能根据调用layer方法后的返回值index来关闭，如果我的对话框在某个内部的回调函数中弹出的，如果在外层或者别处的方法里面要关闭这个对话框目前的做法只能是申明一个全局变量来接收这个index或者使用closeAll方法或者close 最后一个index的方法，但是如果我中间可能出现别的弹窗的情况下就只能是全局变量了。其次layer的content参数测试了下，只能支持jquery对象而不是像文档中所说的dom对象，个人觉得应该处理一下都可以支持才对，甚至可以扩展一下content直接支持jquery（css）选择器。
layer模块里面的图标应该是使用的图片，在视网膜屏幕下看起来比较模糊，既然layer本身内置了一些来自于iconfont的字体，为什么不直接使用字体图标呢？
而且个人感觉layui既然没有原创的字体的话不建议去内置一批字体，除非组件有需要可以集成少量的必须的字体图标，而且定制后的font名字不应再叫iconfont.xxx，如果用户需要自己去iconfont上定制字体就会导致冲突或必须要换目录结构，毕竟对于真正想用字体图标的人来说肯定会自己去找类似于font awesome等库或者去iconfont自己定制。

有一个小疑问就是官方明确说layui是支持全部引用（不适用模块化）的，而相信大多数“老一代”的后端程序员，做那种后台管理不追求性能的项目时，更乐意接受全部引用的方式（至少我就是这样），后端语言模板支持include的一般会选择在顶部统一引用所有的资源，这样在页面中间写js等时不会提示缺少js库什么的，按照这样的使用场景，如果再页面顶部引用全量打包版本的layui会导致比如导航等无法渲染，必须要将全量js放在导航等元素的下面才能自运行渲染，form至少还有个render方法可以重新渲染一下，所以建议将所有初始化渲染的方法放在页面加载完之后或者给如element等独立提供重新渲染的方法。

最后还有一个问题就是官方的版本modules目录下的js包含的jquery，但是却没有提供jquery的$变量出去，以至于如果需要使用第三方jq库还是得引入一个jquery库，layui.all的体积计算一下的话也应该是内置了一个定制的jquery，所以与其这样还不如精简layui不要内置jquery，要求用户单独引入jquery（如果我理解错误的话请原谅）

**Comment by sentsin** [comment]
感谢反馈，下面逐条回复：

* laypage模块
  * 可以在jump中执行 this.pages = 12，来改变总页数
  * 无法通过接口直接跳转到指定页确实没有，2.0会考虑这一块

* form模块
  * 不带filter本身就是监听所有的submit事件，这就跟你给document绑定一个点击事件一个意思，只要是点击他的子元素都会被触发到。所以才需要用filter
  * on 确实会破坏form的链式，下个版本纠正

* layer模块
  * index来关闭应该也足够使用，不过id来关闭倒也行，不用管返回的值。下个版本考虑加上吧
  * layer基于jQuery，支持jQuery对象就足够了

* 其它
  * 关于不建议内置一批字体这一项，我并不认同。如果要扩展字体，本身就应该要考虑覆盖问题，建个目录并不是多大的事。
  * layui有两种加载方式 ，也可以不用模块化：http://www.layui.com/doc/#simple
  * 关于内置的jQuery：http://www.layui.com/doc/base/faq.html#jquery

**Comment by ydq** [comment]
感谢您百忙之中的回复。

- laypage模块目前的问题就是，比如应用场景ajax搜索，搜索的触发是其他元素的点击，所以无法获取当前已经初始化好的page对象也就无法设定pages总页数了

- layer弹窗在使用页面内容弹出的时候貌似有点小bug

测试内容如下
```html
<style>.hide{display:none};</style>
<div id="dialog" class="hide">balabala</div>
<script>
layer.open({
	type:1,
	title:'test',
	content:$('#dialog')
})
</script>
```
此种情况会出现当对话框关闭后 div上依旧残留一个 `style="display:block;"`导致div还原后无法隐藏


```html
<div id="dialog" style="display:none">balabala</div>
<script>
layer.open({
	type:1,
	title:'test',
	content:$('#dialog')
})
</script>
```
此种情况会出现当对话框关闭后 div上的 `style="display:block;"`没还原，style被清空了，导致div还原后无法隐藏



```html
<div id="dialog" class="hide" style="display:none">balabala</div>
<script>
layer.open({
	type:1,
	title:'test',
	content:$('#dialog')
})
</script>
```
此种情况会出现当对话框关闭后 div上依旧残留一个 `style="display:block;"`，样式优先级高于`.hide{display:none}`导致div还原后无法隐藏

而且也不能使用`.layui-hide`，因为有important优先级太高会导致完全无法显示
