### ISSUE TITLE
想使用layuiadmin，但看只能是老用户下载，请问现在可以提供一个购买下载吗

### ISSUE THREAD

**Issue by HolyRisk** [layui/layui#1806]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2

### 问题描述

想使用layuiadmin，但看只能是老用户下载，请问现在可以提供一个购买下载吗

### 业务代码

```auto
想使用layuiadmin，但看只能是老用户下载，请问现在可以提供一个购买下载吗
```

### 浏览器

Chrome/123.0.0.0

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
关注该主题主页说明：https://dev.layuion.com/themes/layuiAdmin

**Comment by HolyRisk** [comment]
看到这篇文章了，所以想通过这里确认是否新渠道提供新用户购买，没有就算了，谢谢

**Comment by HolyRisk** [comment]
> 关注该主题主页说明：https://dev.layuion.com/themes/layuiAdmin
看到这篇文章了，所以想通过这里确认是否新渠道提供新用户购买，没有就算了，谢谢
