### ISSUE TITLE
tree组件，在数据量较大的情况下的问题。

### ISSUE THREAD

**Issue by yestianxu** [layui/layui#1809]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

tree组件，在数据量较大的情况下，调用setChecked方法，展示已经checked的数据，会造成很严重的卡顿，可以解决一下么，谢谢。

### 业务代码

```auto
tree.setChecked('asset_tree_id', selected);
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
ref: https://github.com/layui/layui/issues/1606#issuecomment-1916536470

**Comment by yestianxu** [comment]
谢谢~
