### ISSUE TITLE
select选择框的lay-creatable=""功能出现反射性xss

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#1810]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

我想通过select的lay-creatable=""实现正则表达式选择性输入，但是发现html标签会被解析，如输入<script>alert(1)</script>则直接造成了反射性xss漏洞

![image](https://github.com/layui/layui/assets/112995594/eb59cebe-3ea4-4d5d-8783-153e8a55b392)

### 业务代码

```auto
<div class="layui-col-md6">
    <select lay-search="" lay-creatable="">
      <option value="">可创建新的 option</option>
      <option value="1">AAA</option>
      <option value="2">aaa</option>
      <option value="3">BBB</option>
      <option value="4">bbb</option>
      <option value="5">ABC</option>
      <option value="6">abc</option>
      <option value="7">AbC</option>
    </select>
  </div>
```

### 浏览器

Microsoft Edge 版本 123.0.2420.97 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
问题的确存在，需通过 `util.escape()` 对新添加的选项做编码处理。
