### ISSUE TITLE
最新版的idea在引入了layui.js后无法识别layui

### ISSUE THREAD

**Issue by starao520** [layui/layui#1816]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.6

### 问题描述

最新版的idea在引入了layui.js后无法识别layui,虽然最后编译是正常的,但开发的时候看着总是难受😣

### 业务代码

```auto
layui.use()
```

### 截图补充

![微信截图_20240422102030](https://github.com/layui/layui/assets/46470730/dae3a4c1-6f09-4774-a38b-ce70d4e693b1)

### 浏览器

124.0.6367.60

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
你用了**pear-admin**？

**Comment by Sight-wcg** [comment]
新版 IDEA 默认不会解析压缩后的 JS 文件，将 layui.js 代码格式化即可。
或者参考 IDEA 文档，安装 @types/layui-src，虽然过时了但勉强能用。https://www.jetbrains.com/help/idea/2024.1/configuring-javascript-libraries.html

**Comment by starao520** [comment]
将 layui.js 代码格式化即可
