### ISSUE TITLE
颜色选择器选择#FFF或#000的时候游标会溢出

### ISSUE THREAD

**Issue by abin2011** [layui/layui#1817]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

颜色选择器,,四边选择的时候会超出范围
比如选择#FFF或#000的时候
![error](https://github.com/layui/layui/assets/1227434/fcec0003-ec73-4a85-b0be-df5a12179df9)

### 业务代码

```auto
https://layui.dev/docs/2/colorpicker/
```

### 浏览器

Firefox 125.0 和 Chrome 124.0

### 演示地址

https://layui.dev/docs/2/colorpicker/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by abin2011** [comment]
这个问题并没有修复..修复的代码是针对input的修复.

**Comment by Sight-wcg** [comment]
> 这个问题并没有修复..修复的代码是针对input的修复.

修复后的效果参考 #1850 中的截图，目前
