### ISSUE TITLE
table组件的静态表格渲染，在td单元格不支持div包裹的数据吗？

### ISSUE THREAD

**Issue by yuyiqilin** [layui/layui#1820]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.8

### 问题描述

table组件的静态表格渲染，在td单元格不支持div包裹的数据吗？渲染完成后div元素都转义成了纯文本了。记得2.6左右的老版本没有这个问题的。

### 业务代码

```auto

这个是C#的后台代码段
<td><div><div class="imgDiv"><img src='" + fileimgtype + "'>" + list[i].FileName + "</div></div></td>
```

### 截图补充

![微信截图_20240423085556](https://github.com/layui/layui/assets/52533133/0e93753a-5006-4ef5-b24d-ff6e9adce268)

### 浏览器

Chrome 123.0.6312.124

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
尝试关闭 escape

**Comment by yuyiqilin** [comment]
> 尝试关闭 escape

谢谢，解决了
