### ISSUE TITLE
建议：treeTable组件在isSimpleData时智能判断root节点，不需要用rootPid指定根节点

### ISSUE THREAD

**Issue by gmxyb** [layui/layui#1825]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

treeTable组件在isSimpleData时，使用 id, pid 指明父子关系，root 节点的 pid 如果不是 null 则需要单独用rootPid指定值，这是完全没有必要的，因为根据 pid 找不到父节点的，都可以算作 root 节点，这样可以简化设置，提高容错能力。

### 业务代码

```auto
treeTable.render({
  elem: '',
  tree: { // treeTable 特定属性集
    customName: {},
    data: { rootPid: "0" }, // 用于设置根节点的 pid 属性值【没有必要】
    view: {},
    async: {},
    callback: {}
  },
  // 其他 table 属性
});
```

### 浏览器

通用

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
虽然很容易实现，但我不能排除 rootPid 在将来可能有其他用途(部分 API 设计参考了 zTree)。
如果增加一个 rootPid: 'auto' 时自动寻找根节点，并将 rootPid 默认值修改为 'auto' 如何呢？ @sentsim

**Comment by Sight-wcg** [comment]
虽然实现很简单，但 rootPid 可能有其他设计用途，所以暂时不会支持。

**Comment by Sight-wcg** [comment]
ref: #1912
