### ISSUE TITLE
layui导出拓展

### ISSUE THREAD

**Issue by JiangYuSong** [layui/layui#1827]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.8

### 问题描述

之前用得2.7.6版本，自己在导出做了拓展，后面更新2.9.8后，扩展就不生效了。不知道什么原因导致的

### 业务代码

```auto
case 'LAYTABLE_EXPORT': // 导出
                    if (!data.length) return layer.tips('当前表格无数据', this, { tips: 3 });
                    if (device.ie) {
                        layer.tips('导出功能不支持 IE，请用 Chrome 等高级浏览器导出', this, {
                            tips: 3
                        });
                    } else {
                        openPanel({
                            list: function () {
                                return [
                                    '<li data-type="csv">导出 csv 格式文件</li>',
                                    '<li data-type="xls">导出 xls 格式文件</li>',
                                    '<li data-type="xlsx">导出 xlsx 格式文件</li>'
                                ].join('')
                            }(),
                            done: function (panel, list) {
                                list.on('click', function () {
                                    var type = $(this).data('type')
                                    table.exportFile.call(that, options.id, null, type);
                                });
                            }
                        });
                    }
                    break;
```

### 截图补充

![5d76430e94ca0a03c62c79b27057bac1](https://github.com/layui/layui/assets/40968914/a9c066ae-23d8-4913-b61c-ed6d2bde3d28)

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by JiangYuSong** [comment]
@Sight-wcg 有什么办法可以找到该原因吗，就是标准版的基础中，在table.js中添加了一列导出

**Comment by Sight-wcg** [comment]
> @Sight-wcg 有什么办法可以找到该原因吗，就是标准版的基础中，在table.js中添加了一列导出

没办法，我也猜不出原因。

**Comment by JiangYuSong** [comment]
> > @Sight-wcg 有什么办法可以找到该原因吗，就是标准版的基础中，在table.js中添加了一列导出
> 
> 没办法，我也猜不出原因。

![1714018203425](https://github.com/layui/layui/assets/40968914/5e5adbe8-2cfb-427d-b0b7-a0abf138c2ab)
在这里。。。新版的好像转义了一下
