### ISSUE TITLE
使用layui.use(['layer'], 无法剧中

### ISSUE THREAD

**Issue by taohuangtao** [layui/layui#183]
layui.use(['layer'], function () {
            var layer = layui.layer;
            var index = layer.load();

直接就在最左边，BUG,太大了，只能使用layui.all.js,放弃模块化方式

**Comment by zzliux** [comment]
这个是因为layer的css还没加载完成就被调用了弹窗方法，导致弹出层父级元素宽度计算错误，具体解决的话你可以先手动将layer的css放在head里面引入，我之前也是遇到这个问题，准备提个bug的，看到有人反映就算了吧
