### ISSUE TITLE
我希望通过upload上传组件实现本地加密

### ISSUE THREAD

**Issue by starWillRed** [layui/layui#1831]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

我调用了upload组件，并在before函数中通过obj参数获取了文件，随后我使用对称加密方式加密了文件，但没有找到方法给obj重新赋值加密后的文件，以便上传加密后的文件。

### 业务代码

```auto
无
```

### 截图补充

![IMG_20240424_224311](https://github.com/layui/layui/assets/168001421/2bdd42b9-7b35-4fb3-83ea-c9e62edbc552)

### 浏览器

109

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
在上传前改上传参数确实是比较常用的情况。

**Comment by Sight-wcg** [comment]
obj.resetFile 能否解决？

**Comment by starWillRed** [comment]
> obj.resetFile 能否解决？

我使用了resetFile，在控制台打印obj.pushFile()的时候，文件是resetFile之后的内容，但是在下一行代码中使用obj.preview()预览时，发现文件依然是resetFile之前的内容，上传的文件也依然是resetFile之前的内容。请问这是否意味着resetFile存在某些bug？

**Comment by Sight-wcg** [comment]
> > obj.resetFile 能否解决？
> 
> 我使用了resetFile，在控制台打印obj.pushFile()的时候，文件是resetFile之后的内容，但是在下一行代码中使用obj.preview()预览时，发现文件依然是resetFile之前的内容，上传的文件也依然是resetFile之前的内容。请问这是否意味着resetFile存在某些bug？

没有重现，就没有办法确认

**Comment by starWillRed** [comment]
> obj.resetFile 能否解决？

我使用settimeout方法进一步测试了upload里面的choose、before、progress、done回调函数，发现是因为开启upload的自动上传后，会立即上传文件，而此时choose、before回调函数中的resetFile尚未执行完毕，obj内容自然也就尚未更改。希望在以后的版本更新中能修复这个问题，谢谢。
