### ISSUE TITLE
layui v2.9.8 版本table 有分页查询bug。

### ISSUE THREAD

**Issue by 1124541815** [layui/layui#1833]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

页面单独查询得时候数据没问题，当把分页点击到最后一页得时候，选中一个下拉框查询条件查不到。发现分页参数带过去得是最后一页，然后取消 查询条件，重新查询回到了第一页，再输入条件一个数据都没，发现分页传递得还是最后一页得参数

### 业务代码

```auto
通用写法
```

### 浏览器

谷歌浏览器

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
这个应该不属于bug，查询条件变更之后，应该把当前页调整到第一页，然后再去加载数据。而查询条件是否有变化，只有你自己能控制。

**Comment by 1124541815** [comment]
解决了，跟低版本不一样了。现在查询全部用 table.render(tableOption); 以前低版本用table.reload不行了，要重置分页，最开始老版本不用重置得
