### ISSUE TITLE
请问layui如何实现模块化打包

### ISSUE THREAD

**Issue by fengbingji** [layui/layui#1838]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

请问layui如何实现模块化打包

### 业务代码

```auto
layui.js压缩后的文件大小300多k,说大不大,说小也不小,有时候只需要用到一两个模块,比如layer和datepicker,希望作者可以出一个layui模块化打包的教程.
毕竟300k的js+css+字体icon+其他库,还没算图片什么的,都快到1M了
```

### 浏览器

EDGE

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
有独立版 layer，laydate 需求，可以参考这个项目https://github.com/Sight-wcg/layui-layer。
