### ISSUE TITLE
是否会考虑开发下拉复选框的功能？

### ISSUE THREAD

**Issue by xieyushi** [layui/layui#186]
是否会考虑开发下拉复选框的功能？
比如单个角色对应多个菜单这样的
感觉还是下拉复选框的功能可能最合适呢。。。

**Comment by icey-tea** [comment]
已经有了

https://fly.layui.com/extend/selectN,selectM/
https://fly.layui.com/extend/multiSelect/

**Comment by icey-tea** [comment]
> 是否会考虑开发下拉复选框的功能？
> 比如单个角色对应多个菜单这样的
> 感觉还是下拉复选框的功能可能最合适呢。。。

已经有了

https://fly.layui.com/extend/selectN,selectM/
https://fly.layui.com/extend/multiSelect/

**Comment by fallsea** [comment]
为什么官方不考虑增加下拉复选框 @sentsin
