### ISSUE TITLE
table初始状态配置

### ISSUE THREAD

**Issue by itbencn** [layui/layui#1866]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.8

### 问题描述

table配置url异步请求属性后,每次打开都会自动请求并加载数据,可能存在某些场景不需要首次加载时自动请求并加载

### 业务代码

```auto
*
```

### 浏览器

124.0.6367.119（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
确实没有临时中止请求加载数据的地方

**Comment by mywebtestmail** [comment]
使用函数包裹起来。
如果不需要table界面，不执行函数就好了；
如果需要table界面，但不加载数据，可设置url：变量，变量可初始为空，等需要操作table加载数据时，给变量赋值，再渲染table不就好了

**Comment by itbencn** [comment]
> 使用函数包裹起来。 如果不需要table界面，不执行函数就好了； 如果需要table界面，但不加载数据，可设置url：变量，变量可初始为空，等需要操作table加载数据时，给变量赋值，再渲染table不就好了

不管什么方法肯定没有原生支持体验更好

**Comment by Sight-wcg** [comment]
> 某些场景不需要首次加载时自动请求并加载

可以详细描述下是什么场景吗？首次加载什么的时候自动请求并加载什么？然后，什么时候又需要加载表格数据？

**Comment by itbencn** [comment]
> > 某些场景不需要首次加载时自动请求并加载
> 
> 为了避免理解有偏差，可以详细描述下是什么场景吗？首次加载什么的时候自动请求并加载什么？然后，什么时候又需要加载表格数据？

就是table.render渲染时如果配置了url不要自动请求url地址,只显示table界面即可

模拟场景:有一个搜索数据并显示表格的场景,我希望的是用户输入关键词后手动触发搜索加载数据,而不是页面一加载就自动请求搜索接口

**Comment by Sight-wcg** [comment]
> > > 某些场景不需要首次加载时自动请求并加载
> > 
> > 
> > 为了避免理解有偏差，可以详细描述下是什么场景吗？首次加载什么的时候自动请求并加载什么？然后，什么时候又需要加载表格数据？
> 
> 就是table.render渲染时如果配置了url不要自动请求url地址,只显示table界面即可
> 
> 模拟场景:有一个搜索数据并显示表格的场景,我希望的是用户输入关键词后手动触发搜索加载数据,而不是页面一加载就自动请求搜索接口

可以用上面 @mywebtestmail 提到的解决方案，或者使用 table.render({data:[]}) 和 table.reloadData 来实现
