### ISSUE TITLE
CSP导致table渲染不成功

### ISSUE THREAD

**Issue by anna647** [layui/layui#1870]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.7.6

### 问题描述

出于安全考虑，请求头加入了csp.导致table渲染不成功。有说是new Function导致的。但是提供的解决办法也因为csp被拦截了，这个应该怎么处理啊？

### 业务代码

```auto
function handleFnNonceRequirement(nonce) {
  console.log(999)
    window.Function = function () {
        var renderNode = document.createElement("script"),
            len = arguments.length,
            source = arguments[len-1],
            args = [];

        if ( 1 < len ) {
            for ( var i=0; i<(len-1); i++ ) {
                args.push(arguments[i]);
            }
        }
        renderNode.text = "function __ifYouAbsolutelyMustUseIt() { return function("+args.join(", ")+") {" + source + "}}";
        renderNode.setAttribute('nonce', nonce);

        document.head.appendChild(renderNode).parentNode.removeChild(renderNode);

        return __ifYouAbsolutelyMustUseIt();
    };
}

handleFnNonceRequirement(document.getElementsByTagName("BODY")[0].getAttribute('data-nonce'));
```

### 截图补充

![image](https://github.com/layui/layui/assets/12045697/ddd49c15-f3ee-4b6b-8895-11e5b04716b3)
![image](https://github.com/layui/layui/assets/12045697/321db0be-eb2b-430d-847e-eacd0472a6bc)

### 浏览器

版本 chrome 103.0.5060.53 (正式版本) (64 位元)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
与layui无关，没用过 [内容安全策略（CSP）](https://www.jianshu.com/p/5f9c60db8d00)

**Comment by Sight-wcg** [comment]
没有办法解决这个问题
