### ISSUE TITLE
select 选择框 lay-creatable 输入的自定义信息要到下拉选择才生效 希望回车直接匹配

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1872]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.9

### 问题描述

select 选择框 lay-creatable 输入的自定义信息要到下拉选择才生效 希望回车直接匹配!本身自定义的就没有,还要去选择.

### 业务代码

```auto
lay-search="" lay-creatable=""
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
这很正常嘛，你不选怎么知道创建的选项就是想要的，输入时打字也有回车，无法区分回车是打字还是选择创建的选项。

**Comment by aimu2000** [comment]
用拼音首字母非常有用。打字按的是空格。想用回车行不。或能选择

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月08日 12:00 |
| 收件人 | ***@***.***> |
| 抄送人 | aimu2000 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [layui/layui] select 选择框 lay-creatable 输入的自定义信息要到下拉选择才生效 希望回车直接匹配 (Issue #1872) |

这很正常嘛，你不选怎么知道创建的选项就是想要的，输入时打字也有回车，无法区分回车是打字还是选择创建的选项。
