### ISSUE TITLE
下拉选择框放在 ID-table-demo-page-pagebari 里面显示不出数据

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1875]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.9

### 问题描述

下拉选择框放在 ID-table-demo-page-pagebar 上面显示不出数据

### 业务代码

```auto
<select name="a" lay-filter="a" lay-search="">
				<option value=""></option>
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
			  </select>
```

### 浏览器

ch

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by aimu2000** [comment]
点了没有列表.移出到其它地方正常

**Comment by LSL1618** [comment]
是不是缺少表单域`class="layui-form"`

**Comment by Sight-wcg** [comment]
https://github.com/layui/layui/blob/main/CONTRIBUTING.md
https://gitee.com/layui/layui/issues/I5JBUE

**Comment by aimu2000** [comment]
[LSL1618](https://github.com/LSL1618) 评论 [2小时前](https://github.com/layui/layui/issues/1875#issuecomment-2099824778)
是不是发票表单域class="layui-form"

下拉列表连数据都没有! 不是提交

**Comment by aimu2000** [comment]
> [https://github.com/layui/layui/blob/main/CONTRIBUTING.md ](https://github.com/layui/layui/blob/main/CONTRIBUTING.md) https://gitee.com/layui/layui/issues/I5JBUE

 
	  <script type="text/html" id="ID-table-demo-page-pagebar">
		
		<div class="layui-btn-container">
		  <div class="layui-col-md2 layui-form">
			<div class="layui-input-group layui-form">
			  <div class="layui-input-split layui-input-prefix layui-form" >aaa</div>
			  <select name="bbb" lay-filter="bbb" lay-search="">
				<option value=""></option>
				<option value="1">222</option>
				<option value="2">333</option>
				<option value="3">444</option>
				<option value="4">555</option>
				<option value="5">111</option>
			  </select>
			</div>
		  </div>

又试了一下,确认没有数据显示出来,不放在 <script type="text/html" id="ID-table-demo-page-pagebar"> 这里面就有数据显示的.

**Comment by aimu2000** [comment]
> 是不是发票表单域`class="layui-form"`

就算连 <div class="layui-btn-container"> 加上 都没有用.

**Comment by Sight-wcg** [comment]
> > [https://github.com/layui/layui/blob/main/CONTRIBUTING.md ](https://github.com/layui/layui/blob/main/CONTRIBUTING.md) https://gitee.com/layui/layui/issues/I5JBUE
> 
>  
> 	  <script type="text/html" id="ID-table-demo-page-pagebar">
> 		
> 		<div class="layui-btn-container">
> 		  <div class="layui-col-md2 layui-form">
> 			<div class="layui-input-group layui-form">
> 			  <div class="layui-input-split layui-input-prefix layui-form" >aaa</div>
> 			  <select name="bbb" lay-filter="bbb" lay-search="">
> 				<option value=""></option>
> 				<option value="1">222</option>
> 				<option value="2">333</option>
> 				<option value="3">444</option>
> 				<option value="4">555</option>
> 				<option value="5">111</option>
> 			  </select>
> 			</div>
> 		  </div>
> 
> 又试了一下,确认没有数据显示出来,不放在 <script type="text/html" id="ID-table-demo-page-pagebar"> 这里面就有数据显示的.

请参考链接中的解决方案。

**Comment by aimu2000** [comment]
> > > [https://github.com/layui/layui/blob/main/CONTRIBUTING.md ](https://github.com/layui/layui/blob/main/CONTRIBUTING.md) https://gitee.com/layui/layui/issues/I5JBUE
> > 
> > 
> > ```
> > <script type="text/html" id="ID-table-demo-page-pagebar">
> >   
> >   <div class="layui-btn-container">
> >     <div class="layui-col-md2 layui-form">
> >   	<div class="layui-input-group layui-form">
> >   	  <div class="layui-input-split layui-input-prefix layui-form" >aaa</div>
> >   	  <select name="bbb" lay-filter="bbb" lay-search="">
> >   		<option value=""></option>
> >   		<option value="1">222</option>
> >   		<option value="2">333</option>
> >   		<option value="3">444</option>
> >   		<option value="4">555</option>
> >   		<option value="5">111</option>
> >   	  </select>
> >   	</div>
> >     </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 又试了一下,确认没有数据显示出来,不放在 <script type="text/html" id="ID-table-demo-page-pagebar"> 这里面就有数据显示的.
> 
> 请参考链接中的解决方案。

链接中好像说的是表格组件内部.

放在工具栏就是正常的,
toolbar: '#toolbarDemo',

现在的问题是在分页模板栏
 pagebar: '#ID-table-demo-page-pagebar', // 分页栏模板

**Comment by Sight-wcg** [comment]
https://github.com/layui/layui/blob/main/CONTRIBUTING.md

**Comment by aimu2000** [comment]
一次性说完啊! 标题上都已经说得很清楚了.   ID-table-demo-page-pagebari 不就是分页栏模板吗!

只要不放在这个模板里面 就是正常的!

下拉选择框放在 ID-table-demo-page-pagebari 里面显示不出数据
