### ISSUE TITLE
全局layer设置皮肤  普通msg的layui-layer-hui丢失

### ISSUE THREAD

**Issue by ken678** [layui/layui#1881]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.9

### 问题描述

正常也不会改msg的样式  改他的样式直接重新定义layui-layer-hui就行了，现在一设置皮肤  msg白色就非常丑

### 业务代码

```auto
layer.config({
      skin: 'layui-layer-yzn'
  });
  // 欢迎信息
  layer.msg('Hello World',{time:500000});


这样直接从黑色框变成白色框，样式只想定义alert msg样式不想改动
```

### 浏览器

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这是预期的行为，msg 本身就是通过 dialog 深度定制实现的，内置多款皮肤，默认为 hui。当设置全局皮肤时， msg 就不使用内置的皮肤了。
![image](https://github.com/layui/layui/assets/26325820/e87763ed-54af-477d-a575-d598f4b6d4d4)
