### ISSUE TITLE
 dropdown 的设置lay-id会覆盖原有的lay-id属性·  在tab标签上使用dropdown就会有问题

### ISSUE THREAD

**Issue by fjpcliuhai** [layui/layui#1883]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.9

### 问题描述

如题 

### 业务代码

```auto
if(!lay.isTopElem(elem[0])){
      elem.attr('lay-id',  options.id);
    }
```

### 截图补充

··

### 浏览器

chrome 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
related to #1761
@Sight-wcg 有待晨星评估下内部添加 `lay-id` 之前，是否有必要判断元素已经存在该属性。

**Comment by Sight-wcg** [comment]
> related to #1761 @Sight-wcg 有待晨星评估下内部添加 `lay-id` 之前，是否有必要判断元素已经存在该属性，或提供一个选项用于自定义属性名，默认值 `lay-id`，用户可设置 `false` 禁用该功能。我个人比较倾向于后者。

以组件名做命名空间如何，例如 'lay-dropdown-id',  这样不同组件使用时不会冲突，也不需要新加选项自定义。

- `lay` 为 layui 使用的命名空间
- `dropdown` 为组件命名空间
- `id` 为组件实例的 id/index

需要将所有类似的组件做统一修改，tab 的 'lay-id' 用来标识 tab-title, 保持原样不用处理
