### ISSUE TITLE
table组件，可否增加参数设置loading的样式

### ISSUE THREAD

**Issue by yhl452493373** [layui/layui#1884]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.8

### 问题描述

项目中loading统一用的layui.layer.load(1)，这个和table默认的不一致，也没找到参数能修改。可否加一个这个参数？

### 业务代码

```auto
无
```

### 浏览器

124.0.6367.119

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by yhl452493373** [comment]
> 或许的确可以增加一个函数，用于替代默认的加载风格。

那能否顺便给layer.msg('提示文字',{icon:16})时，的loading样式一起加了，icon:16的时候也是固定的layer.load(0)的样式

**Comment by sentsim** [comment]
```
before: function() { // 数据渲染前
  this.loadIndex = layer.msg('一段提示信息',{
    icon:16
  });
},
complete: { // 数据请求完
  layer.close(this.loadIndex)
}
```

**Comment by sentsim** [comment]
如果要保持两者加载的统一，可以禁用 table 默认的加载，再通过 `before` 回调加上 layer 的加载条
```
loading: false, // 禁用 table 默认加载条
before: function() { // 数据渲染前
  this.loadIndex = layer.msg('一段提示信息',{
    icon:16
  });
},
complete: function() { // 数据请求完
  layer.close(this.loadIndex)
},
```
