### ISSUE TITLE
树形表格无法通过指定父级id以及子级id渲染表格，必须在返回的数据结构中指定children才可以加载树形表格

### ISSUE THREAD

**Issue by XieYun51** [layui/layui#1885]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.9

### 问题描述

无法通过指定父级id以及子级id来渲染树形表格，必须在返回的数据结构中组装好对应的数据结构比如要指定children，特别麻烦，还得在后端重新计算再组装数据结构然后再返回前端，我记得之前是可以直接在前端中指定父级id以及子级id，layui会根据父子id自动渲染他们的层级关系

### 业务代码

```auto
var inst = treeTable.render({

            elem: "#menu-treeTable",
            url: "/users/menuLists",
            request: {
                pageName: 'curPage',
                limitName: 'pageSize'
            },
            page: true,
            toolbar: '#menu-treeTable-method',
            done: function(res, curr, count, origin) {
            },

            tree: { // treeTable 特定属性集

                customName: {
                    name: 'menuName',
                    id: 'menuId',
                    pid: 'menuParentId'
                },



            },
            cols: [
                [{type: 'checkbox', fixed: 'left'},

                {field: 'id', title: '编号', width: 80, align: "center"},

                {field: 'menuName', title: '菜单名称', align: "center"},

                {field: 'menuUrl', title: '菜单地址', align: "center"},

                {field: 'menuIcon', title: '菜单图标',align: "center", width: 150,templet:iconTpl},

                {field: 'menuType', title: '菜单类型',align: "center",templet:typeTpl},
                {field: 'menuShow', title: '可见',align: "center",templet:showTpl},
                {fixed: "right", title: "操作",width: 260, align: "center",toolbar: "#menu-treeTable-utils"}

            ]]

        });
```

### 截图补充

![0809a8beca5482f6ff009d3c95f6286](https://github.com/layui/layui/assets/24429476/269f8b8c-6e04-4f78-8fe4-c238276cc563)
![Uploading 7e92fd2ff4f38d058a38231e565790e.png…]()

### 浏览器

Chrome83.0.4103.106

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
treeTable树表的customName属性不是已经支持你的要求嘛。

**Comment by XieYun51** [comment]
但是在渲染树形表格的时候层级嵌套没有显现出来，而且也没有缩进，只是按照顺序把数据库中的数据渲染到表格了。
![ed8e8143c12985a81f32e63a4342aba](https://github.com/layui/layui/assets/24429476/a785bf9d-91f6-45fe-932b-7ce90fcba8c9)

**Comment by XieYun51** [comment]
已解决，需要使用简单数据模式才可以，文档写的很模糊

**Comment by LSL1618** [comment]
> 已解决，需要使用简单数据模式才可以，文档写的很模糊

`isSimpleData`这个属性的说明确实解释得比较模糊，应该解释为是否平级数据结构或者层级数据结构，这样会更好理解。

**Comment by hjingsuper** [comment]
不好意思，理解错了。当时我做的时候以为isSimpleData只是`treeTable.getData(id, isSimpleData);`有用
使用简单数据结构直接指定父子属性确实可自动渲染层级关系

**Comment by XieYun51** [comment]
相互学习，刚开始有很多不懂的地方，慢慢积累 @hjingsuper

**Comment by Sight-wcg** [comment]
关闭，因为这不是 BUG
