### ISSUE TITLE
table表格组件文档中，似乎缺少totalRowText属性说明

### ISSUE THREAD

**Issue by pkkgu** [layui/layui#1894]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.9

### 问题描述

如题

### 业务代码

```auto
无
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
文档中没有说明，一般代表这个选项已被弃用。不要使用已弃用的选项，他们将来可能会被删除。

**Comment by pkkgu** [comment]
那有其它属性替代totalRowText吗？
我看到issues中还是有很多人在使用这个参数。

**Comment by sentsim** [comment]
因为 `totalRowText` 可被替代，统一使用 `totalRow` 即可，该选项直接设置 `string` 类型值。如：
```
totalRow: '合计：'
```
文档的示例应该是忘了更新。

**Comment by bxjt123** [comment]
> 因为 `totalRowText` 可被替代，统一使用 `totalRow` 即可，该选项直接设置 `string` 类型值。如：
> 
> ```
> totalRow: '合计：'
> ```
> 
> 文档的示例应该是忘了更新。

他俩在导出上貌似有差异，同样`string`类型，`totalRowText`是原样导出，`totalRow`会变成自动合计
![11111](https://github.com/layui/layui/assets/33601030/3c14c69a-e917-44b1-8be3-972e0cb82a51)

**Comment by pkkgu** [comment]
@sentsim @bxjt123 确实有这个问题，但是能需要另开issues讨论。

> > 因为 `totalRowText` 可被替代，统一使用 `totalRow` 即可，该选项直接设置 `string` 类型值。如：
> > ```
> > totalRow: '合计：'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 文档的示例应该是忘了更新。
> 
> 他俩在导出上貌似有差异，同样`string`类型，`totalRowText`是原样导出，`totalRow`会变成自动合计 ![11111](https://private-user-images.githubusercontent.com/33601030/330054257-3c14c69a-e917-44b1-8be3-972e0cb82a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzA3MzQsIm5iZiI6MTcxNTY3MDQzNCwicGF0aCI6Ii8zMzYwMTAzMC8zMzAwNTQyNTctM2MxNGM2OWEtZTkxNy00NGIxLThiZTMtOTcyZTBjYjgyYTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA3MDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3M2ZiM2Y3OTUxYjdmODFkNmQwZTE2YWIzZjA4YjEwNmRiZTk4NGY1YTliMmU4YmE1ZDE2MDU2YWM3NTc1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bbvbb9Z-NA9pHQiHSlpfM0HKrvf39mww42dmB41JBzE)
