### ISSUE TITLE
table 自定义渲染时的字段名称是不是取错了。

### ISSUE THREAD

**Issue by DvShu** [layui/layui#1895]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.9

### 问题描述

table 自定义列渲染时的字段名城是不是应该是 `template` 而不是 `templet`

### 业务代码

```auto
{
  title: "品种",
  templet: function (d) {
    return `${d.name}[${d.symbol}]`;
  },
}
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
历史原因，两者意思基本相同，只是用 `template` 更标准，由于一开始用的是 `templet`，为了保持兼容，就一直没改了。
