### ISSUE TITLE
layui 用vue动态checkbox 显示数据异常,求前端大佬帮忙看哈

### ISSUE THREAD

**Issue by 1124541815** [layui/layui#1902]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

![2AF08771-DD0F-4830-AB42-02254B31BBBA](https://github.com/layui/layui/assets/38807450/7a33ce26-08c3-4c92-b364-1f48af000620)

### 业务代码

```auto
<div style="margin-top:8px;float:left" v-for="v in SelectSiteIds">
                                <input type="checkbox" lay-skin="primary" lay-verify="RadioCheckBox" v-model="CheckSelectSiteIds" lay-filter="SelectSiteIds" name="SelectSiteIds" :value="v.value" :title="v.name" :lay-text="v.name">
                            </div>





//绑定经营站点下拉事件
                    form.on('select(SiteIds)', function (data) {
                        that.SiteIds = data.value
                        if (data.value != "") {
                            var SelectSiteIdsArr = data.value.split(',')
                            that.SelectSiteIds = [];
                            that.CheckSelectSiteIds = [];
                            debugger
                            that.SelectSiteIds = that.SiteIdMapNameList.filter(o => SelectSiteIdsArr.includes(o.value))

                            that.CheckSelectSiteIds = that.SelectSiteIds.map(o => o.value)

                            //更新站点与发货仓关系
                            that.UpdateSiteWarehouseList();
                            form.render();
                        }
                    });
vue 修改了这个值SelectSiteIds    form.render();渲染失败，但是数据值对的。显示bug
```

### 截图补充

无

### 浏览器

谷歌浏览器

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by 1124541815** [comment]
求大佬解决，急死我了。select 下拉框就没这个问题。

**Comment by Sight-wcg** [comment]
不建议和 vue 同时使用，除非你非常了解 vue 的渲染原理。

1. 尝试将 form.render 放在在 nextTick 中
2. 尝试 watch SelectSiteIds，变化时执行 form.render，同样放在 nextTick 中

**Comment by 1124541815** [comment]
> 不建议和 vue 同时使用，除非你非常了解 vue 的渲染原理。
> 
> 1. 尝试将 form.render 放在 nextTick 中
> 2. 尝试观看 SelectSiteIds，变化时执行 form.render，同样放在 nextTick 中

我试下哈

**Comment by 1124541815** [comment]
> 不建议和 vue 同时使用，除非你非常了解 vue 的渲染原理。这会扰乱虚拟 DOM 和真实 DOM 之间的映射，会有各种奇怪的“问题”。
> 
> 1. 尝试将 form.render 放在 nextTick 中
> 2. 尝试观看 CheckSelectSiteIds，变化时执行 form.render，同样放在 nextTick 中

解决了还是不知道为啥要这样写that.$nextTick(function () {
                                that.SelectSiteIds = datas;
                            });要这样写。不能直接that.SelectSiteIds =数组对象。感谢大佬，神奇这玩意
