### ISSUE TITLE
table中使用templet格式化时间戳得到的日期时间不匹配

### ISSUE THREAD

**Issue by devyangbw** [layui/layui#1905]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

V2.9.7

### 问题描述

table组件中使用templet格式化时间戳字段，得到的日期时间与时间戳不匹配，相差8小时，详细见截图。

### 业务代码

```auto
templet: function(d) {
	if (d.alarmDate == null) {
		return "-";
	}
	
	console.log("转换前：", d.alarmDate)
	console.log("转换后：", util.toDateString(d.alarmDate))
	
	return util.toDateString(d.alarmDate);
}
```

### 截图补充

![image](https://github.com/layui/layui/assets/45190435/86ab9065-5345-4c08-8791-e64a46f0afc3)

### 浏览器

版本 124.0.6367.201（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
时区问题，和 layui 无关
