### ISSUE TITLE
日期选择范围

### ISSUE THREAD

**Issue by abc903349085** [layui/layui#1906]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.8

### 问题描述

年月范围在一年内，一个弹窗

### 业务代码

```auto
请问下，这个日期范围 可不可以在一个框中展示
```

### 截图补充

<img width="321" alt="e42d839f6b76c521d7f8c6853bb51090" src="https://github.com/layui/layui/assets/22519646/2db029c5-2d16-4b84-be2c-757c96e238be">
<img width="206" alt="0238f1716dd7da8af0c4d0941b9a3dc8" src="https://github.com/layui/layui/assets/22519646/975427fd-5f5f-4a69-98b1-b990644df751">

### 浏览器

谷歌 eage

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
这些不是吗
![image](https://github.com/layui/layui/assets/10653427/b9848ed2-134d-4d07-a12d-8251d295e467)
