### ISSUE TITLE
关于下拉菜单绑定了input输入框，关闭dropDown后，点击input还是会显示dropdown，如何取消绑定

### ISSUE THREAD

**Issue by 1231211** [layui/layui#1907]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

 v2.9.7 

### 问题描述

关于下拉菜单绑定了input输入框，关闭dropDown后，点击input还是会显示dropdown，如何取消绑定

### 业务代码

```auto
与Layui提供的一致
```

### 截图补充

![image](https://github.com/layui/layui/assets/33928295/e2abf883-028f-4b86-b817-edf7a38be102)

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
$('input-selector').off('click')
