### ISSUE TITLE
LayuiAdmin单页 事件绑定Bug

### ISSUE THREAD

**Issue by youfeed** [layui/layui#1915]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.8.0

### 问题描述

最新版 layuiAdmin SPA 
在 view/page-a 书写的 lay-active="create" 
到 view/page-b 页面 同样的 `lay-active="create"` 它触发的是 `page-a` 的 util.on 监听

### 业务代码

```auto
#### views/page_a.html

<button class="layui-btn layui-btn-normal layui-btn-sm" lay-active="create">创建软件(页面A)</button>
<script>
util.on('lay-active',{
   create:()=>{
     alert('page-a')
   }
})
</script>
```
如果跳转到B页面
```
<button class="layui-btn layui-btn-normal layui-btn-sm" lay-active="create">创建软件(页面B)</button>
```
没有书写js代码 但是你点击按钮 会弹A页面的事件 导致逻辑混乱
```


### 截图补充

_No response_

### 浏览器

谷歌

### 演示地址

_No response_

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。 <!-- layui-issue-template 请务必严格遵循模板规范 -->

**Comment by Sight-wcg** [comment]
这个问题无解，只能靠命名约束来规避，module-action-element  >  userAddButton

layui admin 相关问题建议发布在官网相关的区域。
