### ISSUE TITLE
tree树结构checkbox

### ISSUE THREAD

**Issue by TheNowWJJ** [layui/layui#192]
有俩问题:
1. 官方2.x文档没有tree树结构的文档
2. tree树结构加上{check:"checkbox"}之后只有显示效果,无法选中.

**Comment by di3663** [comment]
就是没有的，模块都没写完的。简单选中自己隐藏下图标、实现逻辑可以凑合用
![default](https://user-images.githubusercontent.com/36250009/38120329-a33f1dd8-33fa-11e8-9918-e8357a531a54.PNG)


功能全ztree可以的

**Comment by TheNowWJJ** [comment]
好的,谢谢. @di3663
