### ISSUE TITLE
layer.msg的加载图标允许自定义

### ISSUE THREAD

**Issue by yhl452493373** [layui/layui#1920]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.10

### 问题描述

2.9.10中，table的loading已经可以自定义了，但是layer.msg的还不行。如下面的代码，我看源码里面是固定了图标的，这个能否和table一样，允许自定义呢？
```javascript
layer.msg('一段提示信息',{
    icon:16
});
```

### 业务代码

```auto
layer.msg('一段提示信息',{
    icon:16
});
```

### 浏览器

124.0.6367.119

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by pkkgu** [comment]
大佬这功能我也需要

**Comment by sentsim** [comment]
```
before: function() { // 数据渲染前
  this.loadIndex = layer.msg('一段提示信息',{
    icon:16
});
},
complete: { // 数据请求完
  layer.close(this.loadIndex)
}
```

**Comment by bxjt123** [comment]
> #1884 是我理解有误吗，标题是 table，描述是 layer, 是希望能够重写 table 内置的 loading 方法？还是自定义 table 加载图标?

我觉得他的意思应该是：他项目中加载用`layer.load(1)`和表格`loading`默认图标不一样，想自定义表格`loading`图标保持统一风格，然后现在表格`loading`图标能自定义了，就想让`layer.load`也实现自定义的`loading`图标。
（我猜，大概是因为`layer.load`加载背景是透明的只会显示一个图标，而`layer.msg`改图标也会有背景。）

**Comment by pkkgu** [comment]
我想要的是icon支持string
```
layer.msg('一段提示信息',{
  icon: 'layui-icon-chrome'
});
```

**Comment by pkkgu** [comment]
我想要的是icon支持string
```
layer.msg('一段提示信息',{
  icon: 'layui-icon-chrome'
});
```

**Comment by sentsim** [comment]
我不建议给 layer.msg 或 layer.loading 实现类似的需求，过于精细化的支持容易过度封装，因为本身可以通过 layer.open 的 `content` 来实现内容的自定义。

要保持 layer 和 table 加载效果的统一，参考 #1884 的回答
