### ISSUE TITLE
关于upload组件，error回调函数为什不能像done 一样能获取到用户自定义的返回值呢，不太方便

### ISSUE THREAD

**Issue by CrazyWalks** [layui/layui#1925]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

关于upload组件，error回调函数为什不能像done 一样能获取到用户自定义的返回值呢，不太方便，，如果所有属性都能获取到res那多好啊

### 业务代码

```auto
error: function(index, upload){
                layer.close(upload_file_Index);
                // layer.msg('错误'); 
                // console.log(index); // 当前文件的索引
                // upload(); 重新上传的方法
            }

只有index和upload 没有用户res自定义的返回值获取
```

### 浏览器

版本 123.0.6312.86（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
也许会有帮助 https://api.jquery.com/ajaxError/#on-
