### ISSUE TITLE
升级2.9.10后，Tab 里面的echarts图表无法显示

### ISSUE THREAD

**Issue by chaoyinsu2011** [layui/layui#1929]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.10

### 问题描述

相同代码在2.9.9正常，升级到2.9.10后，Tab 里面的echarts图表无法显示，一片空白。

### 业务代码

```auto
let option = echartsInst.getOption();
 option.dataset = data;
 option.title = {
     text: lastSelectTitle,
     left: 'center',
     show: true,
 };
 echartsInst.setOption(option);
```

### 浏览器

Google Chrome 125.0.6422.61（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by chaoyinsu2011** [comment]
![微信截图_20240522114659](https://github.com/layui/layui/assets/36907073/eb3ffb85-1946-4826-bf9b-7e248996adfc)
与echarts同一卡片中存在laydate组件。

**Comment by LSL1618** [comment]
检查一下echarts图表容器的宽度或高度是否等于0。

**Comment by chaoyinsu2011** [comment]
> 检查一下echarts图表容器的宽度或高度是否等于0。

3VA那个是echarts 的标题，高度和宽度都没有问题。相同环境，其他不动，只要将layui库降回到2.9.9，则正常。
