### ISSUE TITLE
表格排序：0小于负数！正常情况应该是0要大于负数的

### ISSUE THREAD

**Issue by youhongfeng** [layui/layui#193]
layui表格排序：0小于负数
表现在：
顺序排序时:  0位于负数上方，负数位于正数上方
逆序排序时:0位于负数下发，负数位于正数下发

**Comment by lenghun** [comment]
同样遇到这问题,我的排序是数据库处理的,默认的自动排序autoSort是开启的,关掉就不影响使用,但是这个bug无疑是存在的

**Comment by sentsim** [comment]
后面已经对排序进行了多次优化
