### ISSUE TITLE
请问<input type="checkbox">如何实现禁止修改，又不会像添加disabled属性那样变灰？

### ISSUE THREAD

**Issue by SouSuoKe** [layui/layui#1930]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.9

### 问题描述

![Snipaste_2024-05-22_15-35-41-574](https://github.com/layui/layui/assets/27963195/fffcc123-d85b-4f2a-9248-ff52cde2d210)

如图，展示页面上使用<input type="checkbox">显示了相关设置，但是不想让用户在展示页面修改这个设置，使用disabled又会使checkbox变灰没有那么好看，请问如何设置能使checkbox样式不变又不能修改？

### 业务代码

```auto
<input type="checkbox">
```

### 浏览器

Chrome 124.0.6367.92

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Cuixq123** [comment]
进事件方法，直接返回啊

**Comment by SouSuoKe** [comment]
> 进事件方法，直接返回啊

```
  form.on('checkbox(demo-checkbox-filter)', function(data){

    return false;//是这个吗？

    var elem = data.elem; // 获得 checkbox 原始 DOM 对象
    var checked = elem.checked; // 获得 checkbox 选中状态
    var value = elem.value; // 获得 checkbox 值
    var othis = data.othis; // 获得 checkbox 元素被替换后的 jQuery 对象
    
    layer.msg('checked 状态: '+ elem.checked);
  });
```
请问是直接 `return false;` 吗？加上之后，后面的代码不执行了，但是页面上的按钮还是可以点击切换状态
