### ISSUE TITLE
layui.util事件委托“event”已弃用

### ISSUE THREAD

**Issue by Kiraalla** [layui/layui#1934]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.10

### 问题描述

当我使用事件委托的时候，$(event.target)能够正常工作，但event提示已被弃用，我尝试了多种写法都无法平替event。或许有更好的实现方式？
同一个地方，还有一个问题就是，trigger: 'mouseover',的时候，mouseover 事件会频繁触发，非常诡异，而且无法通过mouseleave来操作移出事件，需要手动重新写一个mouseleave，这一块是否是bug？有更好的方式吗？

### 业务代码

```auto
layui.use(['util'], function () {
  var util = layui.util;
  var $ = layui.jquery;
  util.on({
    news1: function () {
      const newsItem = $(event.target).hasClass('news-item') ? $(event.target) : $(event.target).parents('.news-item');
      newsItem.addClass('active').siblings().removeClass('active');
    },
}, {
    trigger: 'mouseover',
  })
$('.content-service').mouseleave(function () {
    $('.service-content').removeClass('content-offset')
    $('.service-item').removeClass('active')
  });
});
```

### 浏览器

chrome@latest

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
layui.util.on 不是 $.on 的替代品，有其适用场景，请根据需求选择合适的使用方式。

参考 https://gitee.com/layui/layui/issues/I8H0XO
