### ISSUE TITLE
调用treeTable.reload方法之后丢失树表数据

### ISSUE THREAD

**Issue by hawkxu** [layui/layui#1936]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.4

### 问题描述

仅使用id调用treeTable.reload方法之后，原本的数据丢失，显示无数据

备注1：数据通过treeTable.reloadData('tree-id', {data: data}填充，非url模式
备注2：调用table.reload('tree-id')可以正常显示

### 业务代码

```auto
<html>
<head>
	<script src="https://unpkg.com/layui@2.9.10/dist/layui.js"></script>
	<link href="https://unpkg.com/layui@2.9.10/dist/css/layui.css" rel="stylesheet">
</head>
<body>
	<div>
		<button onclick="javascript:layui.treeTable.reload('tree-id')">使用treeTable.reload</button>
		<button onclick="javascript:layui.table.reload('tree-id')">使用table.reload</button>
	</div>
	<div id='tree-id'></div>
	<script>
		layui.use(["treeTable"], function(treeTable){
			let inst = treeTable.render({
				elem: '#tree-id',
				cols: [ [
					{field: 'id', title: 'ID', width: 80},
					{field: 'name', title: 'Name'}
				]]
			});
			treeTable.reloadData("tree-id", {data: [{id: 1, name: '张三'}, {id: 2, name: '李四'}]});
		});
	</script>
</body>
</html>
```

### 浏览器

360安全浏览器15

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
由于 treeTable 选项的特殊性，`treeTable.reloadData` 默认使用的是浅重载，若需携带以前的属性，可尝试设置为深重载。

```
treeTable.reloadData("tree-id",  { }, true);
```

**Comment by Sight-wcg** [comment]
@sentsim 深重载可以解决问题。之前没有确定原因，所以临时去除了 BUG 标签，调试后确认是 BUG，treeTable data 模式非深度重载时，如果 reload 参数中没有 data 选项，会用一个空数组重新初始化缓存。

@hawkxu 感谢您的反馈，确认是 BUG

**Comment by hawkxu** [comment]
> 这可能是由于 treeTable 选项结构的特殊性所致。 `treeTable.reloadData` 默认使用的是浅重载，若需携带旧的属性，可尝试设置为深重载。
> 
> ```
> treeTable.reloadData("tree-id",  {data: []}, true);
> ```

仅探讨：
我遇到这个问题的背景是，我把树表放在选项卡组件中，并通过height回调使树表的高度占满选项卡，当点击选项卡标签切换时，树表的高度会收缩不再占满选项卡（树表数据较少时）。此时使用reloadData不能重设高度，我只能调用reload方法。
