### ISSUE TITLE
csp 问题

### ISSUE THREAD

**Issue by hrmj008** [layui/layui#1937]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.10

### 问题描述

启用了 CSP 
```
Content-Security-Policy: default-src 'self';
```
后
在调用 
```
layui.use(function () {    
        var layer = layui.layer;
        var layerIndex = layer.load(2)
    })
```
和jquery 4.0 后 
由于 layui 生成了inline css
![Screenshot 2024-05-22 at 17 03 20](https://github.com/layui/layui/assets/152969695/0a5771eb-a682-41d7-9299-8964987b5e1c)
浏览器会报错
![Screenshot 2024-05-22 at 17 15 36](https://github.com/layui/layui/assets/152969695/e018f16c-234f-4ede-b3cb-17a365325357)

急需layui 支持csp

### 业务代码

```auto
layui.use(function () {    
        var layer = layui.layer;
        var layerIndex = layer.load(2)
    })
```
```


### 截图补充

![Screenshot 2024-05-22 at 17 15 36](https://github.com/layui/layui/assets/152969695/ec38d008-05d8-4215-9dcd-70132bcc2970)
![Screenshot 2024-05-22 at 17 03 20](https://github.com/layui/layui/assets/152969695/d22df802-9910-4dc6-bcbb-03533af37cda)


### 浏览器

Chrome

### 演示地址

_No response_

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。 <!-- layui-issue-template 请务必严格遵循模板规范 -->

**Comment by sentsim** [comment]
参考：#1176

**Comment by hrmj008** [comment]
@sentsim 这个不是 eval 的问题，这个是inline css的问题

**Comment by sentsim** [comment]
很难避免不使用内联样式的，建议把 `default-src` 改成 `script-src` 即不加载外部脚本文件即可。也可以追加 `frame-src`，其他限制我认为没有太大必要。
