### ISSUE TITLE
select 可以有选择事件,可以加个回调的回车事件吗?

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#1943]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.9

### 问题描述

select 可以有选择事件,可以加个回调的回车事件吗?

### 业务代码

```auto
select 可以有选择事件,可以加个回调的回车事件吗?
```

### 浏览器

ch

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
回车事件自行绑定一下 

```html
<select id="select-id">
  <!-- … -->
</select>

<script>
layui.use(function() {
  var $ = layui.$;
  $('body').on('keydown', '#select-id+', function(e) {
    var value = e.target.value;
    if (e.keyCode === 13) {
      alert(value);
    }
  });
});
</script>
```

最好还是通过 form 的 `select` 事件统一处理，按回车键后最终也会触发 `select` 事件

**Comment by aimu2000** [comment]
<select id="select-id" lay-search="" lay-creatable="">
  
</select>

<script>
layui.use(function() {
  var $ = layui.$;
  $('body').on('keydown', '#select-id', function(e) {
    var value = e.target.value;
    if (e.keyCode === 13) {
      alert(value);
    }
  });
});
</script

刚试了一下,没有弹出

**Comment by aimu2000** [comment]
<select id="select-id" lay-search="" lay-creatable="">
  
</select>
 <script>
layui.use(function() {
  var $ = layui.$;
  $('body').on('keydown', '#select-id+', function(e) {
    var value = e.target.value;
    if (e.keyCode === 13) {
      alert(value);
    }
  });
});
</script>
 刚试了一下，没有弹出

**Comment by aimu2000** [comment]
<select id="select-id"  lay-search="" lay-creatable="">
  
</select>

<script>
layui.use(function() {
  var $ = layui.$;
  $('body').on('keydown', '#select-id', function(e) {
    var value = e.target.value;
    if (e.keyCode === 13) {
      alert(value);
    }
  });
});
</script>
刚试了下,按下回车在V2.9.9没用.没弹出信息

**Comment by aimu2000** [comment]
> 回车事件自行绑定一下
> 
> ```
> <select id="select-id">
>   
> </select>
> 
> <script>
> layui.use(function() {
>   var $ = layui.$;
>   $('body').on('keydown', '#select-id+', function(e) {
>     var value = e.target.value;
>     if (e.keyCode === 13) {
>       alert(value);
>     }
>   });
> });
> </script>
> ```
> 
> 最好还是通过 form 的 `select` 事件统一处理，按回车键后最终也会触发 `select` 事件

刚试了下,没弹出

**Comment by sentsim** [comment]
是 `#select-id+`，不是 `#select-id`，注意 `+`

**Comment by aimu2000** [comment]
> 回车事件自行绑定一下
> 
> ```
> <select id="select-id">
>   
> </select>
> 
> <script>
> layui.use(function() {
>   var $ = layui.$;
>   $('body').on('keydown', '#select-id+', function(e) {
>     var value = e.target.value;
>     if (e.keyCode === 13) {
>       alert(value);
>     }
>   });
> });
> </script>
> ```
> 
> 最好还是通过 form 的 `select` 事件统一处理，按回车键后最终也会触发 `select` 事件

select里面没有值,可以获取得到,但是里面本身有值,  lay-search="" lay-creatable="" 创建出来的,获取不到!

**Comment by Sight-wcg** [comment]
> > 回车事件自行绑定一下
> > ```
> > <select id="select-id">
> >   
> > </select>
> > 
> > <script>
> > layui.use(function() {
> >   var $ = layui.$;
> >   $('body').on('keydown', '#select-id+', function(e) {
> >     var value = e.target.value;
> >     if (e.keyCode === 13) {
> >       alert(value);
> >     }
> >   });
> > });
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最好还是通过 form 的 `select` 事件统一处理，按回车键后最终也会触发 `select` 事件
> 
> select里面没有值,可以获取得到,但是里面本身有值, lay-search="" lay-creatable="" 创建出来的,获取不到!

https://github.com/layui/layui/issues/1874#issuecomment-2100175958 **中已经告诉你解决方案了，有尝试过吗？**

```
      $('body').on('keydown', '#select-id+', function (e) {
        var value = e.target.value;
        var el = $(this);

        setTimeout(() => {
          el.find('.layui-select-create-option').addClass('layui-this').siblings().removeClass('layui-this');
        }, 70);
        
        
        if (e.keyCode === 13) {
          alert(value);
        }
      });
```
