### ISSUE TITLE
Layui TreeTable 组件问题

### ISSUE THREAD

**Issue by kesry** [layui/layui#1944]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

TreeTable重载报错。
提示expandAllDefault属性从undefined的类型中获取失败，
其实就是getOptions()方法没有添加treeTable的默认config，
直接返回了不完整的config对象，导致
renderTreeTable方法执行失败

### 业务代码

```auto
let oIndex = layer.load(0);
                                                $.post(`${apiBaseUrl}/role/menu/add`, {
                                                    ...field
                                                }, res => {
                                                    layer.close(oIndex);
                                                    layer.msg(res.msg);
                                                    layer.close(cur_index);
                                                                                                    
                                                    treeTable.reload(link.id, link);
                                                })
                                                return false; // 阻止默认 form 跳转
                                            });
```

### 截图补充

![image](https://github.com/layui/layui/assets/71216328/e8510bdd-e155-40a4-829e-64014a2aecda)

### 浏览器

Chrome  正式版 123.0.6312.122

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
建议：
1. 升级 Layui 版本到最新的 `2.9.10`
2. 改成深度重载 `treeTable.reload(link.id, link, true);`

**Comment by kesry** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  
  <link href="https://unpkg.com/layui@2.9.8/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<table id="ID-treeTable-demo"></table>
<script type="text/html" id="TPL-treeTable-demo">
  <div class="layui-btn-container">
    <button class="layui-btn layui-btn-sm" lay-event="getChecked">获取选中数据</button>
  </div>
</script>
<script type="text/html" id="TPL-treeTable-demo-tools">
  <div class="layui-btn-container">
    <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">查看</a>
    <a class="layui-btn layui-btn-warm layui-btn-xs" lay-event="addChild">新增</a>
    <a class="layui-btn layui-btn-xs" lay-event="more">更多 <i class="layui-icon layui-icon-down"></i></a>
  </div>
</script>
  

<script src="https://unpkg.com/layui@2.9.8/dist/layui.js"></script>
<script>
    const newData = {
            "children": [],
            "filter": null,
            "isParent": false,
            "menu_id": 1,
            "menu_name": "测试2",
            "parent_id": 0,
            "role": 0,
            "status": 1,
            "tab_content": "123"
        };
    const link = { //菜单列表开始
        id: '#ID-treeTable-demo',
        isTreeTable: true,
        elem: '#ID-treeTable-demo',
        url: `./data.json`, // 此处为静态模拟数据，实际使用时需换成真实接口
        tree: {
            customName: {
                id: "menu_id",
                pid: "parent_id",
                name: "menu_name"
            }
            
        },
        minHeight: '700px',
        defaultToolbar: ["filter"],
        cols: [[
            {field: 'menu_id', title: '菜单ID', width: 100, sort: true},
            {field: 'menu_name', title: '菜单名', width: 180
            },
            {field: 'filter', title: '表单filter', width: 120},
            {field: 'status', title: '状态', width: 90},
            {field: 'role', title: '访问权限', width: 100}
        ]],
        // page: true
    };
layui.use(function(){
  var treeTable = layui.treeTable;
  var layer = layui.layer;
  // 渲染
  var inst = treeTable.render(link);

  // 表头工具栏工具事件
  treeTable.on("toolbar(ID-treeTable-demo)", function (obj) {
    var config = obj.config;
    var tableId = config.id;
    var status = treeTable.checkStatus(tableId);
    // 获取选中行
    if (obj.event === "getChecked") {
      if(!status.data.length) return layer.msg('无选中数据');
      console.log(status);
      layer.alert("当前数据选中已经输出到控制台，<br>您可按 F12 从控制台中查看结果。");
    }
  });
  // 单元格工具事件
  treeTable.on('tool('+ inst.config.id +')', function (obj) {
    var layEvent = obj.event; // 获得 lay-event 对应的值
    var trElem = obj.tr;
    var trData = obj.data;
    var tableId = obj.config.id;
    if (layEvent === "detail") {
      layer.msg("查看操作：" + trData.name);
    } else if (layEvent === "addChild") {
      
        //往后台添加数据之后
        //
        这一步报错
        treeTable.reload(link.id, link);


    } else if (layEvent === "more") {
      // 下拉菜单
    }
  });
});
</script>
 
</body>
</html>

**Comment by kesry** [comment]
大概就是这样，就是添加菜单之后，reload报错

**Comment by kesry** [comment]
https://stackblitz.com/edit/stackblitz-starters-c6zvkj?file=index.js
后台大概是这样

**Comment by Sight-wcg** [comment]
https://antfu.me/posts/why-reproductions-are-required-zh
