### ISSUE TITLE
封装 IndexedDb

### ISSUE THREAD

**Issue by lyons-bin** [layui/layui#1948]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.10

### 问题描述

layui.data 是否可以添加一个封装操作浏览器 IndexedDb 存储的方法

### 业务代码

```auto
layui.data 是否可以添加一个封装操作浏览器 IndexedDb 存储的方法
```

### 浏览器

Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by lyons-bin** [comment]
layui.data 是否可以添加一个封装操作浏览器 IndexedDb 存储的方法

**Comment by Sight-wcg** [comment]
建议自行封装，或者使用相关的库，可以看看 https://github.com/unjs/unstorage
