### ISSUE TITLE
table.renderData 刷新缓存，分页失效

### ISSUE THREAD

**Issue by version16589** [layui/layui#1951]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.10

### 问题描述

分页设置了5，但是table.renderData('ID-table-op'); 之后分页失效，全部在整页显示

### 业务代码

```auto
table.render({
elem: '#ID-table-op',
cols: [[ //标题栏
{field: 'currency', title: '简写', align:'center',width: 70,},
{field: 'name', title: '币种', align:'center',width: 110,},
{field: 'rate', title: '兑换人民币', align:'left',minWidth: 110,templet: function(d){
return '￥'+d.rate;
}},
]],
data: [],
page:{layout: ['prev','page','next']},
limit: 5,
});a




table.cache['ID-table-op']=inData['oss_cny_op']['rates'];
table.renderData('ID-table-op');
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
你采用的是data本地数据模式，并不是url异步数据模式。

**Comment by jichuanan** [comment]
我记得laiui table是没有像bootstrap table那样的客户端分页的功能的。

**Comment by jichuanan** [comment]
做了个最小化的重现的例子 :)
https://stackblitz.com/edit/2hpqvf?file=index.html

建议用reloadData，不要用table.cache[tableId]=data这种直接更新table内部数据的方法;

```
      table.reloadData(tableId, {
        data: data
      });

```
