### ISSUE TITLE
select option 值存在双引号问题，为啥双引号后面内容全部不见了？比如 测试"英文"123 ，只剩下测试

### ISSUE THREAD

**Issue by chenzy571556261** [layui/layui#1952]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.7.6、v2.9

### 问题描述

 select option 值存在双引号问题，为啥双引号后面内容全部不见了？比如 测试"英文"123 ，只剩下测试

修复 form select 中 option 内容出现双引号时的异常显示问题 # I4U9SM

内容显示是没问题，但是值有问题

### 业务代码

```auto
<select id="customer_name" name="customer_name" lay-filter="customer_name" lay-search >
                    <option value="">请选择</option>
                    <?php foreach ($customerSelect as $cusId => $cusName) : ?>
                     
                        <option value="<?= $cusName ?>" ><?= $cusName ?></option>
                    <?php endforeach; ?>
                </select>
```

### 截图补充

![image](https://github.com/layui/layui/assets/170605127/47000281-9426-426a-9445-4e072d70fdda)
![image](https://github.com/layui/layui/assets/170605127/47000281-9426-426a-9445-4e072d70fdda)
![image](https://github.com/layui/layui/assets/170605127/07a006e9-9dad-4bb9-89e7-056ab6159274)
![image](https://github.com/layui/layui/assets/170605127/07a006e9-9dad-4bb9-89e7-056ab6159274)

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
对双引号进行转义 `<option value="\"AAA\"">`

**Comment by chenzy571556261** [comment]
> 对双引号进行转义 `<option value="\"AAA\"">`

试了不行
<option value="测试\"英文\"123" >测试"英文"123</option>
![image](https://github.com/layui/layui/assets/170605127/7801a8a9-5135-481b-bf28-f79729b84725)

**Comment by chenzy571556261** [comment]
> > 对双引号进行转义 `<option value="\"AAA\"">`
> 
> 试了不行
> 
> `<option value="测试\"英文\"123" >测试"英文"123</option>`  <dd` lay-value="测试\" class="">测试"英文"123</dd>`

**Comment by chenzy571556261** [comment]
默认是这样的

`<select>
<option value="测试"英文"123" >测试"英文"123</option>
</select>`


`<select>
<option value="测试" 英文"123">测试"英文"123</option>
</select>`
