### ISSUE TITLE
number类型input的小bug

### ISSUE THREAD

**Issue by FFCZ** [layui/layui#1957]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.10

### 问题描述

number型的input组件，使用lay-affix，在使用readonly限制的情况下，仍可以通过后辍的上下按钮，改变数字。
当前官方演示站点可重现本问题，原生态的number不会出上下按钮。

### 业务代码

```auto
<input type="number" lay-affix="number" readonly placeholder="不允许输入状态" class="layui-input">
```

### 浏览器

Edge 125

### 演示地址

https://layui.dev/docs/2/form/input.html#affix-number

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
`readonly`是只读，不允许键盘输入
`disabled`才是禁用
