### ISSUE TITLE
弹出层(layer.open)在火狐浏览器下打开的窗口不能自适应

### ISSUE THREAD

**Issue by lukeit** [layui/layui#1963]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.10

### 问题描述

在官网的几个在线测试页面和本地测试工程里，使用火狐浏览器32位最新版（126.0 (32 位)）打开弹出层，内容为一张图片，首次打开弹窗高度不能自适应，在火狐浏览器下是否存在异步加载问题？
测试地址：https://layui.dev/2.7/layer/，https://layui.dev/docs/2/layer/；
open的area属性设置为：area: ['auto', 'auto']；
内容随便打开一张图片：content: '<img src="https://picx.zhimg.com/v2-d63aed6b453ca3393a32bb16e8a586e7_r.webp?source=172ae18b&consumer=ZHI_MENG"/>'
异常问题：首次打开窗口高度不能自适应，重新打开可恢复正常

### 业务代码

```auto
layer.open({
  type: 1 //Page 层类型
  ,area: ['auto', 'auto']
  ,title: 'Hello layer'
  ,shade: 0.6 //遮罩透明度
  ,maxmin: true //允许全屏最小化
  ,anim: 0 //0-6的动画形式，-1不开启
  ,content: '<img src="https://picx.zhimg.com/v2-d63aed6b453ca3393a32bb16e8a586e7_r.webp?source=172ae18b&consumer=ZHI_MENG"/>'
});
```

### 截图补充

![layuie1](https://github.com/layui/layui/assets/10087245/b445ff7e-f3cc-4576-a811-9da80b0f7c72)
![layuie2](https://github.com/layui/layui/assets/10087245/d634268b-2da2-44dd-8c6b-10a4cf8eab57)

### 浏览器

火狐浏览器32位最新版（126.0 (32 位)）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
图片存在一个加载过程，普通弹层无法识别图片加载完毕的状态。这种情况建议采用以下任一方案：
1. 给弹层定义一个固定的高度
2. 用 `layui.img(url, callback, error)` 预加载图片，在回调中执行 layer 弹层
3. 用 `<link rel="preload" href="" as="image">` 预加载图片
4. 用 `layer.photos()` 方法来弹出图片
