### ISSUE TITLE
table单元格展开，宽度判断存在异常

### ISSUE THREAD

**Issue by fanyuning** [layui/layui#1967]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

<= v2.9.7

### 问题描述

使用layui的table组件，在引入外部jQuery 3.x版本后，单元格展开判断，特定情况(**宽度不为整数**)下存在异常。
一般场景：小屏幕高分辨下，系统级缩放+浏览器缩放后，导致宽度有时不为整数，从而导致展开逻辑判断异常。

原因是table内的showGridExpandIcon函数，在进行elemCell.prop('scrollWidth') > elemCell.outerWidth()判断时，elemCell.outerWidth()方法获取到的宽度问题，jQuery 1.x版本底层采用[HTMLElement.offsetWidth](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/offsetWidth)获取，这个属性将会 round(四舍五入) 为一个整数。jQuery 3.x采用[Element.getBoundingClientRect()](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/getBoundingClientRect)获取，其width可获取到小数，导致导致判断异常。

### 业务代码

```auto
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>table展开判断异常</title>
    <link href="https://cdn.staticfile.net/layui/2.9.7/css/layui.css" rel="stylesheet">
  </head>
  <body>
    <blockquote class="layui-elem-quote layui-text" id="version">
      当前版本: Layui-v{{= layui.v }}
    </blockquote>
     
    <table class="layui-hide" id="ID-test-table"></table>
    <script type="application/javascript" src="https://cdn.staticfile.net/jquery/3.0.0/jquery.js"></script>
    <script src="https://cdn.staticfile.net/layui/2.9.7/layui.js"></script>
    <script>
    layui.use(function() {
      layui.table.render({
        elem: '#ID-test-table',
        data: [{ "id": 10000, "score": 57},{ "id": 10001, "score": 70.5},{ "id": 10002, "score": 31}], 
        page: false,
        toolbar: '<div><button type="button" lay-event="renderDataTest">重新渲染数据</button></div>', 
        defaultToolbar: false,
        totalRow: true, // 开启合计行
        cols: [[ // 表头
          {type: 'checkbox', fixed: 'left', width:59.88},
          {field: 'id', title: 'ID', width:80, sort: true, totalRow: '合计 : '},
          {field: 'score', title: '评分', width: 80, sort: true, totalRow: true, edit:true}
        ]]
      });

      layui.table.on('toolbar(ID-test-table)', function(obj) {
        switch(obj.event){
          case 'renderDataTest':
            layui.table.renderData('ID-test-table');
          break;
        };
      });
      
      // 显示 Layui 版本
      var versionTPL = lay('#version')[0].innerHTML;
      lay('#version').html(layui.laytpl(versionTPL).render({}))
    });
    </script>
  </body>
</html>
```

### 截图补充

jQuery 3.x代码↓
![jQuery 3 x新增代码](https://github.com/layui/layui/assets/27409048/eb432500-d5e3-4d23-ae5c-b2897df93435)

jQuery 1.x代码↓，layui内部引用的也是这个
![jQuery 1 x代码](https://github.com/layui/layui/assets/27409048/ff02e158-9b1c-4927-ab8e-fa13aa248978)

### 浏览器

任意

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
关联 https://github.com/layui/layui/pull/1728

升级到 layui v2.9.10 仍然能够重现该问题吗？

**Comment by fanyuning** [comment]
在2.9.8版本修复了，我们公司正好用的2.9.7版本 ，好尴尬！！！
