### ISSUE TITLE
导航栏 加上 徽章，徽章过长的话，样式好像不太对

### ISSUE THREAD

**Issue by ahking** [layui/layui#1970]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v 2.9.9

### 问题描述

导航栏 加上 徽章，徽章过长的话，样式好像不太对，整个layui-nav-item的宽度不同步变宽

### 业务代码

```auto
<li class="layui-nav-item @ViewData["NavStyle_bjcz"]" id="navi_bjcz">
     <a href="..." onclick="">报警处置<span class="layui-badge" id="bjCount"></span></a>
 </li>
 <li class="layui-nav-item @ViewData["NavStyle_yhgl"]" style="@ViewData["display_yhgl"]">
     <a href="..." onclick="">用户管理</a>
 </li>
```

### 截图补充

![image](https://github.com/layui/layui/assets/5186706/a3eec845-76dc-49ec-9148-84cbbb88254a)

### 浏览器

edge最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
看代码应该是`nav`里徽章等小图标用的绝对定位的原因

**Comment by Sight-wcg** [comment]
![image](https://github.com/layui/layui/assets/26325820/4a4a7415-79b2-45ed-b56e-96c0ec8f47db)

**Comment by ahking** [comment]
@Sight-wcg  看不打明白，是把.layui-bage的position属性改为相对的？

**Comment by ahking** [comment]
![image](https://github.com/layui/layui/assets/5186706/770530a2-7e1a-492c-85c3-ad5e9d20cdb6)
这是我现在的样式

**Comment by bxjt123** [comment]
@ahking 意思是把绝对定位去掉（或者改成“相对”），因为“绝对”是不计入宽度的，上边距也去掉，然后增加垂直居中

**Comment by ahking** [comment]
十分感谢，解决了
