### ISSUE TITLE
建议给form表单模块增加一个重置表单内容API

### ISSUE THREAD

**Issue by 104828720** [layui/layui#1975]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.10

### 问题描述

每次重置表单元素内容时，有2种方法，一种是使用<button type="reset"><button>，而另外一种是使用form.val，能否给form模块新增一个api，直接调用达到清空/重置表单效果

### 业务代码

```auto
由于表单元素比较多，业务比较复杂，有时有些表单元素是第三方提供，虽然form.val能够很灵活，但元素多时，写起来代码很冗余，希望心姐能提供这个api
```

### 浏览器

chrome 125.0.6422.113

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
可以尝试下这个
```
<button type="reset" class="layui-btn">重置</button>
```

**Comment by bxjt123** [comment]
可以尝试下这个
```
<button type="reset" class="layui-btn">重置</button>
```
