### ISSUE TITLE
为什么导出excel还是xls，不支持xlsx？现在xls打开就报错

### ISSUE THREAD

**Issue by jianhao84** [layui/layui#1981]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.10

### 问题描述

为什么导出excel还是xls，不支持xlsx？现在xls打开就报错

### 业务代码

```auto
为什么导出excel还是xls，不支持xlsx？现在xls打开就报错
```

### 截图补充

![image](https://github.com/layui/layui/assets/1411878/64ab1a36-50e2-49a7-862b-6821b27cb24e)

### 浏览器

和浏览器无关

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
直接点是，是可以打开的。确实不支持导出xlsx，导出的文件内容本质上还是csv格式，可以强制打开。

**Comment by jianhao84** [comment]
用户体验不好，每次都要点…而且提示文件损害，用户比较担心，不信任



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LSL1618 ***@***.***&gt;
发送时间: 2024年6月5日 17:31
收件人: layui/layui ***@***.***&gt;
抄送: jianhao84 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [layui/layui] 为什么导出excel还是xls，不支持xlsx？现在xls打开就报错 (Issue #1981)





 
直接点是，是可以打开的。确实不支持导出xlsx，导出的文件内容本质上还是csv格式，可以强制打开。

**Comment by Sight-wcg** [comment]
Duplicate of #1476
