### ISSUE TITLE
upload组件，希望增加一个点击后就触发的事件，在弹窗选择文件之前

### ISSUE THREAD

**Issue by 1051897274** [layui/layui#1985]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.8.17

### 问题描述

我做了一个上传图片的功能，每次选择单个文件，但是我们有限制数量，比如最多上传5张，目前的框架只能在弹窗选择文件后，再用before事件拦截。这样话，当我选择5张后，再次点击上传，依然会让我选择文件，当我选完后，才能触发判断，提示用户最多5张。所以希望能增加一个事件，在点击绑定的元素后，弹出选择框之前就触发！

### 业务代码

```auto
C.render({
    elem: '#uploadRunUserImgNode',
    url: _APP_SERV.openway.root + 'attachfile/uploadFile', // 实际使用时改成您自己的上传接口即可。
    dataType: 'json',
    accept: 'images',
    size: '1024',
    data: {
        path: 'run-user-imgs'
    },
    acceptMime: 'image/*',
    onclick:function(){
        var acount = $("#uploadRunUserImgNode").attr("data-acount");
        if (acount >= 3) {
            bios.msg.tip("在逃人员照片限制3张内!", "error")
            return false;
        }
        //希望增加此事件，点击上传按钮后，我就可以读取自己设定的已上传的集合去判断文件数，
          不用等用户选择完文件后再判断已达最大值
    },
    before: function (obj) {
        var acount = $("#uploadRunUserImgNode").attr("data-acount");
        if (acount >= 3) {
            bios.msg.tip("在逃人员照片限制3张内!", "error")
            return false;
        }
    },
    done: function (res) {
        if (!uploadRunUserImgsList) {
            uploadRunUserImgsList = [];
        }
        if (uploadRunUserImgsList.length < 3) {
            uploadRunUserImgsList.push(res.data);
        }
        $("#uploadRunUserImgNode").attr("data-acount", uploadRunUserImgsList.length);
        renderUserImgsImgs(uploadRunUserImgsList);
    }
});
```

### 浏览器

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
不选完谁知道有几个文件

**Comment by 1051897274** [comment]
> 不选完谁知道有几个文件

麻烦仔细阅读！我认为我已经表达的很清楚了

**Comment by Sight-wcg** [comment]
参考以下解决方案
1. 给上传按钮绑定单击事件
2. 达到指定最大上传文件数量后，给上传按钮添加 disabled 属性以禁用上传
3. 提示达到最大上传数

**Comment by 1051897274** [comment]
> 参考以下解决方案
> 
> 1. 给上传按钮绑定单击事件
> 2. 达到指定最大上传文件数量后，给上传按钮添加 disabled 属性以禁用上传
> 3. 提示达到最大上传数

方案一，我想过还没尝试，因为担心冒泡，等会儿尝试一下，方案二也想过，但是有点强迫症，感觉从组件层面去实现，更优雅

**Comment by Sight-wcg** [comment]
> > 参考以下解决方案
> > 
> > 1. 给上传按钮绑定单击事件
> > 2. 达到指定最大上传文件数量后，给上传按钮添加 disabled 属性以禁用上传
> > 3. 提示达到最大上传数
> 
> 方案一，我想过还没尝试，因为担心冒泡，等会儿尝试一下，方案二也想过，但是有点强迫症，感觉从组件层面去实现，更优雅

除非使用者无法轻易解决此类问题，否则不会添加的。

**Comment by 1051897274** [comment]
> > > 参考以下解决方案
> > > 
> > > 1. 给上传按钮绑定单击事件
> > > 2. 达到指定最大上传文件数量后，给上传按钮添加 disabled 属性以禁用上传
> > > 3. 提示达到最大上传数
> > 
> > 
> > 方案一，我想过还没尝试，因为担心冒泡，等会儿尝试一下，方案二也想过，但是有点强迫症，感觉从组件层面去实现，更优雅
> 
> 除非使用者无法轻易解决此类问题，否则不会添加的。方案一你可以试试在事件捕获阶段进行处理。

好的
