### ISSUE TITLE
tab 组件 lay-id 属性值包含某些特殊字符时，可能会导致 layui-tab-item 所在的标签解析异常

### ISSUE THREAD

**Issue by ygbh** [layui/layui#1989]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.11

### 问题描述

   51行：  contElem.append('<div class="layui-tab-item" ' + (options.id ? 'lay-id=' + options.id : '') + '>'+ (options.content || '') +'</div>');
问题：lay-id=后面缺少双引号，导致我的项目有一些获取不到id，建议修复一下，谢谢

### 业务代码

```auto
修正后的代码如下：
51行 contElem.append('<div class="layui-tab-item" lay-id="' + (options.id ? options.id : '') + '"' + '>' + (options.content || '') + '</div>');
```

### 浏览器

google

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by ygbh** [comment]
这种肉眼可见的错误我也复制不了什么，就是少了双引号，html语法不规范的问题

**Comment by Sight-wcg** [comment]
> 导致我的项目有一些获取不到id

获取不到 id 属性还是 lay-id 属性，IE8 仿真测试未发现异常。

> 这种肉眼可见的错误我也复制不了什么，就是少了双引号，html语法不规范的问题

HTML 5 规范 https://html.spec.whatwg.org/multipage/introduction.html#a-quick-introduction-to-html
HTML 4.01 规范 https://www.w3.org/TR/html401/intro/sgmltut.html#h-3.2.2

![image](https://github.com/layui/layui/assets/26325820/3635d660-d7fa-4864-8658-08151a0bbca6)

**Comment by ygbh** [comment]
感谢，大佬。

**Comment by Sight-wcg** [comment]
> 鸣鸣， lay-id 属性值获取不到，我的lay-id值是URL来的。建议评估，加一下双引号，不然有特殊符号值获不了，我排查半天才发现，console一点错误都没有报。

layui-tab-item 上的 lay-id 属性是 2.9.11 添加的，如果找不到对应的 id 会回退到默认行为，理论上对以前的项目不会有影响。
你遇到的问题，是直接升级 layui 版本后对现有项目造成影响了吗？

**Comment by ygbh** [comment]
是的，我是使用layui-mini框架，2.9.10都是正常，升级后就发现这个问题了。

![Snipaste_2024-06-06_17-19-18](https://github.com/layui/layui/assets/18203354/03c4ea6c-679f-417a-8cb4-1fdc959292a1)
![Snipaste_2024-06-06_17-20-32](https://github.com/layui/layui/assets/18203354/ec28e5fd-b85c-465d-8969-d3af51decc4e)

**Comment by Sight-wcg** [comment]
有代码问题就显而易见了，并不是不是获取不到 ID，`lay-id=user/page/>` 被解析为闭合标签

**Comment by ygbh** [comment]
嗯，看看框架能否修复一下这个问题，这种出问题排查不好发现，github时儿访问不到，传上图片要等了很久。哈哈。
