### ISSUE TITLE
TAB标签后台，内容页在IOS移动端无法显示

### ISSUE THREAD

**Issue by epsonall** [layui/layui#1993]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.11

### 问题描述

TAB标签后台，选中的TAB标签对应layui-tab-content内容页在IOS移动端无法显示
![搜狗截图20240601111648](https://github.com/layui/layui/assets/171953821/ac7e03e0-68b8-47ff-becf-5e8283694262)

### 业务代码

```auto
<div class="N-tab layui-tab-rollTool layui-tab" lay-filter="LayuTab" lay-allowclose="true">
            <ul class="layui-tab-title">
                <li class="layui-this" id="NHomeTabId" lay-id=""></li>
            </ul>
            <div class="layui-tab-content">
                <div id="NHomeTabIframe" class="layui-tab-item layui-show"></div>
            </div>
        </div>
```

### 浏览器

IOS

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
切换到 `2.9.10` 是否正常？看上去跟 #1989 应该是同一个问题。

**Comment by epsonall** [comment]
也不正常，就是在iphone手机端出现


&nbsp;


536574800
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月6日(星期四) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [layui/layui] TAB标签后台，内容页在IOS移动端无法显示 (Issue #1993)














 
切换到 2.9.10 是否正常？看上去跟 #1989 应该是同一个问题。

**Comment by epsonall** [comment]
已排查出问题了，谢谢
