### ISSUE TITLE
treetable 默认关闭节点，再打开全部节点，done回调里面写的样式方法没有生效。

### ISSUE THREAD

**Issue by Cuixq123** [layui/layui#1996]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.10

### 问题描述

![image](https://github.com/layui/layui/assets/42368775/60d363f3-a804-4ee8-869c-e5b113ab3ef0)
回调里面写一些字段的颜色设置，如果默认是展开，就有效果。 如果是关闭再打开就没有生效。

### 业务代码

```auto
只有截图。
```

### 截图补充

![image](https://github.com/layui/layui/assets/42368775/7a3733ee-df38-4acb-ae06-59ac08ca3249)
![image](https://github.com/layui/layui/assets/42368775/d15cea50-f92b-4f14-903a-fee34103ad0e)

### 浏览器

谷歌

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
treeTable 默认情况初始只渲染根节点，打开节点时才渲染子节点，子节点打开或关闭不会触发 done 回调，可以在展开节点相关的回调中进行处理。
