### ISSUE TITLE
建议优化【选项卡】tab组件在节点比较多场景下的UI

### ISSUE THREAD

**Issue by MonGDCH** [layui/layui#1998]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.11

### 问题描述

![image](https://github.com/layui/layui/assets/19282393/43842c43-aa96-44cb-8b32-b0c0de9d01b8)

【选项卡】组件在节点数量比较多的情况下会进行折叠，但在需要展开的时候有时候会对内容造成挤压，建议优化成滚动的形式

### 业务代码

```auto
无
```

### 浏览器

chomre

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
2.x 暂时不考虑优化该问题，后续 tabs 会在新的大版本中作为单独组件存在，并具备你说的这一功能。

**Comment by MonGDCH** [comment]
听大佬这么说，愈发期待新版本了的
