### ISSUE TITLE
希望功能增强 table 背景行颜色设置.隔行背景颜色设置.鼠标经过颜色设置.选中行颜色设置 

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2000]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.10

### 问题描述

希望功能增强 table 背景行颜色设置.隔行背景颜色设置.鼠标经过颜色设置.选中行颜色设置  even: true, 在这里或单独数组设置

### 业务代码

```auto
希望功能增强 table 背景行颜色设置.隔行背景颜色设置.鼠标经过颜色设置.选中行颜色设置  even: true, 在这里或单独数组设置
```

### 浏览器

ALL

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by aimu2000** [comment]
像 defaultToolbar 一样

**Comment by Sight-wcg** [comment]
这类问题可以通过重写样式解决，不会新增选项来设置。
