### ISSUE TITLE
用form表单通过layer.open+iframe的方式弹窗,通过parent.layer.close(index)关闭弹出层会自动对当前地址发送get请求?

### ISSUE THREAD

**Issue by MourinhoLove** [layui/layui#2006]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.10

### 问题描述

跟这位老哥的情况类似https://github.com/layui/layui/issues/417
只有点击弹窗右上角的关闭按钮和遮罩关闭就不会触发
别的关闭后，我发现会自动请求当前iframe的地址1次

### 业务代码

```auto
关闭代码:
 const index = parent.layer.getFrameIndex(window.name); // 获取弹窗的索引
            parent.layer.close(index); // 关闭弹窗
```

### 浏览器

chrome:125.0.6422.142

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by MourinhoLove** [comment]
[layui弹窗测试.zip](https://github.com/user-attachments/files/15796501/layui.zip)
这是我的demo
里面的b页面的DOMContentLoaded，在关闭的时候会被执行1次

**Comment by MourinhoLove** [comment]
> @MourinhoLove 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)

已提供zip的demo

**Comment by MourinhoLove** [comment]
> @MourinhoLove 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)

[layui弹窗测试.zip](https://github.com/user-attachments/files/15797587/layui.zip)
已提供Demo

**Comment by Sight-wcg** [comment]
给表单中的按钮设置 `type="button"` 即可，更多信息参考 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button#type

```diff
- <button class="layui-btn layui-btn-primary" id="btnClose">
+ <button type="button" class="layui-btn layui-btn-primary" id="btnClose">
   退出
  </button>
```

**Comment by MourinhoLove** [comment]
> 给表单中的按钮设置 `type="button"` 即可，表单中的按钮默认类型为 `submit` 。更多信息参考 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button#type
> 
> ```diff
> - <button class="layui-btn layui-btn-primary" id="btnClose">
> + <button type="button" class="layui-btn layui-btn-primary" id="btnClose">
>    退出
>   </button>
> ```

确实是这个原因，感谢
