### ISSUE TITLE
Tree树组件的节点名称能否支持换行

### ISSUE THREAD

**Issue by starWillRed** [layui/layui#2013]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.8

### 问题描述

我尝试了直接在节点名称中添加<br>换行符，以便在节点名称过长时，能够换行显示。
但是Tree树组件似乎只为节点名称提供一行的高度，因此，当我在节点名称中使用<br>换行后，出现了第二行内容将下一个节点名称遮盖住的问题。希望能够支持节点名称的换行。

### 业务代码

```auto
无。
```

### 浏览器

Chrome 109

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
#1606
