### ISSUE TITLE
建议添加Layui到公共CDN

### ISSUE THREAD

**Issue by aveyuan** [layui/layui#2015]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.11

### 问题描述

建议将版本发布的同时提交一份到 https://github.com/cdnjs/cdnjs
目前我发现字节CDN会去同步 https://cdn.bytedance.com/
只有老的版本，已经很久没有提交了

### 业务代码

```auto
无
```

### 浏览器

edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by hulang** [comment]
https://www.layuicdn.com/index.html
看这里。。。

**Comment by sentsim** [comment]
https://cdnjs.com/libraries/layui
