### ISSUE TITLE
layui 模板引擎

### ISSUE THREAD

**Issue by ghj1040110333** [layui/layui#203]
<div class="layui-input-inline">

                                    <input type="radio" name="sex" value="男" title="男">
                                    <input type="radio" name="sex" value="女" title="女">
                                </div>  怎么实现模板引擎的选则， 将模板代码放到 input 里面则会出现错误

**Comment by ghj1040110333** [comment]
bug太多

**Comment by caokunyu** [comment]
` <div class="layui-form-item">
    <label class="layui-form-label">单选框</label>
    <div class="layui-input-block">
      <input type="radio" name="sex" value="男" title="男" checked="">
      <input type="radio" name="sex" value="女" title="女">
      <input type="radio" name="sex" value="禁" title="禁用" disabled="">
    </div>
  </div>`

你这样写

**Comment by davinma** [comment]
将模板代码放到 input 里面？楼主是不是描述反了？关于模板里面的 input，可以这么写(随便举的例子)：
`````` HTML
<ul class="layui-list-demo">
    <li>
        {{# layui.each(d, function(index, item){ }}
        <input type="radio" name="{{ item.sex_name }}" value="{{ item.sex_value }}" lay-skin="primary" title="{{ item.sex_title }}"
            {{ item.is_checked ? 'checked' : '' }} />
        {{# }); }}
    </li>
</ul>
``````
模板写好以后，如果觉得渲染可能会出错，可以去 [官方调试页面](http://www.layui.com/demo/laytpl.html) 试试，另外楼主最好把问题描述清楚，具体是出现什么错误，把代码贴上来更直观一些。
