### ISSUE TITLE
upload 希望增加自定义上传

### ISSUE THREAD

**Issue by zhuchaoling** [layui/layui#2041]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.13

### 问题描述

现在上传就需要在 render的opts 中配置上传的url，

### 业务代码

```auto
业务场景是： 使用七牛云js-sdk 上传，当前的上传不支持
```

### 浏览器

125.0.6422.142

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
实际遇到了什么问题？

**Comment by Sight-wcg** [comment]
用七牛云 sdk，就没有必要用 layui upload 了，建议将七牛云 sdk 封装为专用的上传组件。
