### ISSUE TITLE
使用laytpl动态添加手风琴面板 使用element.render重新渲染后默认全部展开

### ISSUE THREAD

**Issue by 9007967** [layui/layui#2042]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.13

### 问题描述

使用laytpl动态添加手风琴面板 使用element.render重新渲染后默认全部展开

### 业务代码

```auto
laytpl($('#domain-list').html()).render(result.data, function (html) {
$('.layui-collapse').html(html);
});
element.render('collapse', 'layui-collapse');

<div class="layui-collapse" lay-filter="layui-collapse" lay-accordion>
</div>

<script id="domain-list" type="text/html">
{{#  layui.each(d, function(index, item){ }}
<div class="layui-colla-item">
<div class="layui-colla-title">{{= item.title}}</div>
<div class="layui-colla-content layui-show">{{= item.desc}}</div>
</div>
{{#  }); }}
</script>
```

### 截图补充

![WX20240620-214719](https://github.com/layui/layui/assets/33853639/d030ddd6-d76f-4438-8953-3ae2ee7c0761)

### 浏览器

Microsoft Edge 版本 125.0.2535.92 (正式版本) (arm64)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by niceboyat** [comment]
把layui-show去掉
