### ISSUE TITLE
tree增加 pre operate 方法，return false，则不operate（add|delete|update）

### ISSUE THREAD

**Issue by swanfly** [layui/layui#2043]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

无

### 问题描述

树组件，只要点击添加（➕）按钮，就会加一条数据。添加前，需要弹窗提示：是否要添加？确认后，再添加。目前tree实现不了这个功能。希望增加 pre operate 方法，return false，则不执行operate（add|delete|update）方法

### 业务代码

```auto
无
```

### 浏览器

无

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
v2 版本 tree 暂无调整计划，建议用 zTree 替代

**Comment by swanfly** [comment]
好的，谢谢
