### ISSUE TITLE
下拉组件能否添加根据页面/文档实际大小自动宽高的功能

### ISSUE THREAD

**Issue by JKRaks** [layui/layui#2044]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.13

### 问题描述

在layer的弹出层内使用select经常会因为选项过多或者名字过长导致打开下拉框后超出页面最大宽高, 然后页面出现横滚或者竖滚的滚动条, 比较影响美观而且有时候会导致页面排版出问题, 使用也不太友好, 能否在form.render时控制 dl.layui-anim.layui-anim-upbit 下拉菜单的宽度和高度, 让他不超过可视区域或者文档区域, 或者针对过长/宽的下拉框能否自动调整弹出时下拉列表的位置而不是在下拉框元素下方对齐钉死

### 业务代码

```auto
下面放了一个我在使用的简单实现
```

### 浏览器

Microsoft Edge 版本 125.0.2535.85 (正式版本) (64 位)

### 演示地址

https://stackblitz.com/edit/stackblitz-starters-xbzzqo?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
- 由于 https://github.com/layui/layui/pull/2132 当前版本暂无计划支持，select 面板相关优化将会放到后续大版本中
- iframe 中定位相关问题不会处理
- 非 iframe 建议开启 `lay-append-to="body"`

**Comment by Sight-wcg** [comment]
ref https://github.com/layui/layui/issues/2155#issuecomment-2275819530
