### ISSUE TITLE
layer.prompt有点怪异

### ISSUE THREAD

**Issue by hulang** [layui/layui#2045]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.13

### 问题描述

![动画1111](https://github.com/layui/layui/assets/4961831/cdb8e048-024c-4799-a304-9b8c36dc2278)
有默认值的时候，输入就向上对齐，密码的时候，输入就向左了一个，是我错觉还是？

### 业务代码

```auto
layer.prompt({title: '请输入',formType: 1, value: '不要998'}, function(value, index, elem){
        if(value === '') return elem.focus();
        layer.msg('获得：'+ util.escape(value)); // 显示 value
        // 关闭 prompt
        layer.close(index);
      });
```

### 浏览器

最新edge

### 演示地址

https://layui.dev/docs/2/layer/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
#1471

**Comment by hulang** [comment]
@Sight-wcg 是`chrome`的`BUG`？去年到现在，`chrome`出现这样的BUG，还没有修复，不可能吧，`chrome`大厂啊。。
