### ISSUE TITLE
upload组件，error方法没有像table组件那样，返回状态码，例如401

### ISSUE THREAD

**Issue by 1051897274** [layui/layui#2048]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

upload组件，error方法没有像table组件那样，返回状态码，例如401，希望能把状态码返回，像table一样

### 业务代码

```auto
无
```

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by yswang1024** [comment]
确实，我也遇到了，处理起来比较棘手，最后在上传之前手动调用一次无关的后台地址去验证是否401

**Comment by 1051897274** [comment]
> 确实，我也遇到了，长时间不操作，上传的时候session超时，处理起来比较棘手，最后在上传之前手动调用一次无关的后台地址去验证是否401

加入了改进和增强，但是大佬目前一直还没时间改进处理

**Comment by sentsim** [comment]
error 返回的参数确实有点尴尬，没设计好。不得不新增第四个参数。
