### ISSUE TITLE
能否把layui-vue版的popconfirm和layer.Notify整合过来啊

### ISSUE THREAD

**Issue by hulang** [layui/layui#2051]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

http://www.layui-vue.com/zh-CN/components/popconfirm
我是后端，不会整合。。。`popconfirm`确实不错。。
http://www.layui-vue.com/zh-CN/components/layer
layer的Notify方法也不错

### 业务代码

```auto
官方是不是不在对2x版本增加新的组件了？如果是，就关闭了吧。。。唉。。
```

### 浏览器

最新edge

### 演示地址

http://www.layui-vue.com/zh-CN/components/popconfirm

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by jichuanan** [comment]
去layui-vue那边看了一下，好多不错的组件

**Comment by Sight-wcg** [comment]
暂无计划添加，如果有 PR 且足够好会接受。

其实这些常见的组件，善用搜索都能找到
https://github.com/atomiks/tippyjs
https://github.com/marcelodolza/iziToast

**Comment by hulang** [comment]
@Sight-wcg tippyjs根本不是`popconfirm`。。没有：关闭和确定按钮。。

**Comment by Sight-wcg** [comment]
> @Sight-wcg tippyjs根本不是`popconfirm`。。没有：关闭和确定按钮。。

先看看文档
