### ISSUE TITLE
Table跨域请求支持

### ISSUE THREAD

**Issue by wuweiit** [layui/layui#206]
建议优化下Table，加配置实现跨域的会话支持。目前的table组件跨域能请求数据，但不能保持用户会话。

具体是table.js 421行，jquery的ajax请求加这两个配置

```
 ,crossDomain: true
 ,xhrFields: {
               withCredentials: true
  }
```

**Comment by l511407563** [comment]
使用nginx反向代理前后端分离, 无需考虑任何前端跨域问题,

**Comment by wuweiit** [comment]
目前我们项目Nginx代理前端，没有做后台代理，内网测试直接用的IP地址（**开发环境，每个开发人员利用IDEA内置的服务器启动前端，调用后端接口**），所以有这个问题。
table做一个是否跨域配置还是挺好的，这样需要跨域自行配置就行了。

**Comment by lianghuilin** [comment]
的确，table没有跨域支持，每次都得修改源码，太不方便了

**Comment by leijue222** [comment]
@l511407563 但是就有很多情况下需要请求的是第三方，我们没权限在第三方做设置。
