### ISSUE TITLE
select控件option为空时, placehoder和默认选项都是默认的中文, 能不能像翻页控件一样给个指定语言的地方, 对多国语言友好一点

### ISSUE THREAD

**Issue by cym1102** [layui/layui#2062]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.13

### 问题描述

select控件option为空时, placehoder和默认选项都是默认的中文, 能不能像翻页控件一样给个指定语言的地方, 对多国语言友好一点

### 业务代码

```auto
<select name="proxyType" id="proxyType">

</select>
```

### 截图补充

![QQ截图20240626143127](https://github.com/layui/layui/assets/11779355/0e42ed7b-0da9-45ec-a92a-2e6aabe48098)

### 浏览器

chrome 127

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
最近的 Issue 标题怎么都这么长

**Comment by Sight-wcg** [comment]
分页和日期组件以前有独立版本，可能会在其他组件库中使用，所以才有语言配置。

暂不考虑为其他组件增加类似的配置，因为  layui 目前不支持国际化，有国际化需求的用户一般会修改源码来解决。单独为 select 增加语言配置反而会成为将来支持国际化的“历史包袱”，意义不大。
