### ISSUE TITLE
table 能否多加个禁用行双击的事件设置 特别是列有EDIT的地方 

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2063]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.13

### 问题描述

{field: 'A', width: 90, title: 'A', align: 'center', edit: },
table 能否多加个禁用行双击的事件设置 特别是列有EDIT的地方 
想编辑单元格,鼠标点快了.就成了 行双击事件

### 业务代码

```auto
{field: 'A', width: 90, title: 'A', align: 'center', edit: },
table 能否多加个禁用行双击的事件设置 特别是列有EDIT的地方 
想编辑单元格,鼠标点快了.就成了 行双击事件
```

### 浏览器

CR

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by aimu2000** [comment]
某些加了禁用参数的列,双击事件失效

**Comment by bxjt123** [comment]
可以设置`lay-unrow`阻止行事件

**Comment by aimu2000** [comment]
> 可以设置`lay-unrow`阻止事件

只是需要在编辑的列上 双击事件失效!

**Comment by Sight-wcg** [comment]
> 想编辑单元格,鼠标点快了.就成了 行双击事件
> 只是需要在编辑的列上 双击事件失效!

鉴于这个问题描述比较模糊，无意做阅读理解，关闭。

**Comment by aimu2000** [comment]
表格里面可以编辑的单元格.
让它失去双击行事件的功能

**Comment by aimu2000** [comment]
表格里面多行 多列.
行双击事件会触发.
行数据里面,某些列是设置可以编辑的,这个时候鼠标点快了.就成了行双击事件.而不是点一下去编辑某列的单元格数据.
或者是否可以单点一下单元格进行编辑时,清空单元格里面的数据.这样就不需要多点击次单元格来全选里面的数据了.并在没有编辑的情况下离开当前单元格恢复之前原有的数据.

**Comment by sentsim** [comment]
明白你的意思后，`lay-unrow` 确实无法阻止行双击事件，它只能阻止行单击事件。可等待后续版本优化。
