### ISSUE TITLE
数据表格右上角的defaultToolbar不再支持HTML模板?

### ISSUE THREAD

**Issue by ioripalm** [layui/layui#2066]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

之前一直使用HTML模板来建立数据表格右上角的按钮功能. 
在表格基础属性内,defaultToolbar给个空数组以开启功能:
`defaultToolbar:[],`
在HTML内写一个模板,好处是可以自定义样式,图标等:
新的版本改为了在基础属性内设置,如果还是写defaultToolbar:[],则内置功能不启用,lay-event="LAYTABLE_COLS"无效果
如果要自定义图标,如何使用外部图标?例子中给出的是layui内置图标的示例
`defaultToolbar: [
  'filter', 'exports', 'print', // 内置工具
  {
    // 扩展工具
    title: '提示', // 标题
    name: 'tips', // name
    layEvent: 'LAYTABLE_TIPS', // 事件标识
    icon: 'layui-icon-tips', // 图标 className layui内部图标
    onClick: function(obj) { // 点击事件 - 2.9.12+
      console.log(obj); // 查看返回的对象成员
    }
  }
]`

### 业务代码

```auto
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>table 组件</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="./js/layui/layui.js" charset="utf-8"></script>
    <link href="//cdn.staticfile.net/layui/2.9.13/css/layui.css" rel="stylesheet">
  </head>
  <body>
    <div>
        <table class="layui-hide" id="test" lay-filter="test"></table>
    </div>
  <script type="text/html" id="toolbarTop">
      <div class="layui-input-inline layui-toolbar-left" style="float:left">
          <div class="layui-input-inline"><input class="layui-input" type="text" name="patientIdInput" id="XxxIdInput" placeholder="请输入xxx" autocomplete="off" value="0000103404"></div>
          <button class="layui-btn layui-btn-sm layui-btn-normal" lay-event="searchXxxId" id="searchXxxId">搜索</button>
      </div>
      <div class="layui-input-inline" style="float:right">
          <!-- 自定义顶部工具栏功能,以下功能按钮的图标是自定义图标,非layui内置 -->
          <div class="layui-inline" title="筛选列" lay-event="LAYTABLE_COLS"><i class="fad fa-columns fa-2x"></i></div>
          <div class="layui-inline" title="导出EXCEL" lay-event="table_export"><i class="fad fa-file-excel fa-2x"></i></div>
          <div class="layui-inline" title="打印" lay-event="LAYTABLE_PRINT"><i class="fad fa-print fa-2x"></i></div>
      </div>
  </script>
  </body>
  <script type="text/javascript">// 创建渲染实例
    layui.use(['table', 'dropdown'], function(){
    var table = layui.table;
      table.render({
        elem: '#test',
        url: '/static/json/2/table/demo1.json', // 此处为静态模拟数据，实际使用时需换成真实接口
        toolbar: '#toolbarTop',
        defaultToolbar: [],//defaultToolbar:[],默认工具条不显示
        cols: [[
          {type: 'checkbox', fixed: 'left'},
          {field:'id', fixed: 'left', width:80, title: 'ID', sort: true},
          {field:'username', width:80, title: '用户'},
        ]],
        done: function(){
        },
        error: function(res, msg){
          console.log(res, msg)
        }
      });
    });
  </script>
</html>
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by ymruse** [comment]
借楼请教一下，内置的exports导出，没有excel的选项了吗？现在只有一个CSV选项。想要excel一定要自定义吗？看了文档中的demo也一样这次升级突然不见了.
![image](https://github.com/layui/layui/assets/155124186/0cfe121b-7af7-45fc-baa6-618e4b0b0551)

**Comment by sentsim** [comment]
@ymruse  应尽量避免在不相关的 Issue 中提问。
之前导出 xls 其实本质也是 csv，只是文件扩展名变成了 `.xls`，所以打开时会出现格式被修改的提示。
如果是导出标准的 xls 或 xlsx，推荐自定义，参考：https://layui.dev/docs/2/table/#options.defaultToolbar
