### ISSUE TITLE
功能增强 表格编辑框 在编辑前清空原先的值

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2075]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

{field: 'A', width: 90, title: 'A', align: 'center', edit:clear},
edit: true 正常编辑, clear 鼠标点进去 进去编辑状态清空里面原有的值
多加个列参数选择. 这样会方便很多.

未编辑内容离开编辑状态还原之前的值

### 业务代码

```auto
{field: 'A', width: 90, title: 'A', align: 'center', edit:clear},
edit: true 正常编辑, clear 鼠标点进去 进去编辑状态清空里面原有的值
多加个列参数选择. 这样会方便很多.

未编辑内容离开编辑状态还原之前的值

```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
不算太刚需的功能，建议尝试采用 tool 和 edit 事件外部实现

**Comment by aimu2000** [comment]
> 不算太刚需的功能，建议尝试采用 tool 和 edit 事件外部实现

假如有很多列的表格需要重新输入数据,清空编辑框里面的数据操作都要花很多时间.

希望官方原生支持.

**Comment by sentsim** [comment]
参考：https://github.com/layui/layui/discussions/1947
