### ISSUE TITLE
一些优化组件的功能请求

### ISSUE THREAD

**Issue by 1228181394** [layui/layui#2076]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

建议：
1.在from的必填项的Label上增加红*标记，这样更容易知道哪一个是必填项；
2.增加select多选框：类似于xm-select一样的可以实现多选；https://codecp.tech/static/xm-select/#/component/install
3.增加设置全局的加载loading样式，目前只能单个设置或者使用默认的样式；
4.table的合计行增加int值，目前默认都是优两位小数点，例如可以通过totalRowType:'int'设置小数点属性；https://blog.csdn.net/qq_42175986/article/details/111473134

### 业务代码

```auto
无
```

### 浏览器

版本 126.0.6478.115（正式版本） （64 位）

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
1、2 暂无考虑
3. 直接使用 `layer.load()` 看看呢。
4. 合计行的模板功能完全能够满足该需求
```
totalRow: '{{= parseInt(d.TOTAL_NUMS) }}' // int
totalRow: '{{= d.TOTAL_NUMS.toFixed(3) }}' // 自由设置小数点位
```
https://layui.dev/docs/2/table/#cols.totalRow

**Comment by 1228181394** [comment]
3.layer.load()只是本页面生效，无法甚至全局的loading样式。
4. 合计行是通过页面计算的，不是通过后端返回的。页面中全是整数，计算出来就成小数了。

**Comment by sentsim** [comment]
也可以显示后端返回的合计数据，仔细查阅文档。

**Comment by bxjt123** [comment]
必填项标记其实很简单，在对应的`label`上增加一个例如`required`的类名，使用`before`或`after`均可
```
<label class="layui-form-label required">必填项</label>

.required:before {
    content: "*";
    color: red;
}
```

**Comment by 1228181394** [comment]
已解决哈，谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 青崖 ***@***.***&gt;
发送时间: 2024年7月4日 12:21
收件人: layui/layui ***@***.***&gt;
抄送: 1228181394 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [layui/layui] 一些优化组件的功能请求 (Issue #2076)





 
必填项标记其实很简单，在对应的label上增加一个例如required的类名，使用before或after均可
 <label class="layui-form-label required"&gt;必填项</label&gt; .required:before {     content: "*";     color: red; }
