### ISSUE TITLE
文件上传如何更新数量限制？

### ISSUE THREAD

**Issue by xuanyuanchengshu** [layui/layui#2081]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.5.5

### 问题描述

我想在文件上传增加删除/取消功能（很多文件上传上传功能），但是不知道如何删除文件队列（貌似是this.files）和 更新数量限制。
例如将number设置为1，我选择一个文件后上传，然后删除掉（是想删除控件的文件对象），然后重新选择，此时会提示数量限制，因为上一步上传过了一个文件了。
球球了。

### 业务代码

```auto
// 内网机暂时无法提供
```

### 浏览器

121.0.6167.185（正式版本）（64位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
版本太旧，问题难以追溯。
参考当前支持的最低版本：https://github.com/layui/layui?tab=security-ov-file

**Comment by xuanyuanchengshu** [comment]
较新本版中如何解决这个问题呢？ 还是已直接支持？

**Comment by xuanyuanchengshu** [comment]
> 版本太旧，问题难以追溯。 参考当前支持的最低版本：https://github.com/layui/layui?tab=security-ov-file

较新本版中如何解决这个问题呢？ 还是已直接支持？

**Comment by xuanyuanchengshu** [comment]
> 版本太旧，问题难以追溯。 参考当前支持的最低版本：https://github.com/layui/layui?tab=security-ov-file

已自行解决。将number设置为999，然后自定义数量限制验证。

**Comment by xuanyuanchengshu** [comment]
> > 版本太旧，问题难以追溯。 参考当前支持的最低版本：https://github.com/layui/layui?tab=security-ov-file
> 
> 较新本版中如何解决这个问题呢？ 还是已直接支持？

已自行解决。将number设置为999，然后自定义数量限制验证。
