### ISSUE TITLE
表格行单击更新选中行问题

### ISSUE THREAD

**Issue by qzh010511** [layui/layui#2082]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.13

### 问题描述

设置表格为单选时，想要实现点击行赋值选中此行，选中后再选择其他行则单选框不会变更选中的样式
![image](https://github.com/layui/layui/assets/66982690/57875124-c44e-4930-b728-0306094ccaa1)

### 业务代码

```auto
table.render({
        elem: '#ID-test-table',
        height: 420,
        url: '/static/json/2/table/user.json', // 数据接口（此处为静态数据，仅作演示）
        title: '用户表',
        page: true, // 开启分页
        toolbar: 'default', // 开启工具栏，此处显示默认图标，可以自定义模板，详见文档
        totalRow: true, // 开启合计行
        cols: [[ // 表头
          {type: 'radio', fixed: 'left'},
          {field: 'id', title: 'ID', width:80, sort: true, fixed: 'left', totalRow: '合计 : '},
          {field: 'username', title: '用户名', width:80},
          {field: 'experience', title: '积分', width: 90, sort: true, totalRow: '{{= d.TOTAL_NUMS }}'},
          {field: 'sex', title: '性别', width:80, sort: true},
          {field: 'score', title: '评分', width: 80, sort: true, totalRow: true},
          {field: 'city', title: '城市', width:150},
          {field: 'sign', title: '签名', minWidth: 200},
          {field: 'classify', title: '职业', width: 100},
          {field: 'words', title: '字数', width: 135, sort: true, totalRow: true},
          {fixed: 'right', title: '操作', width: 150, align:'center', toolbar: '#ID-demo-table-tool'}
        ]]
      });
      table.on('row(ID-test-table)',function(obj){
        
          obj.setRowChecked({
            type:'radio'
          });

      })
```

### 浏览器

Google Chrome 126.0.6478.127

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
没有太明白你的表达，建立先搞清楚单选和多选的区别。

**Comment by sentsim** [comment]
没有太明白你的表达，建议先搞清楚单选和多选的区别。

**Comment by sentsim** [comment]
以后提交 Issue 尽量要将意思表达清楚，至少语句要通顺，避免他人做阅读理解 耗费不必要的时间。

**Comment by sentsim** [comment]
我的失误，之前没有太理解这个问题的描述。
已确定为 BUG，等待下个版本发布。

**Comment by Sight-wcg** [comment]
因为有一部分功能请求的问题类型标注的是「疑是 BUG」，通常我们仍需要根据问题描述区分并处理这些请求。而这个问题的描述本身就语句不通且充满歧义，可能是功能请求，也可能是报告 BUG，怎么理解都没问题。

**Comment by qzh010511** [comment]
> 我的失误，之前没有太理解这个问题的描述。 已确定为 BUG，等待下个版本发布。

是我描述不准确，因为我不太擅长言语，生活中都是出现不少问题，哈哈

**Comment by sentsim** [comment]
> 因为有一部分功能请求的问题类型标注的是「疑是 BUG」，通常我们仍需要根据问题描述区分并处理这些请求。而这个问题的描述本身就语句不通且充满歧义，可能是功能请求，也可能是报告 BUG，怎么理解都没问题。

是的，所以为了提升效率，大家在描述 Issue 时，务必要表达清楚，尽量语句通顺，且主旨明确。
