### ISSUE TITLE
我想在每次点击select出现下拉前异步加载一次值该如何实现

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#2085]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

我想在每次点击select出现下拉前异步加载一次值该如何实现

查看了官方文档，只有选中某个值的点击事件可以监控

### 业务代码

```auto
无
```

### 浏览器

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
暂无计划支持，有相关需求建议用第三方 select 组件替代。
