### ISSUE TITLE
关于#1898的改动，大家要注意哦。lay-id有变更

### ISSUE THREAD

**Issue by elylon1101** [layui/layui#2087]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.13

### 问题描述

在#1898的pr里面将部分组件的lay-id进行了调整。如果用到了lay-id的小伙伴要注意变更。我看官方文档里面没有提及这一点

### 业务代码

```auto
无
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
更新日志有记录，升级前务必阅读更新日志。

**Comment by Sight-wcg** [comment]
关闭，因为这不是功能请求。
