### ISSUE TITLE
表格中的文本框问题

### ISSUE THREAD

**Issue by hulang** [layui/layui#2089]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

![px123](https://github.com/layui/layui/assets/4961831/924a65c8-0190-4055-8da9-3f22a72e5448)
都超出了。。我看官方是使用：
```js
css: [ // 设置单元格样式
            // 取消默认的溢出隐藏，并设置适当高度
            '.layui-table-cell{height: 50px; line-height: 40px;}',
            '.layui-table-cell .layui-colorpicker{width: 38px; height: 38px;}',
            '.layui-table-cell select{height: 36px; padding: 0 5px;}'
        ].join(''),
```

但是我有的表格是：sm，每次都这么调整，好累，官方下次更新，能否不需要设置：css啊。。一劳永逸

### 业务代码

```auto
<script type="text/html" id="pxTpl">
  <div><input type="hidden" name="ids[]" value="{{d.group_id}}"><input type="text" name="px[]" maxlength="3" value="{{d.group_px}}" autocomplete="off" class="layui-input"></div>
</script>
```

### 浏览器

最新edge

### 演示地址

https://layui.dev/docs/2/table/#demo-editmodes

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
组件无法知道模板传入什么内容，如果每个模板内容都要在内部适应，显然不现实。
建议设置 `className` 属性，通过它找到 `size="sm"` 属性选择器，直接在你的 css 文件中自主适配，如此可一劳永逸。

**Comment by sentsim** [comment]
`className` 是个很有用的选项，一定要懂得灵活运用，尤其是像你这样的 Layui 的资深用户。

**Comment by hulang** [comment]
@sentsim 处理好。。。我重定义了文本框的高度和宽度
```html
class="layui-input input-w60"
```
```css
.input-w60{height:25px;line-height:25px;width:60px;}
```
