### ISSUE TITLE
layer.tab打开多个iframe失败

### ISSUE THREAD

**Issue by hanjiuri** [layui/layui#2091]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

这是我在官网找的在线代码测试，把type改成2，就会出现这个问题。

### 业务代码

```auto
1
```

### 截图补充

![image](https://github.com/layui/layui/assets/29794210/b1ff8431-1f5f-44a1-9bb4-59cffa56c28c)

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
layer.tab 不支持打开多个 iframe
