### ISSUE TITLE
IOS QQ v9.0.71 内置浏览器无法使用 Upload组件

### ISSUE THREAD

**Issue by teluns** [layui/layui#2092]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

IOS QQ v9.0.71 内置浏览器无法使用 Upload组件，找不到原因

### 业务代码

```auto
官网页面
```

### 截图补充

![2b04d39c152957a38501f17edad004c1](https://github.com/layui/layui/assets/12974398/fcb8d7de-bb76-41e3-8337-d0b144a73466)

### 浏览器

Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 QQ/9.0.71.613 V1_IPH_SQ_9.0.71_1_APP_A Pixel/1179 MiniAppEnable SimpleUISwitch/0 StudyMode/0 CurrentMode/0 CurrentFontScale/1.000000 QQTheme/1000 AppId/537227695 Core/WKWebView Device/Apple(iPhone 14 Pro) NetType/WIFI QBWebViewType/1 WKType/1

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
虚拟机中 Safari on iOS 测试未发现问题，理论上iOS QQ 内置浏览器(套壳)也不会有问题。
![image](https://github.com/layui/layui/assets/26325820/027ccf54-a307-4bf2-86e5-41e77c984814)

![image](https://github.com/layui/layui/assets/26325820/3d8f0b4a-d084-4af0-8cbb-fa60f1023faf)
