### ISSUE TITLE
表格的行右击事件如何获取鼠标所在列？

### ISSUE THREAD

**Issue by zzlatm** [layui/layui#2096]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.9

### 问题描述

表格的行右击事件，如何获取鼠标所在列的信息？
谢谢贤心及各位大神！！！！

### 业务代码

```auto
table.on("rowDouble",function(data){
// data中只包含行数据信息，如何获得列信息？
})
```

### 浏览器

EDGE

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
跟 row 事件返回的参数一样。
参考文档：https://layui.dev/docs/2/table/#on-row

**Comment by sentsim** [comment]
2.9.9 没办法获取列信息。

升级到  2.9.14 可通过以下方式获取：

```
table.on("rowContextmenu",function(obj){
  var options = obj.config; // 获取当前表格基础属性配置项
  var e = obj.e; // 当前的 jQuery 事件对象 --- 2.9.14+
  console.log('rowContextmenu', obj); // 查看返回对象的所有成员
  
  // 获取列信息
  var td = e.target.closest('td');
  var getCol =  function(key){
    try {
      key = key.split('-');
      return options.cols[key[1]][key[2]] || {};
    } catch(e){
      console.error(e);
      return {};
    }
  };
  var col = getCol(layui.$(td).data('key'))
  console.log(col); // 输出当前表头

  // …
})
```

**Comment by zzlatm** [comment]
> 2.9.9 没办法获取列信息，除非自主给绑定表格右键事件。
> 
> 升级到 2.9.14 则可通过以下方式获取：
> 
> ```
> table.on('rowContextmenu', function(obj) {
>   var options = obj.config; // 获取当前表格基础属性配置项
>   var e = obj.e; // 当前的 jQuery 事件对象 --- 2.9.14+
>   console.log('rowContextmenu', obj); // 查看返回对象的所有成员
>   
>   // 获取列信息
>   var td = e.target.closest('td');
>   var getCol =  function(key) {
>     try {
>       key = key.split('-');
>       return options.cols[key[1]][key[2]] || {};
>     } catch(e) {
>       console.error(e);
>       return {};
>     }
>   };
>   var col = getCol(layui.$(td).data('key'));
>   console.log(col); // 输出当前表头
> 
>   // …
> });
> ```

万分感谢！！！！！！！！！！！！！！

**Comment by zzlatm** [comment]
> 2.9.9 没办法获取列信息，除非自主给绑定表格右键事件。
> 
> 升级到 2.9.14 则可通过以下方式获取：
> 
> ```
> table.on('rowContextmenu', function(obj) {
>   var options = obj.config; // 获取当前表格基础属性配置项
>   var e = obj.e; // 当前的 jQuery 事件对象 --- 2.9.14+
>   console.log('rowContextmenu', obj); // 查看返回对象的所有成员
>   
>   // 获取列信息
>   var td = e.target.closest('td');
>   var getCol =  function(key) {
>     try {
>       key = key.split('-');
>       return options.cols[key[1]][key[2]] || {};
>     } catch(e) {
>       console.error(e);
>       return {};
>     }
>   };
>   var col = getCol(layui.$(td).data('key'));
>   console.log(col); // 输出当前表头
> 
>   // …
> });
> ```

新问题来了：初始化一切都正常，但当表格重载table.reloadData()后就出错了.

**Comment by zzlatm** [comment]
新问题来了：初始化一切都正常，但当表格重载table.reloadData()后就出错了.
![cb6e86720d9853964382cdc766dca5d](https://github.com/user-attachments/assets/ac25b619-2b89-434b-800b-9d981347c319)

**Comment by sentsim** [comment]
无法复现，最好直接提供个示例。

**Comment by zzlatm** [comment]
> 无法复现，最好直接提供个示例。

在官网调试工具里最小化还原，发现问题不存在。。。。
然后在自已的程序里一步一步调试，最后发现是当我的table.reloadData()后，表格的options参数对象竟然没了.cols属性，晕倒，好在table提供了table.getOptions()方法，自已重新给options赋值，就能正常运行了，问题目前已解决。

再次谢谢贤心及大神们！！！！！！！！！！！！！！！！！！！！
