### ISSUE TITLE
Tree组件的复选框半选状态

### ISSUE THREAD

**Issue by Tiamo-web66** [layui/layui#2097]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.11

### 问题描述

tree组件的复选框，当有多个子级的情况下，只勾选一个子级，父级也为勾选状态，并没有半选状态，希望后续能够添加半选状态的样式。

### 业务代码

```auto
tree.render({
    elem: '#ID-tree-demo',
    data: data,
    showCheckbox: true,  // 是否显示复选框
    onlyIconControl: true,  // 是否仅允许节点左侧图标控制展开收缩
    id: 'demo-id-1',
    isJump: true, // 是否允许点击节点时弹出新窗口跳转
    click: function(obj){
      var data = obj.data;  //获取当前点击的节点数据
      layer.msg('状态：'+ obj.state + '<br>节点数据：' + JSON.stringify(data));
    }
  });
```

### 浏览器

Chrom

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
https://github.com/layui/layui/issues/1606#issuecomment-1916536470
