### ISSUE TITLE
单选框（<input type="radio">）元素的name属性的值含空格会导致单选框变成多选【纯html没有这个问题】

### ISSUE THREAD

**Issue by cmk271314** [layui/layui#2098]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

按照layui官方文档示例(https://layui.dev/docs/2/form/radio.html )

### 普通单选框例子
 ```
<div class="layui-form">
  <input type="radio" name="AAA" value="1" title="默认">
  <input type="radio" name="AAA" value="2" title="选中" checked> 
  <input type="radio" name="AAA" value="3" title="禁用" disabled> 
</div>
<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>
```
右上角编辑，将`input`元素里面的`name`属性都修改为**name=“AA A”**「加了一个**空格**」，
```
<div class="layui-form">
  <input type="radio" name="AA A" value="1" title="默认">
  <input type="radio" name="AA A" value="2" title="选中" checked> 
  <input type="radio" name="AA A" value="3" title="禁用" disabled> 
</div>
<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>
```
运行，点击选择其它框，发现一、二两个框都被选择了，单选失效了（这些单选框不是一组了）。

**如果只是纯html的就没有这种问题：**
```
<div>
        <input name="a b" type="radio" value="1" checked>
        <input name="a b" type="radio" value="2">
        <input name="a b" type="radio" value="3">
        <input name="a b" type="radio" value="4" disabled>
    </div>
```
### **问题总结：**
单选框`<input type="radio">`的`name`在引入layui后值不能包含空格。
如果这里单选框中的`name`属性的值不支持空格请说明一下（可能只有我无聊书写加了空格，正常写默认是`a_b`）,不过html5这么写没问题。

### 业务代码

```auto
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
  <link href="//unpkg.com/layui@2.9.14/dist/css/layui.css" rel="stylesheet">
</head>
<body class="layui-padding-3">

<div class="layui-form">
  <input type="radio" name="AA A" value="1" title="默认">
  <input type="radio" name="AA A" value="2" title="选中" checked> 
  <input type="radio" name="AA A" value="3" title="禁用" disabled> 
</div>
  
<!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>


</body>
</html>
```

### 截图补充

![image](https://github.com/user-attachments/assets/34457483-aede-45d0-954b-ce4f58e91d71)

### 浏览器

Microsoft Edge 版本 126.0.2592.102 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
name 值一般不应该出现空格，`name="AA A"` 这是一个很奇怪的写法，建议将空格换成`_`或`-`。
