### ISSUE TITLE
Layer弹窗位置不正确

### ISSUE THREAD

**Issue by lh11117** [layui/layui#2099]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [x] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

我尝试在我的个人博客中使用layui的弹窗功能，但我发现在文章阅读页面弹窗位置不在正中间，我也没有去使用某些函数改变layer弹窗的位置。这个弹窗位于水平居中、垂直偏下的位置，在严重时还会使弹窗完全位于网页的不可见区域内，导致用户可能无法关闭或操作此对话框。经过我个人的debug，发现是由于页面文本过多，出现页面滚动造成的，但这不是重点，重点是希望官方能完全修复好这个问题。

我又阅读了layui的源代码：
在src/modules/layer.js第600行的函数中
调用了win.width()获取窗口高度，我在我的博客网站控制台调试了以下代码：
```javascript
// 代码1
window.innerHeight   // 445
layui.jquery(window).height()   // 1658
```

在其他页面：
```javascript
// 代码2
window.innerHeight   // 445
layui.jquery(window).height()   // 445
```
发现了 `window.innerHeight` 与 `layui.jquery(window).height()` 的结果在我的博客页面中结果不一样的问题（来测试的两个页面均出现页面滚动），而在代码1中1658是页面整个区域的高度，445是可视区域的高度，原因我暂时不太清楚

解决方法（猜想）：
将源代码layer.js里所有的`win.height()`改为`window.innerHeight`，以及`win.width()`改为`window.innerWidth`

### 业务代码

```auto
// 这是下方gif中演示的“删除文章”代码片段
function deleteArticle() {
    layer.prompt({
        btn: ['确认', '取消'],
        title: '确认删除文章吗? 确认请输入: 确认删除文章'
    }, function (value) {
        if (value != '确认删除文章') {
            layer.msg('输入错误! ', {
                icon: 2
            });
            return false;
        }
        layui.jquery.ajax({
            url: '/article/delete.php?aid=<?php echo $row['aid'];?>',
            success: function (result) {
                var data = JSON.parse(result);
                if (data['code'] == 200) {
                    layer.msg(data['msg'], {
                        icon: 1
                    });
                    setTimeout(function () {
                        location.href = '/article';
                    }, 1000);
                } else {
                    layer.msg(data['msg'], {
                        icon: 2
                    });
                }
            }
        }, 'json');
    }, function () {});
}
```

### 截图补充

测试请看GIF: 
![msedge_ZDOcw7iQYq](https://github.com/user-attachments/assets/a78ae37e-e7fc-4bad-a27c-3b8cb2ade08e)

我博客的页面获取高度结果：
![image](https://github.com/user-attachments/assets/3fcea5a6-6f60-4b2d-90c4-df31b06597aa)

其他页面获取高度结果：
![image](https://github.com/user-attachments/assets/358b4160-54e0-4363-9aa6-65e0422d6fa8)

### 浏览器

Edge 126.0.2592.102 正式版本 64位 

### 演示地址

暂时没有服务器，给一个蓝奏云链接吧：https://wwk.lanzouj.com/iFn2J24cps4b

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这是一个常见问题，请在页面代码第一行添加 `<!DOCTYPE html>` 以启用标准模式。

**Comment by lh11117** [comment]
> 这是一个常见问题，请在页面代码第一行添加 `<!DOCTYPE html>` 以启用标准模式。

谢谢
