### ISSUE TITLE
轮播组件：在form表单下，点击图片利用HTML DOM Element remove() 方法动态删除图片操作出现错误

### ISSUE THREAD

**Issue by dpc8** [layui/layui#2102]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

1、当删除至只剩一张图片时，指示器总是至少反馈显示2张图片数，且另一张是空白的加载图，与现存图片一张数量不符
2、无论展示多少张图片时，只要进行remove()删除操作后，轮播完成一个循环后，在循环最后总是闪现一张空白的加载图，但指示器数没有对应的标识

### 业务代码

```auto
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
  <link href="//unpkg.com/layui@2.9.14/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<form class="layui-form" method="post">
<div class="layui-fluid"> 
<div class="layui-card text-center">
                <div class="layui-card-body" style="height: 550px">
	<div class="layui-carousel" style="margin-left: 25%" name="fieldPicture" id="fieldPicture">
                        <div carousel-item id="fieldPictureCarousel">
                                <div id="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">< img src="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg"></div>
                                <div id="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">< img src="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg"></div>
    <div id="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg"><img src="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg"></div>
    <div id="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg"><img src="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg"></div>
                        </div>
                 </div>
    
                 <div class="layui-btn-container" style="margin-left: 48%">
                       <button type="button" class="layui-btn layui-bg-blue" id="uploadFieldImg"><div class="layui-icon layui-icon-add-1"></div></button>
                 </div>
                 </div>
</div>
</div>
</form>

<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script> 
<script>

layui.use(function(){

var carousel = layui.carousel;

// 渲染轮播
var carInst = carousel.render({
    elem: '#fieldPicture',
    interval: 1800,
    width: '50%',
    height: '380px',
    autoplay: 'true',
    indicator: 'outside'
});

//点击轮播图片触发删除
$('#fieldPicture').on('click', 'img', function() {

​    // 获取被点击的图片元素
​    var clickedImg = $(this);


​    var divId = clickedImg.context.currentSrc;

​    layer.confirm("你想要删除这张图片吗", function(i){
​        // 删除被点击的图片元素
​        var el = document.getElementById(divId);
​        el.remove();
​        layer.close(i);
​        carInst.reload();
​    });
	//打印
	console.log(document.getElementById("divId);
​        el.remove();
​        layer.close(i);
​        carInst.reload();
​    });
	//打印
	console.log(document.getElementById("fieldPictureCarousel"));

});

});
```

### 截图补充

![917aefff09c50fe254e886bb0306304](https://github.com/user-attachments/assets/432aaf3a-41f5-4254-92af-d42376b29e16)

### 浏览器

Chrome 版本 126.0.6478.127（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
提供的示例代码无法运行，存在「零宽度空格​」字符
![image](https://github.com/user-attachments/assets/93ae00e6-88bf-431e-aa1f-cb7884026b10)

**Comment by dpc8** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>
    
    <link href="//unpkg.com/layui@2.9.14/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<form class="layui-form" method="post">
    <div class="layui-fluid">
        <div class="layui-card text-center">
            <div class="layui-card-body">
                <div class="layui-carousel" style="margin-left: 30%" name="fieldPicture" id="fieldPicture">
                    <div carousel-item id="fieldPictureCarousel">
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                        </div>
                    </div>
                </div>

                <div class="layui-btn-container" style="margin-left: 48%">
                    <button type="button" class="layui-btn layui-bg-blue" id="uploadFieldImg">添加星空图</button>
                </div>

            </div>
        </div>
    </div>
</form>

<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>
<script>

    layui.use(function () {
        var $ = layui.jquery;

        var carousel = layui.carousel;

// 渲染轮播
        var carInst = carousel.render({
            elem: '#fieldPicture',
            interval: 1800,
            height: '360px',
            autoplay: 'true',
            indicator: 'outside'
        });

//点击轮播图片触发删除
        $('#fieldPicture').on('click', 'img', function () {

            // 获取被点击的图片元素
            var clickedImg = $(this);


            var divId = clickedImg.context.currentSrc;

            layer.confirm("你想要删除这张图片吗", function (i) {
                // 删除被点击的图片元素
                var el = document.getElementById(divId);
                el.remove();
                layer.close(i);
                carInst.reload();
            });
            //打印
            console.log(document.getElementById("fieldPictureCarousel"));
        });
        $('#uploadFieldImg').on('click', function () {
            var $ = layui.$;
            $('#fieldPictureCarousel').append('<div id="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg" ><img style="height: 100%;width: 100%" src="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg"></div>');
            carInst.reload();
        });
    });
</script>
</body>

**Comment by dpc8** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>
    
    <link href="//unpkg.com/layui@2.9.14/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<form class="layui-form" method="post">
    <div class="layui-fluid">
        <div class="layui-card text-center">
            <div class="layui-card-body">
                <div class="layui-carousel" style="margin-left: 30%" name="fieldPicture" id="fieldPicture">
                    <div carousel-item id="fieldPictureCarousel">
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                        </div>
                    </div>
                </div>

                <div class="layui-btn-container" style="margin-left: 48%">
                    <button type="button" class="layui-btn layui-bg-blue" id="uploadFieldImg">添加星空图</button>
                </div>

            </div>
        </div>
    </div>
</form>

<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>
<script>

    layui.use(function () {
        var $ = layui.jquery;

        var carousel = layui.carousel;

// 渲染轮播
        var carInst = carousel.render({
            elem: '#fieldPicture',
            interval: 1800,
            height: '360px',
            autoplay: 'true',
            indicator: 'outside'
        });

//点击轮播图片触发删除
        $('#fieldPicture').on('click', 'img', function () {

            // 获取被点击的图片元素
            var clickedImg = $(this);


            var divId = clickedImg.context.currentSrc;

            layer.confirm("你想要删除这张图片吗", function (i) {
                // 删除被点击的图片元素
                var el = document.getElementById(divId);
                el.remove();
                layer.close(i);
                carInst.reload();
            });
            //打印
            console.log(document.getElementById("fieldPictureCarousel"));
        });
        $('#uploadFieldImg').on('click', function () {
            var $ = layui.$;
            $('#fieldPictureCarousel').append('<div id="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg" ><img style="height: 100%;width: 100%" src="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg"></div>');
            carInst.reload();
        });
    });
</script>
</body>

**Comment by dpc8** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>
    
    <link href="//unpkg.com/layui@2.9.14/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<form class="layui-form" method="post">
    <div class="layui-fluid">
        <div class="layui-card text-center">
            <div class="layui-card-body">
                <div class="layui-carousel" style="margin-left: 30%" name="fieldPicture" id="fieldPicture">
                    <div carousel-item id="fieldPictureCarousel">
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-1.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-2.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-3.jpg">
                        </div>
                        <div id="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                            <img src="https://unpkg.com/outeres/demo/carousel/720x360-4.jpg">
                        </div>
                    </div>
                </div>

                <div class="layui-btn-container" style="margin-left: 48%">
                    <button type="button" class="layui-btn layui-bg-blue" id="uploadFieldImg">添加星空图</button>
                </div>

            </div>
        </div>
    </div>
</form>

<script src="//unpkg.com/layui@2.9.14/dist/layui.js"></script>
<script>

    layui.use(function () {
        var $ = layui.jquery;

        var carousel = layui.carousel;

// 渲染轮播
        var carInst = carousel.render({
            elem: '#fieldPicture',
            interval: 1800,
            height: '360px',
            autoplay: 'true',
            indicator: 'outside'
        });

//点击轮播图片触发删除
        $('#fieldPicture').on('click', 'img', function () {

            // 获取被点击的图片元素
            var clickedImg = $(this);


            var divId = clickedImg.context.currentSrc;

            layer.confirm("你想要删除这张图片吗", function (i) {
                // 删除被点击的图片元素
                var el = document.getElementById(divId);
                el.remove();
                layer.close(i);
                carInst.reload();
            });
            //打印
            console.log(document.getElementById("fieldPictureCarousel"));
        });
        $('#uploadFieldImg').on('click', function () {
            var $ = layui.$;
            $('#fieldPictureCarousel').append('<div id="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg" ><img style="height: 100%;width: 100%" src="https://unpkg.com/outeres/demo/carousel/720x360-5.jpg"></div>');
            carInst.reload();
        });
    });
</script>
</body>

**Comment by dpc8** [comment]
[复现.txt](https://github.com/user-attachments/files/16230885/default.txt)

**Comment by dpc8** [comment]
用记事本打开吧，然后第二点，我确认是我用法问题了，第一点还望解答，辛苦了，谢谢

**Comment by sentsim** [comment]
为什么不直接在 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建可供预览的示例，而是要放到一个 txt 文件中呢？
按照规范，原则上这样的问题会被直接 closed ( 详见：  [🍀 Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md))。

打开 txt 按照步骤测了下，这类使用场景很少，但确实会触发 reload 的一个小 BUG，下个版本修复。

**Comment by dpc8** [comment]
收到！不好意思，我是个刚毕业的小白，还是个后端，，初入职场，还没接触过这些工具，我会慢慢学习的，祝layui越来越好！我看一下这个问题指南注意事项，下一次我还提Issues，嘿嘿

**Comment by dpc8** [comment]
收到！不好意思，我还是个毕业未满一年的小白，还是个后端，，我会慢慢学习这些学习工具的，祝layui越来越好！我看一下这个问题贡献指南，下一次我还提issue，嘿嘿
