### ISSUE TITLE
表格默认导出XLSX的功能，怎么没有了？只有CSV格式。建议默认开启默认导出XLSX的功能，谢谢！

### ISSUE THREAD

**Issue by DaisenTravel** [layui/layui#2106]
### 议题条件

- [x] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.14

### 问题描述

表格默认导出XLSX的功能，怎么没有了？只有CSV格式。建议默认开启默认导出XLSX的功能，谢谢！

### 业务代码

```auto
表格默认导出XLSX的功能，怎么没有了？只有CSV格式。建议默认开启默认导出XLSX的功能，谢谢！
```

### 截图补充

表格默认导出XLSX的功能，怎么没有了？只有CSV格式。建议默认开启默认导出XLSX的功能，谢谢！

### 浏览器

edge、chrome、firefox

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by DaisenTravel** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sentsim** [comment]
之前只有 XLS，而不是 XLSX，剔除 XLS 是因为它导出的实际上也是 CSV 格式，因此用 Excel 打开会报格式错误。
至于导出 XLSX 格式，一般 UI 组件不会内置这项功能，因为 XLSX 是基于 Office Open XML 格式，处理起来会很复杂。建议直接采用第三方的专业库处理（如 SheetJS），并配合 table 最新的 defaultToolbar 选项灵活扩展。

- https://github.com/SheetJS/sheetjs
- https://layui.dev/docs/2/table/#options.defaultToolbar

**Comment by LSL1618** [comment]
再推荐一个导出XLSX的专业工具库 [https://github.com/exceljs/exceljs](https://github.com/exceljs/exceljs) [https://gitee.com/mirrors/exceljs](https://gitee.com/mirrors/exceljs)
