### ISSUE TITLE
按钮事件被多次提交,有没有遮罩或LOADING类的方法档一下.不让点击按钮,禁用了都没用.主要是能根本上解决只提交一次

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2108]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.14

### 问题描述

按钮事件被多次提交,有没有遮罩或LOADING类的方法档一下.不让点击按钮,禁用了都没用.

### 业务代码

```auto
按钮事件被多次提交,有没有遮罩或LOADING类的方法档一下.不让点击按钮,禁用了都没用.
```

### 浏览器

A

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by aimu2000** [comment]
难道非要隐藏起来.等接收到成功再取消隐藏

**Comment by sentsim** [comment]
节流函数：`layui.throttle(fn, wait)`
https://layui.dev/docs/2/base.html#api

Issue 标题太长了，详细的描述应该放在内容区域。
