### ISSUE TITLE
form表单提交事件textarea文本数据不同步

### ISSUE THREAD

**Issue by 54shwl** [layui/layui#2114]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

我用的是这个编辑器：https://www.nicemb.com/pro-editor
编辑好内容后立即点击提交，就会出现content内容字段为空，如果编辑好内容后，再去编辑其他layui输入框，提交时就能成功获取到content内容；
不能正常获取实时数据的提交方法
form.on('submit(demo1)', function(data){
    var field = data.field; // 获取表单字段值
    alert(field.content);//这里获取的不同步
    return false; 
});
而用这种方法就能正常使用
$('#list_form').on('submit', function(event) {
    event.preventDefault();
	var pams = $(this).serialize();
    // 使用jQuery的$.ajax方法发送请求
    $.ajax({
        type: 'POST',
        url: config.api.contribute,
        data: pams, // 序列化表单数据
        success: function(response) {
            // 请求成功，处理响应数据
            console.log(response);
        },
        error: function(xhr, status, error) {
            // 请求失败，处理错误
            console.error('提交失败:', error);
        }
    });
});

### 业务代码

```auto
layui.use(function(){
var form = layui.form,$ = layui.$;
var editor=$("#content").editor({toolbar:'full',height:470,upload:'api/upload.php',save:'api/save.php'});
// 提交事件
  form.on('submit(demo1)', function(data){
    var field = data.field; // 获取表单字段值
    // 显示填写结果，仅作演示用
    layer.alert(JSON.stringify(field), {
      title: '当前填写的字段值'
    });
    return false; // 阻止默认 form 跳转
  });
});
$('#list_form').on('submit', function(event) {
    event.preventDefault();
	var field = $(this).serialize();
	layer.alert(JSON.stringify(decodeURIComponent(field)), {
      title: '当前填写的字段值'
    });
});
```

### 截图补充

![QQ截图20240718211134](https://github.com/user-attachments/assets/577a5ddc-baf0-44d1-a222-f8af3cee0309)

### 浏览器

QQ浏览器

### 演示地址

http://b2.kuyuw.cc/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
问题与 Layui 没有太大关联。在 form submit 事件中，调用该编辑器的同步值的相关方法，一般编辑器组件都有类似的方法。
