### ISSUE TITLE
Select组件能否优化搜索，增加设置是否启用非连续字符匹配，之前虽然没有非连续匹配，但是匹配连续字符是很好用的

### ISSUE THREAD

**Issue by zheng-ze-hui** [layui/layui#2115]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.14

### 问题描述

比如我有很多数字编号  12345   12346  12347  12534 ... 这时候我输 12345，会出现很多 12345 13245 14235 ... 眼睛都容易看花，这种字段我就不希望启用非连续字符匹配。

### 业务代码

```auto
无
```

### 浏览器

版本 126.0.6478.127（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
确实存在这方面的影响，2.9.15 版本将评估是否对晨星 #2065 中改进的搜索通过参数形式开启
