### ISSUE TITLE
树组件 tree 使用 Checkbox 时二次读取问题

### ISSUE THREAD

**Issue by fmamcn** [layui/layui#2118]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

树组件 tree 使用Checkbox时在只选择其中子项目的时候（非全选）提交保存，保存的ID没错，但是编辑的时候重新读取ID时，会将该子项目的上级下的所有项目选中，从而出现第二次保存时和初次数据不一致！

如：1的子项目为：11,22,33,44
在只选择其中任意子项目（非全选）时，保存的数据为：1,22,33
下次编辑时会将所有的项目全部选中（包括上级）

### 业务代码

```auto
tree.render({
    elem: '#test'
    ,data: 
    ,showCheckbox: true
    ,id: 'id'
});

var checkedData = tree.getChecked('id');
var nodeIds = new Array();
nodeIds = getCheckedId(checkedData);

function getCheckedId(data) {
    var id = "";
    $.each(data, function (index, item) {
        if (id != "") {
            id = id + "$" + item.id;
        } else {
            id = item.id;
        }
        if (item.children != null) {
            var i = getCheckedId(item.children);
            if (i != "") {
                id = id + "$" + i;
            }
        }
    });
    return id;
}
```

### 浏览器

Google Chrome 126.0.6478.182

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by fmamcn** [comment]
https://stackblitz.com/edit/stackblitz-starters-xaazpv?file=index.html

**Comment by Sight-wcg** [comment]
我误以为可能是 checkbox 相关改动引起的未知问题，从演示来看，似乎是和半选相关的问题。目前不支持半选，layui v2 版本 tree 暂无调整计划。
如果是其他问题，请详细描述一下重现步骤。

**Comment by fmamcn** [comment]
是半选问题，V2暂无调整计划，了解了

**Comment by Sight-wcg** [comment]
建议用 zTree 等第三方组件替代。
