### ISSUE TITLE
静态表格能不能也加个鼠标经过换色？

### ISSUE THREAD

**Issue by hulang** [layui/layui#2120]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.14

### 问题描述

RT，我实在不想加到我的样式里面重定义。。。

### 业务代码

```auto
希望官方加上。。。
```

### 浏览器

最新Edge

### 演示地址

https://layui.dev/docs/2/table/#demo-static

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
静态表格是特意去除了鼠标经过背景色，若需要建议在业务样式表中重定义，一两行样式。

**Comment by hulang** [comment]
@sentsim 作者大佬，主要是公司项目30多个。。
