### ISSUE TITLE
通过动态数据初始化表单组件内容

### ISSUE THREAD

**Issue by fangjunai** [layui/layui#2122]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.14

### 问题描述

```
比如数据为:  [{"0":"手机"},{"1":"家具"},{"2":"电器"},{"3":"食品"}]   动态初始化生成(表单->选择框组件): 

<select name="interest" lay-filter="aihao">
        <option value="0">手机</option>
        <option value="1">家具</option>
        <option value="2">电器</option>
        <option value="3">食品</option>
</select>
```

当然也可以初始化: 复选框,单选框等组件.

### 业务代码

```auto
<select name="interest" lay-filter="aihao"></select>
动态生成:
<select name="interest" lay-filter="aihao">
        <option value="0">手机</option>
        <option value="1">家具</option>
        <option value="2">电器</option>
        <option value="3">食品</option>
</select>
```

### 浏览器

Firefox

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可尝试用 laytpl 自主实现：https://layui.dev/docs/2/laytpl/

**Comment by fangjunai** [comment]
如果能将:  
选择框 Select
复选框 Checkbox
单选框 Radio
等常用组件写成交互组件那最好. 谢谢.

**Comment by hulang** [comment]
@fangjunai laytpl解决一切
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TEST</title>
  <link href="../dist/css/layui.css" rel="stylesheet">
</head>

<body>
<form class="layui-form form-container" action="" method="post" lay-filter="form-val-filter">
方式1
<div id="view1"></div>
<hr>
方式2
<div id="view2"></div>
</form>
<script type="text/html" id="orderNo1">
  {{#  var arrInterest = [{"id":"1", "name":"手机"},{"id":"2", "name":"家具"},{"id":"3", "name":"电器"},{"id":"4", "name":"食品"}]; }}
  <div>
    <select name="interest">
      {{#  layui.each(arrInterest, function(i, v){ }}
	  {{#  console.log(v); }}
      <option value="{{ v['id'] }}"{{ v['id'] == d['id'] ? ' selected="selected"' : '' }}>{{ v['name'] }}</option>
      {{#  }); }}
    </select>
  </div>
</script>
<script type="text/html" id="orderNo2">
  {{#  var arrInterest = [{"id":"1", "name":"手机", "selected":"0"},{"id":"2", "name":"家具", "selected":"1"},{"id":"3", "name":"电器", "selected":"0"},{"id":"4", "name":"食品", "selected":"0"}]; }}
  <div>
    <select name="interest">
      {{#  layui.each(arrInterest, function(i, v){ }}
	  {{#  console.log(v); }}
      <option value="{{ v['id'] }}"{{ v['selected'] == 1 ? ' selected="selected"' : '' }}>{{ v['name'] }}</option>
      {{#  }); }}
    </select>
  </div>
</script>
<script src="../dist/layui.js"></script>
<script src="../jquery.js"></script>
<script>
layui.use(function() {
    var laytpl = layui.laytpl;
    var form = layui.form;
    // 方式1
    // 渲染
    var data = {
        id: '3',
        name: '电器'
    };
    // 获取模板字符
    var getTpl1 = $('#orderNo1').html();
    // 视图对象
    var htmlView1 = $('#view1');
    // 渲染并输出结果
    laytpl(getTpl1).render(data, function(str) {
        htmlView1.html(str);
    });
    // 方式2
    // 渲染
    var dt = {};
    // 获取模板字符
    var getTpl2 = $('#orderNo2').html();
    // 视图对象
    var htmlView2 = $('#view2');
    // 渲染并输出结果
    laytpl(getTpl2).render(dt, function(str) {
        htmlView2.html(str);
    });
    form.render();
});
</script>
</body>
</html>

```

**Comment by fangjunai** [comment]
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta charset="utf-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1">
>   <title>TEST</title>
>   <link href="../dist/css/layui.css" rel="stylesheet">
> </head>
> 
> <body>
> <form class="layui-form form-container" action="" method="post" lay-filter="form-val-filter">
> 方式1
> <div id="view1"></div>
> <hr>
> 方式2
> <div id="view2"></div>
> </form>
> <script type="text/html" id="orderNo1">
>   {{#  var arrInterest = [{"id":"1", "name":"手机"},{"id":"2", "name":"家具"},{"id":"3", "name":"电器"},{"id":"4", "name":"食品"}]; }}
>   <div>
>     <select name="interest">
>       {{#  layui.each(arrInterest, function(i, v){ }}
> 	  {{#  console.log(v); }}
>       <option value="{{ v['id'] }}"{{ v['id'] == d['id'] ? ' selected="selected"' : '' }}>{{ v['name'] }}</option>
>       {{#  }); }}
>     </select>
>   </div>
> </script>
> <script type="text/html" id="orderNo2">
>   {{#  var arrInterest = [{"id":"1", "name":"手机", "selected":"0"},{"id":"2", "name":"家具", "selected":"1"},{"id":"3", "name":"电器", "selected":"0"},{"id":"4", "name":"食品", "selected":"0"}]; }}
>   <div>
>     <select name="interest">
>       {{#  layui.each(arrInterest, function(i, v){ }}
> 	  {{#  console.log(v); }}
>       <option value="{{ v['id'] }}"{{ v['selected'] == 1 ? ' selected="selected"' : '' }}>{{ v['name'] }}</option>
>       {{#  }); }}
>     </select>
>   </div>
> </script>
> <script src="../dist/layui.js"></script>
> <script src="../jquery.js"></script>
> <script>
> layui.use(function() {
>     var laytpl = layui.laytpl;
>     var form = layui.form;
>     // 方式1
>     // 渲染
>     var data = {
>         id: '3',
>         name: '电器'
>     };
>     // 获取模板字符
>     var getTpl1 = $('#orderNo1').html();
>     // 视图对象
>     var htmlView1 = $('#view1');
>     // 渲染并输出结果
>     laytpl(getTpl1).render(data, function(str) {
>         htmlView1.html(str);
>     });
>     // 方式2
>     // 渲染
>     var dt = {};
>     // 获取模板字符
>     var getTpl2 = $('#orderNo2').html();
>     // 视图对象
>     var htmlView2 = $('#view2');
>     // 渲染并输出结果
>     laytpl(getTpl2).render(dt, function(str) {
>         htmlView2.html(str);
>     });
>     form.render();
> });
> </script>
> </body>
> </html>
> ```

谢谢  hulang 的解决办法.

但如果作者能将组件进一步封装成类似:  评分组件 rate 那种会更方便使用.
