### ISSUE TITLE
layui的select组件的选项的前面的空白为什么给过滤了

### ISSUE THREAD

**Issue by netmou** [layui/layui#2130]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

select 选项前面的空白字符被过滤了

### 业务代码

```auto
<div class="layui-form-item">
            <label class="layui-form-label required">上级部门</label>
            <div class="layui-input-block">
                <select name="pid" lay-search>
                    {foreach $parentList as $vo}
                        <option value="{$vo.id}" >{$vo.title|raw}</option>
                    {/foreach}
                </select>
            </div>
        </div>
```

### 浏览器

128

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
```html
<option value="BBB">&nbsp;选项B</option>
```
