### ISSUE TITLE
炫酷图表库及高性能表格库看看是否有需求可以合作接入呢？推荐VisActor可视化开源库

### ISSUE THREAD

**Issue by fangsmile** [layui/layui#2136]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

.

### 问题描述

https://visactor.io/ 这是VisActor的官网，开源的VChart会让layui能力更强大，表格库VTable不仅性能优秀还有多种可视化形态

### 业务代码

```auto
.
```

### 浏览器

.

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
的确很酷，体验中…

**Comment by LSL1618** [comment]
浏览了一下还不错，版本号比较低，应该是面世不太久。目前图表库习惯用apache的echarts(原先是百度的)，表格库习惯用el-table、vxe-table、layui-table。

**Comment by sentsim** [comment]
@LSL1618 不妨也试试 AntV

**Comment by fangsmile** [comment]
> 面世不太久。目前图表库习惯用apache的echarts(原先是百度的)

字节开源出来的。内部的各个产品已经使用了四年了。有专门团队在维护升级功能

**Comment by LSL1618** [comment]
这么说，AntV是阿里系的，VChart是字节系的，echarts可以看成是百度系的，都贡献出了好产品！
