### ISSUE TITLE
轮播文字诡异的出现圆圈圈进度条

### ISSUE THREAD

**Issue by zengbiao** [layui/layui#2137]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

不知道为什么carousel中间出现了圆形进度条，而且没有动

### 业务代码

```auto
html代码如下
    <div class="layui-col-md2 layui-form" >
        <div class="layui-carousel" id="my_tips"  style="background-color: transparent;">
            <div carousel-item id="my_tips_in">
            </div>
        </div>
    </div>
js动态添加文本:
        let cartTextDiv = $('<div></div>');
        let carTextSpan = $('<span></span>');
        carTextSpan.addClass('layui-badge')
        carTextSpan.addClass('layui-bg-green')
        carTextSpan.css({top: '40%',position: 'absolute'})
        carTextSpan.text(carTextLst[i]);
        cartTextDiv.append(carTextSpan);
        cartTextDiv.css({backgroundColor:'transparent',position:'relative'})
        $('#my_tips div[carousel-item]').append(cartTextDiv)
```

### 截图补充

![Snipaste_2024-07-27_14-33-19](https://github.com/user-attachments/assets/a238bf0d-a617-4e32-bb3f-f19c22cd9e75)

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://gitee.com/layui/layui/issues/I8QOJM

**Comment by zengbiao** [comment]
谢谢，css添加.layui-carousel > [carousel-item]:before{content:none; }就可以了
