### ISSUE TITLE
table 有不有方法 调用列统计更新

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2139]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

V2.9.14

### 问题描述

table 从url 获取数据, 编辑单元格 后 更新统计列 table.reloadData 总是发送请求,刚更新好的单元格又被URL的代替,
只有用 data 才能如图.
table 编辑单元格 后 更新统计列 #2131

**# 包括操作删除了行,统计也不会更新**

### 业务代码

```auto
table.render({
	  elem: '#table',
          id: 'table',
	  url: '/Buy',
	  method:'post',




	// 更新当前缓存数据
	  var update = {};
	  update[field] = value;
	  obj.update(update, true); // 参数 true 为 v2.7 新增功能，即同步更新其他包含自定义模板并可能存在关联的列视图
	  table.reloadData('table', {
		// // scrollPos: 'fixed'  // 保持滚动条位置不变 - v2.7.3 新增
	  });
```

 // 单元格工具事件
  table.on('tool(table)', function(obj){
    var data = obj.data; // 得到当前行数据
    var dataCache = obj.dataCache; // 得到当前行缓存数据，包含特定字段 --- 2.8.8+
    var index = obj.index; // 得到当前行索引
    var layEvent = obj.event; // 获得元素对应的 lay-event 属性值
    var tr = obj.tr; // 得到当前行 <tr> 元素的 jQuery 对象
    var options = obj.config; // 获取当前表格基础属性配置项
    var col = obj.getCol(); // 得到当前列的表头配置属性 -- v2.8.3 新增
    // console.log(obj); // 查看对象所有成员

	if(layEvent === 'del') { //删除
	  layer.confirm('确定删除吗？', function (index) {
		obj.del(); // 删除对应行（tr）的 DOM 结构，并更新缓存
		layer.close(index);
		// 向后端发送删除请求，执行完毕后，可通过 reloadData 方法完成数据重载
		/*
		table.reloadData(id, {
		  scrollPos: 'fixed'  // 保持滚动条位置不变 - v2.7.3 新增
		});
		*/
	  });
	}
  });

### 截图补充

https://private-user-images.githubusercontent.com/54925928/351800157-6bddfee7-40cd-488b-83de-f80f2e863024.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTcwMjksIm5iZiI6MTcyMjA5NjcyOSwicGF0aCI6Ii81NDkyNTkyOC8zNTE4MDAxNTctNmJkZGZlZTctNDBjZC00ODhiLTgzZGUtZjgwZjJlODYzMDI0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE2MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYjM0NjdmYjVlNjk4Yzk4ZTkzMGNhZWI0MmViMTJmNWUyN2M2NDM5OTU2NzZjZDEyOTQxNzIyYjk0YTE1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TSUHXU_3d3nOZ3IOkGrG-mFKbMaF-26xE7Mj780pt2I

### 浏览器

A

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
`table.reloadData()` 不是静态重载，它本身就是请求后端接口进行数据更新的。
如果你需要的是静态更新，可以尝试用 `table.renderData()` 方法。

https://layui.dev/docs/2/table/#table.renderData

**Comment by hjingsuper** [comment]
@sentsim 如果是编辑模式下，需要实时更新合计需要怎么处理呢

这是我的table设置
基础属性设置`data: [],totalRow: true`
表头属性设置`totalRow: '合计：{{= d.TOTAL_NUMS }}'`

> 1.现在是这么处理合计的先更新行再数据重载。感觉会多次一举
 能不能`obj.update(data, true);`方法一并更新合计行呢
``` 
obj.update(data, true);  
table.reloadData('MianTable'); 
```  

> 2.然后，测试`obj.update(data, true); table.renderData()`方法似乎不会更新合计行

**Comment by aimu2000** [comment]
https://github.com/layui/layui/issues/2131

data: []

编辑单元格可以更新,url　获取来的数据合计就有问题　#2131 里面有 gif

**Comment by aimu2000** [comment]
> `table.reloadData()` 不是静态重载，它本身就是请求后端接口进行数据更新的。 如果你需要的是静态更新，可以尝试用 `table.renderData()` 方法。
> 
> https://layui.dev/docs/2/table/#table.renderData

data[] 数据 可以用 table.reloadData

**Comment by Sight-wcg** [comment]
> @sentsim 如果是编辑模式下，需要实时更新合计需要怎么处理呢
> 
> 这是我的table设置 基础属性设置`data: [],totalRow: true` 表头属性设置`totalRow: '合计：{{= d.TOTAL_NUMS }}'`
> 
> > 1.现在是这么处理合计的先更新行再数据重载。感觉会多次一举
> > 能不能`obj.update(data, true);`方法一并更新合计行呢
> 
> ```
> obj.update(data, true);  
> table.reloadData('MianTable'); 
> ```
> 
> > 2.然后，测试`obj.update(data, true); table.renderData()`方法似乎不会更新合计行

参考 https://github.com/layui/layui/issues/1801#issuecomment-2277224140
