### ISSUE TITLE
与 VUE 配合使用时，select很不好用，还是要用dom的方式插入option

### ISSUE THREAD

**Issue by GlenLee** [layui/layui#214]
是否可以直接支持vue数据改变时自动渲染layui包装过的select呢？是否有更好的解决办法？

**Comment by remember2011** [comment]
我也遇到这个问题

**Comment by tercel2018** [comment]
花了一天的时间解决了此问题

使用v-modeo 
设置元素，
刷新元素；

**Comment by tercel2018** [comment]
Duplicate of #
https://zhuanlan.zhihu.com/p/60978215

**Comment by TerryLam2010** [comment]
我是自己写的组件。解决的
