### ISSUE TITLE
官网部分示例仍在使用staticfile.net CDN

### ISSUE THREAD

**Issue by xmcp** [layui/layui#2140]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

layui官网文档的多处示例（包括但不限于 https://layui.dev/docs/2/menu/ ）使用了 staticfile.net 作为 CDN：
![image](https://github.com/user-attachments/assets/af0058d1-8962-42e8-9148-e03b52698ad5)

此 CDN 在一个月之前 [被发现存在注入恶意代码的行为](https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/)，目前此域名[已经被 uBlock Origin 过滤](https://github.com/uBlockOrigin/uAssets/pull/24285)。

因此官网相关示例在开启了 adblocker 后无法加载，显示为白屏或排版错误：

![image](https://github.com/user-attachments/assets/d95689ed-a469-419a-bf0f-c981c6029542)
![image](https://github.com/user-attachments/assets/0f7cbd71-4c34-4105-b2a5-423fdfc5ebe3)

### 业务代码

```auto
无
```

### 浏览器

127.0.6533.73 (正式版本) （64 位）

### 演示地址

https://layui.dev/docs/2/menu/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
据我所知， staticfile.net 和 cdn.bootcdn.net 只是部分资源受到影响（由于维护者在 .env 文件中提交了 cloudflare 的密钥），但当前新提交的资源并没有任何问题， **uBlock 这种直接屏蔽整个域名的行为是极不负责的**。
建议更换 AdBlock 插件，或将此网站上暂停 uBlock 。

**Comment by sentsim** [comment]
据我所知， staticfile.net 和 bootcdn.net 并不是所有静态资源都被恶意注入，uBlock 直接屏蔽 staticfile.net 的域名稍显牵强。建议暂时更换别的 AdBlock 插件试试，或将此网站上暂停 uBlock 。

该影响我们也会持续观察，如有必要，会完全切换到 unpkg。

**Comment by xmcp** [comment]
layui好像不同样例用的CDN不完全一样。大多数样例（和官网本身）用的是 res.sentcss.com。是否考虑把所有样例都统一成这个CDN？

**Comment by sentsim** [comment]
使用不同的 CDN 是为了降低公共节点不稳定性的影响，如果使用统一的 CDN，一旦该 CDN 出现网络波动，那么全站都会受到影响。而分散 CDN，则只会影响局部，且可以随时动态切换。

**Comment by sentsim** [comment]
为了让使用 uBlock 的小伙伴避免因拦截 staticfile CDN 而无法正常预览示例的影响，**已将 staticfile.net 更换为 CDNJS**。

同时也弱弱地希望大家尽量不要在官网使用广告拦截插件，官网的广告数量并不多，且遵循「可接受广告」标准，并不会对文档的阅读带来任何干扰。 你看，都没人投广告了 😂

**Comment by tjsky** [comment]
> 据我所知， staticfile.net 和 bootcdn.net 并不是所有静态资源都被恶意注入，uBlock 直接屏蔽 staticfile.net 的域名稍显牵强。建议暂时更换别的 AdBlock 插件试试，或在此网站上暂停 uBlock 。
> 
> 该影响我们也会持续观察，如有必要，会将示例完全切换到 unpkg。

因为并不是全盘注入，而是只在欧洲杯举行期间的时段，对「移动端+第一次访问+非后台管理页+无站点统计代码页面」执行随机注入混淆恶意代码，将访问者跳转到博彩站点去，所以表现上就是“并不是所有静态资源都被恶意注入”。实际从泄露的CF绑定可以看出，黑产已经为此提前布局了1年多了。
