### ISSUE TITLE
dropdown trigger 

### ISSUE THREAD

**Issue by liangchuying** [layui/layui#2149]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

最新

### 问题描述

我想在 dropdown 禁止掉trigger 默认的触发功能 手动去触发 dropdown.open，这样可以在方便在其他元素/子上去操作，我尝试了设置trigger: 'none' 是可以禁止，但是文档上没有这个的介绍，我不知道我设置的是否有问题

### 业务代码

```auto
dropdown.render({
                elem: '#firstElement',
                id: 'firstElementId',
                trigger: 'none ',
                data: [{
                    title: 'menu item 1',
                    id: 100
                }, {
                    title: 'menu item 2',
                    id: 101
                }, {
                    title: 'menu item 3',
                    id: 102
                }],
                click: function (obj) {
                    this.elem.find('span').text(obj.title);
                }
            });
```

### 截图补充

1

### 浏览器

Google

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
没有问题

下次记得在 discussions 提问 https://github.com/layui/layui/blob/main/CONTRIBUTING.md
