### ISSUE TITLE
select输入框在table中使用lay-append-to属性的问题

### ISSUE THREAD

**Issue by kun661** [layui/layui#2152]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

因项目需要，table表格需要放到一个3层的div中，div也分别设置了样式。
在table中使用select新增加的“lay-append-to”属性时，出现select下拉框显示混乱的情况：当弹出select时，如果滚动表格，该select仍然显示在原处，并不能跟随数据行滚动。
以下业务代码可以直接放到表格的“实现多样化编辑”中测试，将原来的table行替换即可看到效果。

### 业务代码

```auto
<div style="position: absolute;top: 0;left: 0;right: 0;bottom: 0;overflow: hidden;">
<div style="position: absolute;  top: 20px;  left: 20px;  z-index: auto;  overflow: auto;  width:100%;  height:100%">
<div style="position: absolute;left: 0;right: 0;top: 80px;bottom: 0;overflow:auto;">
<table class="layui-hide" id="ID-table-demo-editmodes"></table>
</div>
</div>
</div>
```

### 浏览器

Edge版本 127.0.2651.86 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
参考以下两种方案
- 打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时移除面板，参考下面的代码自行修改
-  打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时更新面板位置
  - 参考 PR 评论中的解决方案 https://github.com/layui/layui/pull/1926#issuecomment-2128271994
  - 如果不想用 popperjs，将下面的代码放到你的公共模块并在 layui.js 之后引入
 ```js
// 可能需要额外处理 dropdown 组件, 点击面板外部时忽略 triggerEl，zIndex 相关问题自行处理
lay._originalPositionFn = lay.position;
lay.position = function (triggerEl, contentEl, options) {
  lay._originalPositionFn(triggerEl, contentEl, options);
  if (triggerEl.__has_scroll_event__) return;

  triggerEl.__has_scroll_event__ = true;

  var scrollElements = getScrollElements(triggerEl);
  var scrollHandler = function () {
    lay._originalPositionFn(triggerEl, contentEl, options);
  }

  $.each(scrollElements, function (_, element) {
    element.addEventListener('scroll', scrollHandler, { passive: true });
  })

  var stop = lay.onClickOutside(contentEl, function () {
    triggerEl.__has_scroll_event__ = false;

    $.each(scrollElements, function (_, element) {
      element.removeEventListener('scroll', scrollHandler, { passive: true });
    })
    stop();
  });

  function isScrollElement(element) {
    return (
      element.scrollHeight > element.offsetHeight ||
      element.scrollWidth > element.offsetWidth
    );
  };

  function getScrollElements(container) {
    var scrollElements = [];
    var element = container;
    while (element && element !== document.documentElement) {
      if (isScrollElement(element)) {
        scrollElements.push(element);
      }
      element = element.parentElement ? element.parentElement : undefined;
    }
    scrollElements.push(window)
    return scrollElements;
  };
}
```

**Comment by kun661** [comment]
> 参考以下两种方案
> 
> * 打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时移除面板，参考下面的代码自行修改
> * 打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时更新面板位置
>   
>   * 参考 PR 评论中的解决方案 [feat(form-select): 新增 `lay-append-to` 属性 #1926 (comment)](https://github.com/layui/layui/pull/1926#issuecomment-2128271994)
>   * 如果不想用 popperjs，将下面的代码放到你的公共模块并在 layui.js 之后引入
> 
> ```js
> // 可能需要额外处理 dropdown 组件, 点击面板外部时忽略 triggerEl，zIndex 相关问题自行处理
> lay._originalPositionFn = lay.position;
> lay.position = function (triggerEl, contentEl, options) {
>  lay._originalPositionFn(triggerEl, contentEl, options);
>  if (triggerEl.__has_scroll_event__) return;
> 
>  triggerEl.__has_scroll_event__ = true;
> 
>  var scrollElements = getScrollElements(triggerEl);
>  var scrollHandler = function () {
>    lay._originalPositionFn(triggerEl, contentEl, options);
>  }
> 
>  $.each(scrollElements, function (_, element) {
>    element.addEventListener('scroll', scrollHandler, { passive: true });
>  })
> 
>  var stop = lay.onClickOutside(contentEl, function () {
>    triggerEl.__has_scroll_event__ = false;
> 
>    $.each(scrollElements, function (_, element) {
>      element.removeEventListener('scroll', scrollHandler, { passive: true });
>    })
>    scrollElements = null;
>    stop();
>  });
> 
>  function isScrollElement(element) {
>    return (
>      element.scrollHeight > element.offsetHeight ||
>      element.scrollWidth > element.offsetWidth
>    );
>  };
> 
>  function getScrollElements(container) {
>    var scrollElements = [];
>    var element = container;
>    while (element && element !== document.documentElement) {
>      if (isScrollElement(element)) {
>        scrollElements.push(element);
>      }
>      element = element.parentElement ? element.parentElement : undefined;
>    }
>    scrollElements.push(window)
>    return scrollElements;
>  };
> }
> ```

我曾尝试用这个方案解决table右键菜单的错位问题，由于右键时得到的triggerEl为undefined，只能通过event.target给triggerEl重新赋值，但这样得到的触发元素，仍然没办法让dropdown吸附到数据行上，即使用closest使用该target的tr、table或上级可滚动的div，仍然无效。
如果用popper，就要多加一个依赖。即便如此，暂时也没找到可以让dropdown吸附到数据行上的处理方法。期待官方给出更详细一点的解决方案。感谢！

**Comment by Sight-wcg** [comment]
> > 参考以下两种方案
> > 
> > * 打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时移除面板，参考下面的代码自行修改
> > * 打开 select 面板时，收集 select 元素的所有滚动父元素，监听其滚动事件，滚动时更新面板位置
> >   
> >   * 参考 PR 评论中的解决方案 [feat(form-select): 新增 `lay-append-to` 属性 #1926 (comment)](https://github.com/layui/layui/pull/1926#issuecomment-2128271994)
> >   * 如果不想用 popperjs，将下面的代码放到你的公共模块并在 layui.js 之后引入
> > 
> > ```js
> > // 可能需要额外处理 dropdown 组件, 点击面板外部时忽略 triggerEl，zIndex 相关问题自行处理
> > lay._originalPositionFn = lay.position;
> > lay.position = function (triggerEl, contentEl, options) {
> >  lay._originalPositionFn(triggerEl, contentEl, options);
> >  if (triggerEl.__has_scroll_event__) return;
> > 
> >  triggerEl.__has_scroll_event__ = true;
> > 
> >  var scrollElements = getScrollElements(triggerEl);
> >  var scrollHandler = function () {
> >    lay._originalPositionFn(triggerEl, contentEl, options);
> >  }
> > 
> >  $.each(scrollElements, function (_, element) {
> >    element.addEventListener('scroll', scrollHandler, { passive: true });
> >  })
> > 
> >  var stop = lay.onClickOutside(contentEl, function () {
> >    triggerEl.__has_scroll_event__ = false;
> > 
> >    $.each(scrollElements, function (_, element) {
> >      element.removeEventListener('scroll', scrollHandler, { passive: true });
> >    })
> >    scrollElements = null;
> >    stop();
> >  });
> > 
> >  function isScrollElement(element) {
> >    return (
> >      element.scrollHeight > element.offsetHeight ||
> >      element.scrollWidth > element.offsetWidth
> >    );
> >  };
> > 
> >  function getScrollElements(container) {
> >    var scrollElements = [];
> >    var element = container;
> >    while (element && element !== document.documentElement) {
> >      if (isScrollElement(element)) {
> >        scrollElements.push(element);
> >      }
> >      element = element.parentElement ? element.parentElement : undefined;
> >    }
> >    scrollElements.push(window)
> >    return scrollElements;
> >  };
> > }
> > ```
> 
> 我曾尝试用这个方案解决table右键菜单的错位问题，由于右键时得到的triggerEl为undefined，只能通过event.target给triggerEl重新赋值，但这样得到的触发元素，仍然没办法让dropdown吸附到数据行上，即使用closest使用该target的tr、table或上级可滚动的div，仍然无效。 如果用popper，就要多加一个依赖。即便如此，暂时也没找到可以让dropdown吸附到数据行上的处理方法。期待官方给出更详细一点的解决方案。感谢！

triggerEl 取自 dropdown.render 的 elem 选项，理论上不会为 undefined。

**Comment by kun661** [comment]
> triggerEl 取自 dropdown.render 的 elem 选项，理论上不会为 undefined。

我用console确定过的，右键菜单中的triggerEl真的就是undefined。

**Comment by kun661** [comment]
> // 可能需要额外处理 dropdown 组件, 点击面板外部时忽略 triggerEl，zIndex 相关问题自行处理
> lay._originalPositionFn = lay.position;
> lay.position = function (triggerEl, contentEl, options) {
>  lay._originalPositionFn(triggerEl, contentEl, options);
>  if (triggerEl.__has_scroll_event__) return;

还是想尝试使用此方案解决table中的右键菜单无法吸附到数据行上的问题。为避免错误，我在这段代码中插入了一行：
lay._originalPositionFn = lay.position; 
lay.position = function (triggerEl, contentEl, options) { 
	lay._originalPositionFn(triggerEl, contentEl, options);
	**if(options.clickType === 'right') triggerEl = event.target;**
	if (triggerEl.__has_scroll_event__) return;
        ....

但仍然实现不了吸附效果。想请教下，lay.position在更新弹层面板位置时还要注意什么？是否还需要在options中加入一些其他配置参数？

**Comment by Sight-wcg** [comment]
> > // 可能需要额外处理 dropdown 组件, 点击面板外部时忽略 triggerEl，zIndex 相关问题自行处理
> > lay._originalPositionFn = lay.position;
> > lay.position = function (triggerEl, contentEl, options) {
> > lay._originalPositionFn(triggerEl, contentEl, options);
> > if (triggerEl.**has_scroll_event**) return;
> 
> 还是想尝试使用此方案解决table中的右键菜单无法吸附到数据行上的问题。为避免错误，我在这段代码中插入了一行： lay._originalPositionFn = lay.position; lay.position = function (triggerEl, contentEl, options) { lay._originalPositionFn(triggerEl, contentEl, options); **if(options.clickType === 'right') triggerEl = event.target;** if (triggerEl.**has_scroll_event**) return; ....
> 
> 但仍然实现不了吸附效果。想请教下，lay.position在更新弹层面板位置时还要注意什么？是否还需要在options中加入一些其他配置参数？

为什么呢？您后续能提出的各种问题，popperjs 都能解决，popperjs 方案相比这个方案，除了引入依赖有什么缺点吗？我已经提供了完整的解决方案。

您非要自己写的话，可以参考 https://github.com/layui/layui/issues/2155#issuecomment-2275819530 右键菜单坐标更新方法，
 - 设置一个参照物，参照元素必须是包含初始坐标的 DOM 元素
 - 记录触发右键菜单时的初始坐标和参照元素的相对偏移量
 - 滚动时获取参照元素的位置，通过相对偏移量计算面板的坐标
 - 更新 lay._originalPositionFn(triggerEl, contentEl, options); 第三个参数中 options.e 选项的位置信息为上一步计算的面板坐标（类似 popperjs 中的 virtual element）https://github.com/layui/layui/blob/af792a8452df4e3b0be40ad2760177ce6bbc8369/src/modules/lay.js#L303-L310

有问题或边缘情况您可以参考 popperjs 源码中的解决方案或搜索 [floating-ui](https://github.com/floating-ui/floating-ui) 仓库解决。

**Comment by kun661** [comment]
> 为什么呢？您后续能提出的各种问题，popperjs 都能解决，popperjs 方案相比这个方案，除了引入依赖有什么缺点吗？我已经提供了完整的解决方案。

popper方案确实已经很完美了，这里再次提出此方案，是想彻底搞明白lay.position的用法，想多向您学习一点知识。谢谢啦，我后续先好好消化一下。。
