### ISSUE TITLE
希望table组件能在多样化编辑功能的基础上实现添加新行的功能

### ISSUE THREAD

**Issue by starWillRed** [layui/layui#2153]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.14

### 问题描述

我发现使用table的多样化编辑功能可以大幅提升用户编辑表格的体验和效率，实现所见即所得。
我注意到table的工具条的有一个默认按钮是添加，但没有找到添加新行的功能。我希望点击添加按钮后，会在table的第一行出现一个空白行提供给用户填写，空白行的格式与table.render里面指定的格式一致，然后用户点击提交就可以添加新行，可以给提交指定一个回调函数，由开发者决定是post提交还是其他方式。
希望能够实现这个功能。

### 业务代码

```auto
无。
```

### 浏览器

chrome 109

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
treeTable 有表格行 crud 操作的实现，可以替代 table。

**Comment by hjingsuper** [comment]
推荐参考 #1947

**Comment by starWillRed** [comment]
> treeTable 有表格行 crud 操作的实现，可以替代 table。

我使用了treeTable，但是添加节点后无法直接在表格中编辑新添加的行，会提示无法找到table的id，而我编辑原来的行则没报错
