### ISSUE TITLE
 弹窗的叉老是变成奇怪的符号

### ISSUE THREAD

**Issue by 2361788963** [layui/layui#2163]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

弹窗的叉老是变成奇怪的符号

### 业务代码

```auto
layer.open({
  type: 1, // page 层类型
  area: ['500px', '300px'],
  title: 'Hello layer',
  shade: 0.6, // 遮罩透明度
  shadeClose: true, // 点击遮罩区域，关闭弹层
  maxmin: true, // 允许全屏最小化
  anim: 0, // 0-6 的动画形式，-1 不开启
  content: '<div style="padding: 32px;">一个普通的页面层，传入了自定义的 HTML</div>'
});
```

### 截图补充

![image](https://github.com/user-attachments/assets/7fa25d69-0787-4280-a391-535bb61c92e0)

### 浏览器

chrome 和 火狐

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
一般网络比较差时会出现这个问题，参考以下方案
1. 如没有特殊需求，优先使用打包后的版本而不是源码版
2. 尝试预加载字体 `<link rel="preload" href="layui/dist/font/iconfont.woff2" as="font" type="font/woff2" crossorigin="anonymous">`
3. 尝试将字体文件转为 base64 内联到 CSS 文件中
