### ISSUE TITLE
有什么办法能让表格的title不出现...，而是自动换行显示？

### ISSUE THREAD

**Issue by beijing-penguin** [layui/layui#2164]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

如下图，内容过长会出现... 但是我的需求是换行
![image](https://github.com/user-attachments/assets/6f8e0603-891d-4cff-866f-9eda1ddc5a61)

### 业务代码

```auto
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>table 自定义样式 - Layui</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//cdnjs.cloudflare.com/ajax/libs/layui/2.9.14/css/layui.css" rel="stylesheet">
  <style>
    /* 自定义样式  */
    .layui-table-testcss .layui-table-header,
    .layui-table-testcss thead tr{background-color: #F8FCF9; color: #16BAAA}
    .layui-form-testcss > div{margin-bottom: 6px;}
  </style>
</head>
<body>
  <div style="padding: 16px;"> 
    <table class="layui-hide" id="ID-table-demo-css"></table>
  </div>
  <script type="text/html" id="ID-table-demo-css-user">
    <ul>
      <li><strong>ID:</strong> {{= d.id }} </li>
      <li><strong>用户:</strong> {{= d.username }} </li>
      <li><strong>性别:</strong> {{= d.sex }} </li>
      <li><strong>城市:</strong> {{= d.city }} </li>
    </ul>
  </script>
  <script type="text/html" id="ID-table-demo-css-tool">
    <div class="layui-form layui-form-testcss">
      <div class="layui-input-wrap">
        <input name="AAA" value="{{= d.AAA || '' }}" lay-affix="clear" placeholder="表单 1" class="layui-input" >
      </div>
      <div class="layui-input-wrap">
        <input name="BBB" value="{{= d.BBB || '' }}" lay-affix="clear" placeholder="表单 2" class="layui-input" >
      </div>
      <div>
        <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="demo-css-submit">确认</button>
      </div>
    </div>
  </script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/layui/2.9.14/layui.js"></script>
  <script>
  layui.use(['table'], function(){
    var table = layui.table;
    var form = layui.form;
    
    // 创建渲染实例
    table.render({
      elem: '#ID-table-demo-css',
      url:'https://unpkg.com/outeres@0.1.3/json/2/table/demo1.json', // 此处为静态模拟数据，实际使用时需换成真实接口
      page: true,
      height: 'full-35',
      lineStyle: 'height: 151px;', // 定义表格的多行样式
      css: [ // 直接给当前表格主容器重置 css 样式
        '.layui-table-page{text-align: center;}' // 让分页栏居中
      ].join(''),
      className: 'layui-table-testcss', // 用于给表格主容器追加 css 类名
      cols: [[
        {field:'username', width:160, title: '用户', templet: '#ID-table-demo-css-user'},
        // 设置单元格样式
        {field:'sign', minWidth:50, title: '签名1111111111111111111111111111111111<br />111111111111111111111111111111111111111', style:'color: #000;height:150px'},
        {width:160, title: '操作', templet: '#ID-table-demo-css-tool'}
      ]]
    });
    // 表单提交
    form.on('submit(demo-css-submit)', function(data){
      var field = data.field; // 获取表单字段值
      // 显示填写结果，仅作演示用
      layer.alert(JSON.stringify(field), {
        title: '当前填写的字段值'
      });
      // 此处可执行 Ajax 等操作
      // …
      return false; // 阻止默认 form 跳转
    });
    
  });
  </script>
</body>
</html>
```

### 浏览器

版本 125.0.6422.113（正式版本） （64 位）

### 演示地址

https://stackblitz.com/edit/f3zmc2?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by lylsaaa** [comment]
.layui-table-cell {height: auto;}
  这样可以临时解决一下，但是title过多出现横向滚动条，并且设置了固定列，固定列的高度会有问题

**Comment by beijing-penguin** [comment]
> .layui-table-cell {height: auto;} 这样可以临时解决一下，但是title过多出现横向滚动条，并且设置了固定列，固定列的高度会有问题

感谢大佬问题得到基本解决！

多出的行向滚动条，能接受的。。
我一共用到2个css参数。但是现在还需要title设置里面必须加速<br>才能换行（有没有不加<br>的办法，自动换行呢？）
表格json设置如下：
{
    field: 'yearBuyRatio',
    minWidth: 90,
    sort: true,
    title: '年<br>购买率'
}
css设置如下：

.layui-table-cell {
    height: auto;
}

.layui-table-header th {
    height: 70px;
}


![image](https://github.com/user-attachments/assets/dce3c1fb-6e83-4eb3-bc7c-cf31268e8795)

**Comment by lylsaaa** [comment]
> > .layui-table-cell {height: auto;} 这样可以临时解决一下，但是title过多出现横向滚动条，并且设置了固定列，固定列的高度会有问题
> 
> 感谢大佬问题得到基本解决！
> 
> 多出的横向滚动条，能接受的。 我一共用到2个css参数。但是现在还需要title设置里面必须加才能换行（有没有不加的办法，自动换行呢？） 表格json设置如下： { field: 'yearBuyRatio', minWidth: 90, sort: true, title: '年购买率' } css设置如下：
> 
> .layui-table-cell { height: auto; }
> 
> //添加这个参数的原因是，我使用了固定列，fixed: 'left'，所以要对齐高度。 .layui-table-header th { height: 70px; }
> 
> ![image](https://private-user-images.githubusercontent.com/10703753/357676852-dce3c1fb-6e83-4eb3-bc7c-cf31268e8795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTI1MzcsIm5iZiI6MTcyMzYxMjIzNywicGF0aCI6Ii8xMDcwMzc1My8zNTc2NzY4NTItZGNlM2MxZmItNmU4My00ZWIzLWJjN2MtY2YzMTI2OGU4Nzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA1MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmZlOWNhYmM1OTI1ZDZjZWFmZjlhZjk5OWQxNTE3MTUzMGY0MjZhNDY0ZDJmYmVlNWI4MGRhY2Q5Mzg1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXfSWWpFhgFU-ChNh4AI0_iuLTNMs6JmnFzLzpb7vXs)

貌似没有别的方法了

**Comment by Sight-wcg** [comment]
将这段代码，添加到表格的 css 选项中

```css
'.layui-table-header .layui-table-cell{height: auto;white-space: normal;text-overflow: clip;word-wrap: break-word;overflow-wrap: break-word;}'
```
