### ISSUE TITLE
官方教程-登录模板 2.8+有个奇怪的问题

### ISSUE THREAD

**Issue by tonycheungzyz** [layui/layui#2166]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

![图片](https://github.com/user-attachments/assets/752c9b4f-f35d-4cb1-8413-71f1b7a471f7)
这段代码直接使用是正常的，但是只要把css路径换成本地，则不正常，图标会在文本框外面
我开始以为是版本问题，于是将远程地址的css下载到本地结果是一样的。所以就不懂了，业务代码不用看了是直接从教程里复制的

更新，问题解决了，由于我低级失误，没有将版本更新成功造成的，sorry。
感谢作者回复，谢谢！
### 业务代码

```auto

```

### 浏览器

什么浏览器都一样

### 演示地址

http://ks.163k.top:88/page/login.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
<img width="431" alt="111" src="https://github.com/user-attachments/assets/2d02c28d-9039-4e32-99f3-8ca1230873b9">
你本地文件是旧版的，根本没有前缀的样式，看js是2.7.3的，所以会样式错乱

**Comment by tonycheungzyz** [comment]
感谢回复，我的问题解决，原因是我用的是火狐浏览器，即使原文件更新，必须Ctrl+f5强制刷新才能更新js和css等外挂文件，普通刷新没用。导致一直看不到效果，然后我提供的演示地址忘记换版本了。本帖没啥营养，帮忙删了吧
