### ISSUE TITLE
2.9.15版的表格打印按钮无效呢

### ISSUE THREAD

**Issue by jinyanzeng** [layui/layui#2174]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.15

### 问题描述

2.9.15版的表格打印按钮无效呢，google浏览器可以，360急速浏览器无效

### 业务代码

```auto
2.9.15版的表格打印按钮无效呢，google浏览器可以，360急速浏览器无效
```

### 浏览器

360急速浏览器

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
感谢您的反馈，需要提供更多信息以协助调查

1. 360 极速浏览器的版本是多少，旧版能否重现这个问题
2. 操作系统版本，其他系统中能否重现这个问题
3. layui 表格打印相关的代码已经几十个版本没有修改过了，您发现从哪个版本开始 360 极速浏览器中表格打印按钮无效?
4. 请提供一段 GIF 或视频

**Comment by sentsim** [comment]
我猜是 360 急速浏览器版本过低。

**Comment by jinyanzeng** [comment]
![image](https://github.com/user-attachments/assets/45efdf3e-f139-400f-aa1e-08b61afd6c32)
![1724023838799](https://github.com/user-attachments/assets/2a50894c-588d-4d39-a3ab-7b3add7a8763)

**Comment by Sight-wcg** [comment]
如果 360 极速浏览器最新版上面仍有问题而 Chrome 和 Firefox 上都没问题，那么大概率是 360 极速浏览器的问题，建议前往 360 论坛寻求 360 极速浏览器团队的帮助。

**Comment by Sight-wcg** [comment]
> ![image](https://private-user-images.githubusercontent.com/61130259/358942107-45efdf3e-f139-400f-aa1e-08b61afd6c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzU2NzMsIm5iZiI6MTcyNDAzNTM3MywicGF0aCI6Ii82MTEzMDI1OS8zNTg5NDIxMDctNDVlZmRmM2UtZjEzOS00MDBmLWFhMWUtMDhiNjFhZmQ2YzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAyNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjRmNmRmNjU3YWZkMjM1YWZiYTJmZDAyYjcyYzNhYzgwN2JkNGViNDAxM2YxMzU5ODhlN2JhNmNjOTVkZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OiQTzZMlj8_XYaXJX09JvvksJOh69ErEmP7j9HFxH6E) ![1724023838799](https://private-user-images.githubusercontent.com/61130259/358942127-2a50894c-588d-4d39-a3ab-7b3add7a8763.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzU2NzMsIm5iZiI6MTcyNDAzNTM3MywicGF0aCI6Ii82MTEzMDI1OS8zNTg5NDIxMjctMmE1MDg5NGMtNTg4ZC00ZDM5LWEzYWItN2IzYWRkN2E4NzYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAyNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTc3ZjgxODllMmFiYWFkOWI2ZTUzY2I3ODA5MGQxOTRmMjFiNjgyZjRkNjYyMTI0YTQxNGI2YzMwZGY3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dUS2r0PCPRThr7VN5S65Zem0wwQoyazkbNmwqKkrgP4)

如果 360 极速浏览器最新版上面仍有问题而 Chrome 和 Firefox 上都没问题，那么大概率是 360 极速浏览器的问题，建议前往 360 论坛寻求 360 极速浏览器团队的帮助。

**Comment by Sight-wcg** [comment]
因为缺乏足够的信息而关闭
