### ISSUE TITLE
希望实现通过点击按钮实现编辑Table，并点击按钮提交

### ISSUE THREAD

**Issue by 2019211001001006-WangWei** [layui/layui#2177]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.15

### 问题描述

现有版本只能通过点击行进行编辑，希望能够点击按钮再进行编辑，然后点击按钮提交修改

### 业务代码

```auto
// 创建表格实例
  table.render({
    elem: '#ID-table-demo-editable',
    url: '/static/json/2/table/edit.json', // 此处为静态模拟数据，实际使用时需换成真实接口
    page: true,
    //,editTrigger: 'dblclick' // 触发编辑的事件类型（默认 click ）。 v2.7.0 新增，之前版本固定为单击触发
    css: [
      // 对开启了编辑的单元格追加样式
      '.layui-table-view td[data-edit]{color: #16B777;}'
    ].join(''),
    cols: [[
      {checkbox: true, fixed: true},
      {field:'id', title: 'ID', width:80, sort: true, fixed: true},
      {field:'username', title: '用户名', width:80, edit: editable},
      {field:'sex', title: '性别', width:80, sort: true, edit: editable},
      {field:'city', title: '城市', width:80, edit: editable},
      {field:'sign', title: '签名', edit: editable},
      {field:'experience', title: '积分', sort: true, width:80, edit: editable}
    ]],
    height: 310
  });
```

### 浏览器

Microsoft Edge 127.0.2651.105

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by hulang** [comment]
你这种需要，我个人做法是，使用：`layer.prompt`方法，点击按钮弹出，编辑后，确定后使用：ajax提交。。

**Comment by 2019211001001006-WangWei** [comment]
> 你这种需要，我个人做法是，使用：`layer.prompt`方法，点击按钮弹出，编辑后，确定后使用：ajax提交。。

我知道可以用弹出层，但是现在有一个需求就是要直接在Table中更改，类似Ant Design中的样式
![擷取](https://github.com/user-attachments/assets/2de03f63-2fad-4523-9650-5024517a4549)

**Comment by Sight-wcg** [comment]
关闭了，因为这不是 BUG
