### ISSUE TITLE
laydate的回车监听会导致页面刷新（触发了表单提交）

### ISSUE THREAD

**Issue by YSB123123123** [layui/layui#2178]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.15

### 问题描述

layer.open打开一个弹窗，里面插入了一个form和一个input，选中input按回车会导致页面刷新

### 业务代码

```auto
lay(document).on('keydown', function(e){
      if(!laydate.thisId) return;
      var that = thisModule.getThis(laydate.thisId);
      if(!that) return;

      // 回车触发确认
      if(that.config.position === 'static') return;
      if(e.keyCode === 13){
        if(lay('#'+ that.elemID)[0] && that.elemID === Class.thisElemDate){
          e.preventDefault();
          lay(that.footer).find(ELEM_CONFIRM)[0].click();
        }
      }
    });
```

### 浏览器

Chrome 127.0.6533.120（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
试试给form表单元素加上onsubmit属性`<form class="layui-form" onsubmit="return false;">`，或者给button按钮加上type属性`<button type="button" class="layui-btn">`。

**Comment by wuyaoqing** [comment]
> 试试给form表单元素加上onsubmit属性`<form class="layui-form" onsubmit="return false;">`，或者给button按钮加上type属性`<button type="button" class="layui-btn">`。

今天也遇到这个问题：layui的form中的控件回车就自动提交，兄弟的这个办法是可以的，给按钮增加点击方法加上form.submit('form1-filter', function(data){})即可
