### ISSUE TITLE
Table组件分页为流加载

### ISSUE THREAD

**Issue by Tiamo-web66** [layui/layui#2179]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.8.18

### 问题描述

后期是否有考虑table组件为流加载形式代替表格分页

### 业务代码

```auto
后期是否有考虑table组件为流加载形式代替表格分页
```

### 浏览器

Chrom

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
你指的是滚动到底部就加载下一页数据，然后追加在上一页数据的底部，是这意思吧。

**Comment by Sight-wcg** [comment]
参考 https://gitee.com/layui/layui/issues/I5LQ2D

**Comment by Tiamo-web66** [comment]
> 你指的是滚动到底部就加载下一页数据，然后追加在上一页数据的底部，是这意思吧。

对的，主要是想使用table一些api方法，分页换成流加载的形式。

**Comment by Tiamo-web66** [comment]
> 参考 https://gitee.com/layui/layui/issues/I5LQ2D
