### ISSUE TITLE
下拉选择框手机端无法点击选中v2.9.15

### ISSUE THREAD

**Issue by 386303180** [layui/layui#2180]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.15

### 问题描述

![image](https://github.com/user-attachments/assets/0ff6203e-7d08-4a78-8fda-1648c2dd76be)
edge 安卓多不行

### 业务代码

```auto
edge 安卓多不行
```

### 截图补充

![image](https://github.com/user-attachments/assets/54462acc-dc74-4288-a933-6ac224a40425)

### 浏览器

edge 安卓多不行

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
测得很及时，修得更及时 👍👍👍
