### ISSUE TITLE
表单规则检查BUG

### ISSUE THREAD

**Issue by cproape** [layui/layui#2182]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.11

### 问题描述

对表单输入框进行格式检查，当输入框内容末尾加入空格时，例如 `"1234      "`,  规则验证函数`function (value, item)` 中`value`不会携带输入末尾的空格，导致无法对输入内容进行异常判断

### 业务代码

```auto
例如官网示例程序
```

### 截图补充

![企业微信截图_20240821134352](https://github.com/user-attachments/assets/eb4ba5ee-78db-428c-996e-ce906b243548)

### 浏览器

任意

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
表单验证通常需要去除首尾空白符。如果需要保留空白符进行验证，可直接在 form submit 事件中处理。

**Comment by cproape** [comment]
> 表单验证通常需要去除首尾空白符。如果需要保留空白符进行验证，可直接在 form submit 事件中处理。

不好意思，我对前端通常的做法不是很清楚(我是做嵌入式开发)，我个人觉得既然是可以自定义验证规则，凡是用户的输入内容，都应该原封不动交给`form.verify(obj)`，而不是框架内部进行一部分过滤(去除首尾空白符)， 而且form submit事件 就是原始值(上述截图)，  总之`form.verify`的值和f`orm submit事件`的值不一样感觉很奇怪，  个人观点，欢迎大佬指正

**Comment by cproape** [comment]
@sentsim 或者是否可以在`form submit事件`  遍历field，去除每个字段首尾空格，这样`form.verify`的值和`form submit`事件的值就一致了，不再需要用户单独的去处理这个问题了

**Comment by sentsim** [comment]
@cproape 

可以通过验证函数的第二个参数得到表单原始值：

```
form.verify({
  // 必填项
  title: function(value, elem) {
    console.log(elem.value); // 原始值
  }
});
```

https://layui.dev/docs/2/form/#verify
