### ISSUE TITLE
2.9.16版本中,移动端select下拉框可以展示，但是无法选中，退回2.9.14就没问题

### ISSUE THREAD

**Issue by mrfish-li** [layui/layui#2188]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.16

### 问题描述

2.9.16版本中,移动端select下拉框可以展示下拉列表，但是无法选中，退回2.9.14就没问题

### 业务代码

```auto
无
```

### 浏览器

移动端

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #2180

这是 2.9.15 中出现的问题，2.9.16 中已修复
