### ISSUE TITLE
DropDown下拉列表展示时，如果配置遮盖功能shade，点击下拉框外的遮盖范围，如果有按钮，则按钮事件被触发

### ISSUE THREAD

**Issue by mrfish-li** [layui/layui#2189]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.14

### 问题描述

      DropDown下拉列表展示时，如果配置遮盖功能shade，点击下拉框外的遮盖范围，下拉框会关闭，但是如果点击的时遮盖区域的按钮，则按钮事件也会被触发； 
      但是layer.open打开时如果配置遮盖，那么点击遮盖区域，只会把弹出层关闭，遮盖区域的事件不会触发。

### 业务代码

```auto
dropdown.render({
             elem: '.dropdown-prov',
             // align: 'center' // align 已配置在元素 `lay-options` 属性上
             //data: datas,
             className:'layui-dropdownzdy1',
             id:'iddropdownprov',
             trigger:'click',
             shade: [0.3, '#000'],
             content: [tplstr].join(''),
             click: function(obj){
            },
             close: function(elem){
                 $('#idprovicon').removeClass("layui-icon-up");
                 $('#idprovicon').addClass("layui-icon-down");
                 if(!Wb.isEmpty(app.datasinfo.prov)){ //如果没有过滤条件 则不需要高亮
                    $('#idprovbtn').addClass('active');
                  }else{
                    $('#idprovbtn').removeClass('active');
                 }
              },
             ready: function(elemPanel, elem){
                form.render('radio');
                $('#idprovicon').removeClass("layui-icon-down");
                $('#idprovicon').addClass("layui-icon-up");
                $('#'+app.datasinfo.prov).prop("checked", true); // 选中 单个单选框	
               
                form.render('radio');
             }
          });
```

### 截图补充

![97d29eb13132943c487a59dbf9f730b](https://github.com/user-attachments/assets/a7ad8c7b-8093-43ec-ac97-b3cf93b18706)

### 浏览器

移动端

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sunxiaobin89** [comment]
一般这种问题就是因为层级的关系，可能那个按钮的比遮罩层节点更接近用户，可以在遇到这种情况的时候打开遮罩层时，鼠标右键那个按钮检查元素看看控制台找到的节点是按钮还是遮罩层节点来排查

**Comment by Sight-wcg** [comment]
因为这不是功能请求并且缺乏足够的信息，暂时关闭这个问题，请提供重现以重新打开。

**Comment by Sight-wcg** [comment]
ref: https://github.com/layui/layui/discussions/2193
重新打开，移动端点击穿透问题
