### ISSUE TITLE
框体布局 手机端左侧菜单没有收起来

### ISSUE THREAD

**Issue by LBC000** [layui/layui#2191]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.16

### 问题描述

![image](https://github.com/user-attachments/assets/fa0f21c4-04ba-4e6d-9325-f45e5099db56)

### 业务代码

```auto
官网代码
```

### 浏览器

谷歌浏览器

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
![image](https://github.com/user-attachments/assets/cc7f131c-33be-41cb-923e-1c03b7b15dfb)
