### ISSUE TITLE
select 能不能引入拼音字母库来实现拼音首字母搜索

### ISSUE THREAD

**Issue by aimu2000** [layui/layui#2192]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

ALL

### 问题描述

select 能不能引入拼音字母库来实现拼音首字母搜索

### 业务代码

```auto
select 能不能引入拼音字母库来实现拼音首字母搜索
```

### 浏览器

123

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可借助 dropdown 的数据重载自主实现。
参考：https://layui.dev/docs/2/dropdown/#dropdown.reloadData
