### ISSUE TITLE
建议表单中的单选和多选，增加以图片为选项的功能

### ISSUE THREAD

**Issue by haodiao** [layui/layui#2195]
### 议题类型

功能请求

### 建议描述

```
表单能否增加： 单选和多选以图片为选项的功能，例如商城系统的商品选择 SKU 时显示缩略图的选项，就是 layui-vue 中的 “多选卡片”  功能。

同时建议把 layui-vue 的 “文字提示”、“确认提示” 也一起弄过来吧，太需要这样的常用功能了。
```

**Comment by sentsim** [comment]
参考 checkbox 和 radio 的自定义任意风格模板来实现：

- https://layui.dev/docs/2/form/checkbox.html#skin
- https://layui.dev/docs/2/form/radio.html#skin
