### ISSUE TITLE
建议增加 提示 功能

### ISSUE THREAD

**Issue by haodiao** [layui/layui#2196]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2-latest

### 问题描述

建议把 layui-vue 的  “文字提示”、“确认提示”，太需要这样的常用的基础功能了。

### 业务代码

```auto
无
```

### 浏览器

Chrome latest

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
你如果指的是这个的话 [https://www.layui-vue.com/zh-CN/components/tooltip](https://www.layui-vue.com/zh-CN/components/tooltip)，那layui一直都有这个，就在layer弹出层组件中 [https://layui.dev/docs/2/layer/#demo-tips](https://layui.dev/docs/2/layer/#demo-tips)

**Comment by LSL1618** [comment]
没想到**`layui-vue`**也发展的这么丰富了！

**Comment by hulang** [comment]
@LSL1618 那是，layui-vue一直在增加组件
layui目前不到3x版本，只修复和增加现有组件功能，不再增加新组件

https://www.layui-vue.com/zh-CN/components/popconfirm
这个也可以

**Comment by sentsim** [comment]
用 layer 或 dropdown 也能轻松实现，Layui 的很多组件都具有一定扩展性，不要只局限于示例所呈现的部分。
