### ISSUE TITLE
v2.9.16  版本 在谷歌浏览器下 使用

### ISSUE THREAD

**Issue by wtta1812** [layui/layui#2201]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

引用 layui.js 报错如图

### 业务代码

```auto
引用 layui.js
```

### 截图补充

<img width="1280" alt="微信图片_20240829173513" src="https://github.com/user-attachments/assets/5844c5bc-a456-4a93-89d9-590123312d9e">

### 浏览器

127.0.6533.120

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
测试官网 https://layui.dev 无此报错。
建议提供更多有效信息，顺带把浏览器也升级一下，Chrome 最新版是 128
