### ISSUE TITLE
官网在线测试用不了，一直转圈圈

### ISSUE THREAD

**Issue by 1271058326** [layui/layui#2202]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.16

### 问题描述

官网在线测试用不了，一直转圈圈。

### 业务代码

```auto
无
```

### 截图补充

![image](https://github.com/user-attachments/assets/6dce7a0d-ca96-47f6-98d7-02139c24d5bf)

### 浏览器

qq浏览器+谷歌

### 演示地址

https://layui.dev/playground/2/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
可能是网络问题，尝试切换不同的网络访问

**Comment by 1271058326** [comment]
翻墙也是
