### ISSUE TITLE
upload加入同时上传数控制

### ISSUE THREAD

**Issue by CallMeBatMan** [layui/layui#2208]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.8.18

### 问题描述

upload功能加入限制同时发起上传请求的数量。用来控制同时发起数据提交的请求数。
在开启批量上传时，每个文件，都会发起提交数据请求。在文件较多的情况下可能会导致后端接口压力突增，出现异常。
如果能排队上传，每次只允许x个文件进行同时请求就好了。

### 业务代码

```auto
upload.render({
            elem: '#selectFile'
            , url: 'xxxx' //改成您自己的上传接口
            , multiple: true
            , number: 100
            , auto: false
            , accept: "images"
            , exts: "jpg|jpeg|gif|png"
            , acceptMime: "image/jpg,image/jpeg,image/gif,image/png"
            , size: 10240
            , bindAction: '#testListAction' // 触发上传的按钮
            , data: {
                info: function (a, b, c) {
                    let trs = demoListView.find("tr");
                    let map = new Map();
                    for (let tr of trs) {
                        let fileName = $(tr).find(".file-name").text();
                        let name = $(tr).find(".name").val();
                        map.set(fileName, name);
                    }
                    return JSON.stringify(Object.fromEntries(map));
                }
            }
            , choose: function (obj) { }
            , done: function (res, index, upload) {  }
            , allDone: function (obj) {  
            }
            , error: function (index, upload) { 
            }
            , progress: function (n, elem, e, index) { //注意：index 参数为 layui 2.6.6 新增
                element.progress('progress-demo-' + index, n + '%'); //执行进度条。n 即为返回的进度百分比
            }
});
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by CallMeBatMan** [comment]
简单点可以给个数值的配置项出来；
复杂点可以暴露function，参数是已选文件总数，已上传文件数，正在上传文件数；返回值是个数值用来标记是否继续触发下一个文件的上传流程。

**Comment by sentsim** [comment]
尝试设置 `unified: true` 将多个文件合并成一个请求上传。
相关文档：https://layui.dev/docs/2/upload/#options

**Comment by CallMeBatMan** [comment]
> 尝试设置 `unified: true` 将多个文件合并成一个请求上传。 相关文档：https://layui.dev/docs/2/upload/#options

多谢回复！
我确实看到了这个设置项，但这样做会引发问题：
1. 如果这些文件的总和比较大，就会出现漫长的等待（比如两人协同处理文件，A负责上传，B负责处理文件。B要等A所有的文件传完才能开始处理）
2. 后端接口要求一次提交的数据大小有限制。（比如后端接口一次数据提交大小上限为10M，当用户的每个文件大小不确定时，他在选择文件的时候无法快速确定自己要选几个文件，上传才不会出现。这时就只需要让用户无脑选文件，设置`unified: false` & 控制并发上传文件的文件数量即可）
