### ISSUE TITLE
treeTable 组件添加{type: 'checkbox', fixed: 'left'}, 然后使用insTb.reloadData重载表报错

### ISSUE THREAD

**Issue by 15894237752** [layui/layui#2212]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

layui.js:1 Uncaught TypeError: Cannot create property 'hasChecboxCol' on string '#tableContract'
    at layui.js:1:304620
    at Object.<anonymous> (layui.js:1:299622)
    at n (layui.js:1:6852)
    at n.each (layui.js:1:6941)
    at n (layui.js:1:299537)
    at x.eachCols (layui.js:1:299633)
    at d (layui.js:1:304520)
    at a.reload (layui.js:1:319130)
    at B.reload (layui.js:1:330485)
    at B.reloadData (layui.js:1:319297)

### 业务代码

```auto
cols: [ [
          {type: 'checkbox', fixed: 'left'},
          {field: 'id', title: '', hide: true},
          {field: 'name', title: '文件名称',width: 500, align: 'left'},
          {field: 'format', title: '文件格式'},
          {field: 'remarks', title: '备注信息'},
          {align: 'center', toolbar: '#tableBarContract', title: '操作', minWidth: 200}
        ] ],

 function showEditModel(id) {
      var title = id ? '修改合同管理' : '新增合同管理';
      var url = id ? '/fams/contract/form?id=' + id : '/fams/contract/form';
      layer.open({
        type: 2,
        title: title,
        content: url,
        area: ['900px', '500px'],
        shadeClose: true,// true点击遮罩区域可关闭
        maxmin: true, //开启最大化最小化按钮
        skin: 'layui-layer-rim', // 加上边框
        end: function(){
          insTb.reloadData('#tableContract');
        }
      });
    }
```

### 截图补充

![image](https://github.com/user-attachments/assets/e1def936-fce5-4e8d-ade8-9beecd4b4c7c)

### 浏览器

128.0.6613.119（正式版本）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
错误信息已经明确告知了原因，这个错误是一个 JavaScript 运行时错误，表示尝试在一个字符串值 '#tableContract' 上创建一个名为 hasChecboxCol 的属性，而字符串是原始值类型，不能直接添加属性。这个函数期望接收一个包含可扩展属性的对象作为参数，但实际传入的是一个字符串 '#tableContract'。

**Comment by sentsim** [comment]
reloadData 第一个参数接受的是 id 值，而不是选择器。
将 `insTb.reloadData('#tableContract')` 改成 `insTb.reloadData('tableContract')`
