### ISSUE TITLE
弹出层layer抽屉效果下，设置最大宽度maxWidth不生效。

### ISSUE THREAD

**Issue by LawyerLu** [layui/layui#2213]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

目前制作的左侧栏滑出目录的功能，即：基于layui的layer组件，使用从左向右滑出，area设置为auto的情况下，设置最大宽度不生效，依然是auto。

### 业务代码

```auto
layer.open({
                type: 1,
                offset: 'l', // 从左向右滑出
                anim: 'slideRight', // 动画效果
                maxWidth: 200, // 设置最大宽度，目前未生效
                area: ['auto', '100%'], // 设置弹出层宽度和高度
                shade: 0.5, // 遮罩透明度
                title:'目录',
                shadeClose: true, // 点击遮罩关闭
                id: 'layer-menu', // 设置弹出层唯一ID
                skin: 'menu-skin',// 弹框最外层增加一个class
                content: $('#menu-content'), // 目录内容
                success: function(layero, index){
                    // 监听目录内链接的点击事件
                    $('#menu-content a').on('click', function(){
                        // 移除其他链接的 active 状态
                        $('#menu-content a').removeClass('active-link');
                        // 为当前点击的链接添加 active 状态
                        $(this).addClass('active-link');
                    });
                }
            });
```

### 浏览器

目前测试是移动端Safari浏览器，以及电脑端谷歌浏览器的调试模式下的移动端测试

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LawyerLu** [comment]
简单编写了一个demo：https://codepen.io/kyfhibrj-the-vuer/pen/jOjQegO
目前设置了最大宽度为100，但实际上弹框宽度仍然为auto。

**Comment by Sight-wcg** [comment]
应该是文档描述的歧义，「当 area 属性值为默认的 'auto' 时有效」指的是 `area: 'auto'`，后续考虑下是改文档还是改代码实现。
![image](https://github.com/user-attachments/assets/a60ba647-fdec-4e5b-8f6f-90c0e37da42a)

**临时的解决方案**
设置 `area: ['', '100%']`

**Comment by LawyerLu** [comment]
好的，感谢，目前使用area: ['', '100%']能够满足项目需求。

**Comment by sentsim** [comment]
题主设置的 `area: ['auto', '100%']` 表示宽度自适应，高度 100%。
根据文档描述，`maxWidth` 是只有 `area: 'auto'` 才有效，即宽度和高度都自适应的情况， 不过，应该只要宽度自适应，`maxWidth` 就应该要起效才合理。
