### ISSUE TITLE
table 开启合计后 totalRow 能否添加指定的数据字段的统计

### ISSUE THREAD

**Issue by tj224589** [layui/layui#2216]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.16

### 问题描述

如截图补充，在合计行，费用就合计不了。能否在新版新增 合计指定数据字段 如：
{field: 'number_01', title: '01月(数量/费用)', totalRow: '{{= d.TOTAL_NUMS }} / {{= d.TOTAL_NUMS.price_01  }}', templet: '<div>{{= d.number_01 }} / {{= d.price_01 }}</div>'}，
而不是去 d.TOTAL_NUMS.price_01 取后端合计的 totalRow 里面的值。

### 业务代码

```auto
{field: 'number_01', title: '01月(数量/费用)', totalRow: '{{= d.TOTAL_NUMS }} / XXX', templet: '<div>{{= d.number_01 }} / {{= d.price_01 }}</div>'},
{field: 'number_02', title: '02月(数量/费用)', totalRow: '{{= d.TOTAL_NUMS }} / XXX', templet: '<div>{{= d.number_02 }} / {{= d.price_02 }}</div>'},
...
...
{field: 'number_12', title: '12月(数量/费用)', totalRow: '{{= d.TOTAL_NUMS }} / XXX', templet: '<div>{{= d.number_12 }} / {{= d.price_12 }}</div>'},
```

### 截图补充

![20240905173838](https://github.com/user-attachments/assets/6c4797dd-66e5-4edf-9374-34186222ff82)

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可将合计数据直接放在接口的返回数据的 `totalRow` 字段中，然后通过 `{{= d.TOTAL_ROW.score }}` 即可获取到。
文档已有相关讲述：https://layui.dev/docs/2/table/#cols.totalRow
