### ISSUE TITLE
数据表格导出excel合计行模板，无法导出合计数据

### ISSUE THREAD

**Issue by 345956517** [layui/layui#2221]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

![88888](https://github.com/user-attachments/assets/051885c9-444b-440f-a8b4-deadf235ecd9)

### 业务代码

```auto
var tableIns = table.render({ //其它参数在此省略
            elem: '#idTest',
            url: 'Comm/Record.ashx',
            toolbar: '#toolbarDemo',
            totalRow: true,
            cols: [[
                { title: '汇总', width: 200, totalRow: '分数：{{= d.TOTAL_ROW.AllSum }}' }
            ]],
            where: wheredata,//如果无需传递额外参数，可不加该参数
            page: false //开启分页
             , done: function () {
                 element.init();
             }
        });
```

### 浏览器

Chrome 127.0.6533.89

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by 345956517** [comment]
https://stackblitz.com/edit/stackblitz-starters-j3r3oq?file=index.html
最后一行合计行，所有带有中文的数据都未导出，该演示代码99.9%来自辣鱼官网，基本上没做什么修改，就想导出excel数据要求包含合计行的内容

**Comment by xunenz0** [comment]
{title: '序号', field: 'sno', align: 'center', type: 'numbers', width: 30} 宽度显示30
{title: '序号', field: 'sno', align: 'center', type: 'normal', width: 30}  宽度显示60,"width: 30"配置未生效
{title: '序号', field: 'sno', align: 'center', width: 30}  宽度显示60,"width: 30"配置未生效

@sentsim 帮忙验证一下最新版v2.9.16，table cols 列宽度，设置不生效的问题。（反馈问题填写表单太麻烦，请谅解）

**Comment by xunenz0** [comment]
{title: '序号', field: 'sno', align: 'center', width: 30, maxWidth: 30}
问题已解决，再加一个maxWidth标签将OK，应该是被默认值给干扰了

**Comment by sentsim** [comment]
2.9.19 还是漏掉了这个 issue，由于合计行模板导出场景的特殊，2.x 可能暂时不会对此再做处理。
当前建议：通过在 `options.defaultToolbar` 选项中，自定义导出来实现相关需求，您可以使用后端导出或采用 `table.exportFile()` 方法前端导出。

参考文档：
- https://layui.dev/docs/2/table/#options.defaultToolbar
- https://layui.dev/docs/2/table/#table.exportFile

**Comment by l585826** [comment]
@sentsim 2.9.20版本当合计行数据都为0的时候，导出csv中的合计数据都是空的。
