### ISSUE TITLE
上传组件的choose回调问题

### ISSUE THREAD

**Issue by polarxy** [layui/layui#2222]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.7

### 问题描述

upload组件的choose回调，obj.preview如果遇到很大的文件就会内存溢出报错，能不能修复一下。或者可以将文件内容的预览做成可选项，很多时候不需要读内容。只需要获取当前选择的文件，添加到页面的上传列表里。只有preview方法可以拿到当前选中的文件。

### 业务代码

```auto
choose: function(obj){   
      var that = this;
      var files = this.files = obj.pushFile(); // 将每次选择的文件追加到文件队列
      // 读取本地文件
      obj.preview(function(index, file, result){};
}
```

### 浏览器

chrome 75

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #1543  #1671
