### ISSUE TITLE
请求开放仓库漏洞提交入口 (Private Vulnerability Reporting)

### ISSUE THREAD

**Issue by jackfromeast** [layui/layui#2234]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

暂无。

### 问题描述

Layui的开发团队，您好！

当前仓库虽然设置了Security Policy，但未开放漏洞提交的入口 (Private Vulnerability Reporting)。请问能否开放该提交入口，以便我们能够更安全地报告和解决在仓库中发现的安全问题？

![tmp](https://github.com/user-attachments/assets/f8bebbdd-30e4-48f2-802e-eb8bdcc2c1c3)

感谢您的理解与支持！

### 业务代码

```auto
暂无。
```

### 浏览器

N/A

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
已经开通。
