### ISSUE TITLE
laydate组件value与min使用同一时间,会提示不在有效日期或时间范围内

### ISSUE THREAD

**Issue by ddiptg** [layui/layui#2236]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.16

### 问题描述

laydate组件value与min使用同一时间,会提示不在有效日期或时间范围内,
查看源代码 1018行:  
``` 
if(that.getDateTime(dateTime) > that.getDateTime(options.max)){ //若超出最大日期
```
是options.max时间 "2099-12-31"没有转换为日期格式, 而是以字符串形式参与比较, 而生成了一个默认时间
Tue Jan 01 1901 00:00:00 GMT+0800

### 业务代码

```auto
layui.use(function () {
        var laydate = layui.laydate;
        var current = new Date();
        // 限定可选日期
        var ins22 = laydate.render({
          elem: '#ID-laydate-limit-1',
          value: current,
          min: current,
        });
      });
```

### 截图补充

<img width="965" alt="layui" src="https://github.com/user-attachments/assets/72477d36-bc48-4b0b-b2db-e65a02281c97">

### 浏览器

Chrome 128.0.6613.138

### 演示地址

https://stackblitz.com/edit/krrd6z-7uwebc?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
你应该将 min 选项的值类型由日期对象转为日期字符串或时间戳，文档中明确指出了其支持的类型。
详见 https://layui.dev/docs/2/laydate/#options.minmax

**Comment by ddiptg** [comment]
是的, 我后来又对文档看了一边, min/max是不支持Date类型的,
<img width="1010" alt="layui02" src="https://github.com/user-attachments/assets/bd6e49db-c1dd-4dee-9ecd-4865a4cedc09">

**Comment by Sight-wcg** [comment]
> 是的, 我后来又对文档看了一边, min/max是不支持Date类型的, 但是还是有新的问题, value的时间有截断时分秒, 但min的值没有, 所以会显示超出时间范围了 <img alt="layui02" width="1010" src="https://private-user-images.githubusercontent.com/17867028/369429558-bd6e49db-c1dd-4dee-9ecd-4865a4cedc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDA5NzYsIm5iZiI6MTcyNjg0MDY3NiwicGF0aCI6Ii8xNzg2NzAyOC8zNjk0Mjk1NTgtYmQ2ZTQ5ZGItYzFkZC00ZGVlLTllY2QtNDg2NWE0Y2VkYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDc4NGFhN2FiNWRmNmRlOWQzZDcwYzk5NTQ0M2U4NWM1M2IxMzJhZmIzZDkxNzFjNDVmMGQ2YWUzMjM2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LdyZBsjsf5ynldxZSFlkE2pvFPcZ5Szae-yXU_J5hK0">

`min: current.setHours(0, 0, 0, 0)`

**Comment by ddiptg** [comment]
> > 是的, 我后来又对文档看了一边, min/max是不支持Date类型的, 但是还是有新的问题, value的时间有截断时分秒, 但min的值没有, 所以会显示超出时间范围了 <img alt="layui02" width="1010" src="https://private-user-images.githubusercontent.com/17867028/369429558-bd6e49db-c1dd-4dee-9ecd-4865a4cedc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDA5NzYsIm5iZiI6MTcyNjg0MDY3NiwicGF0aCI6Ii8xNzg2NzAyOC8zNjk0Mjk1NTgtYmQ2ZTQ5ZGItYzFkZC00ZGVlLTllY2QtNDg2NWE0Y2VkYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDc4NGFhN2FiNWRmNmRlOWQzZDcwYzk5NTQ0M2U4NWM1M2IxMzJhZmIzZDkxNzFjNDVmMGQ2YWUzMjM2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LdyZBsjsf5ynldxZSFlkE2pvFPcZ5Szae-yXU_J5hK0">
> 
> `min: current.setHours(0, 0, 0, 0)`

手动添加一下setHours并不是很难, 没有冒犯的意思, 这个setHours由组件内部来处理, 或文档明确说明(原谅我刚看文档不仔细), 而不是使用者额外去发掘.
