### ISSUE TITLE
LayDate与flow的需求建议

### ISSUE THREAD

**Issue by zhanghong1peng** [layui/layui#2237]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.3

### 问题描述

在做移动端项目时，经常需要用到日期组件和流式加载组件，但在效果体验上不太好，具体表现如下，帮忙评估一下能否进行优化，谢谢。
一、日期选择组件可以正常的加载，但因移动端没有鼠标且屏幕比较小，在选择日期时很不好操作，能否优化成年、月、日的三列滑动的选择效果，如下图所示；
![f8235b2089781b2dce0717681c0ee2c](https://github.com/user-attachments/assets/7d157591-2cc7-48f9-a555-52f510978289)

二、流式加载在处理数据量大的列表时可以减少前后端的压力，是否可以增加一个滑动的响应选项，以便可以增加如滑动删除、滑动编辑的功能。实现如下图所示的效果。
![c436b7b7c5c9b1fb556ddd3bca715fd](https://github.com/user-attachments/assets/7b83fc99-85e1-4cc5-8926-4f2f7589e2f1)

这两个组件在移动端的前端开发中使用了很多，还请在百忙这中抽空评估一下，看看能否在新的版本中加入这两个新功能，非常感谢。

### 业务代码

```auto
无
```

### 截图补充

![Uploading f8235b2089781b2dce0717681c0ee2c.jpg…]()
![Uploading c436b7b7c5c9b1fb556ddd3bca715fd.jpg…]()

### 浏览器

Chorme 128.0.6613.138（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
layui 主要面向桌面端，移动端只做简单的适配，不接受移动端的功能请求。

议题中提到的需求建议用其他面向移动端的组件库来实现。
