### ISSUE TITLE
upload组件有什么办法实现Ctrl+V粘贴上传？

### ISSUE THREAD

**Issue by zzlatm** [layui/layui#2238]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.16

### 问题描述

希望通过Ctrl+V 方式实现粘贴上传，包括内存截图，请大神们赐教，谢谢。

### 业务代码

```auto
//
```

### 浏览器

EDGE

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by shenshu666** [comment]
获取剪切板中的数据，转base64 然后发送给后台

**Comment by shenshu666** [comment]
获取剪切板中的数据  百度就能找到       转base64百度也能找到

**Comment by shenshu666** [comment]
`
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>单个上传</title>
        <link rel="stylesheet" href="../../../../component/pear/css/pear.css" />
        <link href="../../../../component/fontawesome/css/all.min.css" rel="stylesheet" />
    </head>
    <body id="body">
        <div id="uploadDrag" class="layui-upload-drag" style="display: block; height: calc(100vh - 80px)">
            <div style="margin-top: 64px">
                <i class="layui-icon layui-icon-upload"></i>
                <div style="margin-top: 16px">
                    说明： =>>点击上传&nbsp;&nbsp;&nbsp;
                    <span id="base64Explain" style="display: none;">=>>Ctrl+V上传图片（无效请点击当前窗口）&nbsp;&nbsp;&nbsp;</span>
                    =>>将文件拖拽到此处&nbsp;&nbsp;&nbsp;
                </div>
            </div>
        </div>
        <script src="../../../../component/layui/layui.js"></script>
        <script src="../../../../component/pear/pear.js"></script>
        <script>
            layui.use(['upload', 'form', 'jquery', 'common', 'request', 'generate', 'repUtil', 'element'], function () {
                let form = layui.form;
                let $ = layui.jquery;
                let common = layui.common;
                let request = layui.request;
                let repUtil = layui.repUtil;
                let upload = layui.upload;

                /**
                 * 需要传参数
                 * reqData 请求数据 需要encodeURIComponent编码 并json字符串传输
                 * reqUrl 请求地址
                 * reqBase64Url ctrl+v 上传地址
                 * 		base64ParamName 上传Base64参数名字 默认base64Data
                 */
                var urlParam = repUtil.getUrlParam();
                console.log(urlParam);
                let reqData = {};
                if (urlParam.reqData) {
                    urlParam.reqData = decodeURIComponent(urlParam.reqData);
                    reqData = JSON.parse(urlParam.reqData);
                }

                let reqUrl = urlParam.reqUrl;
                let reqBase64Url = urlParam.reqBase64Url;
                let base64ParamName = urlParam.base64ParamName;

                if (reqBase64Url) {
                    $('#base64Explain').show();
                } else {
                    $('#base64Explain').hide();
                }

                if (!base64ParamName) {
                    base64ParamName = 'base64Data';
                }

                // 渲染
                upload.render({
                    elem: '#uploadDrag',
                    url: repUtil.getBaseUrl() + reqUrl, // 实际使用时改成您自己的上传接口即可。
                    data: reqData,
                    accept: 'file',
                    headers: {
                        erpToken: repUtil.getToken()
                    },
                    done: function (res, index, upload) {
                        // 成功的回调
                        var that = this;
                        if (res.code === '0') {
                            // 上传成功
                            succHandle(res);
                            return;
                        }
                        this.error(index, upload, res);
                    },
                    error: function (index, upload, res) {
                        // 错误回调

                        if (res) {
                            layer.msg('上传失败：' + res.message, {
                                icon: 2,
                                time: 3000
                            });
                        }
                    },
                    text: {
                        // 自定义提示文本
                        'data-format-error': '数据格式错误!', // 数据格式错误的提示
                        'check-error': '文件格式校验失败!', // 文件格式校验失败的提示
                        error: '上传失败', // 上传失败的提示
                        'limit-number': null, // 限制 number 属性的提示。若设置，需为函数写法
                        'limit-size': null, // 限制 size 属性的提示。若设置，需为函数写法
                        'cross-domain': '下跨域出现问题' // IE 下跨域的提示
                    }
                });

                //ctrl+v 上传
                // demo 程序将粘贴事件绑定到 document 上
                window.focus(); //当前窗口重新获取焦点
                document.addEventListener(
                    'paste',
                    function (e) {
                        var cbd = e.clipboardData;
                        var ua = window.navigator.userAgent;

                        // 如果是 Safari 直接 return
                        if (!(e.clipboardData && e.clipboardData.items)) {
                            return;
                        }

                        // Mac平台下Chrome49版本以下 复制Finder中的文件的Bug Hack掉
                        if (
                            cbd.items &&
                            cbd.items.length === 2 &&
                            cbd.items[0].kind === 'string' &&
                            cbd.items[1].kind === 'file' &&
                            cbd.types &&
                            cbd.types.length === 2 &&
                            cbd.types[0] === 'text/plain' &&
                            cbd.types[1] === 'Files' &&
                            ua.match(/Macintosh/i) &&
                            Number(ua.match(/Chrome\/(\d{2})/i)[1]) < 49
                        ) {
                            return;
                        }

                        for (var i = 0; i < cbd.items.length; i++) {
                            var item = cbd.items[i];
                            if (item.kind == 'file') {
                                var blob = item.getAsFile();
                                if (blob.size === 0) {
                                    return;
                                }
                                // blob 就是从剪切板获得的文件 可以进行上传或其他操作
                                // console.log(blob)
                                if (blob) {
                                    var reader = new FileReader(); //调用FileReader
                                    reader.readAsDataURL(blob); //将文件读取为 DataURL(base64)
                                    reader.onload = function (evt) {
                                        //读取操作完成时触发。
                                        // $("#img").attr('src', evt.target.result) //将img标签的src绑定为DataURL
                                        // console.log(evt.target.result)
                                        reqData[base64ParamName] = evt.target.result;
                                        request.post({
                                            url: reqBase64Url,
                                            data: reqData,
                                            succFun: function (res) {
                                                succHandle(res);
                                            }
                                        });
                                    };
                                }
                            }
                        }
                    },
                    false
                );

                //请求成功处理
                function succHandle(res) {
                    if (res.data.type === 'img') {
                        // 上传成功
                        top.layer.photos({
                            photos: {
                                title: res.data.title,
                                start: 0,
                                data: [
                                    {
                                        alt: res.data.title,
                                        pid: res.data.id,
                                        src: res.data.url
                                    }
                                ]
                            },
                            time: 2000,
                            footer: false, // 是否显示底部栏 --- 2.8.16+
                            toolbar: false,
                            end: function () {
                                top.layer.msg('上传成功：' + res.message, {
                                    icon: 1,
                                    time: 1000
                                });
                                window.focus(); //当前窗口重新获取焦点
                            }
                        });
                        return;
                    } else {
                        top.layer.msg('上传成功：' + res.message, {
                            icon: 1,
                            time: 1000
                        });
                        window.focus(); //当前窗口重新获取焦点
                    }
                }
            });
        </script>
    </body>
</html>


`

**Comment by zzlatm** [comment]
> <title>单个上传</title>
> 说明： =>>点击上传    =>>Ctrl+V上传图片（无效请点击当前窗口）    =>>将文件拖拽到此处   
> <script src="../../../../component/layui/layui.js"></script> <script src="../../../../component/pear/pear.js"></script> <script> layui.use(['upload', 'form', 'jquery', 'common', 'request', 'generate', 'repUtil', 'element'], function () { let form = layui.form; let $ = layui.jquery; let common = layui.common; let request = layui.request; let repUtil = layui.repUtil; let upload = layui.upload;
> ```
>             /**
>              * 需要传参数
>              * reqData 请求数据 需要encodeURIComponent编码 并json字符串传输
>              * reqUrl 请求地址
>              * reqBase64Url ctrl+v 上传地址
>              * 		base64ParamName 上传Base64参数名字 默认base64Data
>              */
>             var urlParam = repUtil.getUrlParam();
>             console.log(urlParam);
>             let reqData = {};
>             if (urlParam.reqData) {
>                 urlParam.reqData = decodeURIComponent(urlParam.reqData);
>                 reqData = JSON.parse(urlParam.reqData);
>             }
> 
>             let reqUrl = urlParam.reqUrl;
>             let reqBase64Url = urlParam.reqBase64Url;
>             let base64ParamName = urlParam.base64ParamName;
> 
>             if (reqBase64Url) {
>                 $('#base64Explain').show();
>             } else {
>                 $('#base64Explain').hide();
>             }
> 
>             if (!base64ParamName) {
>                 base64ParamName = 'base64Data';
>             }
> 
>             // 渲染
>             upload.render({
>                 elem: '#uploadDrag',
>                 url: repUtil.getBaseUrl() + reqUrl, // 实际使用时改成您自己的上传接口即可。
>                 data: reqData,
>                 accept: 'file',
>                 headers: {
>                     erpToken: repUtil.getToken()
>                 },
>                 done: function (res, index, upload) {
>                     // 成功的回调
>                     var that = this;
>                     if (res.code === '0') {
>                         // 上传成功
>                         succHandle(res);
>                         return;
>                     }
>                     this.error(index, upload, res);
>                 },
>                 error: function (index, upload, res) {
>                     // 错误回调
> 
>                     if (res) {
>                         layer.msg('上传失败：' + res.message, {
>                             icon: 2,
>                             time: 3000
>                         });
>                     }
>                 },
>                 text: {
>                     // 自定义提示文本
>                     'data-format-error': '数据格式错误!', // 数据格式错误的提示
>                     'check-error': '文件格式校验失败!', // 文件格式校验失败的提示
>                     error: '上传失败', // 上传失败的提示
>                     'limit-number': null, // 限制 number 属性的提示。若设置，需为函数写法
>                     'limit-size': null, // 限制 size 属性的提示。若设置，需为函数写法
>                     'cross-domain': '下跨域出现问题' // IE 下跨域的提示
>                 }
>             });
> 
>             //ctrl+v 上传
>             // demo 程序将粘贴事件绑定到 document 上
>             window.focus(); //当前窗口重新获取焦点
>             document.addEventListener(
>                 'paste',
>                 function (e) {
>                     var cbd = e.clipboardData;
>                     var ua = window.navigator.userAgent;
> 
>                     // 如果是 Safari 直接 return
>                     if (!(e.clipboardData && e.clipboardData.items)) {
>                         return;
>                     }
> 
>                     // Mac平台下Chrome49版本以下 复制Finder中的文件的Bug Hack掉
>                     if (
>                         cbd.items &&
>                         cbd.items.length === 2 &&
>                         cbd.items[0].kind === 'string' &&
>                         cbd.items[1].kind === 'file' &&
>                         cbd.types &&
>                         cbd.types.length === 2 &&
>                         cbd.types[0] === 'text/plain' &&
>                         cbd.types[1] === 'Files' &&
>                         ua.match(/Macintosh/i) &&
>                         Number(ua.match(/Chrome\/(\d{2})/i)[1]) < 49
>                     ) {
>                         return;
>                     }
> 
>                     for (var i = 0; i < cbd.items.length; i++) {
>                         var item = cbd.items[i];
>                         if (item.kind == 'file') {
>                             var blob = item.getAsFile();
>                             if (blob.size === 0) {
>                                 return;
>                             }
>                             // blob 就是从剪切板获得的文件 可以进行上传或其他操作
>                             // console.log(blob)
>                             if (blob) {
>                                 var reader = new FileReader(); //调用FileReader
>                                 reader.readAsDataURL(blob); //将文件读取为 DataURL(base64)
>                                 reader.onload = function (evt) {
>                                     //读取操作完成时触发。
>                                     // $("#img").attr('src', evt.target.result) //将img标签的src绑定为DataURL
>                                     // console.log(evt.target.result)
>                                     reqData[base64ParamName] = evt.target.result;
>                                     request.post({
>                                         url: reqBase64Url,
>                                         data: reqData,
>                                         succFun: function (res) {
>                                             succHandle(res);
>                                         }
>                                     });
>                                 };
>                             }
>                         }
>                     }
>                 },
>                 false
>             );
> 
>             //请求成功处理
>             function succHandle(res) {
>                 if (res.data.type === 'img') {
>                     // 上传成功
>                     top.layer.photos({
>                         photos: {
>                             title: res.data.title,
>                             start: 0,
>                             data: [
>                                 {
>                                     alt: res.data.title,
>                                     pid: res.data.id,
>                                     src: res.data.url
>                                 }
>                             ]
>                         },
>                         time: 2000,
>                         footer: false, // 是否显示底部栏 --- 2.8.16+
>                         toolbar: false,
>                         end: function () {
>                             top.layer.msg('上传成功：' + res.message, {
>                                 icon: 1,
>                                 time: 1000
>                             });
>                             window.focus(); //当前窗口重新获取焦点
>                         }
>                     });
>                     return;
>                 } else {
>                     top.layer.msg('上传成功：' + res.message, {
>                         icon: 1,
>                         time: 1000
>                     });
>                     window.focus(); //当前窗口重新获取焦点
>                 }
>             }
>         });
>     </script>
> </body>
> ```

万分感谢，顺便问一句，您这个程序支持内存截图粘贴的吧？

**Comment by shenshu666** [comment]
是的我现在的项目就是用这个C+V 上传图片 ~ 但是里面请求函数没有  需要用你自己的。  然后服务器端也要对base64字符串处理。  base64转文件流并保存。

**Comment by shenshu666** [comment]
文件复制好些我还没测试。 这个是微信截图，直接粘贴上传，类似的操作

**Comment by zzlatm** [comment]
> 是的我现在的项目就是用这个C+V 上传图片 ~ 但是里面请求函数没有 需要用你自己的。 然后服务器端也要对base64字符串处理。 base64转文件流并保存。

收到，感谢
