### ISSUE TITLE
table组件分页状态下，字段类型number时，后台条件过滤导致序号错误

### ISSUE THREAD

**Issue by fanyuning** [layui/layui#2240]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

所有

### 问题描述

table组件使用分页，并且其中一个字段类型为number时，先切换到非第一页后，在进行外部过滤搜索时，后端进行了分页合理化时，如果结果页号小于当前页号，会导致number序号错误。例如每页20条，共23条数据，当前为第2页，序号从21开始(图1)，改变条件后，共23条数据，当前页切换到第一页，但是序号还是从21开始(图2)。
![1](https://github.com/user-attachments/assets/940e0bff-fc45-4d9a-abb1-cb0ac7be3d71)
图1

![2](https://github.com/user-attachments/assets/27310085-685c-404c-957b-75c4585a2430)
图2

### 业务代码

```auto
第一次调用正常使用render函数，外部过滤搜索用reload函数。page属性为true
```

### 截图补充

我通过看源码，感觉是内部调用pullData函数时，传递curr参数是查询时的当前页号，在后端进行分页合理化处理时，实际页号会小于请求页号，后端这样做是为了避免空白列表问题。
![image](https://github.com/user-attachments/assets/8817c077-74b9-4b88-a0cf-1e78413b1b64)
curr参数主要来源于`that.page = options.page.curr = options.page.curr || 1;`这行代码

### 浏览器

任意

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
搜索条件变更之后，需要将当前页重置为第1页，再去加载数据。

**Comment by fanyuning** [comment]
> 搜索条件变更之后，需要将当前页重置为第1页，再去加载数据。

这是一种方式，但是需求要求尽量保持当前页，因为不是所有情况都会减少页数。

**Comment by hulang** [comment]
没有必要用ajax。直接使用`table`的`reload`或者`reloadData`方法就行。。。
