### ISSUE TITLE
upload 组件 在before参数中拦截return false 问题

### ISSUE THREAD

**Issue by lifeihub** [layui/layui#2241]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.11

### 问题描述

upload 组件 在before参数中拦截return false 后再次选择相同文件不触发上传

### 业务代码

```auto
before: function(obj){
      // 预读本地文件示例，不支持ie8
      return new Promise(function(resolve, reject ){
        obj.preview(function(index, file, result ){
          var imageObj = new Image();
          imageObj.src = result;
          imageObj.onload = function () {
            if (this.width != 250 || this.height != 250) {
              layer.msg('请上传宽*高为250*250像素的图片', {icon: 2});
              coverImage.config.elem.next()[0].value = null
              reject(false)
            } else {
              $('#cover_image_img').attr('src', result); // 图片链接（base64）
              element.progress('cover_image_filter', '0%'); // 进度条复位
              layer.msg('上传中', {icon: 16, time: 0});
              resolve(true)
            }
          }
        });
      })
    },
```

### 浏览器

Chrome  版本 129.0.6668.59（正式版本） （64 位）

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #1987

升级到 2.9.16 能否重现这个问题？
