### ISSUE TITLE
table在grid下（？）reloadData后宽度会变化，撑开

### ISSUE THREAD

**Issue by snowalk3671** [layui/layui#2244]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.17

### 问题描述

不知道为何，在grid模式下？每次更新表格数据宽度都会加1
详见演示

### 业务代码

```auto
https://codepen.io/snowalk/pen/wvQeMJp
```

### 浏览器

chrome 129

### 演示地址

https://codepen.io/snowalk/pen/wvQeMJp

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
ref https://github.com/layui/layui/issues/2168
