### ISSUE TITLE
icon如何扩展，之前的示例无法打开了

### ISSUE THREAD

**Issue by Tiamo-web66** [layui/layui#2246]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v1

### 问题描述

可以按照这个扩展下：http://fly.layui.com/jie/19051/
已经无法打开了

### 业务代码

```auto
可以按照这个扩展下：http://fly.layui.com/jie/19051/
已经无法打开了
```

### 浏览器

1

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
参考以下教程
- https://www.baidu.com/s?tn=68018901_3_dg&ie=UTF-8&wd=%E8%87%AA%E5%AE%9A%E4%B9%89layui%E5%9B%BE%E6%A0%87
- https://www.php.cn/faq/436838.html
- https://blog.csdn.net/weixin_43702272/article/details/134283582

下次记得在 [Discussions](https://github.com/layui/layui/discussions) 提问，[Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
