### ISSUE TITLE
2.9.17疑似bug反馈，table白屏

### ISSUE THREAD

**Issue by FFCZ** [layui/layui#2248]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.17

### 问题描述

jQuery v3.7.1 + layui 2.9.17，出现以下错误提示，table位置白屏，可能跟最新版jq有冲突，同环境恢复到2.9.16正常。
`
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at n.getElementSize (table.js:2810:24)
    at l (table.js:495:27)
    at l (table.js:505:52)
    at l (table.js:505:52)
    at l (table.js:505:52)
    at n.setInit (table.js:507:7)
    at n.render (table.js:371:10)
    at new n (table.js:290:10)
    at x.render (table.js:3255:16)
    at HTMLDocument.<anonymous> (center.html:103:15)
    
jQuery.Deferred exception: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at n.getElementSize (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:298031)
    at l (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:267115)
    at l (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:267308)
    at l (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:267308)
    at l (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:267308)
    at n.setInit (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:267323)
    at n.render (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:265452)
    at new n (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:264472)
    at x.render (https://www.ab.com/static/layui/layui.js?ver=4.1.20240925-01:1:303844)
    at HTMLDocument.<anonymous> (https://www.ab.com/manager/workflow/center.html:103:15) undefined
`

### 业务代码

```auto
table.render({
            elem: '#data_list'
            , id: 'data_table'
            , title: '审批管理数据'
            , url: 'center_data.php'
            , height: 'full-50'
            , limit: 50
            , limits: [50, 100, 200, 300, 500, 1000, 2000]
            , page: true
            , toolbar: '#toolbar'
            , defaultToolbar: ['filter', { title: '导出', layEvent: 'export', icon: 'layui-icon-download-circle' }, { title: '刷新', layEvent: 'reload', icon: 'layui-icon-refresh-3' }]
            , escape: false
            , totalRow: true
            , cellExpandedMode: 'tips'
            , className: 'layui-table-data'
            , cols: [
                [
                    { type: 'checkbox', fixed: 'left', width: 60, align: 'center', totalRow: '<span id="checkboxTotal">0</span>' }
                    , { field: 'order_id', title: '编号', fixed: 'left', align: 'center', minWidth: 80, hide: true }
                    , { field: 'order_sn', title: '单据编号', fixed: 'left', align: 'center', minWidth: 160 }
                    , { field: 'order_title', title: '标题内容', align: 'left', minWidth: 240 }
                    , { field: 'order_status', title: '单据状态', align: 'center', minWidth: 100 }
                    , { field: 'summary_info', title: '摘要信息', align: 'left', minWidth: 240 }
                    , { field: 'template_name', title: '模板名称', align: 'center', minWidth: 120 }
                    , { field: 'launch_staff_name', title: '发起人', align: 'center', width: 120 }
                    , { field: 'launch_time', title: '发起时间', align: 'center', minWidth: 160 }
                    , { field: 'handle_staff_name', title: '最后处理', align: 'center', width: 120 }
                    , { field: 'wait_staff_name', title: '等待处理', align: 'center', width: 120 }
                    , { field: 'last_status', title: '最后状态', align: 'left', minWidth: 160 }
                    , { field: 'stop_reason', title: '结束原因', align: 'left', minWidth: 160 }
                    , { field: 'stop_time', title: '结束时间', align: 'center', minWidth: 160 }
                    , { field: 'cost_times', title: '总耗时', align: 'center', minWidth: 120, sort: true }
                    , { field: 'receivable', title: '应收账款', align: 'center', width: 120 }
                    , { fixed: 'right', title: '操作', align: 'center', minWidth: 180, toolbar: '#tools' },
                ],
            ],
        });
```

### 浏览器

Edge129

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by hulang** [comment]
`jQuery`都用到3x版本了啊。我一直用1x版本，上次点击密码框那个显示，无法显示，`jQuery`切换到2x版本才正常。。。
使用`jQuery`3x版本，好像有点和我的项目中的哪个插件不兼容，一直没有用3x。。。

**Comment by SimonSUSU** [comment]
我也是，现在降级加2.9.16就正常了。

**Comment by SimonSUSU** [comment]
2.9.17版的白屏，我看说是已解决并关闭了。我怎没有看懂如何解决的？大神指点一下。
