### ISSUE TITLE
时间限制

### ISSUE THREAD

**Issue by s209392599** [layui/layui#2252]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.16

### 问题描述

要求是显示年月日时分，且当前时间之后的时间(包括小时分钟)才能被选择

### 业务代码

```auto
laydate.render({
  elem: '#task_end_time',
  theme: 'ymdhm',
  type: 'datetime',
  min: CustomDateFtt(new Date(), "yyyy-MM-dd hh:mm"),// 2024-09-26 17:13
  value: lineObj.planEndTime,
  format: 'yyyy-MM-dd HH:mm',
  done: function (value, date) {
  },
  btns: ['confirm'],
  fullPanel: true
});
```

### 浏览器

谷歌最新版本

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://layui.dev/docs/2/laydate/#demo-limit

参考文档示例 disabledDate 和 disabledTime
