### ISSUE TITLE
树表隔行变色展开收起后样式错误

### ISSUE THREAD

**Issue by Tiamo-web66** [layui/layui#2258]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

树表组件开启隔行变色，进行展开下级后再收起，就会出现收起的不进行各行变色。
修改样式设置为排除layui-hide还是不行
.layui-table[lay-even] tbody tr:not(.layui-hide):nth-child(even)

### 业务代码

```auto
var inst = treeTable.render({
    elem: '#test',
    url: './json/treeTable/demo-1.json',
    // data: createData(!0),
    maxHeight: 'full-32',
    toolbar: '#TPL-treeTable-demo',
    even: true,
    tree: {
      customName: {
        name: 'name'
      },
      view: {
        iconLeaf: ''
      },
      data: {
        // isSimpleData: true
      }
    },
    cols: [[
      {type: 'checkbox', fixed: 'left'},
      {type: 'numbers', fixed: 'left'},
      {field: 'id', title: 'ID', width: 145, sort: true, fixed: 'left', totalRow: '合计：'},
      {field: 'name', title: '用户名', width: 180, fixed: 'left'},
      {field: 'experience', title: '积分', width: 90, sort: true},
      {field: 'sex', title: '性别', width: 80, sort: true},
      {field: 'score', title: '评分', width: 80, sort: true},
      {field: 'city', title: '城市', width: 150},
      {field: 'description', title: '描述', minWidth: 200},
      {field: 'createTime', title: '创建时间', width: 170},
      { fixed: "right", title: "操作", width: 190, align: "center", toolbar: "#TPL-treeTable-demo-tools"}
    ]],
    page: true
  });
```

### 截图补充

![image](https://github.com/user-attachments/assets/a3fc29e8-f612-45ad-8650-2bef9891174b)
![image](https://github.com/user-attachments/assets/540edce3-fc47-4e79-9791-349669b5d85d)
![image](https://github.com/user-attachments/assets/1baeddb6-03bc-4d0f-9aca-5dd58b0fee18)

### 浏览器

版本 129.0.6668.60（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
参考 MDN https://developer.mozilla.org/zh-CN/docs/Web/CSS/:nth-child#%E4%BD%BF%E7%94%A8_of_selector_%E4%BF%AE%E5%A4%8D%E6%9D%A1%E7%BA%B9%E8%A1%A8%E6%A0%BC

```css
.layui-table[lay-even] tbody tr:nth-child(even){
  background: none;
}
.layui-table[lay-even] tbody tr:nth-child(even of :not(.layui-hide)) {
  background: #f8f8f8;
}
```
