### ISSUE TITLE
table 能否提供更为紧凑的数据显示模式，类使用 Excel 或 MiniUI 那种紧凑显示

### ISSUE THREAD

**Issue by Gipors** [layui/layui#2263]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v 2.9.7

### 问题描述

table 是非常重要和常用的组件，layui table 简单大气十分好用，但唯有点瑕疵在于，需要显示较多数据的时候，数据的显示量较少，希望能出一个类似于 Excel 或 MiniUI、jEasyUI、DWZ 等的那种紧凑样式，显示更多数据。可参考的样式包括如下：

MiniUI datagrid 样式 http://www.miniui.com/demo/datagrid/detailgrid.html
DWZ 常用组件 - 表格容器 https://jui.org/#w_tree

我尝试过修改css 显示更紧凑，添加一个新选项 **size:'xs**'，但技艺拙劣，分界不明、checkbox/radio不适配，显示效果不佳，且列宽计算失效，希望能官方提供一版紧凑显示适配。

### 业务代码

```auto
/** 为 layui.table 添加更紧凑样式 skin='xs' */
.layui-table[lay-size=xs] td,.layui-table[lay-size=xs] th {
    padding-right: 3px;
	padding-left: 3px;
    font-size: 12px
}

.layui-table-view .layui-table[lay-size=xs] .layui-table-cell {
    height: 30px;
    line-height: 20px;
    padding-top: 5px;
    padding-left: 0;
    padding-right: 0;
}

.layui-table-view .layui-table[lay-size=xs] .layui-table-expanded .layui-table-cell {
    height: auto;
    max-height: 94px;
    white-space: normal;
    text-overflow: clip
}

.layui-table-view .layui-table[lay-size=xs] .layui-table-edit {
	position:absolute;left:0;top:0;z-index:199;min-width:100%;min-height:100%;padding:0px 3px;border-radius:0;box-shadow:1px 1px 20px rgba(0,0,0,.15);background-color:#fff
}
```

### 截图补充

![image](https://github.com/user-attachments/assets/639cd816-93d7-40e2-9827-9aa5c782a28c)
![image](https://github.com/user-attachments/assets/7bb2b576-c5ed-40cb-af41-493e28f6869a)
![image](https://github.com/user-attachments/assets/3cb84b85-b035-4855-ba7c-e8c306b5a0d1)
![image](https://github.com/user-attachments/assets/87f25613-d277-4a35-994c-9e6388a127ea)

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可通过 `css` 或 `className`  选项实现。
https://layui.dev/docs/2/table/#options

**Comment by dbkuaizi** [comment]
现在 Layui2 的表单组件、表格组件确实有点大 面向后台这种数据量多的场景 能呈现的信息量不多，我的做法是 重写了这两个组件 高度相关的 CSS 其实量不是很大。（可能 Layui3 用 CSS 变量的时候 更容易处理）

**Comment by Gipors** [comment]
> 现在 Layui2 的表单组件、表格组件确实有点大 面向后台这种数据量多的场景 能呈现的信息量不多，我的做法是 重写了这两个组件 高度相关的 CSS 其实量不是很大。（可能 Layui3 用 CSS 变量的时候 更容易处理）

我也是自己些了点css，代码贴上来了，给 table 添加了一个新选项 size:'xs'，但是表格的宽度计算又不正确了。可否分享下你的方案实例？

**Comment by flytkgl** [comment]
我是把表格和表单的行高都设置为了30px,感觉这个尺寸还是比较顺眼的,默认的的确感觉大了一点
![截图_17296791551048](https://github.com/user-attachments/assets/69cadf44-c7af-4a84-80cb-7b9b3bb62765)
