### ISSUE TITLE
tree 是否能支持显示半选状态

### ISSUE THREAD

**Issue by Gipors** [layui/layui#2264]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v 2.9.7

### 问题描述

tree 的选中状态只有 选中/没选中 2个状态，能够支持 半选状态？ table 的表头里的 checkbox 是支持显示半选状态的，希望 tree 也能支持

### 业务代码

```auto
无
```

### 截图补充

![image](https://github.com/user-attachments/assets/30c47ca8-1aab-4c3d-ad4f-119428a5a8c8)

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
参考回答：https://github.com/layui/layui/issues/1606#issuecomment-1916536470
