### ISSUE TITLE
[BUG] dropdown 自定义 content 的上下文菜单异常关闭

### ISSUE THREAD

**Issue by Sight-wcg** [layui/layui#2275]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.17

### 问题描述

dropdown 使用 content 选项自定义面板元素时，若 trigger 选项为 `contextmenu`，点击面板任意处会关闭

**重现步骤**

1. 首先右键点击预览中的按钮
2. 然后左键点击弹出的面板，此时面板会关闭，预期不应关闭

### 业务代码

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
    <link href="//unpkg.com/layui@2.9.17/dist/css/layui.css" rel="stylesheet" />
  </head>
  <body class="layui-padding-3">
    <button class="layui-btn" id="ID-dropdown-demo-content">右键点击</button>

    <!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
    <script src="//unpkg.com/layui@2.9.17/dist/layui.js"></script>
    <script>
      layui.use(function () {
        var dropdown = layui.dropdown;
        // 自定义内容
        dropdown.render({
          trigger: 'contextmenu',
          elem: '#ID-dropdown-demo-content',
          content: '<div style="width:200px;height:100px;background:#eee">点击面板任意处</div>',
        });
      });
    </script>
  </body>
</html>
```

### 浏览器

Microsoft Edge  122.0.2365.80 (正式版本) (64 位)

### 演示地址

https://stackblitz.com/edit/mzscac?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
一个很棒的 Issue 范本，一目了然。
