### ISSUE TITLE
级联选择器

### ISSUE THREAD

**Issue by mouse0w0** [layui/layui#2277]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.17

### 问题描述

目前正在开发的项目中有一个选择用户所在部门的需求，需要使用级联选择器组件。

尝试使用layui第三方扩展组件，但主要存在以下问题：
1. 不支持选择非叶子结点。
2. 支持选择非叶子结点的不支持隐藏单选框。
3. 组件样式与layui的风格不一致。

目前[Ant Design的级联组件](https://ant.design/components/cascader-cn#cascader-demo-change-on-select)的功能是比较符合需求的，但是没法在项目中使用。

### 业务代码

```auto
无
```

### 截图补充

![示例](https://github.com/user-attachments/assets/d6d2d62f-a9a9-44b0-a018-f0cbc7952ca5)

### 浏览器

Edge 129.0.2792.79 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
建议直接使用 Layui 第三方扩展 lay_cascader 实现。
相关问题可反馈到对应的 Gitee 主页：https://gitee.com/yixiacoco/lay_cascader
