### ISSUE TITLE
layer弹出层组件中的confirm有bug

### ISSUE THREAD

**Issue by yqsphp** [layui/layui#2279]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

layer弹出层组件中的confirm提示框打开后，
在回调函数中如果什么代码都不写，
点击确定不能关闭

### 业务代码

```auto
layer.confirm('一个询问框的示例？', {icon: 3}, function(){
                    //这里面什么都没有
                }, function(){
                    //layer.msg('点击取消的回调');
                });
```

### 浏览器

任何浏览器

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
预期行为，第一个回调写了的话，就需要添加 layer.close(index) 自主控制关闭。
https://layui.dev/docs/2/layer/#confirm
