### ISSUE TITLE
弹窗含有数据表格时在弹出后再F12打开工具改变窗口大小会报错

### ISSUE THREAD

**Issue by DOUYS** [layui/layui#2282]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.18

### 问题描述

弹窗在含有数据表格时，弹出后再F12打开工具时、以及改变窗口大小会报错：

### 业务代码
```auto
$(".btn").on('click',function(){
    layer.open({
        type: 1,
        area: ['420px', '240px'], // 宽高
        title: false, // 不显示标题栏
        closeBtn: 0,
        shadeClose: true, // 点击遮罩关闭层
        content: '<table class="layui-hide" id="ID-table-demo-data"></table>',
        success: function(){
            layui.table.render({
                elem: '#ID-table-demo-data',
                cols: [[ //标题栏
                  {field: 'id', title: 'ID', width: 80, sort: true},
                  {field: 'username', title: '用户', width: 120},
                  {field: 'sign', title: '签名', minWidth: 160},
                  {field: 'sex', title: '性别', width: 80},
                  {field: 'city', title: '城市', width: 100},
                  {field: 'experience', title: '积分', width: 80, sort: true}
                ]],
                data: [{ // 赋值已知数据
                  "id": "10001",
                  "username": "张三1",
                  "sex": "男",
                  "city": "浙江杭州",
                  "sign": "人生恰似一场修行",
                  "experience": "116"
                }, {
                  "id": "10002",
                  "username": "张三2",
                  "sex": "男",
                  "city": "浙江杭州",
                  "sign": "人生恰似一场修行",
                  "experience": "12",
                  "LAY_CHECKED": true
                }],
                page: true, // 是否显示分页
                limits: [5, 10, 15],
                limit: 5 // 每页默认显示的数量
              });
        }
    });
});
```

### 截图补充

![1](https://github.com/user-attachments/assets/d8af3259-34ee-46ac-956c-f2dc6a1082db)

### 浏览器

Google Chrome 129.0.6668.103 (64)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by DOUYS** [comment]
> @DOUYS 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)

先点击按钮弹出弹窗，然后关闭弹窗，再F12, 或拖动改变窗口大小，即可看到报错
https://stackblitz.com/edit/stackblitz-starters-ebae5r?file=layui.js

**Comment by Sight-wcg** [comment]
@sentsim 是否需要新增一个 table.destroy 方法主动销毁实例？这里可能会有内存泄漏。

**Comment by sentsim** [comment]
@Sight-wcg  我认为不需要增加 `table.destroy()` 方法。这里应该不存在内存泄漏问题，内部实例对象是通过 id 作为索引存储的，也就是说即便 table 容器被反复创建和移除，thisTable 中存储的实例也并不会无限叠加。

该 Issue 的触发原因是 table 容器被移除后，resize 事件中的行为找不到 table 元素所致。只需将 https://github.com/layui/layui/blob/main/src/modules/table.js#L1063 简单优化下即可：

```
// table 容器是否存在于页面
if (!that.layMain || !$(that.layMain).closest('html')[0]) {
  return;
}
```

如果不兼容 IE8 其实也可以直接使用 `document.contains` 来判断。
