### ISSUE TITLE
时间区间选择器无法设置结束时间小于开始时间

### ISSUE THREAD

**Issue by jwwb681232** [layui/layui#2283]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.17

### 问题描述

有时需要结束时间小于开始时间，具体时间由后端处理，如果结束时间小于等于开始时间，那么结束时间就递增一天。

### 业务代码

```auto
layui.laydate.render({elem: '#field-date',type:'date',lang:'en',theme:'grid'});
layui.laydate.render({elem: '#field-time',type:'time',lang:'en',theme:'grid',range:'~'});
```

### 截图补充

![微信图片_20241017155427](https://github.com/user-attachments/assets/252d5fcc-37b6-47bc-90c2-dfce817beee8)

### 浏览器

Chrome 129.0.6668.101

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
这是预期的行为。你可以用日期时间选择器或尝试用两个时间选择器封装符合业务需求的组件。

**Comment by jwwb681232** [comment]
> 这是预期的行为。你可以用日期时间选择器或尝试用两个时间选择器封装符合业务需求的组件。

之前我们都是按照你这种方法设置的，但是实际使用中经常操作错误导致跨多天
