### ISSUE TITLE
表格表头的高度和固定列表头的高度不一致

### ISSUE THREAD

**Issue by Botti307** [layui/layui#2287]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

表头的列宽设置的不能满足表头标题的长度时，表头会自动调整高度，但是固定列的高度不会跟着变
![微信图片_20241021172952](https://github.com/user-attachments/assets/8cb554dd-0cdd-4603-a6b6-bf56e325901c)

### 业务代码

```auto
//我目前的处理时在table的done方法里面调整
//表格中间部分标题的高，统一两边固定列的高
var $body = $('div[lay-table-id=' + tableID + ']');
var cHeight = $body.find('.layui-table-header th').height();
$body.find('.layui-table-fixed .layui-table-header th').css({ 'height': cHeight });
```

### 浏览器

Google Chrome 130.0.6723.59

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
Duplicate of #1477  #1032
