### ISSUE TITLE
fixbar的top置顶在指定scroll时，click单击无效

### ISSUE THREAD

**Issue by kun661** [layui/layui#2288]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.17

### 问题描述

例如，将bars的scroll设置为'div.layui-body-header+div'，当滚动到底部时，top虽然可以显示，但单击无法滚动到顶部。
经查看util.js源代码，发现是在绑定单击事件时有错误，将target改成scroll即可正常，请修复！
另外还有很重要的一点，当指定scroll时，如果仿真移动设备，这个top图标居然不显示。请官方一并检查看看，谢谢！

### 业务代码

```auto
util.fixbar({
    bars: [{ // 定义可显示的 bar 列表信息 -- v2.8.0 新增
      type: 'share',
      icon: 'layui-icon-share'
    }, {
      type: 'help',
      icon: 'layui-icon-help'
    }, { 
      type: 'cart',
      icon: 'layui-icon-cart',
      style: 'background-color: #FF5722;'
    }, {
      type: 'groups',
      content: '群',
      style: 'font-size: 21px;'
    }],
    scroll:'div.layui-body-header+div'
})
```

### 浏览器

Edge版本 127.0.2651.86 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
你能提供重现并录制两段视频吗？

**Comment by kun661** [comment]
经再次测试，移动端应该是我自己的代码问题。
但util中的click事件代码确实是错的，需要修改。这个事件里的判断代码如下：
options.target === 'body'
这个单击事件是要将滚动条所在元素对象滚动到顶部，当然要通过options.scroll判断，否则，我在bars里指定的scroll属性在这儿就无效了。如果target使用默认，同时又指定了scroll，那这段代码滚动的永远是body。
明显的逻辑问题，不需要再写重现代码或者录制视频了吧？

**Comment by kun661** [comment]
> 你能提供重现并录制两段视频吗？

我本以为移动端不显示top是我的css代码问题，但刚刚把这些代码删除之后，移动端滚动还是不显示。我尽量写一个最小化的示例代码以便重现吧
