### ISSUE TITLE
请教：如何从外部获得layer的配置信息？

### ISSUE THREAD

**Issue by ymruse** [layui/layui#2292]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.18

### 问题描述

有没有layer.getconfig()这样的方法？

### 业务代码

```auto
//
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
目前不支持这样的方法，不过可以用别的方式拿到配置信息，参考如下：
```
let myDialog;
layer.open({
    ...
    success: function($dom, index, that) {
        // 配置信息在 myDialog.config 中
        myDialog = that;
    },
    ...
});
```

**Comment by ymruse** [comment]
> 目前不支持这样的方法，不过可以用别的方式拿到配置信息，参考如下：
> 
> ```
> let myDialog;
> layer.open({
>     ...
>     success: function($dom, index, that) {
>         // 配置信息在 myDialog.config 中
>         myDialog = that;
>     },
>     ...
> });
> ```

谢谢！
