### ISSUE TITLE
弹出层z-index，打开多次后，最开始打开的弹出层z-index，会变得比遮罩层低，导致页面操作不了

### ISSUE THREAD

**Issue by FlankMiao** [layui/layui#2302]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.17

### 问题描述

弹出层z-index，打开多次后，最开始打开的弹出层z-index，会变得比遮罩层低，导致页面操作不了。issue2285，那个关闭了。
[modalDemo.zip](https://github.com/user-attachments/files/17594869/modalDemo.zip)

### 业务代码

```auto
触发方式：live server启动index.html后，点击modal show弹出表单，不要输入，点击确定，触发表单校验提示信息，多次点击后，关闭弹出层，再次打开，再点击确定，点击几次后就会复现。页面点不了，表单弹出层的shade层的z-index大于弹出层的z-index，这种方式目前可以稳定触发。
```

### 浏览器

 129.0.6668.90

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
目前建议在 content 和 footer 区域阻止 mousedown 事件冒泡来规避这个问题

**Comment by sentsim** [comment]
你前面提供的 `modalDemo.zip` 并非复现的代码，里面只是一些 HTML，并没有看到 layer+form 联动的详细业务代码。
建议按照上述说明，创建在线 Demo。

**Comment by FlankMiao** [comment]
确实，去掉zIndex: layer.zIndex 和 window.layui.layer.setTop(layero);后，没出现描述的问题。
