### ISSUE TITLE
右键菜单无法绑定到动态生成的元素上，有什么解决办法吗，事件委托有办法实现吗，layui版本为2.9.18

### ISSUE THREAD

**Issue by mrliuyin1204** [layui/layui#2303]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.18

### 问题描述

右键菜单无法绑定到打开的tab标签上，tab标签是动态生成的

<img width="860" alt="10A4C133-6109-454c-B5B2-E4758FB8A85C" src="https://github.com/user-attachments/assets/fe99e9c9-4275-4323-b276-157d5a0d1123">

### 业务代码

```auto
layui.use(function(){
  var dropdown = layui.dropdown;
  var util = layui.util;
  // 右键菜单
  dropdown.render({
    elem: '#ID-dropdown-demo-contextmenu', // 也可绑定到 document，从而重置整个右键
    trigger: 'contextmenu', // contextmenu
    isAllowSpread: false, // 禁止菜单组展开收缩
    style: 'width: 200px', // 定义宽度，默认自适应
    data: [{
      title: 'menu item 1',
      id: 'test'
    }, {
      title: 'Printing',
      id: 'print'
    },{
      title: 'Reload',
      id: 'reload'
    },{type:'-'},{
      title: 'menu item 3',
      id: '#3',
      child: [{
        title: 'menu item 3-1',
        id: '#1'
      },{
        title: 'menu item 3-2',
        id: '#2'
      },{
        title: 'menu item 3-3',
        id: '#3'
      }]
    },
    {type: '-'},
    {
      title: 'menu item 4',
      id: ''
    },{
      title: 'menu item 5',
      id: '#1'
    },{
      title: 'menu item 6',
      id: '#1'
    }],
    click: function(obj, othis){
      if(obj.id === 'test'){
        layer.msg('click');
      } else if(obj.id === 'print'){
        window.print();
      } else if(obj.id === 'reload'){
        location.reload();
      }
    }
  });
```

### 浏览器

chrome  版本 130.0.6723.70（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
参考 https://layui.dev/docs/2/dropdown/#demo-table

**Comment by mrliuyin1204** [comment]
> 参考 https://stackblitz.com/edit/teyzfg?file=index.html
> 
> 下次记得在 [Discussions](https://github.com/layui/layui/discussions) 提问，分清 issues 和 questions 的区别，提问前请先阅读 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)。

好的，感谢感谢
