### ISSUE TITLE
图片弹窗工具栏是否可以增加一个显示实际大小的按钮

### ISSUE THREAD

**Issue by finemanlf** [layui/layui#2305]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.18

### 问题描述

layer.photos 弹窗的工具栏建议增加一个显示实际图片大小（或图片最大化适应窗口）的功能，放在恢复按钮旁边

### 业务代码

```auto
layer.photos({});
```

### 浏览器

主流浏览器需求

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
图片组件底部有"查看原图"功能，可看原始尺寸。
