### ISSUE TITLE
部分情况下的下拉组件切换事件没有触发

### ISSUE THREAD

**Issue by 469888647** [layui/layui#2306]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

  1. 下拉组件设置lay-search属性开启输入编辑功能
  2. 使用form的on方法给这个下拉组件添加监听事件
  3. 渲染表单
  4. 手动切换下拉项,监听事件可以触发
  5. 将下拉项随便切换到一项,然后删除输入框中的内容,点击其它区域,此时下拉项的值切换成默认值,但是不会触发监听事件
  
> 之前没有发现这个问题，怀疑是下拉事件从以前的window事件修改成现在的lay.onClickOutside事件引起的。

### 业务代码

```auto
<select name="interest" lay-search="{caseSensitive:false, fuzzy: true}" lay-hint="" lay-filter="aihao">
        <option value=""></option>
        <option value="0">写作</option>
        <option value="1" selected="">阅读</option>
        <option value="2">游戏</option>
        <option value="3">音乐</option>
        <option value="4">旅行</option>
</select>
layui.form.render();
layui.form.on("select(aihao)",function (data) {
    console.log('value:'+data.value);
});
```

### 截图补充

> 正常手动切换,可以触发监听事件

![image](https://github.com/user-attachments/assets/fe790238-a2bd-44be-89ca-aee66be1f01b)

> 表单取值正常

![image](https://github.com/user-attachments/assets/5b456488-1bf7-41c8-8b3a-b005ef84baf5)

> 点输入框删除内容后失去焦点后,不触发监听事件

![image](https://github.com/user-attachments/assets/c8349baa-de0b-4fcc-bee8-f8dc3288c1ba)

> 不过表单取值是正常的

![image](https://github.com/user-attachments/assets/5870fe3b-c517-4f78-b10e-b4a7a9048693)

### 浏览器

Chrome 130.0.6723.92

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
最好直接提供一个可供预览的在线 Demo

**Comment by 469888647** [comment]
可以试试这个地址能不能打开
https://codepen.io/469888647/pen/QWeVzeK


这是旧版本的处理,并不会修改表单值





这是新版本的处理,清除搜索内容后将表单值修改为空字符串







这个操作应该是修改了表单值,但是没有看到它去触发事件。我搜索了一下,只有点击dd标签事件里面才有这个操作





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "layui/layui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月5日(星期二) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [layui/layui] 部分情况下的下拉组件切换事件没有触发 (Issue #2306)





 
最好直接提供一个可供预览的在线 Demo

**Comment by Sight-wcg** [comment]
旧版本指的是哪个版本？
