### ISSUE TITLE
layer.prompt设置了maxlength无效

### ISSUE THREAD

**Issue by wangzhi0313** [layui/layui#2307]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

layer.prompt设置了maxlength无效

### 业务代码

```auto
layer.prompt({
  title: '修改【<span class="layui-font-red">标题</span>】名称',
  value: data.mingcheng,
  placeholder: '请输入名称',
  maxlength: '50',
}, function(value, index, elem){
  if(value === '') return elem.focus();
  layer.msg('获得：'+ util.escape(value)); // 显示 value
  // 关闭 prompt
  layer.close(index);
});
```

### 浏览器

版本 130.0.6723.70（正式版本

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
![image](https://github.com/user-attachments/assets/93f4433a-8432-4de0-9553-323848e3ffb2)

测试正常。
另外，`maxlength` 值最好写作数值型 `maxlength: 50`

**Comment by wangzhi0313** [comment]
![tijiao](https://github.com/user-attachments/assets/f424e9b8-532e-4a3b-b223-c16377dddb62)
这个验证怎么提前验证了，当我提交数据，这样的话这个验证就不走了，直接就提交走了
