### ISSUE TITLE
dropdown绑定的元素如果出现滚动条 并将滚动条下滑时 弹出的下拉框位置会发生偏移 偏移量为滚动的宽度或高度

### ISSUE THREAD

**Issue by qq1009404424** [layui/layui#2310]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

dropdown绑定的元素如果出现滚动条 并将滚动条下滑时 弹出的下拉框位置会发生偏移 偏移量为滚动的宽度或高度

### 业务代码

```auto
dropdown.render({
		elem : 'body', // 也可绑定到 document，从而重置整个右键
		trigger : 'contextmenu', // contextmenu
		isAllowSpread : false, // 禁止菜单组展开收缩
		style : 'width: 200px', // 定义宽度，默认自适应
		data : [ {
			title : '刷新页面',
			id : 'reload'
		}, {
			title : '关闭页面',
			id : 'close'
		} ],
		click : function(obj, othis) {
			if (obj.id === 'reload') {
				location.reload();
			} else if (obj.id == 'close') {
				var i = layer.confirm("是否关闭当前页面", {
					btn : [ "确认关闭", "取消" ]
				},
					function(text, index) {
						layer.close(i);
						window.parent.closeTab(window.name);
					}, null);
			}
		}
	});
```

### 截图补充

![QQ图片20241105120217](https://github.com/user-attachments/assets/dfe91137-b519-4c1a-b903-1802308ad27e)

### 浏览器

Firfox 132

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sancome** [comment]
我也遇到这个类似的问题，请问怎么解决的呢？

**Comment by qq1009404424** [comment]
> 我也遇到这个类似的问题，请问怎么解决的呢？

我是导入了一个老版本的Jquery 取消后直接用Layui自带的jquery 就没这个问题了
