### ISSUE TITLE
layui的table和treeTable能否增加个内部搜索

### ISSUE THREAD

**Issue by baobeiqie** [layui/layui#2312]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.18

### 问题描述

layui的table和treeTable能否增加个内部搜索，就是不去请求后台接口，在当前表格内搜索。

### 业务代码

```auto
无
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可借助 `table.cache` 和 `table.renderData(id)` 直接外部实现。

**Comment by baobeiqie** [comment]
好的，谢谢
