### ISSUE TITLE
更新到版本2.9.18后，flow组件，设置options._reload = true后，页面上内容没有清空并重新从第一页加载

### ISSUE THREAD

**Issue by 1051897274** [layui/layui#2313]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.18

### 问题描述

更新到版本2.9.18后，flow组件，设置options._reload = true后，页面上内容没有清空并重新从第一页加载，以前我提功能，flow重新从page=1加载，给的方案的是设置._reload = true，然后重新加载flow.load(Conf.flowoptions);现在page=1是生效的，但是next（）方式未生效。昨天我更新到2.9.18的

### 业务代码

```auto
Conf.flowoptions = {
    elem: '#table-row-box', // 流加载容器
    scrollElem: '#table-row-box', // 流加载容器
    mb: 360,
    done: function (page, next) { // 执行下一页的回调
        let send = {
            limit: 20,
            page,
            id: Conf.id,
            key: Conf.key,
            userInfo: $("#username").val(),
            sortId: Conf.sortId,
            scoreType: Conf.scoreType,
            orderBy: Conf.orderBy
        };
        H.get({
            url: "/api/comparison-log/score-list",
            data: send,
            load: false,
            suc: (d) => {
                Conf.key = d.extend;
                Conf.count = d.total;
                Conf.tpl.render({ pageData: d.pageData, first: Conf.tableData.length, edit: Conf.edit }, function (str) {
                    next(str, page * send.limit < Conf.count);
                    Conf.tableData.push(...d.pageData);
                });
                $("#count").text(Conf.count);
            }
        });
    }
};

//它处调用 
Conf.flowoptions._reload = true;
flow.load(Conf.flowoptions);
```

### 浏览器

edg

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by 1051897274** [comment]
我测试了一下，先往下滚动几页，然后触发load,一直到next()之前都是正常的，next()看上去未执行，页面未触发任何改变

**Comment by sentsim** [comment]
flow 组件没有 `_reload` 选项。若需要清空内容重新从第一页加载，建议在外部删除原有容器，然后重新执行 flow.load() 实现。

**Comment by 1051897274** [comment]
> flow 组件没有 `_reload` 选项。若需要清空内容重新从第一页加载，建议在外部删除原有容器，然后重新执行 flow.load() 实现。

我注意到在2.9.17版本进行了flow组件的回滚，目前我已将版本回退至2.9.16，功能正常使用。对于提出的用法问题，【建议在外部删除原有容器，然后重新执行 flow.load() 实现】我尝试了将容器执行empty()，会导致flow不再工作，删除是说删除整个html节点再重新添加节点绑定吗？
