### ISSUE TITLE
table table.resize(id);  可以重载表格高度

### ISSUE THREAD

**Issue by zhouqianyismx** [layui/layui#2314]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

table.resize(id); 目前只会重载宽度，希望可以支持高度重载

### 业务代码

```auto
table.resize(id);
```

### 浏览器

Microsoft Edge 版本 130.0.2849.68 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
```
table.resize(id, {
  height: 320
});
```
