### ISSUE TITLE
希望下个版本可支持设置全局主题色

### ISSUE THREAD

**Issue by arsnyeon** [layui/layui#2317]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.18

### 问题描述

现在只有少部分组件支持js渲染主题，如果要改其他组件的颜色就正常的麻烦，每个组件的样式都要拎出来改色，希望下个版本可支持直接在初始化时设置全局的主题色，谢谢！

### 业务代码

```auto
如问题描述
```

### 浏览器

Microsoft Edge 版本 125.0.2535.67 (正式版本) (64 位)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
https://gitee.com/layui/layui/issues/I5IBUX
