### ISSUE TITLE
弹窗弹起后，底部内容不可选择，或按钮不可点击，是否可以考虑增加一下这个功能，谢谢！

### ISSUE THREAD

**Issue by swanfly** [layui/layui#2319]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.7

### 问题描述

弹窗弹起后，底部内容不可选择，或按钮不可点击，是否可以考虑增加一下这个功能，谢谢！

### 业务代码

```auto
无
```

### 浏览器

Chrome 122.0.6261.69

### 演示地址

无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by swanfly** [comment]
> 很奇怪的需求，不过layer那么灵活没有办法实现？

我们的需求是，需要同时操作左侧弹出的菜单弹窗中的内容和遮罩层下的内容。要不然，还要关闭弹窗后，再打开，比较麻烦。

**Comment by LSL1618** [comment]
不是很明白，截图说明一下会更好。

**Comment by swanfly** [comment]
> 不是很明白，截图说明一下会更好。

如图所示的情况下，是无法点击或者拷贝选中的文字的，希望弹窗弹出后，可以拷贝弹窗下面的文字。不知道是否能够做到？

<img width="776" alt="image" src="https://github.com/user-attachments/assets/b27ddb07-470a-414b-8d6d-57d3835d9e60">

**Comment by swanfly** [comment]
> 这个需求应该是弹出时不加遮罩层就可以解决。

太好了，谢谢 ！
