### ISSUE TITLE
缩放表格后底部出现滚动条（无数据缩小时）

### ISSUE THREAD

**Issue by netmou** [layui/layui#2323]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.8

### 问题描述

![image](https://github.com/user-attachments/assets/7363b521-12f9-42c0-85be-92bbec3de1d0)

### 业务代码

```auto
无
```

### 浏览器

chrom 最新

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
升级到最新版试试：https://layui.dev/docs/2/versions.html

**Comment by netmou** [comment]
用的就是最新版

**Comment by netmou** [comment]
之前版本号写错了是2.9.18

**Comment by netmou** [comment]
![6pghLvgGAP](https://github.com/user-attachments/assets/9bd1fa12-05b1-463c-aa60-5a7138bfb421)

**Comment by netmou** [comment]
![6pghLvgGAP](https://github.com/user-attachments/assets/99957334-366c-4bfa-b002-c310049947cc)

**Comment by netmou** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
  <link href="//unpkg.com/layui@2.9.18/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<table class="layui-hide" id="ID-table-demo-filter"></table>
  
<!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
<script src="//unpkg.com/layui@2.9.18/dist/layui.js"></script>
<script>
layui.use(function(){
  var $ = layui.$;
  var table = layui.table;
  // 渲染
  table.render({
    elem: '#ID-table-demo-filter',
    url:'empty.json', // 此处为静态模拟数据，实际使用时需换成真实接口
    toolbar: 'default',
    height: 315,
    text : {none:'<img alt="暂无数据" src="nodata.png">'},
    cols: [[
        {field:'id', title:'ID', width:80, fixed: 'left'},
        {field:'username', title:'用户', width:120},
        {field:'sex', title:'性别'},
        {field:'city', title:'城市'},
        {field:'sign', title:'签名'},
        {field:'classify', title:'职业'}
      ]],
  });
});
</script>
</body>
</html>
```

**Comment by netmou** [comment]
empty.json
```json
{
  "code": 0,
  "msg": "",
  "count": 0,
  "data": []
}
```

**Comment by netmou** [comment]
![image](https://github.com/user-attachments/assets/7f62b776-d74e-47a0-979d-8d852cc5ca7a)
上面的代码选择layui文档，稍作调整，没有其他css\js干扰

**Comment by netmou** [comment]
// text : {none:'<img alt="暂无数据" src="nodata.png">'},    这行注释掉任然有滚动条
