### ISSUE TITLE
layer 弹出 ，关闭时导致electron 整个程序关闭

### ISSUE THREAD

**Issue by xiaoluGood** [layui/layui#2325]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.8

### 问题描述

我在electron 项目中使用 layer 弹窗，项目多处用到layer 加载iframe 页面， 在点击关闭弹窗按钮后，整个electron程序也自动关闭了，我查看了layer 的源码，发现问题所在:
iframe.contentWindow.close();   
源码中的这行代码会引起electron 整个程序关闭， 我去这行代码问题解决。

### 业务代码

```auto
layer.open({
        type: 2,
        title: 'iframe test',
        shadeClose: true,
        shade: 0.8,
        area: ['380px', '80%'],
        content: '/layer/test/1.html' 
      });
```

### 浏览器

electron14

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
尝试对 iframe 层设置 `id` 选项和 `hideOnClose: true` 规避该问题
