### ISSUE TITLE
treeTable如何实现行拖拽

### ISSUE THREAD

**Issue by Qq247534686** [layui/layui#2334]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.18

### 问题描述

treeTable如何实现行拖拽

### 业务代码

```auto
layui.treeTable.render({
                elem: '#bomtreetable',
                data: [],
                page: false,
                height: (window.innerHeight - 90) + 'px',
                cols: [[
                    { type: 'radio' },
                    { field: 'id', title: 'id', width: 80, hide: true },
                ]],
            });
```

### 浏览器

谷歌浏览器

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
treeTable 目前不支持行拖拽

**Comment by ioripalm** [comment]
我测试过使用参数:
drag:true,
和
rowDrag: {before:: function(obj) {},done: function(obj) {}},
可以实现根父级行的拖拽,不支持子拖拽
