### ISSUE TITLE
table行的上下移动时的更新缓存问题

### ISSUE THREAD

**Issue by zhanghong1peng** [layui/layui#2337]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

业务使用的table的编辑功能，在功能上有一个行的上移和下移功能，在移动后发现页面在编辑时时会带出错误的数据。
业务功能如下图所示：
上移功能代码如下：
 //监听上移
        $('#btnMoveup').on('click', function () {
            //获取当前选中行
            if (layui.table.CheckedRow == null) {
                layer.msg('请选择数据');
                return;
            }
            if (layui.table.CheckedRow.tr.prev().html() == null) {
                layer.msg('当前已是第一行，不能上移了');
                return;
            }
            //调整顺序
            var tr = layui.table.CheckedRow.tr;
            var tbData = layui.table.cache[layuitable.config.id];//获取缓存数据，layuitable.config.id记录的table的id
            var tem = tbData[tr.index()];
            var tem2 = tbData[tr.prev().index()];
            $(tr).insertBefore($(tr).prev());
            //更新缓存
            tbData[tr.index()] = tem;
            tbData[tr.next().index()] = tem2;
        });
业务操作如下：
1、选中第2行数据（“字段默认名称”为“关键词”的那行数据）；
2、点击“上移”按钮；
执行操作如如下图所示，看起来正常。
但是在选中行数据进行编辑时，出现了异常。
当前选中行已经移到了第一行，别名显示为“关键词”，但在鼠标选中进行编辑时，“关键词”会自动变成“编码”，鼠标再次移开时又变回“关键词”。如下图所示
感谢在百忙之中看一下此问题，谢谢

### 业务代码

```auto
//监听上移
        $('#btnMoveup').on('click', function () {
            //获取当前选中行
            if (layui.table.CheckedRow == null) {
                layer.msg('请选择数据');
                return;
            }
            if (layui.table.CheckedRow.tr.prev().html() == null) {
                layer.msg('当前已是第一行，不能上移了');
                return;
            }
            //调整顺序
            var tr = layui.table.CheckedRow.tr;
            var tbData = layui.table.cache[layuitable.config.id];//获取缓存数据，layuitable.config.id记录的table的id
            var tem = tbData[tr.index()];
            var tem2 = tbData[tr.prev().index()];
            $(tr).insertBefore($(tr).prev());
            //更新缓存
            tbData[tr.index()] = tem;
            tbData[tr.next().index()] = tem2;
        });
```

### 浏览器

Chorme版本 130.0.6723.117（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
虽然没有重现，但我猜问题原因和 data-index 有关，移动行之后需要**更新所有行**的 data-index Attribute 和 jQuery 缓存的 index，例如
```js
var index = trElem.index()
trElem.attr('data-index', index).data(index)
```
注意固定列和主体区域单独更新

**Comment by zhanghong1peng** [comment]
对应的图片没有上传成功，这里重新上传一下：
1、业务功能图片
![业务功能图片](https://github.com/user-attachments/assets/ce9ae4bf-146d-4884-a16a-97cac5feb731)

2、执行上移操作后的图片

![执行上移操作后的图片](https://github.com/user-attachments/assets/09407cb6-9705-4918-bf0d-214d960c91d0)

3、出现异常时的图片
![出现问题时的图片](https://github.com/user-attachments/assets/b4e6ad0f-14f8-4cac-ad32-d601d86e68e7)

**Comment by zhanghong1peng** [comment]
对应的图片没有上传成功，这里重新上传一下：
1、业务功能图片
![业务功能图片](https://github.com/user-attachments/assets/cc3e8b1e-878b-4eff-bdfe-b802355d0543)


2、执行上移操作后的图片
![执行上移操作后的图片](https://github.com/user-attachments/assets/e4121a05-b7f0-428d-967c-00e43121a5a2)


3、出现异常时的图片
![出现问题时的图片](https://github.com/user-attachments/assets/def5f073-b83e-4795-a4d2-602b5bc57f7e)

**Comment by zhanghong1peng** [comment]
> 虽然没有重现，但我猜问题原因和 data-index 有关，移动行之后需要**更新所有行**的 data-index Attribute 和 jQuery 缓存的 index，例如
> 
> ```js
> // 查找所有行遍历
> // 更新索引
> var index = trElem.index()
> trElem.attr('data-index', index).data(index)
> ```
> 
> 注意固定列和主体区域单独更新

非常感谢你的回复，手动调整了data-index后，发现问题依旧，如下图所示
![dataindex调整](https://github.com/user-attachments/assets/67f35cb2-b2ef-47f3-b999-c1d305008405)
还是要再找一下原因

**Comment by LSL1618** [comment]
改变数据顺序后试试重新renderData()或者reloadData()。

**Comment by zhanghong1peng** [comment]
> @zhanghong1peng 你好，请提供一个最小化的重现，以便我们为你协助排查问题。良好的重现应当包括但不仅限于：
> 
> * 产生问题的详细步骤
> * 与问题相关的完整代码
> * 在线 Demo (推荐通过 [stackblitz](https://stackblitz.com/) 或 [codepen](https://codepen.io/) 创建)
> 
> > 详见：🍀 [Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)
> > 延伸：👉 [为什么要提供最小化重现？](https://antfu.me/posts/why-reproductions-are-required-zh)
这是一个最小化的Demo，在选中上移或下移时会出现这个问题，还请帮忙看看，谢谢。
[demotablerowupdown.zip](https://github.com/user-attachments/files/17793963/demotablerowupdown.zip)

**Comment by Sight-wcg** [comment]
> > 虽然没有重现，但我猜问题原因和 data-index 有关，移动行之后需要**更新所有行**的 data-index Attribute 和 jQuery 缓存的 index，例如
> > ```js
> > // 查找所有行遍历
> > // 更新索引
> > var index = trElem.index()
> > trElem.attr('data-index', index).data(index)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意固定列和主体区域单独更新
> 
> 非常感谢你的回复，手动调整了data-index后，发现问题依旧，如下图所示 ![dataindex调整](https://private-user-images.githubusercontent.com/182314906/386942625-67f35cb2-b2ef-47f3-b999-c1d305008405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDk4MTEsIm5iZiI6MTczMTkwOTUxMSwicGF0aCI6Ii8xODIzMTQ5MDYvMzg2OTQyNjI1LTY3ZjM1Y2IyLWIyZWYtNDdmMy1iOTk5LWMxZDMwNTAwODQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNTU4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTQwMjE2M2M5NDk3ODJmZmQzYjA4NzViYjZmYzIwNjRlNjk5NWE0NGQ3ZDVlMDg0ZDkzYTM4NDA5MjQ3MDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YA5jWrHEfkwYq9WOU4UsM5e49oFliFd-lZeCmsVa8fc) 还是要再找一下原因

手动调整了data-index 指的是在开发者工具中手动改？上面建议的方案明确说明了需要修改哪些地方。
```
            // 写到上移代码最后面
            var i1 = tr.index();
            var i2 = tr.next().index();
            tr.attr('data-index', i1).data('index', i1);
            tr.next().attr('data-index', i2).data('index', i2);
            // 写到下移代码最后面
            var i1 = tr.index();
            var i2 = tr.prev().index();
            tr.attr('data-index', i1).data('index', i1);
            tr.prev().attr('data-index', i2).data('index', i2);
```

**Comment by zhanghong1peng** [comment]
> 改变数据顺序后试试重新renderData()或者reloadData()。

感谢你的建议，有测试过，这个方法不行。

> > > 虽然没有重现，但我猜问题原因和 data-index 有关，移动行之后需要**更新所有行**的 data-index Attribute 和 jQuery 缓存的 index，例如
> > > ```js
> > > // 查找所有行遍历
> > > // 更新索引
> > > var index = trElem.index()
> > > trElem.attr('data-index', index).data(index)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 注意固定列和主体区域单独更新
> > 
> > 
> > 非常感谢你的回复，手动调整了data-index后，发现问题依旧，如下图所示 ![dataindex调整](https://private-user-images.githubusercontent.com/182314906/386942625-67f35cb2-b2ef-47f3-b999-c1d305008405.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDk4MTEsIm5iZiI6MTczMTkwOTUxMSwicGF0aCI6Ii8xODIzMTQ5MDYvMzg2OTQyNjI1LTY3ZjM1Y2IyLWIyZWYtNDdmMy1iOTk5LWMxZDMwNTAwODQwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNTU4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTQwMjE2M2M5NDk3ODJmZmQzYjA4NzViYjZmYzIwNjRlNjk5NWE0NGQ3ZDVlMDg0ZDkzYTM4NDA5MjQ3MDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YA5jWrHEfkwYq9WOU4UsM5e49oFliFd-lZeCmsVa8fc) 还是要再找一下原因
> 
> 手动调整了data-index 指的是在开发者工具中手动改？上面建议的方案明确说明了需要修改哪些地方。
> 
> ```
>             // 写到上移代码最后面
>             var i1 = tr.index();
>             var i2 = tr.next().index();
>             tr.attr('data-index', i1).data('index', i1);
>             tr.next().attr('data-index', i2).data('index', i2);
>             // 写到下移代码最后面
>             var i1 = tr.index();
>             var i2 = tr.prev().index();
>             tr.attr('data-index', i1).data('index', i1);
>             tr.prev().attr('data-index', i2).data('index', i2);
> ```

非常感谢，这么做可以完美处理，谢谢！！

**Comment by zhanghong1peng** [comment]
已经完美解决，感谢大家的帮忙！

**Comment by Sight-wcg** [comment]
重新renderData()或者reloadData 怎么可能会不行？

**Comment by Sight-wcg** [comment]
> 改变数据顺序后试试重新renderData()或者reloadData()。
  > 感谢你的建议，有测试过，这个方法不行。

重新renderData()或者reloadData 怎么可能会不行？
