### ISSUE TITLE
模板引擎 换行报错 不知道算不算bug 

### ISSUE THREAD

**Issue by shenshu666** [layui/layui#2346]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.14

### 问题描述

模板引擎三元表达式 换行报错了。   因为代码自动排版三元表达式  就自动换行了。。。。  所以报错了。。。

### 业务代码

```auto
<div>
                身份证认证： {{- uc && uc.idCardFrontUrl&&uc.idCardBackUrl?"
                <span class="layui-badge layui-bg-green">已通过</span>
                ":"
                <span class="layui-badge">未通过</span>
                "}}
            </div>
```

### 浏览器

Edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
引号配的不对
```
<div>
身份证认证： {{- uc && uc.idCardFrontUrl&&uc.idCardBackUrl ? '<span class="layui-badge layui-bg-green">已通过</span>' : '<span class="layui-badge">未通过</span>' }}
</div>
```
<img width="376" alt="1" src="https://github.com/user-attachments/assets/56b0011b-c561-4845-a361-e0aab7e4de34">
