### ISSUE TITLE
兼容自定义多层数据结构

### ISSUE THREAD

**Issue by l511407563** [layui/layui#235]
#### 使用方法
![default](https://user-images.githubusercontent.com/25783291/39461248-fea666f4-4d3b-11e8-91fd-6ae516c56f17.png)

#### 新增数据处理方法
![default](https://user-images.githubusercontent.com/25783291/39461266-1615a444-4d3c-11e8-88df-b99861e23a14.png)

#### 处理数据总条数
![default](https://user-images.githubusercontent.com/25783291/39461265-15e41550-4d3c-11e8-8b6a-dc3808ff8071.png)

#### 处理获取不同格式表格数据
![default](https://user-images.githubusercontent.com/25783291/39461264-15aeb504-4d3c-11e8-8498-c8ea2365df93.png)

**Comment by l511407563** [comment]
@sentsin   闲心大佬, 跪求新增table的处理自定义多层级data的新版本, 我自己改的这个不知道会有什么bug, 只能暂时先使用。。。

**Comment by l511407563** [comment]
@sentsin 心姐，求更新table支持自定义多层级数据获取。目前只能自己写个暂时使用, 害怕在其他情况下会出现各种BUG

**Comment by cc0001** [comment]
高
期待早日加入这个功能

**Comment by cc0001** [comment]
期待早日添加这个功能
