### ISSUE TITLE
layui的默认尺寸都很大，比如：button是38px，input也是38px，在1k显示器下非常大

### ISSUE THREAD

**Issue by yswang0927** [layui/layui#2357]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.18

### 问题描述

layui的默认尺寸都很大，比如：button是38px，input也是38px，在1k显示器下非常大，效果比较差，**能否将尺寸的定义变成变量**，方便我们自己根据分辨率(1k,2k,4k,...)自适应调整尺寸来达到最优的展示效果？

目前我们采用的方法是一个个去覆盖相关的css定义，比如：.layui-btn {height:0.3rem;padding:0 0.1rem;} ，这样做工作量不仅很大且不友好。

### 业务代码

```auto
无
```

### 浏览器

chrome-v128

### 友好承诺

- [x] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
当前版本无法加入变量

**Comment by yswang0927** [comment]
> 当前版本考虑到广泛的兼容性，无法加入变量
好的，我们只能继续干苦力去css覆盖了，哈哈
