### ISSUE TITLE
CheckBox只有最后一个选择的值

### ISSUE THREAD

**Issue by kyoxt** [layui/layui#2359]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.8.11

### 问题描述

form下的同一组checkbox(相同的name),多选情况下,form的提交方法里的data.field里对应的键值对里的值只有选择的最尾的值,而不是所有选择的值。

虽然可以自行用代码调整提交的数据，但感觉就是很别扭。明明提交data.field就好了(checkbox处理正确的话）。

### 业务代码

```auto
form.on('submit(sub)', function(data){
    var field = data.field;    
    layer.alert(JSON.stringify(field), {
      title: '当前填写的字段值'
    });
 return false;
  });
```

### 浏览器

chrome 版本 130.0.6723.92（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
用这种方式可以 `name="arr[]"`
