### ISSUE TITLE
layer.photos 显示问题

### ISSUE THREAD

**Issue by cc0001** [layui/layui#236]
通过模板生成的 layer-photos-div, 然后调用 layer.photos 方法，第一次显示正常。

但是第二次生成  layer-photos-div， 然后再调用 layer.photos 方法时，
显示的是上一次的图片。
layui-layer-photos 里面的图片路径是  **上一次** layer-photos-div里面的路径。

![dfq03721](https://user-images.githubusercontent.com/38883119/39473300-bf8a2f10-4d80-11e8-999e-248b94633db2.png)

**Comment by SunLightFor6** [comment]
重新点击是不是就行了？
好像是第二次生成了div，调用了layer.photos方法，但此时方法内部首先"发现"的是已经存在的图片集合，而一经发现就显示出来，导致显示出错。而在此时，后台也已经“发现”了新加进去的图片，可是此时弹出层已经显示了错误内容。然后重新点击图片，显示就正常了。
我是修改了源码，在弹出窗口之前判断一下当前“发现”的图片数量是不是对的。
参考https://www.jianshu.com/p/c594811fa882
