### ISSUE TITLE
select 等组件没有 “内容清除” 功能

### ISSUE THREAD

**Issue by xtuul** [layui/layui#2360]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.20

### 问题描述

希望增加此功能

### 业务代码

```auto
希望select等输入框增加内容清除功能
```

### 截图补充

![image](https://github.com/user-attachments/assets/2e51fef4-6b07-4eb3-b1f9-3f432330fd3f)
这是input框的内容清除

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
当前版本无此功能计划。
