### ISSUE TITLE
treeTabler如果初始数据中childrens为空则无法异步加载子节点

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#2365]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.20

### 问题描述

我想在项目中实现多级菜单管理
默认加载一级菜单，其中children为空，通过showFlexIconIfNotParentc参数显示下拉框，同时配置async异步加载
但是点击后并没有发起异步请求

### 业务代码

```auto
tree: {
                    // 异步加载子节点
                    async: {
                        enable: true,
                        url: '2.json', // 此处为静态模拟数据，实际使用时需换成真实接口
                        autoParam: ["parent_name"]
                    },
                    view: {
                        // expandAllDefault: true,
                        showFlexIconIfNotParent: true,
                    },
                },
```

### 截图补充

![image](https://github.com/user-attachments/assets/af0c9854-f666-435f-aff7-96acba670841)

### 浏览器

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

### 演示地址

https://stackblitz.com/edit/fykh6i-51n64p?file=1.json,index.html,2.json

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
treeTable 根据 `isParent` key 来判断一个节点是否为父节点。没有 `isParent` key 时，根据 children length 更新 `isParent`。
后端返回数据中给父节点添加 `isParent` 属性即可。

**Comment by wwsuixin** [comment]
> treeTable 根据 `isParent` key 来判断一个节点是否为父节点。没有 `isParent` key 时，根据 children length 更新 `isParent`。 后端返回数据中给父节点添加 `isParent` 属性即可。

感谢大佬解惑

**Comment by Sight-wcg** [comment]
若是不想修改后端返回数据，可以在 parseDate 中格式化数据
```js
async:{
  parseData(res){

  }
}
```
