### ISSUE TITLE
官方文档存在笔误

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#2366]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.20

### 问题描述

https://layui.dev/docs/2/table/#demo-editable 功能说明页
有5处 dropdown写成了dropdpwn
![image](https://github.com/user-attachments/assets/b984742e-588f-4813-a808-58c6704d4c1c)

### 业务代码

```auto
dropdpwn-demo
```

### 浏览器

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

### 演示地址

https://layui.dev/docs/2/table/#demo-editable 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
已经更正，谢谢。
