### ISSUE TITLE
官方文档缺失项

### ISSUE THREAD

**Issue by purecici** [layui/layui#2369]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.20

### 问题描述

在v2.9.20版本的Layui官方文档 https://layui.dev/docs/2 的左侧功能菜单区域，缺失了“常用元素操作 element”功能项，
导致目前只能在v2.7.6旧文档中参考对应的api，而新的变更没法在此看到。

### 业务代码

```auto
常用元素操作element
```

### 截图补充

![jt](https://github.com/user-attachments/assets/9d1cb3fe-88a0-4314-ae19-f1d3caf39e9d)

### 浏览器

Edge v131.0.2903.70 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by purecici** [comment]
![jt](https://github.com/user-attachments/assets/05bf9f93-c0da-4584-925a-f08b5b281563)

**Comment by sentsim** [comment]
不是缺失，而是拆分成了 nav, tab, collapse 单独的文档

**Comment by purecici** [comment]
> 不是缺失，而是拆分成了 nav, tab, collapse 单独的文档

学习了，谢谢
