### ISSUE TITLE
选项卡tab第二个内容为table表格时，tab切换时列宽展示有问题

### ISSUE THREAD

**Issue by CrazyProgrammerPeng** [layui/layui#2370]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.20

### 问题描述

选项卡tab第二个内容为table表格时，列宽展示有问题

### 业务代码

```auto
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
    <link href="//unpkg.com/layui@2.9.20/dist/css/layui.css" rel="stylesheet" />
  </head>
  <body class="layui-padding-3">
    <div class="layui-tab layui-tab-brief">
      <ul class="layui-tab-title">
        <li class="layui-this">标签1</li>
        <li>标签2</li>
      </ul>
      <div class="layui-tab-content">
        <div class="layui-tab-item layui-show">1111</div>
        <div class="layui-tab-item">
          <table class="layui-hide" id="ID-table-demo-data"></table>
        </div>
      </div>
    </div>

    <!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
    <script src="//unpkg.com/layui@2.9.20/dist/layui.js"></script>

    <script>
      layui.use('table', function () {
        var table = layui.table;

        // 已知数据渲染
        var inst = table.render({
          elem: '#ID-table-demo-data',
          cols: [
            [
              //标题栏
              { field: 'id', title: 'ID', width: 80, sort: true },
              { field: 'username', title: '用户', width: 120 },
              { field: 'sign', title: '签名', minWidth: 160 },
              { field: 'sex', title: '性别', width: 80 },
            ],
          ],
          data: [
            {
              // 赋值已知数据
              id: '10001',
              username: '张三1',
              sex: '男',
              city: '浙江杭州',
              sign: '人生恰似一场修行',
            },
            {
              id: '10002',
              username: '张三2',
              sex: '男',
              city: '浙江杭州',
              sign: '人生恰似一场修行',
              experience: '12',
              LAY_CHECKED: true,
            },
          ],
          //skin: 'line', // 表格风格
          //even: true,
          page: true, // 是否显示分页
          limits: [5, 10, 15],
          limit: 5, // 每页默认显示的数量
        });
      });
    </script>
  </body>
</html>
```

### 截图补充

![image](https://github.com/user-attachments/assets/2778f448-95f3-47e4-9a08-e0a59b6c916c)

### 浏览器

Chrome  版本 131.0.6778.86

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by CrazyProgrammerPeng** [comment]
![image](https://github.com/user-attachments/assets/4d831819-02b7-4b27-acb6-a21bac4b9dbb)

**Comment by bxjt123** [comment]
使用tab切换事件，在切换时用`table.resize(id)`

**Comment by wangkang5** [comment]
> 使用tab切换事件，在切换时用`table.resize(id)`

我使用2.9.20版本也遇到了这个问题，table.resize(id)没有解决问题，甚至第一个tab切换回去后也进行resize的话，本来正常的表格也会被挤压

**Comment by lxflxf757** [comment]
呃，我也碰到这个问题了。之前不用怎么处理，一直正常的。

**Comment by lxflxf757** [comment]
这应该是版本的问题，还是等贤心更新吧。

**Comment by CrazyProgrammerPeng** [comment]
> 这应该是版本的问题，还是等贤心更新吧。

应该是的，我是升级最新版才出现的问题

**Comment by Sight-wcg** [comment]
Duplicate of #2358 #2183

@CrazyProgrammerPeng @wangkang5 @lxflxf757 @Yan-Jie-Peng

既然这么多人反馈 「2.9.20 tab 切换选项卡时执行 `table.resize()` 其中的表格宽度仍然不正确」，也许是表格宽度计算仍有边缘情况。
你们能提供**完整的重现代码**并录制**一段视频**吗？

**Comment by CrazyProgrammerPeng** [comment]
> Duplicate of #2358 #2183
> 
> @CrazyProgrammerPeng @wangkang5 @lxflxf757 @Yan-Jie-Peng
> 
> 既然这么多人反馈 「2.9.20 tab 切换选项卡时执行 `table.resize()` 其中的表格宽度仍然不正确」，也许是表格宽度计算仍有边缘情况。 你们能提供**完整的重现代码**并录制**一段视频**吗？

直接把我上面代码复制过去就会出现

**Comment by sentsim** [comment]
@Sight-wcg tab 事件中执行 `table.resize` 应该是没有问题。
看上述几位主要反馈的是之前不用做额外处理，2.9.19 之前的版本，确实不用 `table.reisze` 也是正常的。

**Comment by Sight-wcg** [comment]
总共 4 例报告，其中 2 例表示 tab 事件中执行 table.resize 无效，我比较好奇为什么无效，也许是某种很隐蔽的边缘情况。

table 内部获取隐藏容器内表格宽度的方法本身就是一种变通的方法，只能处理部分情况，考虑兼容性的情况下是无法完美解决问题的，所以该用 table.resize 的情况(例如 table 在没有大小的容器内渲染)最好手动调用。能用 table.resize 解决的问题，都不算问题。
