### ISSUE TITLE
layuiadmin在多标签模式下渲染form老是要错乱。

### ISSUE THREAD

**Issue by msmax589** [layui/layui#2375]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.16

### 问题描述

layuiadmin版本是2.5.2
我用的是单页模式，在多标签下，用view.render('/todo/demo',data)这样来渲染的话，老是要错乱。

### 业务代码

```auto
view(this.id).render('/todo/demo', data).done(function(){
                            form.render(null,'daye');
                            console.log('daye') 比如这个页面。
<div class="layui-form" lay-filter="daye" id="daye" style="padding: 20px 30px 0 0;">
    <h1>hello world</h1>
</div>
<script>
    layui.use(['form'],function(res){
        console.log(res)
        layui.form.render(null,'daye')
        console.log('成功')
    })
</script>
这个页面是这样的。 admin.popup({
                        title: '编辑'
                        , area: ['780px', '680px']
                        , id: 'LAY-popup-content-edit'
                        , success: function (layero, index) {
                            view(this.id).render('/cate/cate_form', data).done(function () {
                                form.render(null, 'layuiadmin-app-form-list-ketang-cate');
                            });
                        }
                    });当我在这个页面编辑过以后在返回来，todeo/demo这个页面就不显示了。渲染不出来了。
```

### 截图补充

<img width="332" alt="image" src="https://github.com/user-attachments/assets/51ffd655-2fd5-46f0-a3de-c3d77d43d072">
这是第一次是有的。
<img width="388" alt="image" src="https://github.com/user-attachments/assets/f64af160-a529-4f53-8325-7b434b066297">
我编辑过其它页面这是第一次渲染出来了。
<img width="440" alt="image" src="https://github.com/user-attachments/assets/5dbf462c-aeb0-4efb-8b2f-3b44ed9af4bd">
我去别的页面编辑后，这个就显示不出来了。没搞懂

### 浏览器

版本 131.0.6778.86（正式版本） (x86_64)

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
这里只受理 Layui 相关 Issue。模板主题相关的问题请发到对应的专区：https://dev.layuion.com/themes/layuiadmin/
