### ISSUE TITLE
希望input number添加千分位支持

### ISSUE THREAD

**Issue by DukeJin-Dev** [layui/layui#2379]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2_9_10

### 问题描述

在input number时,很多场景是输入金额,当金额很大时,用户阅读起来并不是很流畅(如 156464675.74),希望输入框支持千分位显示,在有需要时可配置,会极大提高阅读性.

### 业务代码

```auto
<input type="number" lay-affix="number" name="amount" lay-precision="2" step="0.01" lay-filter="amount" class="layui-input">
以下是我写的部分拓展,因无法操作输入框后面加减按钮,所以无法使用.可参考
layui.define(['form', 'jquery'], function(exports){
  let $ = layui.jquery;
  let form = layui.form;

  // 自定义组件
  let thousandInput = {
    render: function(options) {
      let elem = $(options.elem);
      var decimalPlaces = options.decimalPlaces || 2;
      // 创建隐藏输入框并插入DOM
      let hiddenInput = $('<div style="display:none"><input lay-affix="number" type="number" lay-filter="' + (options.name || elem.attr('name')) + '" lay-precision="2" step="0.01" id="' + (options.name || elem.attr('name')) + '" name="' + (options.name || elem.attr('name')) + '"></div>');
      elem.after(hiddenInput);
      elem.css('text-align', 'right')
      // 输入事件处理
      elem.on('input', function() {
          var unformattedValue = elem.val().replace(/,/g, '');
          if (!/^\d*\.?\d{0,6}$/.test(unformattedValue)) {
              elem.addClass('layui-form-danger')
              elem.val(null)
              $("#"+options.name).val(null)
              return
          } else {
              elem.removeClass('layui-form-danger')
          }
        if (unformattedValue.includes('.')) {
            var parts = unformattedValue.split('.');
            parts[1] = parts[1].slice(0, decimalPlaces);
            unformattedValue = parts.join('.');
        }
        var formattedValue = unformattedValue.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
        elem.val(formattedValue)
        $("#"+options.name).val(unformattedValue)
      });
       form.on('input-affix('+(options.name || elem.attr('name'))+')', );
      // 在元素属性中保存隐藏输入框引用
      elem.data('hiddenInput', hiddenInput);
    }
  };

  // 输出模块
  exports('thousandInput', thousandInput);
});
```

### 浏览器

Chrome Version 120.0.6099.200 

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
你说的是千位分隔符吧？设置 `<input type="text" lay-affix="number">`  也能正常显示，但因为 `,` 号不属于数值字符，因此无法参与加减，需要内部做特殊处理，后续再做考虑吧。

**Comment by Sight-wcg** [comment]
以下外部扩展方法仅供参考，自行扩展
https://learn.microsoft.com/zh-cn/previous-versions//ff382725(v=vs.85)?redirectedfrom=MSDN
```
          $('.layui-form .input-number-group').each(function (_, el) {
            var inputElement = $(el);
            inputElement.attr('type', 'text');
            var originValuePropDesc = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value');
            var formatter = function (value) {
              var values = value.split('.');
              values[0] = values[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');

              return values.join('.')
            };

            var parser = function (value) {
              return value.replace(/,/g, '')
            };

            Object.defineProperty(inputElement[0], 'value',
              $.extend({}, originValuePropDesc, {
                get: function () {
                  var formatedValue = originValuePropDesc.get.call(this);
                  return parser(formatedValue);
                },
                set: function (newValue) {
                  var oldValue = this.value;
                  originValuePropDesc.set.call(this, formatter(newValue));
                }
              })
            );
            // 初始渲染时触发 get set
            inputElement.val(inputElement.val());
            inputElement.off('input.plus').on('input.plus', function (e) {
              // 输入时触发 get set
              this.value = this.value
            })
          })
```

**Comment by DukeJin-Dev** [comment]
> 分享一个外部无痕扩展的方法，参考 laydate formatToDisplay 的实现。注意 get set 内只能用原生 JS 写，以精确控制行为，jQuery 内部一些兼容性方法频繁取值赋值，会导致无限递归。 https://learn.microsoft.com/zh-cn/previous-versions//ff382725(v=vs.85)?redirectedfrom=MSDN
> 
> ```js
>           $('.layui-form .input-number-group').each(function (_, el) {
>             var inputElement = $(el);
>             inputElement.attr('type', 'text');
>             var originValuePropDesc = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value');
>             var formatter = function (value) {
>               var values = value.split('.');
>               values[0] = values[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');
> 
>               return values.join('.')
>             };
> 
>             var parser = function (value) {
>               return value.replace(/,/g, '')
>             };
> 
>             Object.defineProperty(inputElement[0], 'value',
>               $.extend({}, originValuePropDesc, {
>                 get: function () {
>                   var formatedValue = originValuePropDesc.get.call(this);
>                   return parser(formatedValue);
>                 },
>                 set: function (newValue) {
>                   var oldValue = this.value;
>                   originValuePropDesc.set.call(this, formatter(newValue));
>                 }
>               })
>             );
>             // 初始渲染时触发 get set
>             inputElement.val(inputElement.val());
>             inputElement.off('input.plus').on('input.plus', function (e) {
>               // 输入时触发 get set
>               this.value = this.value
>             })
>           })
> ```

**Comment by DukeJin-Dev** [comment]
已采用,谢谢
