### ISSUE TITLE
关于 合并模块入口 问题

### ISSUE THREAD

**Issue by EagriSiol** [layui/layui#2383]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.20 

### 问题描述

https://layui.dev/docs/2/modules.html#index
我进行过多次各种方法 想要将多个模块打包为一个文件并进行一次加载 我现在有十几个文件并且可能还会增多  我尝试用gulp打包 一种情况(建立入口文件, 通过layui.define调用所有被打包模块) layui打印出来所有模块都正确的加载但是 layui.mod或者layui.use("mod") 就会 报undefined 另外一种方式 就是简单将所有模块合并为一个 文件  引入时 会多次加载同一个文件 这跟我想要减少请求背道而驰了

### 业务代码

```auto
layui.config({
    base: "/static/js/plugin/"
}).extend({
    mod1: "打包后的文件",
    mod2: "打包后的文件"
})
```

### 浏览器

all

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by EagriSiol** [comment]
我是想要实现 打包 所有模块 为一个文件减少http请求 但是 文档内没有教程  我使用提供的例子gulpfile.js 成功的将我所有模块打包 

gulpfile.js
`const gulp = require("gulp");
const uglify = require("gulp-uglify");
const cleanCSS = require("gulp-clean-css");
const concat = require("gulp-concat");
const sourcemaps = require("gulp-sourcemaps");
const del = require("del");

// 新增：打包 plugin.js 文件
const pluginJs = () => {
    // 使用通配符匹配所有 .js 文件，并允许空文件列表
    return gulp.src(["./public/static/js/plugin/**/*.js"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(uglify({
            output: {
                ascii_only: true // escape Unicode characters in strings and regexps
            },
            ie: true
        }))
        .pipe(concat("all.js", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/js/plugin"));
};

// 新增：打包 ui.css 文件
const uiCss = () => {
    return gulp.src(["./public/static/css/ui/**/*.css"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(cleanCSS({
            compatibility: "ie8"
        }))
        .pipe(concat("all.css", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/css/ui"));
};

// 清理旧文件的任务
const cleanPluginJs = () => {
    return del(["./public/static/js/plugin/all.js", "./public/static/js/plugin/all.js.map"]);
};

const cleanUiCss = () => {
    return del(["./public/static/css/ui/all.css", "./public/static/css/ui/all.css.map"]);
};

// 默认任务：先清理再构建
exports.default = gulp.series(
    gulp.parallel(cleanPluginJs, cleanUiCss), // 先执行清理任务
    gulp.parallel(pluginJs, uiCss)           // 再执行构建任务
);`

引入方式(原单文件)
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "*",
    mt*: "*",
})`


打包后 的 all.js  我不知道用什么办法引入 所有模块 如果这样引入 是可以使用的 但是 会多次引入 all.js这个文件
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "all",
    mt*: "all",
})`

**Comment by EagriSiol** [comment]
我是想要实现 打包 所有模块 为一个文件减少http请求 但是 文档内没有教程  我使用提供的例子gulpfile.js 成功的将我所有模块打包 

gulpfile.js
`const gulp = require("gulp");
const uglify = require("gulp-uglify");
const cleanCSS = require("gulp-clean-css");
const concat = require("gulp-concat");
const sourcemaps = require("gulp-sourcemaps");
const del = require("del");

// 新增：打包 plugin.js 文件
const pluginJs = () => {
    // 使用通配符匹配所有 .js 文件，并允许空文件列表
    return gulp.src(["./public/static/js/plugin/**/*.js"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(uglify({
            output: {
                ascii_only: true // escape Unicode characters in strings and regexps
            },
            ie: true
        }))
        .pipe(concat("all.js", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/js/plugin"));
};

// 新增：打包 ui.css 文件
const uiCss = () => {
    return gulp.src(["./public/static/css/ui/**/*.css"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(cleanCSS({
            compatibility: "ie8"
        }))
        .pipe(concat("all.css", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/css/ui"));
};

// 清理旧文件的任务
const cleanPluginJs = () => {
    return del(["./public/static/js/plugin/all.js", "./public/static/js/plugin/all.js.map"]);
};

const cleanUiCss = () => {
    return del(["./public/static/css/ui/all.css", "./public/static/css/ui/all.css.map"]);
};

// 默认任务：先清理再构建
exports.default = gulp.series(
    gulp.parallel(cleanPluginJs, cleanUiCss), // 先执行清理任务
    gulp.parallel(pluginJs, uiCss)           // 再执行构建任务
);`

引入方式(原单文件)
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "*",
    mt*: "*",
})`


打包后 的 all.js  我不知道用什么办法引入 所有模块 如果这样引入 是可以使用的 但是 会多次引入 all.js这个文件
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "all",
    mt*: "all",
})`

**Comment by EagriSiol** [comment]
我是想要实现 打包 所有模块 为一个文件减少http请求 但是 文档内没有教程  我使用提供的例子gulpfile.js 成功的将我所有模块打包 

gulpfile.js
`const gulp = require("gulp");
const uglify = require("gulp-uglify");
const cleanCSS = require("gulp-clean-css");
const concat = require("gulp-concat");
const sourcemaps = require("gulp-sourcemaps");
const del = require("del");

// 新增：打包 plugin.js 文件
const pluginJs = () => {
    // 使用通配符匹配所有 .js 文件，并允许空文件列表
    return gulp.src(["./public/static/js/plugin/**/*.js"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(uglify({
            output: {
                ascii_only: true // escape Unicode characters in strings and regexps
            },
            ie: true
        }))
        .pipe(concat("all.js", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/js/plugin"));
};

// 新增：打包 ui.css 文件
const uiCss = () => {
    return gulp.src(["./public/static/css/ui/**/*.css"], { allowEmpty: true })
        .pipe(sourcemaps.init())
        .pipe(cleanCSS({
            compatibility: "ie8"
        }))
        .pipe(concat("all.css", { newLine: "" }))
        .pipe(sourcemaps.write("."))
        .pipe(gulp.dest("./public/static/css/ui"));
};

// 清理旧文件的任务
const cleanPluginJs = () => {
    return del(["./public/static/js/plugin/all.js", "./public/static/js/plugin/all.js.map"]);
};

const cleanUiCss = () => {
    return del(["./public/static/css/ui/all.css", "./public/static/css/ui/all.css.map"]);
};

// 默认任务：先清理再构建
exports.default = gulp.series(
    gulp.parallel(cleanPluginJs, cleanUiCss), // 先执行清理任务
    gulp.parallel(pluginJs, uiCss)           // 再执行构建任务
);`

引入方式(原单文件)
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "*",
    mt*: "*",
})`


打包后 的 all.js  我不知道用什么办法引入 所有模块 如果这样引入 是可以使用的 但是 会多次引入 all.js这个文件
`layui.config({
    base: "/static/js/plugin/"
}).extend({
    mt*: "all",
    mt*: "all",
})`

**Comment by EagriSiol** [comment]
```
<!--common 主控-->
<script src="@fileUrl/static/js/common.js?v=@version" type="text/javascript"></script>  
```
以上全部都在这个文件内 这个文件负责 加载所有插件

并且我可以在使用使用时调用  ` layui.use(["mt*", "mt*"], function () {})`

**Comment by sentsim** [comment]
引入的 Layui 是源码版本（src），还是构建后的呢（dist）？
源码版本不适合这类扩展模块合并的场景，必须引入构建后的 `layui.js`

**Comment by EagriSiol** [comment]
layui/v2.9.18/layui.js 我用的是 dist版本     你将所有的模块都打包为  layui.js  我也想将 所有我做的模块打包为 all.js 但是我又不想修改你的源码
