### ISSUE TITLE
layer.confirm 能够加入回车确认 esc关闭类快捷键

### ISSUE THREAD

**Issue by lgh-1997** [layui/layui#2384]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.20

### 问题描述

项目中使用了大量layer.confirm作为操作提示，目前需要回车确认 esc关闭快捷操作confirm框，是否能够新增该功能或者在layer.js源码部分给于允许范围内的技术支持回复

### 业务代码

```auto
无
```

### 浏览器

版本 133.0.6847.2（正式版本）dev （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
尝试在 `layer.confirm` 的 `success` 事件中外部实现，在 `keydown` 事件中判断回车键码执行 `layer.close()` 关闭，不会太难。
