### ISSUE TITLE
动态新增多个复选框时如何监听事件

### ISSUE THREAD

**Issue by wwsuixin** [layui/layui#2385]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.20

### 问题描述

有这样一个业务需求，通过异步加载了input  textarea  checkbox  等多个表单框，通过修改某个表单值自动生成结果，其中checkbox的复选框事件只能监听单个layui-filter，而动态生成的filter值是不一样的，请问有其他办法吗

### 业务代码

```auto
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Demo</title>
    <!-- 请勿在项目正式环境中引用该 layui.css 地址 -->
    <link href="//unpkg.com/layui@2.9.20/dist/css/layui.css" rel="stylesheet" />
  </head>
  <body class="layui-padding-3">
    <div class="layui-form">
      <div class="layui-form-item" id="demo"></div>
      <div class="layui-form-item">
        <button class="layui-btn" lay-submit lay-filter="demo-checkbox-submit">
          确认
        </button>
      </div>
    </div>

    <!-- 请勿在项目正式环境中引用该 layui.js 地址 -->
    <script src="//unpkg.com/layui@2.9.20/dist/layui.js"></script>
    <script>
      layui.use(function () {
        var form = layui.form;
        var layer = layui.layer;
        var $ = layui.$;
        var html = ``;
        var data_list = [1, 2, 3, 4];
        data_list.forEach((item) => {
          html += `   <input type="checkbox" name="agreement_${item}" value="1" title="是否同意-${item}" lay-filter="demo-checkbox-filter-${item}">`;
        });
        $('#demo').html(html);
        form.render();
        // checkbox 事件
        form.on('checkbox(demo-checkbox-filter-1)', function (data) {
          var elem = data.elem; // 获得 checkbox 原始 DOM 对象
          var checked = elem.checked; // 获得 checkbox 选中状态
          var value = elem.value; // 获得 checkbox 值
          var othis = data.othis; // 获得 checkbox 元素被替换后的 jQuery 对象

          layer.msg('checked 状态: ' + elem.checked);
        });
      });
    </script>
  </body>
</html>
```

### 浏览器

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

### 演示地址

https://stackblitz.com/edit/cyp8ztvj?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
不设置 filter 即可，例如
```diff
- form.on('checkbox(demo-checkbox-filter-1)', function (data) {
+ form.on('checkbox', function (data) {
```

关于他们的区别，可参考文档 https://layui.dev/docs/2/base.html#api
![image](https://github.com/user-attachments/assets/8877a307-7015-454d-86b7-e65d4e7a84db)

**Comment by wwsuixin** [comment]
> 不设置 filter 即可，例如
> 
> ```diff
> - form.on('checkbox(demo-checkbox-filter-1)', function (data) {
> + form.on('checkbox', function (data) {
> ```
> 
> 关于他们的区别，可参考文档 https://layui.dev/docs/2/base.html#api ![图像](https://private-user-images.githubusercontent.com/26325820/393520618-8877a307-7015-454d-86b7-e65d4e7a84db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Nzk0MjksIm5iZiI6MTczMzU3OTEyOSwicGF0aCI6Ii8yNjMyNTgyMC8zOTM1MjA2MTgtODg3N2EzMDctNzAxNS00NTRkLTg2YjctZTY1ZDRlN2E4NGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEzNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMTFmYmVlYjRmY2UwNWMyMWNkMDg2MDljMTQ5OTZjNGE4NzU1ZTNhNDFiNDZlMWFkZjliMzU4ZWFhOGQxY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JXVWT_qmVwd_32QcsSSbQ0w2jA6gYwYORlp-Qq0GVjI)

谢谢大佬  我尝试了  checkbox()   原来后面的括号也是不需要的
