### ISSUE TITLE
表单校验错误提示图标和位置是否可以支持配置

### ISSUE THREAD

**Issue by ynahauH** [layui/layui#2388]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.14

### 问题描述

设置验证异常时的提示层模式值为msg时，提示位置默认为页面中间，能否支持参数调整到页面顶部
![image](https://github.com/user-attachments/assets/50a2efe3-5410-4095-8d46-ba5361d54254)

### 业务代码

```auto
无
```

### 浏览器

最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by sentsim** [comment]
可通过重写内置的验证规则自定义提示风格
参考：https://layui.dev/docs/2/form/#verify
