### ISSUE TITLE
layui 表格 有个筛选记忆功能，如果要实现重新打开页面的时候，还是筛选之前的状态，如果要保留筛选之后的状态，有什么思路解决吗？

### ISSUE THREAD

**Issue by a1b2c3c** [layui/layui#2390]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.20

### 问题描述

layui 表格 有个筛选记忆功能，如果要实现重新打开页面的时候，还是筛选之前的状态，如果要保留筛选之后的状态，有什么思路解决吗？

### 业务代码

```auto
暂无
```

### 浏览器

chrome

### 演示地址

暂无

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
表格文档里搜索筛选列记忆，参考实现思路，或者 gitee 议题里找一下，应该有筛选记忆的解决方法。

**Comment by a1b2c3c** [comment]
好的，我找下

**Comment by Sight-wcg** [comment]
破戒了，我确实不该处理这类问题的

**Comment by hulang** [comment]
https://gitee.com/saodiyang/layui-soul-table
看看吧。。。实在不行，官方整合一下也可以。。。主要是：叶子老大，更新没有时间
@Sight-wcg

**Comment by hulang** [comment]
> 破戒了，我确实不该处理这类问题的

思路应该是：https://layui.dev/docs/2/base.html#data，来实现。。。

**Comment by a1b2c3c** [comment]
我知道怎么解决了，关闭了，谢谢了
