### ISSUE TITLE
[BUG] treetable  第一个父节点无法异步加载子节点 (实际有3层，只加载到第2层)

### ISSUE THREAD

**Issue by YouZiXiL** [layui/layui#2396]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.8.12

### 问题描述

treetable  第一个父节点无法异步加载子节点 (实际有3层，只加载到第2层)

### 业务代码

```auto
layui.use(['table', 'form', 'common', 'jquery'], function () {
        let table = layui.table;
        let form = layui.form;
        let $ = layui.jquery;
        let common = layui.common;
        var treeTable = layui.treeTable;
        var layer = layui.layer;
        // 渲染
        var inst = treeTable.render({
            elem: '#ID-treeTable-demo',
            id: 'ID-treeTable-demo',
            url: SELECT_API + "?parent_id=0" , // 此处为静态模拟数据，实际使用时需换成真实接口
            tree: {
                customName: {
                    'name': 'nickname',
                    'pid':'parent_id'
                },
                // 异步加载子节点
                async: {
                    enable: true,
                    url: SELECT_API, // 此处为静态模拟数据，实际使用时需换成真实接口
                    autoParam: ["parent_id=id"],

                },
            },
            toolbar: '#TPL-treeTable-demo',
```

### 截图补充

![image](https://github.com/user-attachments/assets/49db1a65-7a48-4caa-a9f2-2e3ed7f32966)
![image](https://github.com/user-attachments/assets/ad6ee976-61d8-47cb-abb2-615e43e1393b)
![image](https://github.com/user-attachments/assets/9a4c0245-0457-4f44-9538-3239d2f68813)

### 浏览器

Chrome 131.0.6778.109（正式版本） （64 位）

### 演示地址

https://stackblitz.com/edit/stackblitz-starters-vn5u15bp?file=index.html

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
layui 2.9.20能否重现？

**Comment by YouZiXiL** [comment]
> layui 2.9.20能否重现？

替换了最新版依然会重现

**Comment by YouZiXiL** [comment]
![Uploading image.png…]()
最新版依然重现

**Comment by YouZiXiL** [comment]
@Sight-wcg  大哥 这个bug太严重了

**Comment by YouZiXiL** [comment]
@sentsim

**Comment by YouZiXiL** [comment]
重现Demo https://stackblitz.com/edit/stackblitz-starters-vn5u15bp?file=index.html

**Comment by YouZiXiL** [comment]
@sentsim 已复现demo

**Comment by Sight-wcg** [comment]
懒加载父节点不需要携带所有子节点信息，即不需要 children 属性，需要添加 isParent 属性

不想改后端的话就在 parseData 里格式化
![Screenshot_2024-12-13-13-02-40-460_com.kiwibrowser.browser.jpg](https://github.com/user-attachments/assets/de293222-8bb4-4c83-a66c-5c963e054735)

**Comment by YouZiXiL** [comment]
感谢 已解决
