### ISSUE TITLE
颜色选择器清空后，点击右侧颜色滑块，色值出现-，色值错误

### ISSUE THREAD

**Issue by lxland** [layui/layui#2397]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.18

### 问题描述

颜色选择器初始色值设置#000000或者点击清空后，点击右侧颜色滑块，色值中出现-，色值错误
![1234](https://github.com/user-attachments/assets/e937790b-ac3b-4bba-96ca-3fc86a41451c)

### 业务代码

```auto
layui.use(function(){
  var colorpicker = layui.colorpicker;
  var $ = layui.$;
  // 渲染
  colorpicker.render({
    elem: '#ID-colorpicker-demo-form',
    color: '#000000',
    done: function(color){
      $('#ID-colorpicker-demo-form-color').val(color);
    }
  });
});
```

### 浏览器

Chrome

### 演示地址

https://layui.dev/docs/2/colorpicker/

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
由 #1863 造成的问题
