### ISSUE TITLE
现在的颜色值都是写死的，后续考虑将颜色加入到变量中吗，现在对于色彩定制实现的复杂度有一点高

### ISSUE THREAD

**Issue by 1617184046** [layui/layui#2400]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [x] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [x] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.20

### 问题描述

现在的颜色值都是写死的，后续考虑将颜色加入到变量中吗，现在对于色彩定制实现的复杂度有一点高

### 业务代码

```auto
-
```

### 浏览器

_

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
2.x 暂无计划。

目前应该不会有大的变动，有人感兴趣的话可以考虑做社区版的。
