### ISSUE TITLE
页面全屏显示的情况下，打开iframe类型的弹窗不能显示在顶层

### ISSUE THREAD

**Issue by ynahauH** [layui/layui#2409]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.14

### 问题描述

layer.open打开的弹窗不能显示在全屏模式上

### 业务代码

```auto
1. requestFullscreen API实现全屏
2. window.top.layer.open({type: 2})打开一个弹窗页面
```

### 浏览器

最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by caicai-bb** [comment]
var elem = document.getElementById("page_div");
if (elem.requestFullscreen) {
      elem.requestFullscreen();
    } else if (elem.mozRequestFullScreen) { /* Firefox */
      elem.mozRequestFullScreen();
    } else if (elem.webkitRequestFullscreen) { /* Chrome, Safari & Opera */
      elem.webkitRequestFullscreen();
    } else if (elem.msRequestFullscreen) { /* IE/Edge */
      elem.msRequestFullscreen();
    }
把父div设置全屏后 
layer.open(）打开的弹窗没在全屏上
取消全屏后才会看到layer.open()的内容
