### ISSUE TITLE
upload组件，选择添加了几个文件后，再点击选择，这时候不添加新的文件，上传功能失效

### ISSUE THREAD

**Issue by junjun231953** [layui/layui#241]
如题！

**Comment by hubyuan** [comment]
upload组件，选择添加了几个文件后，再点击选择，这时候添加超出限制大小的文件，上传功能失效。同上

**Comment by zYunQiShi** [comment]
我最近也遇到类似问题然后解决了。你可以看看有没有帮助嘿嘿
[https://blog.csdn.net/qq_42996171/article/details/103292900](url)

**Comment by zYunQiShi** [comment]
> 上传组件，选择添加了几个文件后，再点击选择，这时候添加超过限制大小的文件，上传功能失效。同上

我最近也遇到类似问题然后解决了。你可以看看有没有帮助嘿嘿（写在csdn）
https://blog.csdn.net/qq_42996171/article/details/103292900

**Comment by zYunQiShi** [comment]
已解决并pull request，请查看一下哈
