### ISSUE TITLE
lay-affix="clear"的问题

### ISSUE THREAD

**Issue by pmmiaoAliyun** [layui/layui#2416]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.20

### 问题描述

input type="text"，使用了lay-affix="clear"，但如果该文本框是js改变的值，此时当焦点进入到文本框时，clear并不能显示出来。此时，如果改变一下文本框的值，则clear会显示出来
建议：不管在什么情况下，只要文本框中有值，焦点到文本框时，均要显示clear

### 业务代码

```auto
<div class="layui-form-item" style="margin-bottom:0">
			<div class="layui-inline" style="width:100%;display:inline-flex;margin-bottom:0">
				<div class="layui-input-inline" style="width:56%;overflow:visible;position:relative;padding:0 2px 0 5px" id="barcodeDiv">
                    <input type="text" name="tBarCode" id="tBarCode" class="layui-input" placeholder="药品条形码…" lay-affix="clear"/>
				</div>
				<div class="layui-input-inline" style="width:23%;overflow:visible;position:relative;padding:0 5px 0 0" id="medicineDiv">
                    <input type="text" name="tMedicine" id="tMedicine" class="layui-input" placeholder="药名…" lay-affix="clear"/>
				</div>
				<div class="layui-input-inline" style="width:16%;overflow:visible;position:relative" id="buttonDiv">
                    <button class="layui-btn" lay-submit="" lay-filter="search">查找</button>
				</div>
            </div>
        </div>
```

### 浏览器

版本 131.0.6778.205（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by bxjt123** [comment]
用 `form.val(filter, obj)` 给表单的文本框赋值即可
