### ISSUE TITLE
tree树组件 选中父节点后自动选中子节点

### ISSUE THREAD

**Issue by Nobbyte** [layui/layui#2423]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.20

### 问题描述

树组件 选中父节点后自动选中子节点。
举个例子，有一个父节点A，下面有子节点A1,A2,A3
我选中A1，然后获取已选中的就会包含A和A-1，但是通过数据渲染的时候，如果设置A和A1选中，A2和A3都会一并被选中。我不清楚这是否属于BUG，已经有许多人提出这样的问题。

[[解决layui的bug 在layui tree 组件中 禁用选中父节点后自动选中子节点功能](https://www.cnblogs.com/wordblog/p/17581386.html)](https://www.cnblogs.com/wordblog/p/17581386.html)
[layui tree组件 回显bug(只要勾选一个子集在回显的时候会勾选全部子集)](https://juejin.cn/post/6981639481212289060)
[layui tree 组件 回显 bug](https://www.jianshu.com/p/968cfa8b19b3)
等等。

并且树组件不支持数据平铺格式，tableTree支持数据平铺格式

### 业务代码

```auto
tree.render({

})
```

### 浏览器

Chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
#1606
