### ISSUE TITLE
treeTable 选中子节点时如何同时选中父节点

### ISSUE THREAD

**Issue by th8664484** [layui/layui#2424]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.18

### 问题描述

treeTable 选中子节点时如何同时选中父节点，如tree组件演示的效果。
如果可以请告知如何设置

### 业务代码

```auto
treeTable.checkStatus(id)
获取不到半选中的数据
```

### 截图补充

![image](https://github.com/user-attachments/assets/031ffc72-fc49-4c67-8bce-3875bc06b9fd)
![image](https://github.com/user-attachments/assets/6263ac82-1220-47f4-a5d8-bfc9bd505d28)

### 浏览器

edge

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
```
table.checkStatus(id, true);
```

**Comment by Sight-wcg** [comment]
「如 tree 演示的效果」可以设置 tree.data.cascade:'none' 关闭选中联动，然后在选中事件中通过数据的父节点 id，向上递归获取父级数据并用 setRowChecked() 选中行来实现。

**Comment by th8664484** [comment]
好的，感谢
