### ISSUE TITLE
请下有没有考虑增加table列的拖动换列位置并且能够记忆的功能？

### ISSUE THREAD

**Issue by a1b2c3c** [layui/layui#2432]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.20

### 问题描述

请下有没有考虑增加table列的拖动换列位置的功能？

### 业务代码

```auto
暂无
```

### 截图补充

![image](https://github.com/user-attachments/assets/dafc4665-1e5f-4598-8c7d-7e89f46219b3)

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by LSL1618** [comment]
这种功能说实话没啥实用性，自己也可以实现，改变cols数组元素位置然后重新render或者reload就行了。
