### ISSUE TITLE
调整dropdown的click触发方式

### ISSUE THREAD

**Issue by lanrenbulan** [layui/layui#2433]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.20

### 问题描述

目前利用dropdown的content来实现自定义内容，但又想借用原默认的ul.li的click事件，因为需要会动态添加li，是否可以将li.click改成委托呢。

之前用reloadData()的方式实现，但总对表单不友好，比如根据input事件来过滤ul.li的显示和隐藏，reload后就会丢失focus()，总要单独处理。

https://stackblitz.com/edit/stackblitz-starters-2vjeuumw?file=index.html

### 业务代码

```auto
<div class="layui-dropdown layui-border-box layui-panel layui-anim layui-anim-downbit" lay-dropdown-id="22" style="left: 474.4px; top: 1690.78px;">
  <!--content为下面的元素-->
  <div>自义定</div>
  <ul class="layui-menu layui-dropdown-menu">
    <li><div class="layui-menu-body-title">menu item test 111</div></li>
    <li><div class="layui-menu-body-title">menu item test 222</div></li>
    <li><div class="layui-menu-body-title">menu item test 333</div></li>
    <li>other</li>
  </ul>
</div>
```

### 浏览器

版本 131.0.6778.205（正式版本） （64 位）

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by lanrenbulan** [comment]
```
//  这样是否可行
 mainElem.find('.layui-menu').on('click', 'li', function(e) {

});
```

**Comment by lanrenbulan** [comment]
遇到另一个问题，当页面有iframe时,dropdown为非hover触发时，点击到iframe内容区时，不能关闭dropdown。

**Comment by Sight-wcg** [comment]
> 遇到另一个问题，当页面有iframe时,dropdown为非hover触发时，点击到iframe内容区时，不能关闭dropdown。

https://github.com/layui/layui/commit/1fe122bbb4f6390c61f61114df0d7a37127593e6

你可以新创建一个议题吗，预计会放到 2.9.22 解决。为了尽可能保证新版本稳定，2.9.21-rc 除严重问题外，只解决这个版本内的提交产生的问题。

**Comment by lanrenbulan** [comment]
> > 遇到另一个问题，当页面有iframe时,dropdown为非hover触发时，点击到iframe内容区时，不能关闭dropdown。
> 
> [1fe122b](https://github.com/layui/layui/commit/1fe122bbb4f6390c61f61114df0d7a37127593e6) 这里之前写的时候我记得遇到过浏览器兼容性问题，原生代码要测各种浏览器，略麻烦一些，很可能会引入新的问题。
> 
> 你可以新创建一个议题吗，预计会放到 2.9.22 解决。为了尽可能保证新版本稳定，2.9.21-rc 除严重问题外，只解决这个版本内的提交产生的问题。

已创建https://github.com/layui/layui/issues/2434

**Comment by Sight-wcg** [comment]
> ```
> //  这样是否可行
>  mainElem.find('.layui-menu').on('click', 'li', function(e) {
> 
> });
> ```

修改后只有阻止事件冒泡的行为变化，我也不确定会不会有什么边缘情况

你可以暂时用这个变通的方法
> 动态添加li，是否可以将li.click改成委托
```js
    ready:function(){     
         var that = this;
         // 移除 dropdown li 原来的事件
        $dropdown.find('li').off('click');
        $dropdown.on('click', 'li', function (e) {
          var el = $(this);
          var data = el.data('select-opt-data');
          that.click(data, el, e);
        });
    }
```

> 用reloadData()的方式实现，但总对表单不友好，比如根据input事件来过滤ul.li的显示和隐藏，reload后就会丢失focus()，总要单独处理

这种自定义场景每次重载全部内容有点麻烦，建议自定义一个局部刷新的方法
```js
  // header|body|footer 或者直接传要更新区域的 jQuery 对象
  Class.prototype.updateDropdownContent = function (type, opt) {
    if (type === body) {
      this.reloadOptionElems(opt.xxx);
    }
    else if
    ...
  };
  Class.prototype.reloadOptionElems = function (str) {
     var optionsContainer = dropdownPanel.find('xxx')
     optionsContainer.html(str)
  };
```

**Comment by lanrenbulan** [comment]
我先这样的操作下
