### ISSUE TITLE
问下模版写法，可以写到样式里面吗？

### ISSUE THREAD

**Issue by a1b2c3c** [layui/layui#2435]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

2.9.20

### 问题描述

问下模版写法，可以写到样式里面吗？我试了好像咋写都报错，是不是不能写到样式里面？

### 业务代码

```auto
<script type="text/html" id="ID-table-demo-templet-user">
    <span style="color:{{=d.StateColor2 }}"> {{=d.IsPaymentValue}}</span>
</script>
```

### 浏览器

chrome

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by lanrenbulan** [comment]
建议提供一个在线示例

**Comment by a1b2c3c** [comment]
已经找到解决方案了

**Comment by PTA00** [comment]
他没说解决方案，那么我来补一个方案😃：（旧模板写法）
```
{{# var tempstyle=`style="color: ${task.color};"`}}
<span {{- tempstyle }}>{{ task.room }}</span>
```

**Comment by PTA00** [comment]
> 他没说解决方案，那么我来补一个方案😃：（旧模板写法）
> 
> ```
> {{# var tempstyle=`style="color: ${task.color};"`}}
> <span {{- tempstyle }}>{{ task.room }}</span>
> ```

**这么做的原因是解决vscode css属性误报错误，其实直接写`style="color: {{ task.color }};"`也是相同的，只要你觉得报error不碍事**
