### ISSUE TITLE
关于相同 name 的 checkbox，将值序列化为数组的建议

### ISSUE THREAD

**Issue by sinbh** [layui/layui#2441]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

功能请求

### 使用版本

v2.9.21-rc1

### 问题描述

// 取值
form.val('filter')  =>  {like: ['write', 'read']} 
如果只选择一个值时,能不能改成:  {like: ['read']}, 依然还是数组,目前好像是=>  {like: 'read'}, like值为字符串, 感觉还是不太方便, 如果不论选择多少个都统一为数组就更方便使用了,不知道这样是不是更合适些?

### 业务代码

```auto
<div class="layui-input-block">
  <input type="checkbox" name="like" value="write" title="写作">
  <input type="checkbox" name="like" value="read" title="阅读">
  <input type="checkbox" name="like" value="daze" title="发呆">
</div>

// 赋值
form.val('filter', {
  like: ['write', 'read'] // value 包含于数组值的 checkbox 将被选中
})
// 取值
form.val('filter')  =>  {like: ['write', 'read']} // 未选中返回 null
```

### 浏览器

任意

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
是的，复选框无论选择多少个都统一为数组会更好，但这会和以前的行为不一致。
