### ISSUE TITLE
IE8中下拉options不支持-1

### ISSUE THREAD

**Issue by strivezsh** [layui/layui#253]
form.js 250行
,selected = $(select.options[select.selectedIndex]) //获取当前选中项
selectedIndex会有等于-1的情况
这样IE8会报 对象不支持此属性或方法

**Comment by strivezsh** [comment]
造成这种情况是 因为 我
$(select).empty();
了一下
然后render的时候 就出现 -1 的情况

**Comment by dotaconan** [comment]
form.js 250行
修改为：
 ,selected = $(select.selectedIndex===-1?"":select.options[select.selectedIndex]) //获取当前选中项
