### ISSUE TITLE
请问一个form表单里的事件监听怎么写？

### ISSUE THREAD

**Issue by linyasa** [layui/layui#26]
通过form.on来监听好像只能监听submit之类的事件。 

如果我想监听form表单里一个普通的button事件。应该怎么写。
比如
```
<div class="layui-form-item">
            <label class="layui-form-label">图片</label>
            <div class="layui-input-inline">
                    <input type="text" name="i_img" class="layui-input">
            </div>
            <div class="layui-input-inline">
                <button class="layui-btn layui-btn-small" id="uploadBtn" lay-filter="uploadBtn" type="button">上传</button>
            </div>
        </div>
```

测试过使用 
```
$('#uploadBtn').on('click',function(){
            console.log(22);
        }) ;
```
和 
```
form.on('submit(uploadBtn)',function(){
            console.log(22);
        });
```
都不能起作用。

**Comment by enboyd2** [comment]
需要引入jquery

**Comment by linyasa** [comment]
@enboyd2  jquery已经引入。
```
layui.use(['layer', 'laypage', 'element','form','laydate','upload'], function(){
        var layer = layui.layer
                ,laypage = layui.laypage
                ,element = layui.element(),
        $ = layui.jquery, form = layui.form(),layerIndex;
});
```

**Comment by enboyd2** [comment]
@linyasa 监听是写在use内的吗？例如：
layui.use(['layer', 'laypage', 'element','form','laydate','upload'], function(){
        var layer = layui.layer
                ,laypage = layui.laypage
                ,element = layui.element(),
        $ = layui.jquery, form = layui.form(),layerIndex;
		
		$('#uploadBtn').on('click',function(){
            console.log(22);
        }) ;
});

**Comment by linyasa** [comment]
@enboyd2  是的，所有的代码都写在里面的。

**Comment by sentsin** [comment]
第一种方式应该是没问题，断点调试一下

**Comment by linyasa** [comment]
@sentsin 我明白什么原因了。 我那个是模板， 模板的内容放到弹出层弹出，弹出后有两个id就没起作用了。   但是又另外一个问题，如果模板里面含有<script></script>标签的话应该怎么写，我的模板里用了ueditor。
