### ISSUE TITLE
layer.open 或 layer.conform 非阻塞，如何改为阻塞？

### ISSUE THREAD

**Issue by youkuiflyer** [layui/layui#271]
在用layer.conform 时候非阻塞，不管如何都会直接执行layer.conform 后面的代码，这问题有何解决方案？ 代码如下：
function checkCode(){
		var isPass= false;
		var codeDiv = '<div class="layui-code-box">'+
							'<input type="text" id="verifyCode"  name="code" placeholder="验证码" maxlength="4" class="login_txtbx">'+
					        '<img src="${pageContext.request.contextPath}/checkCode/image" alt="" class="verifyImg" id="verifyImg" onClick="changeImg()">'+
						'</div>'; 
			
			layer.confirm(
					 codeDiv
					,['确定','取消']
			,function(index){
					var  code = $("#verifyCode").val();
					if(code == null || code ==""){
						layer.msg("验证码不能为空");
						
					} else{
						var req = {
					    		"code":code
					    };	
					  $.ajax({
							url : "/shareDesign/checkCode/checkInputCode",
							data : "req="+JSON.stringify(req),
							contentType : "application/x-www-form-urlencoded",
							dataType : "json",
							type : "post",
							success : function(data) {
								if(data.code==200){
									isPass =  true ;
									
									layer.msg(data.detail);
								}
								
								if(data.code== 100 || data.code== -2){
									layer.msg(data.detail);
								}
							},			
							error : function(data) {
								layer.msg("网络异常",{icon:7});
								
							}
							
						});
					}
				}
			,function(index){
													
			});
			
			return isPass;
		
	}

求大神解答？？

**Comment by leesing** [comment]
不知道如何改为阻塞，但是你可以改逻辑，先判断是否为空，不为空再使用layer.confirm。我也被这个问题困扰过，后来发现没好的办法。

**Comment by yuk320** [comment]
> 在用layer.conform 时候非阻塞，不管如何都会直接执行layer.conform 后面的代码，这问题有何解决方案？ 代码如下：
> function checkCode(){
> var isPass= false;
> var codeDiv = '
> 
> '+
> ''+
> '![](${pageContext.request.contextPath}/checkCode/image)'+
> '
> ';
> ```
> 		layer.confirm(
> 				 codeDiv
> 				,['确定','取消']
> 		,function(index){
> 				var  code = $("#verifyCode").val();
> 				if(code == null || code ==""){
> 					layer.msg("验证码不能为空");
> 					
> 				} else{
> 					var req = {
> 				    		"code":code
> 				    };	
> 				  $.ajax({
> 						url : "/shareDesign/checkCode/checkInputCode",
> 						data : "req="+JSON.stringify(req),
> 						contentType : "application/x-www-form-urlencoded",
> 						dataType : "json",
> 						type : "post",
> 						success : function(data) {
> 							if(data.code==200){
> 								isPass =  true ;
> 								
> 								layer.msg(data.detail);
> 							}
> 							
> 							if(data.code== 100 || data.code== -2){
> 								layer.msg(data.detail);
> 							}
> 						},			
> 						error : function(data) {
> 							layer.msg("网络异常",{icon:7});
> 							
> 						}
> 						
> 					});
> 				}
> 			}
> 		,function(index){
> 												
> 		});
> 		
> 		return isPass;
> 	
> }
> ```
> 求大神解答？？

你想说的应该是，为啥一直返回false是吧？
那是因为 layer.open 或 layer.confirm 算初始化 弹框，实际上运行完 马上就会 到 return isPass;
正确做法是 在 callback 里面去return
