### ISSUE TITLE
layer在ios10上面的BUG

### ISSUE THREAD

**Issue by zoeDylan** [layui/layui#28]
```
//主要问题出现原因
.layui-layer {
    -webkit-overflow-scrolling: touch;
//下面代码是出现使用这个方法的位置
.layui-layer-iframe{
   overflow-y:auto;
   -webkit-overflow-scrolling:touch
}
```
这段`css`会再`IOS10`浏览器里面报错，错误原因是`IOS10`浏览器的`css`解析是找不到这个方法。

出现的问题是，比如一篇长文章，你用手指不停（速度要快）的向上或者向下划动屏幕会导致屏幕卡顿（屏幕会出现短暂不渲染，显示浏览器自身底纹），安卓没发现这个问题。

> 测试浏览器（`IOS`系统）

>> 微信

>> 苹果自带

>> UC

> 测试地址

>> [BUG页面](https://zoedylan.github.io/test/layer_001.BUG.html)

>> [正常页面](https://zoedylan.github.io/test/layer_001.html)

**Comment by sentsin** [comment]
建议使用 layer mobile：http://layer.layui.com/mobile/
layer pc版不大适合用于手机端
