### ISSUE TITLE
文件上传失败callback需要取到responseCode进行一些处理，望改进

### ISSUE THREAD

**Issue by eahom1** [layui/layui#281]
error: function(index, upload){
    layer.closeAll('loading'); //关闭loading

    **### _这个地方希望有responseCode！！！_**

  }

**Comment by eahom1** [comment]
文档上有这么句话：
当请求上传时出现异常时触发（如网络异常、404/500等）。回调返回三个参数，分别为：当前文件的索引、重新上传的方法

前面说了回调返回3个参数，是3个！后面却只列了2个（文件索引和重传方法），这是几个意思？

**Comment by ylh23y** [comment]
我也遇到这个相关问题，401没有权限的错误，只能改源代码，没有对错误处理的机制

**Comment by fzzflxk** [comment]
是的，没有错误处理机制很无语 。比如 table.render() ，如果服务器出错了，怎么捕获异常 ？只有done, 没有error 。 若是使用 ajax ，重载表格又不是很舒服。

**Comment by ylh23y** [comment]
table.js需要修改
z.prototype.pullData = function (R, M) {
        var O = this, S = O.config, L = S.request, K = S.response, N = function () {
            if (typeof S.initSort === "object") {
                O.sort(S.initSort.field, S.initSort.type)
            }
        };
        if (S.url) {
            var J = {};
            J[L.pageName] = R;
            J[L.limitName] = S.limit;
            k.ajax({
                type: S.method || "get",
                url: S.url,
                data: k.extend(J, S.where),
                dataType: "json",
                success: function (T) {
                    if (T[K.statusName] != K.statusCode) {
                        O.renderForm();
                        return O.layMain.html('<div class="' + n + '">' + (T[K.msgName] || "返回的数据状态异常") + "</div>")
                    }
                    O.renderData(T, R, T[K.countName]), N();
                    M && H.close(M);
                    typeof S.done === "function" && S.done(T, R, T[K.countName])
                },
                error: function (T, V, U) {
                    O.layMain.html('<div class="' + n + '">数据接口请求异常</div>');
                    O.renderForm();
                    M && H.close(M);
                    if (T.status == 401) {
                        localStorage.removeItem("token");
                        location.href = "/login.html"
                    }
                }
            })
        } else {
            if (S.data && S.data.constructor === Array) {
                var Q = {}, P = R * S.limit - S.limit;
                Q[K.dataName] = S.data.concat().splice(P, S.limit);
                Q[K.countName] = S.data.length;
                O.renderData(Q, R, S.data.length), N();
                typeof S.done === "function" && S.done(Q, R, Q[K.countName])
            }
        }
    };

**Comment by ylh23y** [comment]
table.js需要修改:
![11](https://user-images.githubusercontent.com/13464610/88447244-adbab500-ce63-11ea-8107-7f584b468c96.png)
使用的时候添加：error判断：
![20](https://user-images.githubusercontent.com/13464610/88447258-d478eb80-ce63-11ea-84d6-874afc4fc025.png)

**Comment by ylh23y** [comment]
@贤心  希望可以改进
