### ISSUE TITLE
开始时间大于结束时间问题，最新版本V5.0.9

### ISSUE THREAD

**Issue by chenzanlee** [layui/layui#316]
开启时间范围双控件及设置默认初始日期时间，第一次点击时间控件时，更改日期，选择一个大于默认日期的值后，点击确认，只更改了开始时间的日期，导致开始时间大于结束时间，即输入了无效格式的日期。在第二次点击弹出时间控件会提示开始时间大于结束时间，为无效格式。

**Comment by MaxTsang30** [comment]
`t.index = ++n.index, t.config = w.extend({}, t.config, n.config, e), n.ready(function () {
            if(t.config.range!=null&&t.config.value!=null){
                t.startState=true;
                t.endState=true;
            }
            t.init()
        })`
