### ISSUE TITLE
table滚动条出现闪烁

### ISSUE THREAD

**Issue by adevin** [layui/layui#333]
当右侧页面滚动条出现的时候 table的横向滚动条也随之出现 然后隐藏在出现 一直闪烁反复。恰巧在一定高度的时候才会出现。可以打开控制台调整高度复现

**Comment by wellsea** [comment]
，好

**Comment by adevin** [comment]
这是2.4.0版本 请问在以后的问题解决了吗？这算是一个比较严重的bug 期待解决。应该是解决隐藏滚动条bug的时候 出现竞争了。横向和竖向交替出现。
