### ISSUE TITLE
引用layui模块工具包时出错！

### ISSUE THREAD

**Issue by slipy-spy** [layui/layui#35]
java web项目，将官网下载的layui文件夹放入WebRoot目录下，然后出错。layui.js等文件报错：
-Missing semicolon
-Missing semicolon
-Missing semicolon
-Missing semicolon
-Syntax error on token "break",;expected after this token
.....

**Comment by wenfer** [comment]
这种问题通常是编译器的问题，不用管他，忽略就行了
