### ISSUE TITLE
滑块初始化设置min的值，导致change事件value不正确

### ISSUE THREAD

**Issue by Pody2015** [layui/layui#360]
当滑块初始化的时候，我设置一个min的值，例如
tsSlider = slider.render({
    elem: '#tsSlide',  //绑定元素
    tips: false,
    min:20,
    change: function (value) {
        console.log(value) //动态获取滑块数值
        //do something                   
    }
});
然后，给这个滑块赋值：
tsSlider.setValue(20);
这时候change输出的value是40。
这是啥设计？为啥要加上min的值？
有谁遇到过这样的问题吗？咋解决的？

**Comment by zy4944796** [comment]
遇到同样问题

**Comment by hanfengniubi** [comment]
解决了吗？求解😭

**Comment by Sight-wcg** [comment]
> 解决了吗？求解😭

#1174
升级到 2.8+
