### ISSUE TITLE
数据表格绑定的工具兰，如果放置了表单元素，重新请求ajax数据后，会导致表单元素重置

### ISSUE THREAD

**Issue by SirBeansBJ** [layui/layui#361]
如题，我是把搜索选项放在工具栏里了，加载新的数据是不是没有必要重置工具栏啊？

**Comment by sentsim** [comment]
table.reload 方法是对整个表格容器进行重载，确实会让工具栏中的表单进行重置。但是也有解决办法，即在表单中设置初始值，如：
```
value="{{= d.data.where.title }}"
```
title 即重载时 where 中传递的参数
