### ISSUE TITLE
模板tpl渲染出来的upload上传html，点击上传无效？

### ISSUE THREAD

**Issue by dafa168** [layui/layui#366]
模板代码中存在绑定了上传组件的class 类， 当点击事件添加模板到页面中， 再次点击upload上传按钮无效的？ 

类似：把下面这段代码添加到 页面中， 再次点击这个按钮没反应的，事件绑定没有了？
<script id="xx">
<button class="uploadPic">上传</button> 
</script>

**Comment by dafa168** [comment]
版本： layui-v2.3.0

**Comment by leChengWebDev** [comment]
遇到相同的问题
