### ISSUE TITLE
一个广泛存在于框架中的bug，是否数组类型的判断

### ISSUE THREAD

**Issue by jiaowochunge** [layui/layui#380]
bug描述：框架判断一个对象是否数组是用 obj.constructor === Array 。
这个判断方式在跨frame时并不管用。我在追踪这个bug的过程中了解到，原生API和jquery都提供是否数组的方法，Array.isArray
重现bug：这个方式判断数组，当跨frame时就会失败。我在某个页面打开一个对话框，success回调中为对话框中的iframe设置数据源，然后iframe中的table无法通过这个数据渲染。

**Comment by wingmeng** [comment]
```js
// use ES5:
Array.isArray([]);  // true

// use jQuery:
$.isArray([]);  // true
```

**Comment by sentsim** [comment]
layui 在后面的版本已经提供了 `layui.isArray()` 方法来判断是否数组
