### ISSUE TITLE
slider setValue

### ISSUE THREAD

**Issue by 617429782** [layui/layui#382]
<div id="slider"></div>

var slider = layui.slider;
var option = {
elem: "#slider",
input: true,
min: 1,
max: 100,
step: 2,
change: function (value) {
console.log("监听到"+value) // 此处打印的是 20 * 2 + 1 = 41
}
};
var obj = slider.render(option);
obj.setValue(20)
如上述代码，使用 setValue赋值时，理应打印出20 ，实际上打印的是 value * step + min

**Comment by hanfengniubi** [comment]
加min怎么解决的，我也遇到了，求解
