### ISSUE TITLE
form内的file input在选择完文件后自动提交表单

### ISSUE THREAD

**Issue by Jamling** [layui/layui#39]
问题描述详见在社区链接：https://fly.layui.com/jie/10517/
然后详细看了下代码，发现upload.js第126行有提交表单的操作。
item.parent().submit();

```
<form target="layui-upload-iframe" method="post" key="set-mine" enctype="multipart/form-data" action="upload"><input name="file" lay-ext="" lay-type="file" lay-title="浏览..." class="layui-upload-file" type="file"></form>
```
感觉提交错了表单。应该是提交上面代码中upload生成的这个表单，而不是外面我自己写的表单

**Comment by wxw0518** [comment]
按钮写在form里点击时会默认提交，不想提交把按钮写在form外面，没有form标签的话就是有layui-form类名的标签

**Comment by Jamling** [comment]
@wxw0518 我说的就是这个问题，这是一个bug。
