### ISSUE TITLE
table组件 当options.size === 'sm'时高度计算的bug

### ISSUE THREAD

**Issue by junshaochen** [layui/layui#397]
当options.size === 'sm'时 
无法获取到layHeader layTotal 的渲染高度时默认值错误的问题
源代码行 1127 1135
修改为
 //减去列头区域的高度
 bodyHeight = parseFloat(height) - (that.layHeader.outerHeight() || (options.size === 'sm' ? 31 : 38));

//减去统计朗的高度
        if (options.totalRow) {
            bodyHeight = bodyHeight - (that.layTotal.outerHeight() || (options.size === 'sm' ? 32 : 40));
        }

**Comment by zhe-he** [comment]
你可以提一个 pull requests :smirk:
