### ISSUE TITLE
upload.js的源码疑惑

### ISSUE THREAD

**Issue by 303182519** [layui/layui#400]
https://github.com/sentsin/layui/blob/master/src/lay/modules/upload.js#L449
看了一下这句代码
that.elemFile[0].click();
按正常是jq选择出来的dom元素，为什么会有click事件的

**Comment by zhe-he** [comment]
js模拟点击事件，偷懒的写法，完整的写法如下
`
var event = document.createEvent('MouseEvents');    

  event.initEvent("click", false, true);    

  that.elemFile[0].dispatchEvent(event);`
[详情](https://www.cnblogs.com/MrBackKom/archive/2012/06/26/2564501.html)

**Comment by 303182519** [comment]
that.elemFile 这个是JQ的选择出来的。
that.elemFile[0]当这样取的话，就变成了原生的了，是没有click事件的

**Comment by zhe-he** [comment]
如果我给它加一个click事件(不论js或者jq)，然后它不就有了吗？ 点击上传的时候 如果不执行我的事件是不是bug？
我没怎么仔细看，没找到这行文件的click事件，只找到了change事件，可能其他文件有click，或者是为了兼容用户的click。
