### ISSUE TITLE
授权问题

### ISSUE THREAD

**Issue by weathon** [layui/layui#415]
layui是MIT授权的吧，但是这个issue里面为什么有一个要付费的css文件呢？是layadmin的吗。、
https://github.com/hsiangleev/layuiExtend/issues/3

**Comment by weathon** [comment]
同时无意间发现一个疑似盗版
https://github.com/MrMoveon/layuiAdmin

**Comment by weathon** [comment]
https://github.com/sangezier/chat-layui
这个也是盗版

**Comment by weathon** [comment]
@sentsin

**Comment by weathon** [comment]
追究一下吧，第一个作者说是不小心放错了，后面两个很明显是故意公开代码
@sentsin @weianguo

**Comment by sentsim** [comment]
layui 是 MIT 开源协议。LPPL 那个属于之前的盗版上传所致。
