### ISSUE TITLE
有没有三级菜单栏的功能

### ISSUE THREAD

**Issue by hpxmk** [layui/layui#42]
在文档的垂直导航栏并无发现三级额，最多看到二级
<dl><dd><a></a></dd></dl>

**Comment by nabaonan** [comment]
我试过这个框架默认不支持三级导航，按理说也不应该有第三级，可以在顶部横向做一级左侧做两级，如果全放左侧交互会不太好吧

**Comment by boss1000** [comment]
你要的应该是树型结构，得自己写

**Comment by newyoung21** [comment]
@hpxmk 
请问你是怎么解决这个三级导航栏的呢
