### ISSUE TITLE
table的 lay-data属性的url如何传递动态参数

### ISSUE THREAD

**Issue by y451687300** [layui/layui#427]
table的 lay-data属性的url如何传递动态参数
我在项目中想通过表格的lay-data的url属性传递动态参数   请问应该怎么写
我用传统的字符串拼接变量的方式后台会报错 无法获取到

**Comment by Tk4s** [comment]
获取你可以使用table reload的方式来加载

![image](https://user-images.githubusercontent.com/48111180/54263055-d746a980-45aa-11e9-8d53-99f8bcdc1145.png)

**Comment by y451687300** [comment]
> 来

能否给个完整截图

**Comment by Tk4s** [comment]
//所获得的 tableIns 即为当前容器的实例
var tableIns = table.render({
  elem: '#id'
  ,cols: [] //设置表头
  ,url: '/api/data' //设置异步接口
  ,id: 'idTest'
}); 
 
//这里以搜索为例
tableIns.reload({
  where: { //设定异步数据接口的额外参数，任意设
    aaaaaa: 'xxx'
    ,bbb: 'yyy'
    //…
  }
  ,page: {
    curr: 1 //重新从第 1 页开始
  }
});
//上述方法等价于
table.reload('idTest', {
  where: { //设定异步数据接口的额外参数，任意设
    aaaaaa: 'xxx'
    ,bbb: 'yyy'
    //…
  }
  ,page: {
    curr: 1 //重新从第 1 页开始
  }
});




[https://www.layui.com/doc/modules/table.html](url)
