### ISSUE TITLE
layuiTable.reloadTable(tableId) where参数拷贝问题

### ISSUE THREAD

**Issue by jianchengwang** [layui/layui#429]
原本 `tableInstance.where.clsId = [1,2,3]`

```js
layerTable.reload(tableId, {
  where: {
    clsId: [4] 
  }
});
```
源码使用的是
```js
config = $.extend(true,{},config,options)
```
会导致最终 `config.where.clsIds = [4,2,3]`
显然跟预期的 `clsIds = [4]` 不一致，
而且感觉`tableInstance.reload` 跟 `layuiTable.reload` 很多地方不一样，
`layuiTable.reload`会返回一个新的tableInstance并且这个tableInstance 会包含很多信息，比如我之前tableInstance 配置只有`page = true`, 返回的tableInstance 的`page = {curr:1, limit: 10..}`这样的。
而且作者是不是不维护了，还是要搞一次大的更新，感觉好几个月都没有push了

**Comment by jacksimon** [comment]
对啊，这个bug都存在好久了，什么时候修复啊

**Comment by sentsim** [comment]
这个早在 2.6.0 就已经优化了。
