### ISSUE TITLE
XSS issues

### ISSUE THREAD

**Issue by weathon** [layui/layui#433]
If I am using a data table, and I edit it into something like `<script>//do something</script>`, it will have an XSS issues.
(I'm sorry about I cannot input Chinese on school's computer)

**Comment by monyxie** [comment]
我也发现了这个问题。Table组件默认不转义HTML会带来巨大的安全风险，因为它大多数时候都是用来展示用户输入数据。而且要转义表格的全部字段的话，我要在所有的列定义中加上`templet: "{{= d.field }}"，这样不仅平添了很多模板代码，还难以确保不会出现遗漏。所以我觉得，如果不能默认转义HTML，也至少应该有一个全局开启/关闭HTML转义的选项。

**Comment by weathon** [comment]
@sentsin

**Comment by coofo** [comment]
同样碰到这个问题，希望可以得到重视。

**Comment by sentsim** [comment]
后面的版本增加了 `escape` 参数，可对 xss 相关字符进行过滤
