### ISSUE TITLE
手机号码验证有问题

### ISSUE THREAD

**Issue by popring** [layui/layui#436]
178的手机号通不过验证？？？
在某个医院的网站报名时候发现的，是网站过于旧的原因？还是layui的表单验证有问题？

**Comment by zx01785233** [comment]
form表单模块的验证规则 phone:[/^1\d{10}$/,"请输入正确的手机号"] 版本2.45；
检查一下是否重设了layui.form.verify；

**Comment by popring** [comment]
> 表单模块的验证规则电话：[/ ^ 1 \ d {10} $ /，“请输入正确的手机号”]版本2.45; 
> 检查一下是否重设了layui.form.verify;

首先感谢您的回复，我是作为一名使用者的时候发现这个问题的，只是想看下layui官网有没有这个问题，如果没有那正是我们所希望的。总之，感谢你的回复。
