### ISSUE TITLE
LayUI日期选择 窗口小于日期控件的时候 闪退

### ISSUE THREAD

**Issue by zerox-v** [layui/layui#447]
LayUI日期选择 窗口小于日期控件的时候 闪退
![1234](https://user-images.githubusercontent.com/24620885/55708140-c0636d80-5a17-11e9-9f45-bd129e532f25.gif)

**Comment by li2251421** [comment]
同样遇到此问题，请问怎么解决的

**Comment by ZeroX-V** [comment]
> 同样遇到此问题，请问怎么解决的

和测试沟通，让他把提的这个bug删了

**Comment by li2251421** [comment]
我刚解决了，增加  trigger: 'click' 这个就可以了

**Comment by ZeroX-V** [comment]
> 我刚解决了，增加 trigger: 'click' 这个就可以了

真的可以，谢谢

**Comment by jianghuyihong** [comment]
我增加了，连日期面板都出不来

**Comment by ZeroX-V** [comment]
> 我增加了，连日期面板都出不来
`  laydate.render({
        elem: '.layui-date' //指定元素
        , trigger: 'click'//
    });`

**Comment by li2251421** [comment]
trigger - 自定义弹出控件的事件
类型：String，默认值：focus，如果绑定的元素非输入框，则默认事件为：click

可能跟这个有关，自己尝试一下
