### ISSUE TITLE
新需求：layer弹出层的content定时更新，或者被JS赋值

### ISSUE THREAD

**Issue by wangfan9002** [layui/layui#452]
使用layer弹出层显示运行日志，但日志的内容一般是一直随着后台程序的运行一直追加的，所以希望content内容，能够定时被更新或者被JS赋值
$.post(post_url,  param, function(data, status) {
            if (data.code == "200") {
                layer.open({
                    type: 1,
                    title: "运行日志" ,
                    btn: [ "确定" ],
                    area: ['520px', '340px'],
                    content: data.content,
                      end: function(layer, index){

                    }
                });
            } else {
                layer.open({
                    title: "操作提示" ,
                    btn: [ "确定" ],
                    content: (data.msg || "操作失败"),
                    icon: '2'
                });
            }
        });

**Comment by sentsim** [comment]
这类业务型的定时操作，建议直接在外部实现。
