### ISSUE TITLE
关于数据表格，异步加载数据参数提交的问题

### ISSUE THREAD

**Issue by colaicode** [layui/layui#460]
我使用的是最新的Layui，我遇到一个问题：
服务器的接口是有参数签名的。但是使用了数据表格的分页控件的话，我无法对page和pageSize进行签名，能不能在数据表格加上请求开始之前的回调，方便我们对参数进行二次处理

**Comment by sentsim** [comment]
tanle 的 `request ` 参数可以对请求时的参数进行重定义
