### ISSUE TITLE
v2.4.5 监听单元格编辑事件table.on('edit(demo)', function(obj){}) 报错

### ISSUE THREAD

**Issue by allenwhm** [layui/layui#470]
使用https://res.layui.com/static/download/layui/layui-v2.4.5.zip 下载的包。
参考demo : https://www.layui.com/demo/table/cellEdit.html
一直报错 ：  Cannot set property['fieldName'] of undefined
在把lay.modules中的table.js替换为demo页面js资源文件 https://res.layui.com/layui/dist/lay/modules/table.js 得到解决。

**Comment by kevin4j** [comment]
我遇到的是table监听行单双击事件不起作用，但是点击排序后又起作用了
