### ISSUE TITLE
数据表格可以根据值使某一行某一列变成单独的颜色吗？

### ISSUE THREAD

**Issue by Clearlove9** [layui/layui#480]
如题

**Comment by ederson520** [comment]
clearlove……9，你是在暗示什么？明年你还得改clearlove10

**Comment by sentsim** [comment]
只能通过表头的 `style` 属性对对应列设置单独的样式，无法通过 options 属性设置行样式，只能外部 css 控制。

**Comment by Clearlove9** [comment]
邮件已收到，谢谢！
