### ISSUE TITLE
table的 checkbox设置不可选中

### ISSUE THREAD

**Issue by MinHongwei** [layui/layui#487]
请问table的复选框，怎么设置部分数据不可被选中，无论是全选还是单选。

**Comment by sentsim** [comment]
**layui v2.7 的 table 已经增加对返回数据中的特定字段 `LAY_DISABLED` 的解析，用于设定禁止选择行。
> 参考文档：https://layui.gitee.io/v2/docs/modules/table.html#specific-field**
