### ISSUE TITLE
upload模块发起ajax请求时type写死为post的bug

### ISSUE THREAD

**Issue by songchang001** [layui/layui#495]
![image](https://user-images.githubusercontent.com/25171699/59591818-4dfec000-9121-11e9-9a91-9d79ac47121a.png)
**### upload模块发起ajax请求时type写死为post的bug**
发起ajax请求时，type应为“options.method”，现在写死为“post”

**Comment by saton720** [comment]
然后怎么搞？

**Comment by sentsim** [comment]
upload 组件只能 `post` 上传
