### ISSUE TITLE
富文本编辑器： 如何填充内容至编辑器

### ISSUE THREAD

**Issue by pygyme** [layui/layui#496]
在API中只有 `layedit.getContent(index)`

**Comment by WXiangQian** [comment]
<div class="layui-form-item">
            <label class="layui-form-label" id="link-word">内容</label>
            <div class="layui-input-block">
                <textarea id="contents" name="contents" type="text/plain">{{$info->contents}}</textarea>
            </div>
        </div>

直接写在textarea里即可
