### ISSUE TITLE
穿梭框的问题

### ISSUE THREAD

**Issue by gostfather** [layui/layui#502]
当穿梭框给height属性时内部数据会溢出
<img width="395" alt="图片" src="https://user-images.githubusercontent.com/29191934/60479110-37c33900-9cb7-11e9-9a14-37c5f78b4eb3.png">
<img width="70" alt="图片1" src="https://user-images.githubusercontent.com/29191934/60479232-a43e3800-9cb7-11e9-876a-653bb56b47df.png">

**Comment by sentsim** [comment]
后面的版本已经修复了此问题。
