### ISSUE TITLE
当有负数时 排序 （由小到大） 负数会排在0后面 

### ISSUE THREAD

**Issue by Wenxiaoxiao** [layui/layui#523]
debugger了两个小时，发现当数值为浮点数且小于零的时候，return出来的就是false;
改法：
return n.test(r)&&(r=parseFloat(r)),n.test(i)&&(i=parseFloat(i)),r&&!i?1:!r&&i?-1:r>i?1:r<i?-1:0
将这行代码注释掉
换成return r-i;
问题完美解决!

**Comment by sentsim** [comment]
2.6.x 开始，排序均已得到优化，您返回的这个负数问题已不复存在
