### ISSUE TITLE
spring boot中table工具条单击时获取的行obj为空

### ISSUE THREAD

**Issue by zeng-shuo** [layui/layui#529]
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>商品信息</title>
    <link rel="stylesheet" href="../../layui/css/layui.css">
</head>
<body>

<table id="demo" lay-filter="test"></table>
<script src="../../layui/layui.js" ></script>

<script id="barDemo" type="text/html">
    <a id="update" class="layui-btn layui-btn-xs" lay-event="edit" >修改</a>
    <a id="delete" class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del" >下架</a>
</script>

<script>
    layui.use('table', function(){
        var table = layui.table;
        var $ = layui.jquery;

        //第一个实例
        table.render({
            elem: '#demo'
            ,height: 'full-200'
            ,url:'http://localhost:8080/shangpin/list' //数据接口
            ,page: true //开启分页
            ,cols: [
                [
                {field: 'sid', title: '商品ID', width:135, style:"height:150px;",fixed: 'left'}
                ,{field: 'name', title: '名称', width:125}
                ,{field: 'pic', title: '图片', width: 150,templet:'<div><img src="{{d.pic}}"></div>'}
                ,{field: 'cost', title: '单价', width:125}
                ,{field: 'store', title: '库存', width: 125}
                ,{field: 'type', title: '类目', width: 125}
                ,{field: 'ctime', title: '创建时间', width: 125}
                ,{field: 'gtime', title: '修改时间', width: 125}
                ,{field: 'operate', title: '操作', toolbar: '#barDemo',width: 200}

            ]
            ]
            ,done: function (res) {
                console.log(res.data);
            }
        });
        table.on('tool(test)', function(obj){
            var data = obj.data;
            console.log(obj);
            console.log(obj.data.sid);
            $('#delete').attr('href',"/produce/update/"+obj.data.sid);
        });

    });

</script>

<style type="text/css">

    .layui-table-cell{

        text-align:center;

        height: auto;

        white-space: normal;

    }

</style>
</body>
</html>
![V_4$V87MSP)KQ8XMZQA~8(C](https://user-images.githubusercontent.com/45067247/62591059-f864b980-b900-11e9-96ca-b533aaa6f74e.png)

**Comment by lxjmaster** [comment]
我也遇到了,大佬解决没?

**Comment by shukuang01** [comment]
> 我也遇到了,大佬解决没?
我的解决了，我是替换了layui里面中的lay文件夹，不知道什么原因。找bug时是用一个现成能访问到数据的项目，一个一个文件替换测试，发现是lay文件有问题。不知道能不能帮到你。

**Comment by shukuang01** [comment]
我的解决了，我是替换了layui里面中的lay文件夹，不知道什么原因。找bug时是用一个现成能访问到数据的项目，一个一个文件替换测试，发现是lay文件有问题。

**Comment by lxjmaster** [comment]
> 我的解决了，我是替换了layui里面中的lay文件夹，不知道什么原因。找bug时是用一个现成能访问到数据的项目，一个一个文件替换测试，发现是lay文件有问题。

大佬可以把你那边的layui源码给我么？邮箱379501669@qq.com

**Comment by shukuang01** [comment]
> > 我的解决了，我是替换了layui里面中的lay文件夹，不知道什么原因。找bug时是用一个现成能访问到数据的项目，一个一个文件替换测试，发现是lay文件有问题。
> 
> 大佬可以把你那边的layui源码给我么？邮箱[379501669@qq.com](mailto:379501669@qq.com)

已发

**Comment by lxjmaster** [comment]
> > > 我的解决了，我是替换了layui里面中的lay文件夹，不知道什么原因。找bug时是用一个现成能访问到数据的项目，一个一个文件替换测试，发现是lay文件有问题。
> > 
> > 
> > 大佬可以把你那边的layui源码给我么？邮箱[379501669@qq.com](mailto:379501669@qq.com)
> 
> 已发

收到了，感谢大佬

**Comment by lxjmaster** [comment]
看了大佬发给我的demo，是layui源码的table组件有问题，我换了大佬给我的table.js就可以了。。。。这坑爹的框架，醉了。。。。。
