### ISSUE TITLE
2.5.4的table，totar类型的单元格，不再触发任何事件，但是当一个totar里放入多个button，导致不够宽，也不会出现展开的按钮

### ISSUE THREAD

**Issue by cn1001wang** [layui/layui#542]
https://github.com/sentsin/layui/blob/efb865266164af6e570cc99514f6e830f04c858d/src/lay/modules/table.js#L1640
现在版本当遇到totar会给他加上‘data-off’这个属性，在事件触发时，判断如果有则不触发。如标题所描述，当多个按钮宽度不足时，也将不能展开。

**Comment by sentsim** [comment]
如果 button 太多，可采用 dropdown 下拉的方式
> 参考示例：https://layui.gitee.io/v2/demo/dropdown.html
