### ISSUE TITLE
相册弹出层 layer.photos问题

### ISSUE THREAD

**Issue by lalalsls** [layui/layui#543]
问题描述: 
当采用layer.photos的直接读取页面图片方式时,
如果动态添加页面中的img,弹出层本身会报错
![image](https://user-images.githubusercontent.com/31378186/63667593-08d4c980-c807-11e9-8eec-8cc0a0f50dd4.png)

猜测是因为动态添加的img没有被layer装进本身的data中

修改源代码
第1110行,将pushdata()方法,提前到1101行之前,可以解决此问题
![image](https://user-images.githubusercontent.com/31378186/63668077-96fd7f80-c808-11e9-90b4-c3bf8e718652.png)
动态拼接的img,也能够被正确识别
但不清楚会不会有什么别的问题,
望解答并修正此问题...

**Comment by sentsim** [comment]
这个后面的版本应该是已经修复了。
