### ISSUE TITLE
监听选项卡删除事件BUG or 文档错误?

### ISSUE THREAD

**Issue by nfangxu** [layui/layui#557]
layui 版本: v2.5.4

![image](https://user-images.githubusercontent.com/33243730/64931585-f977f780-d86b-11e9-85cb-ed124ce6642e.png)

https://www.layui.com/doc/modules/element.html#ontabDelete

其中 this 所代表的并不是 tab 标题所在的原始DOM元素,  而是 删除对应的 icon 的DOM元素

**Comment by sentsim** [comment]
的确如此，属于文档标注有误
