### ISSUE TITLE
关于Layer.js的一个Bug

### ISSUE THREAD

**Issue by GGHWDong** [layui/layui#561]
2.5.5 版本 layer.js 第791行对 btnHeight 做了“||0”判断，但是 809 行直接进行了赋值，导致 btnHeight 最终可能为 undefined 或 null，使得最终 iframe 高度计算得出 NAN 的值。

我们在项目中遇到了此问题，呈现为 iframe 放大后无法高度自适应（底部下面有一个白色块），所以反馈给您作为参考。

**Comment by sentsim** [comment]
这个在上个月发布的 2.7 已经修复了。很抱歉这么久才留意到 github 已经有类似的 issue 反馈
