### ISSUE TITLE
日期控件设置最大时间和最小时间限制后，【现在】按钮仍然可点

### ISSUE THREAD

**Issue by FrontEnd-GuoXi** [layui/layui#573]
比如我设置最小时间是2016-01-01，最大时间2016-12-30。而我【现在】的时间是2019-10-17，按道理这个【现在】按钮是无法点击的，因为他不在我设置的区间内，但是实际上他居然可以点击。

**Comment by sentsim** [comment]
这个小问题确实一直存在，将会在 `v2.8.0` 修复

**Comment by sentsim** [comment]
2.8.0 已修复该问题。
见：https://github.com/layui/layui/releases/tag/v2.8.0-beta.1
