### ISSUE TITLE
table reload 多次使用是，where 的字段不会清空，上一次的对象字段还依旧保留着；

### ISSUE THREAD

**Issue by wsilly** [layui/layui#592]
```js
// ... 其他业务代码
 layui.table.reload('tableId', {
       where: {
           id: 1
       }
 });
// ... 其他业务代码

第一次重载里的where 是{id:1}

// ... 其他业务代码
 layui.table.reload('tableId', {
       where: {
           name: '李四'
       }
 });
// ... 其他业务代码

第二次重载里的where 是{id:1，name : '李四'}
```

**Comment by zhenhua-li** [comment]
我也遇到了同样的bug,  看了源码 发现是config的保存机制出的问题. 
没办法, 只能暂时先把不用的值置空. 但依旧会送出空的字段.
```javascript
        // 搜索按钮点击事件
        $('#btnSearch').click(function () {
            let key = $('#sltKey').val(), value=$('#edtSearch').val();
            let param = {};
            ['userId','username','company'].forEach(i=>{ (i===key)?param[i]=value : param[i]=null; });
            table.reload('userTable', {where : param});
        });
```

**Comment by yyc007** [comment]
> 我也遇到了同样的bug, 看了源码 发现是config的保存机制出的问题.
> 没办法, 只能暂时先把不用的值置空. 但依旧会送出空的字段.
> 
> ```js
>         // 搜索按钮点击事件
>         $('#btnSearch').click(function () {
>             let key = $('#sltKey').val(), value=$('#edtSearch').val();
>             let param = {};
>             ['userId','username','company'].forEach(i=>{ (i===key)?param[i]=value : param[i]=null; });
>             table.reload('userTable', {where : param});
>         });
> ```

谢谢，这方法可行。看来暂时只能这样了

**Comment by sentsim** [comment]
这是因为 layui 的早期版本，table.reload 采用的是深度重载，所以参数会叠加。后面 2.6 已经改成默认浅重载了，也就不会存在上一次参数保留的问题。
> 详见文档：https://layui.gitee.io/v2/docs/modules/table.html#reload
