### ISSUE TITLE
版本 2.5.4 tab选项卡加数据表格，tips展示所有选项卡都展示

### ISSUE THREAD

**Issue by muxiaobai** [layui/layui#603]
![截图_15752920217651](https://user-images.githubusercontent.com/13265901/69961893-c9c1bd00-1547-11ea-99ad-282576982910.png)
![截图_15752920027369](https://user-images.githubusercontent.com/13265901/69961890-c8909000-1547-11ea-9f4e-e0acabdeba24.png)

**Comment by muxiaobai** [comment]
@sentsin @weianguo @xuexb

**Comment by sentsim** [comment]
这个一般在实际使用的时候，需在 tab 事件中加上 `layer.closeAll('tips')` 来关闭 tips 层
