### ISSUE TITLE
请问：laydate如何控制不准跨年份选择时间段

### ISSUE THREAD

**Issue by nottellyou** [layui/layui#618]
请问：laydate如何控制不准跨年份选择时间段。比如说：我选择了2019年的时间开始，结束时间不能为2020年的时间。

<script type="text/javascript">
    var endtime = laydate.render({elem: '#day'
        , range: true
        , min:'2019-08-06'
        , change: function(value, date, endDate){
            console.log(value);
            console.log(date);
            if(date.year != endDate.year){
                endDate = date;
                //layer.alert('禁止跨年选择时间');
                endtime.hint('禁止跨年选择时间');
            }
            endtime.max = date.year + '-12-31';
            endtime.config.max = {
                year: date.year,
                month: date.month - 1,
                date: date.date - 1
            }

            console.log(endDate);
        }
    });
</script>

这样虽然会有提示，但依然可以选择。搞不定呀。希望高手支个招。

**Comment by ZBTLR** [comment]
有最大最小日期min、max属性，多看文档
