### ISSUE TITLE
关于Layui的权限管理

### ISSUE THREAD

**Issue by mark0614** [layui/layui#624]
楼主，你好：layui中如何做到按钮级别或者<div>区块级别的权限控制？之前的JSP中，shiro和spring security有自带的权限标签；现在的ant design也有<authCheck permission=“some_permission”>这种这种组件。在layui中如何实现？

我想了下，是不是可以用layui中的模板引擎实现？ 我不是一名纯前端人员，见谅。

**Comment by ZBTLR** [comment]
同为后端人员，在客户端渲染我知道，无非用权限属性标识html，$('[权限属性]')遍历，异步读取权限没有权限则$(this).remove，或者使用laytpl做。但是后端渲染我就不太清楚

**Comment by sentsim** [comment]
前端的权限管理主要是控制视图的状态，如：是否输出内容、是否隐藏、是否禁用等
归纳起来比较笼统，没有专门针对权限控制的组件，不过倒也可以用 laytpl 来控制状态输出。
