### ISSUE TITLE
layui + jquery 3 导致transfer高度不正确

### ISSUE THREAD

**Issue by heichong** [layui/layui#673]
代码如下，看下效果就知道了，ul的高度没有计算出来，导致滚动条不能出现

<div id="test2" class="demo-transfer"></div>
   <script src="https://cdn.bootcss.com/jquery/1.10.1/jquery.js"></script>
<script src="https://www.layuicdn.com/layui-v2.5.6/layui.all.js" charset="utf-8"></script>

<script>

  var $ = layui.$
  ,transfer = layui.transfer
  ,layer = layui.layer
  ,util = layui.util;
  
  //模拟数据
  var data1 = [
    {"value": "1", "title": "李白"}
    ,{"value": "2", "title": "杜甫"}
    ,{"value": "3", "title": "苏轼"}
    ,{"value": "4", "title": "李清照"}
    ,{"value": "5", "title": "鲁迅", "disabled": true}
    ,{"value": "6", "title": "巴金"}
    ,{"value": "7", "title": "冰心"}
    ,{"value": "8", "title": "矛盾"}
    ,{"value": "9", "title": "贤心"}
  ]
  //定义标题及数据源
  transfer.render({
    elem: '#test2'
    ,title: ['候选文人', '获奖文人']  //自定义标题
    ,data: data1
    //,width: 150 //定义宽度
    ,height: 210 //定义高度
  })
 
</script>

**Comment by AlphaGee** [comment]
@heichong 不是jquery问题版本。我看了，你开启search就可以了。没开search的话search那一栏为undefined，计算不到值。
