### ISSUE TITLE
重载数据表格时,旧条件不会被自动删除

### ISSUE THREAD

**Issue by adinlead** [layui/layui#676]
![image](https://user-images.githubusercontent.com/15228785/76135302-a0419180-6060-11ea-9f71-cfb196224382.png)
最近在开发时遇到一个问题,我们做了一个from表单来展示查询条件,但是在请求列表时发生了问题.
```
// 监听from的search 按钮
form.on('submit(search)', function (data) {
    table.reload('table', {
        url: listurl
        , where: data.field
    });
    return false;
});
```
第一次请求时:
data.field为:
```
{"keyword":"20200202","wx":"true"}
```
请求列表的参数为:
```
account/admin/list?page=1&rows=10&keyword=20200202&wx=true
```
当去掉微信查询项时,data.field为:
```
{"keyword":"20200202"}
```
理想情况下的请求列表的参数应当是:
```
account/admin/list?page=1&rows=10&keyword=20200202
```
但实际请求列表的参数依然是:
```
account/admin/list?page=1&rows=10&keyword=20200202&wx=true
```

**Comment by sentsim** [comment]
参考：https://github.com/layui/layui/issues/592#issuecomment-1200390616
