### ISSUE TITLE
LayUI 的tree 组件有一些问题

### ISSUE THREAD

**Issue by fengxiaozi123** [layui/layui#685]
v2.5.4的数据过多渲染会很慢的问题在 V2.5.5已经修复，但是伴随了一个在勾选未勾选的选项时，会把其他层级的为选中的项勾选上。希望可以解决一下问题。谢谢。

**Comment by redemptiongh** [comment]
我也碰到了相关问题，BUG原因如下：
1、tree组件的逻辑是这样的：如果直接选中根节点，则根节点check=true，子节点check=false（虽然子节点显示为打钩）；如果直接选中了子节点，那么子节点check=true，根节点check=false（虽然界面显示为打钩）。
2、回显渲染的时候，如果根节点check=true，则忽略其下的所有子节点的check属性，下属的所有节点全部显示为打钩。
解决的办法：
数据预处理，即把所有需要打钩的叶子节点（最下层无children节点）的check属性设置成true , 其他节点的check属性设置成false，然后再交给tree渲染可以解决这个BUG。
本质上，这个也可能不是BUG，只要交给tree渲染的数据符合上述1,2的规范，就能够正常显示，但是在实际使用过程中（用户在UI上各种骚操作过后）提交给后端的tree数据是很可能是错误的，所以才造成了选中混乱的现象。

**Comment by fengxiaozi123** [comment]
好的，谢谢。



---原始邮件---
发件人: "redemptiongh"<notifications@github.com&gt;
发送时间: 2020年4月9日(周四) 中午1:42
收件人: "sentsin/layui"<layui@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"fengxiaozi123"<932397207@qq.com&gt;;
主题: Re: [sentsin/layui] LayUI 的tree 组件有一些问题 (#685)




 
我也碰到了相关问题，BUG原因如下：
 1、tree组件的逻辑是这样的：如果直接选中根节点，则根节点check=true，子节点check=false（虽然子节点显示为打钩）；如果直接选中了子节点，那么子节点check=true，根节点check=false（虽然界面显示为打钩）。
 2、回显渲染的时候，如果根节点check=true，则忽略其下的所有子节点的check属性，下属的所有节点全部显示为打钩。
 解决的办法：
 数据预处理，即把所有需要打钩的叶子节点（最下层无children节点）的check属性设置成true , 其他节点的check属性设置成false，然后再交给tree渲染可以解决这个BUG。
 本质上，这个也可能不是BUG，只要交给tree渲染的数据符合上述1,2的规范，就能够正常显示，但是在实际使用过程中（用户在UI上各种骚操作过后）提交给后端的tree数据是很可能是错误的，所以才造成了选中混乱的现象。
