### ISSUE TITLE
存在多个单选时，checked状态会丢失

### ISSUE THREAD

**Issue by lzpswat** [layui/layui#705]
项目需要多个单选，发现单选组A和单选组B的checked只能存在一个

![Snipaste_2020-05-20_17-34-06](https://user-images.githubusercontent.com/28242587/82431285-0b77fd00-9ac1-11ea-8c73-85466854d1d3.png)
![Snipaste_2020-05-20_17-40-16](https://user-images.githubusercontent.com/28242587/82431295-0dda5700-9ac1-11ea-8908-1657a889a8d6.png)

**Comment by maszy** [comment]
name一样，当然只存下一组状态了。
