### ISSUE TITLE
希望可以增加 下拉按钮 组件

### ISSUE THREAD

**Issue by outer199** [layui/layui#714]
希望可以增加 下拉按钮 组件(表格内使用), 灰常感谢

**Comment by muxiaobai** [comment]
我实现了一个下拉列表可以参考一下？

**Comment by muxiaobai** [comment]
![image](https://user-images.githubusercontent.com/13265901/87397604-2e1d2280-c5e7-11ea-8fe6-80243fcb0ee4.png)

**Comment by sentsim** [comment]
https://layui.gitee.io/v2/demo/dropdown.html
