### ISSUE TITLE
数据表格的表头中设置了templet并且值中带有双引号的时候，HTML标签出现错乱

### ISSUE THREAD

**Issue by lvqier** [layui/layui#725]
在 src/lay/modules/table.js 文件的第 799 行，直接使用字符串拼接将数据放到了 data-content 标签中：
`if(item3.templet) attr.push('data-content="'+ content +'"'); //自定义模板`
如果 content 中带有双引号，比如 
`var content='I have " in content';`
 时，会变成
`data-content="I have " in content"`
HTML标签就会因为引号不配对而出现错乱

**Comment by sentsim** [comment]
该问题已经在 2.7.x 修复了
