### ISSUE TITLE
自写源码中如函数名等含有layui字样（内容没有抄袭复制）是否构成侵权？

### ISSUE THREAD

**Issue by qian-xiang** [layui/layui#728]
想请问下后面开源或商用的话，源码中含有Layui字样会侵权么？如果构成侵权，为尊重版权，开发者该如何规避？

如图

![image](https://user-images.githubusercontent.com/37764940/88480747-65e27d80-cf8a-11ea-9108-9b04367fe506.png)

**Comment by sentsim** [comment]
不会的，这个有点多虑了哈，MIT 本身就是采用 MIT 宽松协议的开源项目
