### ISSUE TITLE
layui select组件如何设置为选中？

### ISSUE THREAD

**Issue by KaloSora** [layui/layui#734]
<img width="1236" alt="行政区域绑定" src="https://user-images.githubusercontent.com/35422660/89157911-e400de80-d59f-11ea-920e-d66a0b9f4eb8.png">
您好，我想问一下如何能根据后台返回的值选中下拉框。我从后台加载了行政区域以后，用$('#selector').val()赋值，但是带出来仍然是空的数据，

**Comment by KaloSora** [comment]
这里的行政区域是通过$('#selector').html()加载进去的，手动点击选择了以后，$('#selector').val()能够取到

**Comment by JPAdCoder** [comment]
给你想选中的option 添加checked 保证它是第一个checked，我看你有加默认请选择的option如果那个option拥有checked的话记得去掉，然后调用以下form.render()参数根据情况填。取值的话通过form.on()进行下拉监听 多看看官方的文档，表单里相关的操作写的很详细也有实例

**Comment by KaloSora** [comment]
非常感谢您在百忙之中的回复！
我在github上提的issue主要问题点在于，我在动态加载完下拉框以后，使用$('selector').val()赋值不成功。
同样地，写死的下拉框，我通过$('selector').val()却能成功赋值，并且页面会自动选中value对应的text


实例：
下图框起来的地方是写死的下拉框，可以通过$('selector').val()赋值，并且赋值以后能够自动选中value对应的text




下面是赋值的js语句，赋值过后调用了form.render()




下图是出问题的地方：
通过ajax加载完数据以后进行绑定，可以看到这里没有问题，option里面也没有checked选项


绑定数据的js代码，同样调用了form.render()，目前都是正常的



出问题的地方在于，在动态绑定下拉框以后，通过$('selector').val()赋值失败

赋值代码如下，我单步调试回传到前台是有值，但是重新取值却为空



再次感谢您的耐心回复🙏
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "sentsin/layui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午4:07
收件人:&nbsp;"sentsin/layui"<layui@noreply.github.com&gt;;
抄送:&nbsp;"KaloSora"<1183616932@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sentsin/layui] layui select组件如何设置为选中？ (#734)





 
给你想选中的option 添加checked 保证它是第一个checked，我看你有加默认请选择的option如果那个option拥有checked的话记得去掉，然后调用以下form.render()参数根据情况填。取值的话通过form.on()进行下拉监听 多看看官方的文档，表单里相关的操作写的很详细也有实例

**Comment by KaloSora** [comment]
非常感谢您在百忙之中的回复！
我在github上提的issue主要问题点在于，我在动态加载完下拉框以后，使用$('selector').val()赋值不成功。
同样地，写死的下拉框，我通过$('selector').val()却能成功赋值，并且页面会自动选中value对应的text


实例：
下图框起来的地方是写死的下拉框，可以通过$('selector').val()赋值，并且赋值以后能够自动选中value对应的text




下面是赋值的js语句，赋值过后调用了form.render()




下图是出问题的地方：
通过ajax加载完数据以后进行绑定，可以看到这里没有问题，option里面也没有checked选项


绑定数据的js代码，同样调用了form.render()，目前都是正常的




出问题的地方在于，在动态绑定下拉框以后，通过$('selector').val()赋值失败


赋值代码如下，我单步调试回传到前台是有值，但是重新取值却为空




再次感谢您的耐心回复🙏
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "sentsin/layui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午4:07
收件人:&nbsp;"sentsin/layui"<layui@noreply.github.com&gt;;
抄送:&nbsp;"KaloSora"<1183616932@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sentsin/layui] layui select组件如何设置为选中？ (#734)





 
给你想选中的option 添加checked 保证它是第一个checked，我看你有加默认请选择的option如果那个option拥有checked的话记得去掉，然后调用以下form.render()参数根据情况填。取值的话通过form.on()进行下拉监听 多看看官方的文档，表单里相关的操作写的很详细也有实例

**Comment by KaloSora** [comment]
非常感谢您在百忙之中的回复！
我在github上提的issue主要问题点在于，我在动态加载完下拉框以后，使用$('selector').val()赋值不成功。
同样地，写死的下拉框，我通过$('selector').val()却能成功赋值，并且页面会自动选中value对应的text

实例：
下图框起来的地方是写死的下拉框，可以通过$('selector').val()赋值，并且赋值以后能够自动选中value对应的text
<img width="1163" alt="成功赋值1" src="https://user-images.githubusercontent.com/35422660/89603363-8fa97780-d89b-11ea-84f4-2dc5d48a34ca.png">
下面是赋值的js语句，赋值过后调用了form.render()
<img width="1112" alt="成功赋值2" src="https://user-images.githubusercontent.com/35422660/89603393-9b953980-d89b-11ea-8af2-84d20c4cc411.png">

下图是出问题的地方：
通过ajax加载完数据以后进行绑定，可以看到这里没有问题，option里面也没有checked选项
<img width="1046" alt="赋值失败1" src="https://user-images.githubusercontent.com/35422660/89603469-c8495100-d89b-11ea-8ba1-c574e6225896.png">

绑定数据的js代码，同样调用了form.render()，目前都是正常的
<img width="701" alt="赋值失败2" src="https://user-images.githubusercontent.com/35422660/89603518-e8791000-d89b-11ea-9556-578679e77ae5.png">

出问题的地方在于，在动态绑定下拉框以后，通过$('selector').val()赋值失败
<img width="904" alt="赋值失败3" src="https://user-images.githubusercontent.com/35422660/89603599-12cacd80-d89c-11ea-8103-64408ce54575.png">


赋值代码如下，我单步调试回传到前台是有值，但是重新取值却为空
<img width="626" alt="赋值失败4" src="https://user-images.githubusercontent.com/35422660/89603638-2413da00-d89c-11ea-96f1-1be01532b063.png">


再次感谢您的耐心回复🙏

**Comment by JPAdCoder** [comment]
根据你的描述我猜应该是ajax异步请求导致的，代码执行到给select赋值的时候可能请求并未执行完成。你可以试着将ajax的async设置为false或者在请求的succes方法中进行赋值试下

**Comment by KaloSora** [comment]
我尝试把下拉框赋值写到success的回调函数里，但是仍然没有起效果

以下是修改后的代码:
<img width="858" alt="赋值1" src="https://user-images.githubusercontent.com/35422660/89614183-7eba2f80-d8b6-11ea-9f77-0e1707af4edd.png">

以下是前端调试效果:
<img width="971" alt="赋值2" src="https://user-images.githubusercontent.com/35422660/89614203-8a0d5b00-d8b6-11ea-8166-8cc009d8e0db.png">

**Comment by indiboy** [comment]
建议你看一下文档的赋值部分，

> `//给表单赋值
form.val("formTest", { //formTest 即 class="layui-form" 所在元素属性 lay-filter="" 对应的值
  "username": "贤心" // "name": "value"
  ,"sex": "女"
  ,"auth": 3
  ,"check[write]": true
  ,"open": false
  ,"desc": "我爱layui"
});
 
//获取表单区域所有值
var data1 = form.val("formTest");`

**Comment by JPAdCoder** [comment]
> 我尝试把下拉框赋值写到success的回调函数里，但是仍然没有起效果
> 
> 以下是修改后的代码:
> <img alt="赋值1" width="858" src="https://user-images.githubusercontent.com/35422660/89614183-7eba2f80-d8b6-11ea-9f77-0e1707af4edd.png">
> 
> 以下是前端调试效果:
> <img alt="赋值2" width="971" src="https://user-images.githubusercontent.com/35422660/89614203-8a0d5b00-d8b6-11ea-8166-8cc009d8e0db.png">

我看你赋值之后好像没有调用form.render()楼上说的你也可以看下，我用的时候一直都是拼接html没太注意官方文档的赋值方法

**Comment by JVxie** [comment]
有人解决这个问题了吗，我也困扰了很久

**Comment by JVxie** [comment]
> 我尝试把下拉框赋值写到success的回调函数里，但是仍然没有起效果
> 
> 以下是修改后的代码:
> <img alt="赋值1" width="858" src="https://user-images.githubusercontent.com/35422660/89614183-7eba2f80-d8b6-11ea-9f77-0e1707af4edd.png">
> 
> 以下是前端调试效果:
> <img alt="赋值2" width="971" src="https://user-images.githubusercontent.com/35422660/89614203-8a0d5b00-d8b6-11ea-8166-8cc009d8e0db.png">

我解决这个问题了，是因为异步请求的原因，页面还没加载完就已经请求完了，所以使用jquery的时候无法获取到dom元素

**Comment by ning-ll** [comment]
抱歉，我还是没太理解，赋值具体需要放在哪一步，在页面完全加载完成后，在控制台手动执行form.val能够赋值成功，在请求完成后执行form.val就赋值不上

**Comment by ning-ll** [comment]
> > 我尝试把下拉框赋值写到success的回调函数里，但是仍然没有起效果
> > 以下是修改后的代码:
> > <img alt="赋值1" width="858" src="https://user-images.githubusercontent.com/35422660/89614183-7eba2f80-d8b6-11ea-9f77-0e1707af4edd.png">
> > 以下是前端调试效果:
> > <img alt="赋值2" width="971" src="https://user-images.githubusercontent.com/35422660/89614203-8a0d5b00-d8b6-11ea-8166-8cc009d8e0db.png">
> 
> 我解决这个问题了，是因为异步请求的原因，页面还没加载完就已经请求完了，所以使用jquery的时候无法获取到dom元素

抱歉，我还是没太理解，赋值具体需要放在哪一步，在页面完全加载完成后，在控制台手动执行form.val能够赋值成功，在请求完成后执行form.val就赋值不上

**Comment by ning-ll** [comment]
> > > 我尝试把下拉框赋值写到success的回调函数里，但是仍然没有起效果
> > > 以下是修改后的代码:
> > > <img alt="赋值1" width="858" src="https://user-images.githubusercontent.com/35422660/89614183-7eba2f80-d8b6-11ea-9f77-0e1707af4edd.png">
> > > 以下是前端调试效果:
> > > <img alt="赋值2" width="971" src="https://user-images.githubusercontent.com/35422660/89614203-8a0d5b00-d8b6-11ea-8166-8cc009d8e0db.png">
> > 
> > 
> > 我解决这个问题了，是因为异步请求的原因，页面还没加载完就已经请求完了，所以使用jquery的时候无法获取到dom元素
> 
> 抱歉，我还是没太理解，赋值具体需要放在哪一步，在页面完全加载完成后，在控制台手动执行form.val能够赋值成功，在请求完成后执行form.val就赋值不上

我找到问题了，我表单渲染后还有表格渲染，在表格渲染完成后执行赋值就可以了
