### ISSUE TITLE
请问能不能出一个vue版的layui

### ISSUE THREAD

**Issue by TerryLam2010** [layui/layui#738]
请问能不能出一个vue版的layui，现在vue用得更多了，layui的样式还挺好看。可以兼容下？

**Comment by TerryLam2010** [comment]
请问能不能出一个vue版的layui，现在vue用得更多了，layui的样式还挺好看。可以兼容下？

**Comment by JPAdCoder** [comment]
还不如直接Vue + Element UI Vue和layui应该算是两个方向吧

**Comment by LbhFront-end** [comment]
react版本的呢

**Comment by sentsim** [comment]
https://gitee.com/layui/layui-vue
