### ISSUE TITLE
能否支持多级嵌套

### ISSUE THREAD

**Issue by AceEzio** [layui/layui#755]
请问关于table.js模块，response能否支持多级嵌套，比如
response: {
    dataName: 'data.results' 
 }

**Comment by sentsim** [comment]
可以通过 parseData 函数对多级数据进行解析为 table 规范的数据格式
> 详见：
> https://layui.gitee.io/v2/docs/modules/table.html#parseData
> https://layui.gitee.io/v2/demo/table/parseData.html
