### ISSUE TITLE
#数据表表格#当工具多了被折叠，展开后的按钮无法监听事件

### ISSUE THREAD

**Issue by gewanbo** [layui/layui#757]
在使用数据表格的时候，添加了多个工具（即每行右侧末尾的工具按钮）如果宽度固定的话，显示出来的按钮会被自动折叠，需要点击每行后面的“...”才能展开所有工具按钮。但此时展开的工具按钮就无法触发所绑定的事件了。没有任何报错信息，看了下dom结构，是动态创建出来的工具层，可能是没有绑定事件。
这个功能还是很有必要的，因为有适合会添加多个按钮，但又不需要一直显示，显示太多会让数据表格可显示区域变得更小了。如果能折叠起来，还能正常触发绑定在工具按钮上的事件，就非常完美了。先点个赞👍

**Comment by sentsim** [comment]
> 我也遇到这个问题了 我的操作栏 按钮五六个，在小屏幕里后面的按钮都变成“...” 而且还无法点击

用 layui dropdown 下拉菜单组件来替代。没必要一行展示那么多按钮的。
https://layui.gitee.io/v2/demo/dropdown.html
