### ISSUE TITLE
English version of LayUI

### ISSUE THREAD

**Issue by SoufianAkh** [layui/layui#775]
Hello guys!

Recently I discovered this LayUI and I find it an amazing framework for which I can't find any alternative that's English.
Will you ever consider releasing an English version? I'm pretty sure there'll be a major user base wanting to use such framework.

I have personally translated a few JS files to English so I can use it in my international projects, but it would be much better if LayUI themselves decide to go international

**Comment by sentsim** [comment]
Sorry, I only saw your suggestion now. 
Due to limited personal energy and some deficiencies in the project, there is no English version.
