### ISSUE TITLE
父层触发子层元素事件

### ISSUE THREAD

**Issue by fy-kenny** [layui/layui#790]
由于找不到其他途径，所以来这里问一下前端大佬。

如题，可能我的功能实现有些古怪，大致功能是**编辑页编辑后，暂存在父层，当父层从jstree双击后，重新获取暂存的数据，再打开子编辑页后赋值（**给input赋值是正常的**），并选择好级联select和重新更新jstree中的节点数据并且根据数据重新显示树**。

我有一个表格，点击编辑按钮layer.open编辑页，再在编辑页双击jstree后layer.open一个子编辑页（当然是其他对象的编辑页）。
此时，我想通过 **父层弹出子层后触发事件**

-  级联选择select控件，第二个select是根据第一个select值动态获取
-   更新树（jstree）组件数据和控制树组件刷新。

我看了文档有个**success的回调函数**，使用了后始终不能触发select控件的change事件（子层自己是可以触发的）
$('.select').change() 子编辑页自己是可以这样触发的。
树组件无法通过 $('#tree').jstree(true)获取，因为我是更新，所以使用了.jstree(true)

**这里是我获取子编辑页的代码**
let openDialog = layero.find('iframe').contents();

openDialog.find('.select-broker').val(brokerId);
openDialog.find('.select-broker').change();

openDialog.find('#treeJson').val(data.json);
openDialog.find('#treeJson').jstree(true).settings.core.data = data.json;
openDialog.find('#treeJson').jstree(true).refresh();

**Comment by xxg01039** [comment]
有两个问题，change触发应该用layui自带的表单监听事件，还有就是jstree用的jQuery会跟layui内部jQuery冲突

**Comment by fy-kenny** [comment]
问题还没解决
你说的冲突我也不懂怎么解决，监听确实在layui的表单里的，打开表单有一次设置级联触发change，但是在父层success主动设置新的broder代理，然后触发change获取子代理，然后根据新的id选择当前子代理，这个地方change无效，很奇怪。

我发现layui.open后，触发子层自己的change事件，但是立马就回调success，这个时候success主动触发change无效。
子厚又回到子层的change事件继续往下走。

**Comment by xxg01039** [comment]
（1）、你的select是自己写的change事件吗，如果是请不要这样写，应该使用layui自带的监听事件
form.on('select(filter)', function(data){
  console.log(data.elem); //得到select原始DOM对象
  console.log(data.value); //得到被选中的值
  console.log(data.othis); //得到美化后的DOM对象
}); 
filter 与 select原始dom的lay-filter设置的值保持一致
（2）、至于jQuery冲突我想到两种解决方案，一种是layui采用模块加载，并且不要加载【jQuery】组件，页面使用外部jQuery。
第二种是用jQuery.noConflict()方法让出外部jQuery的$占用，jstree相关代码使用新的全局变量替换$。第一种方案我在曾经做过的项目里试过了，可以。第二种没试过，理论可行，靠你自己了。
以上纯属个人的浅薄见解，希望能够帮助到你~

**Comment by xxg01039** [comment]
仔细读了你前面的问题，发现看错了你关于change触发的描述，误以为你说的是监听，请忽略我上面说的第一点内容。
至于你说的主动触发change无效，由于你的描述有点绕，没有太理解你的意思。

**Comment by fy-kenny** [comment]
> 仔细读了你前面的问题，发现看错了你关于change触发的描述，误以为你说的是监听，请忽略我上面说的第一点内容。
> 至于你说的主动触发change无效，由于你的描述有点绕，没有太理解你的意思。

好的，我简单描述一下我要做到功能，我有个编辑页里面有级联选择，代理->子代理还有其他一些普通属性。
在编辑后保存在data中，重新打开后，获取data的值，重新设置值并且级联选择，第一个代理能设置，第二个子代理是在第一个代理设置后触发select change事件，从后台获取级联子代理，然后根据data中新的值重新设置

弹出页是可以监听到change事件，功能正常，

但是在弹出页回调success中触发change事件，弹出页不能监听到change事件，因而不能设置成功子代理

openDialog.find('.select-broker').change(); 没有异常的
控件也是获取到了

**Comment by fy-kenny** [comment]
功能很简单，就是父层弹出子层，在弹出后回调success，然后操作子层级联选择 @xxg01039

**Comment by fy-kenny** [comment]
@xxg01039 会不会由于父层在一个iframe中，子层在另一个iframe中，导致事件不能触发
还是let openDialog = layero.find('iframe').contents(); 我这样得到的时候不能触发子层事件

**Comment by xxg01039** [comment]
你的弹出层type是什么类型

**Comment by fy-kenny** [comment]
> 你的弹出层type是什么类型

就是用了layer.open  type = 2

**Comment by xxg01039** [comment]
建议子层选用页面层试试。

**Comment by fy-kenny** [comment]
改成页面层，就把我的url显示出来，我这个url是先从后台获取，暂后根据前端暂时存储的数据更新的
