### ISSUE TITLE
表格部分的：cols - 表头参数缺少自定义id的功能

### ISSUE THREAD

**Issue by emcchui** [layui/layui#792]
表格部分的：cols - 表头参数缺少自定义id的功能

比如：

td id="自定义id：比如  data.id+"_td"">第一行 ID001 nanan  nnn</td
td id="自定义id：比如  data.id+"_td"">第二行 ID002 mmM   mm</td

`</br>`
td id="001_td"">第一行 ID001 nanan  nnn</td
td id="003_td">第二行 ID002 mmM   mm</td

**Comment by sentsim** [comment]
`field` 属性的功能类似于您所说的 id
