### ISSUE TITLE
table渲染后端的数据，如何处理特殊字符如："<"">"这样的字符

### ISSUE THREAD

**Issue by zhaoxinhu** [layui/layui#794]

**Comment by ferrinweb** [comment]
`&lt; // <` `&gt; // >` 是这个意思吗？

**Comment by zithua** [comment]
这个问题解决了么？ 我也遇到这个问题了 ，后端 返回的数据 带有/test/<id> ,在前端表单 没有显示出来，

**Comment by zithua** [comment]
好吧   ,竟然git 上，也有这样的问题 ，这个 '<>' 没显示出来  ，谁来试下？

**Comment by reber0** [comment]
table.js 第 848 行改为 return parseTempData(item3, util.escape(content), tplData);

**Comment by sentsim** [comment]
这个在后面的版本已经优化了
