### ISSUE TITLE
Layui table toolbar 工具条是否可以分开多次绑定事件？

### ISSUE THREAD

**Issue by eviltomato** [layui/layui#806]
toolbar 工具条是否可以分开多次绑定事件？
比如我在文件A中绑定Add事件到toolbar工具条，然后再文件B中绑定Delete事件到toolbar. 通过测试会存在覆盖的情况，是否有比较好的解决方案？谢谢。

**Comment by sentsim** [comment]
最早的版本，组件的事件是支持多次绑定的，但由于很多人的代码组织部规范，而导致 form.on 被重复执行，进而导致事件重复，所以才改成了以 filter 为识别的唯一事件绑定，所以这块功能为了向下兼容，只能如此「将错就错」。当然，若未来推出大版本，事件这一块也会考虑重新设计

**Comment by miaoweibiao** [comment]
其实是否可以考虑做成一个table可以绑定多个filter？
