### ISSUE TITLE
使用form.on监听表单提交，正常提交一次后按空格或是回车键会重复触发监听事件，导致数据重复提交

### ISSUE THREAD

**Issue by TioaChan** [layui/layui#812]
监听表单提交的代码如下：

![输入图片说明](https://raw.githubusercontent.com/TioaTyan/attachment/master/2021/01/13/code.png)

![输入图片说明](https://raw.githubusercontent.com/TioaTyan/attachment/master/2021/01/13/console.png)

layui在线演示里就有这个问题，[在线演示](http://https://www.layui.com/demo/form.html)

![输入图片说明](https://raw.githubusercontent.com/TioaTyan/attachment/master/2021/01/13/QQ%E5%BD%95%E5%B1%8F20210113220946.gif)

**Comment by TioaTyan** [comment]
目前发现在提交监听里面加入`$(":focus").blur();`可避免这种问题

```
form.on("submit(demo1)", function (data) {
    $(":focus").blur();
    layer.alert(JSON.stringify(data.field), {
        title: "最终的提交信息",
    });
    return false;
});
```
