### ISSUE TITLE
transfer搜索框输入一个汉字时无法匹配到内容bug

### ISSUE THREAD

**Issue by 80905949** [layui/layui#824]
首次输入一个汉字时无法匹配，输入两个汉字删除一个汉字，就可以匹配内容
![layui](https://user-images.githubusercontent.com/29423495/106977672-baff1780-6795-11eb-9661-e8afc8c754a2.gif)

**Comment by ss7424Refar** [comment]
搜索框好像不支持小写查询，
有啥解决办法吗？

**Comment by sentsim** [comment]
> 

2.7 版本已经支持不区分大小写搜索了
