### ISSUE TITLE
表格在加载大数据量时候加载很慢，而且加载后页面很卡

### ISSUE THREAD

**Issue by lizhizhang** [layui/layui#825]
表格在加载大数据量时候加载很慢，而且加载后页面很卡，数据量大概1000行，列数大概20列左右

**Comment by sentsim** [comment]
若给出的列数过多，的确会大幅影响 table 的性能，建议改成：转换静态表格的方式处理。
或者直接用静态表格配合 laypage 组件来单独实现。

详见：

- https://layui.gitee.io/v2/demo/table/static.html
- https://layui.gitee.io/v2/demo/table-element.html
- https://layui.gitee.io/v2/demo/laypage.html
