### ISSUE TITLE
表格重载不合理，可否改进

### ISSUE THREAD

**Issue by ox188** [layui/layui#837]
所谓重载，就是结构不变，只有数据发生变化，而数据变化一般是由其他方法或函数致使的，比如执行了删除操作或修改某个字段值后，运行table.reload（id），重新请求表格初始渲染的接口，将的到的变化了的数据渲染到原表格结构中。

如搜索操作，应该在表格渲染时制定一个json数据集data，重载时只赋予新的数据集data，比如table.reload（id，data），这样，可能需要对表格的渲染做一定的修改，将数据集data作为独立参数。

但目前重载操作，按文档对table.reload(ID, options)中的options的说明，options的参数和table.render中表格渲染一样，这样不是很科学，也不容易操作。能否去掉options参数，执行重载后，按照渲染表格时的设定或参数重新请求一次数据接口。至于表格的结构，因为是重载，所以这些参数都已经存在，读取就行。

想的不是很清楚，但总感觉表格重载不好用！

**Comment by sentsim** [comment]
2.7 已经新增了一个 `table.reloadData()` 方法，用于仅重载数据，options 中与数据无关的属性不会参与到重载中。
> 详见文档：https://layui.gitee.io/v2/docs/modules/table.html#reload
