### ISSUE TITLE
table组件有一个巨大的bug,

### ISSUE THREAD

**Issue by easy999000** [layui/layui#840]
table组件有一个巨大的bug,一个参数,是一个数组.我第一次查询的时候,传值了,发送到服务端之后,也有值,正确的. 第二次,这个数组参数,明明没有值,但是传递到服务端的时候,既然还有这个参数, 导致数据错误.
![image](https://user-images.githubusercontent.com/45551150/110877387-4aa76100-8314-11eb-81ed-b40262643633.png)

![image](https://user-images.githubusercontent.com/45551150/110877169-f1d7c880-8313-11eb-923c-e848b1a82592.png)
![image](https://user-images.githubusercontent.com/45551150/110877481-73c7f180-8314-11eb-9567-7a64f6962c2f.png)
![image](https://user-images.githubusercontent.com/45551150/110877667-b7226000-8314-11eb-8ceb-9ff1baddb574.png)

**Comment by easy999000** [comment]
经过测试还发现,如果参数是数组,第一次提交的时候,数组有3个参数,第二次只有一个参数的时候.最终提交结果,还是有3个参数,fuck

**Comment by sentsin** [comment]
layui 2.6 优化了这个问题
