### ISSUE TITLE
关于 table.js 中 reload 的疑问

### ISSUE THREAD

**Issue by charexcalibur** [layui/layui#841]
版本：2.5.5
path：lay/modules/table.js

```js
  Class.prototype.reload = function(options){
    var that = this;
    
    options = options || {};
    delete that.haveInit;
    
    if(options.data && options.data.constructor === Array) delete that.config.data;
    that.config = $.extend(true, {}, that.config, options);
  
    that.render();
  };
```

经测试，当传入 table 的数据为 **直接赋值数据** 时，reload table 会出现 无限 loading 的 bug。根据数据流定位到 reload 中的 if 判断。delete 后的 that.config 中不存在 data 属性了。打印 extend 后的 that.config 中确实不含 data。此时 reload 就会出现无限 loading 的 bug。

目前的解决方案，手动在触发 reload 时传入 data, 同时注释掉 table.js 中 650 行，对于 that.config.data 的 delete

```js
myTable.data = yourData
table.reload(myTable.id, myTable);
```

**Comment by sentsim** [comment]
url 属性和 data 属性只能二选一，因此如果您使用了 data 属性，那么原来的 url 属性就要置空
```
data: [],
url: null
```
