### ISSUE TITLE
希望Layer启用自动关闭的功能时，提供计时回调

### ISSUE THREAD

**Issue by firstrose** [layui/layui#845]
如题

这样可以制作倒计时显示

**Comment by eclix-del** [comment]
为什么不用定时器呢

**Comment by firstrose** [comment]
> 
> 
> 为什么不用定时器呢

1. layer有time选项，为什么不用？
2. 用了time选项，却又自己写定时器，无法保证两者的同步。

**Comment by sentsim** [comment]
layer 主页有一个及时关闭的例子：https://layui.gitee.io/v2/layer/
实现起来倒也没多少代码。
![image](https://user-images.githubusercontent.com/3277200/182027314-e697dfef-23fb-47c8-8bed-e217af5157a0.png)
