### ISSUE TITLE
2.6.0 无需再通过 layui.use 来加载内置模块，无法直接使用

### ISSUE THREAD

**Issue by 35598253** [layui/layui#847]
直接下载的master，使用src中的文件；
<script src="../layui/layui.js"></script>
<script>
//从 layui 2.6.0 开始，由于内置模块会一次性加载，因此不必再执行 layui.use() 来加载对应模块，直接使用即可：
;!function(){
  var layer = layui.layer
  ,form = layui.form;
  
  layer.msg('Hello World');
}();
</script> 
提示： Cannot read property 'msg' of undefined；
console.log(layui.layer)
提示：undefined;
问题出在哪？

**Comment by sentsin** [comment]
如果是引入的 src 目录的，仍然需要 layui.use 来加载。文档说的主要引入是构建后的目录

**Comment by 35598253** [comment]
哦，这样啊！
后期会支持SRC目录直接引用么？项目还没上线，对layui好多组件进行了定制，无法及时实施构建！
