### ISSUE TITLE
[bug]在IE8下，多选下拉框必须至少选中一个值否则form.render(type, filter)方法报错无法渲染表单

### ISSUE THREAD

**Issue by SakuOtonashi** [layui/layui#854]
下拉框没有值时selectElem.selectedIndex是-1，IE8下selectElem.options[-1]取到的不是undefined，而是抛出异常

**Comment by JxiaoC** [comment]
现在还管IE8...敬职敬业值得学习...

**Comment by SakuOtonashi** [comment]
> 现在还管IE8...敬职敬业值得学习...

没办法呀，之前给公司维护的项目都只要Chrome正常就好了，现在要维护一个给政府部门用的项目，难顶
现在解决办法是，改源码重新编译了一份那个页面爆出bug就替换掉引用的库，重新理一下这个页面的代码

**Comment by zz925625** [comment]
解决了吗。怎么搞的呢。。。。。
