### ISSUE TITLE
当form表单中有select时，使用form.val()会将已选的select 重渲

### ISSUE THREAD

**Issue by DavidWong2019** [layui/layui#856]

**Comment by DavidWong2019** [comment]
`
  //赋值/取值
  Form.prototype.val = function(filter, object){
    var that = this
    ,formElem = $(ELEM + '[lay-filter="' + filter +'"]');
    
    //遍历
    formElem.each(function(index, item){
      var itemForm = $(this);
      
      //赋值
      layui.each(object, function(key, value){
        var itemElem = itemForm.find('[name="'+ key +'"]')
        ,type;
        
        //如果对应的表单不存在，则不执行
        if(!itemElem[0]) return;
        type = itemElem[0].type;
        
        //如果为复选框
        if(type === 'checkbox'){
          itemElem[0].checked = value;
        } else if(type === 'radio') { //如果为单选框
          itemElem.each(function(){
            if(this.value == value ){
              this.checked = true
            }     
          });
        } else { //其它类型的表单
          itemElem.val(value);
        }
      });
    });
    
  // 应该是这行代码导致的
    form.render(null, filter);
    
    //返回值
    return that.getValue(filter);
`

**Comment by sentsim** [comment]
赋值后是会有一个重新渲染的过程，因为赋值是直接面向原始表单的，渲染的目的是为了让替换元素与原始原素的值同步。
