### ISSUE TITLE
使用第三方基于jquery的库方法，如何使用layui中的jquery

### ISSUE THREAD

**Issue by zhangaoqi** [layui/layui#862]
比如想使用waitMe.js，我在layui.use中使用var $=layui.$;然后$.getScript();引入waitMe.js,但是使用时会提示$(...).waitMe is not a function.

**Comment by sentsin** [comment]
因为 第三方库是绑定在你外部引入的 jQuery 之上。这种情况你可以使用 jQuery().waitMe 的方式调用

**Comment by zhangaoqi** [comment]
> 因为 第三方库是绑定在你外部引入的 jQuery 之上。这种情况你可以使用 jQuery().waitMe 的方式调用

意思是这种情况就必须在外面单独再引入jQuery吗？我想的理想状况是能不能就用layui的，不再单独引入jQuery了

**Comment by cdoer** [comment]
你把第三方库  封装成layui模块   依赖腊layui 的Jquery就行了   第一句 window.$=window.JQuery=layui.jquery;第二句代码 通过Jquery的getScript加载第三方库就行

**Comment by cdoer** [comment]
> 
> 
> 比如想使用waitMe.js，我在layui.use中使用var $=layui.$;然后$.getScript();引入waitMe.js,但是使用时会提示$(...).waitMe is not a function.

你这样引用的是局部变量,对第三方组件没用的  要赋值给window.$ = layui.$;

**Comment by zhangaoqi** [comment]
> 你把第三方库 封装成layui模块 依赖腊layui 的Jquery就行了 第一句 window.$=window.JQuery=layui.jquery;第二句代码 通过Jquery的getScript加载第三方库就行

有用，Thx~
