### ISSUE TITLE
多表单校验

### ISSUE THREAD

**Issue by TomClancy258** [layui/layui#863]
一个页面有form1和form2两个表单，他俩都有startIP这个输入框字段，请问多表单验证这样写不对呢，是必须把校验规则写在同一个layui.form里面吗，也就是只能有一个verify吗？
layui.use(['layer', 'form', 'element'], function () {
        let layer = layui.layer,
            element = layui.element,
            $ = layui.jquery,
            form1= layui.form,
            form2= layui.form;

       function startIP(val, item, name) {
            let endIP = $('#form-' + name + ' input[name="endIP"]').val()
            console.log('endIP', endIP)
            if (val === '' && endIP === '') {
                return
            } else if (val !== '' && endIP !== '') {
                if (!checkIP(val)) {
                    return '起始IP格式错误'
                } else if (!compareIP(val, endIP)) {
                    return '结束IP必须大于开始IP'
                }
            } else {
                return '起始IP和结束IP必须同时存在或同时不存在'
            }
        }

        form1.verify({
            startIP: function (val, item) {
                return startIP(val, item, 'zoomeye')
            },
            chunk: function (val, item) {
                if (val === '') {
                    return '请输入分块页数'
                } else {
                    return
                }
            }
        });
        form2.verify({
            startIP: function (val, item) {
                return startIP(val, item, 'shodan')
            }
        });

        form1.on('submit(form1)', function (data) {...})
        form2.on('submit(form2)', function (data) {...})

**Comment by sentsim** [comment]
参考 Gitee issue 的讨论：https://gitee.com/layui/layui/issues/I5HC2L#note_11673264_link
或者直接参考实现的示例：https://codepen.io/sentsim/pen/xxWRexb

**Comment by yiuked505** [comment]
多表单验证确实有问题，form1会去检测form2的项
