### ISSUE TITLE
日期时间选择器, 结束时间BUG

### ISSUE THREAD

**Issue by juneszh** [layui/layui#869]
2.6.6默认展开时, 结束时间为23:59:59, 这个改动非常好!
![image](https://user-images.githubusercontent.com/2436252/117655303-78503f80-b1c9-11eb-8597-f052aded57ef.png)

但是点一下其他日期, 又变回了0:0:0
![image](https://user-images.githubusercontent.com/2436252/117655537-c6fdd980-b1c9-11eb-8574-160eb7b39d7a.png)

**Comment by sentsin** [comment]
切换的时候确实有所疏忽，下次再继续改一下，刚好还有几个小问题同步优化

**Comment by sentsim** [comment]
v2.6.6 已经修复这个问题了，issue 忘了关
