### ISSUE TITLE
关于数据表单totalRow的默认小数点位数, 建议保留与原始结果

### ISSUE THREAD

**Issue by juneszh** [layui/layui#870]
由于在v2.6.3/4在totalRow引入了动态模板支持: {{ d.TOTAL_NUMS }}, 这非常好, 增加了不少灵活性.

这里建议d.TOTAL_NUMS保留原合计结果的小数点位数, 而不是强制保留2位, 否则就算用parseFloat(d.TOTAL_NUMS).tofix(4)也只会获得x.xx00的结果.

因为像一些广告业务或币圈业务, 核算的小数点位数都是4位或以上.

**Comment by juneszh** [comment]
补充: 
以上建议是在totalRow值为string的情况上. totalRow为true时仍可保留2位小数的处理, 这可减少兼容性问题.

**Comment by sentsim** [comment]
后面的版本已经优化这一块了，小数点可以在合计模板中自由控制
