### ISSUE TITLE
建议官方对layUI的Table数据表格的 “单元格筛选” 功能强化

### ISSUE THREAD

**Issue by xujinliang** [layui/layui#872]
![QQ截图20210515170151](https://user-images.githubusercontent.com/18339005/118354940-12d0ca00-b5a0-11eb-8be2-64ecdf2f5f93.png)
 如截图所示，目前没有单元格筛选的功能，cols的参数title里面可以写html源码，
比如上面加个过滤的小图片，但是点击的时候连带点击了title，又要考虑阻止事件冒泡。
虽然能凑活用，还是建议官方考虑单元格筛选功能，
市场比较有需求的。

**Comment by xujinliang** [comment]
再直观一点就是类似于微软的Excel的单元格筛选功能
![QQ截图20210515171844](https://user-images.githubusercontent.com/18339005/118355266-a35bda00-b5a1-11eb-8e56-6ef5f1916ab2.png)

**Comment by waloyn** [comment]
同样非常希望官方能有自己的筛选功能。我现在用的是第三方插件SoulTable，地址：https://github.com/yelog/layui-soul-table
  ##其实我只需要筛选数据右侧的筛选框，不需要菜单，现在只能把菜单挂着。
![QQ图片20210517162221](https://user-images.githubusercontent.com/20416585/118457682-97505380-b72c-11eb-8464-6be3f967fd95.png)

**Comment by sentsim** [comment]
这个功能确实暂时还没有，主要是基于 2.x 的 table 加上这块会牵涉到太多改动。
只能寄希望于未来的某个大版本对 table 组件重构啦。
