### ISSUE TITLE
upload组件BUG: 拖拽上传时index为0

### ISSUE THREAD

**Issue by juneszh** [layui/layui#880]
当按钮选择上传时, 事件传入的index是正常的:
choose(obj.preview): 1622017963259-0
progress: 1622017963259-0
done: 1622017963259-0

当拖拽上传时, index除了choose都为0:
choose(obj.preview): 1622017925757-0
progress: 0
done: 0
error: 0

**Comment by sentsim** [comment]
该问题已经在 v2.7.x 修复了
