### ISSUE TITLE
穿梭框组件开启右侧搜索后获取到的数据问题

### ISSUE THREAD

**Issue by 645934707** [layui/layui#884]
穿梭框组件，开启搜索后，如果右侧搜索了，提交时的 transfer.getData('demo1') 方法获取到的数据只有搜索出来的数据， 是否能够添加一个参数，可以获取原 右侧的数据？（即隐藏掉的数据也获取到）

**Comment by 645934707** [comment]
临时解决办法： 在提交数据之前 使用 transfer.reload('transfer_id'); 重新加载一下穿梭框

**Comment by MengLei1102** [comment]
重置便不能解决“筛选便移动数据”这种情况
