### ISSUE TITLE
table.render和table.reload时页面闪烁

### ISSUE THREAD

**Issue by zhangaoqi** [layui/layui#885]
现在table.render和reload的时候页面都会闪烁一下，特别是页面色调是深色的，每次重载加载数据或者点搜索的时候都要闪烁一下白色，特别丑陋，请问有更优雅的解决方案吗？

**Comment by sentsim** [comment]
2.7 已经新增了一个 `table.reloadData()` 方法，用于仅重载数据，该方法不存在页面闪烁了。
> 详见文档：https://layui.gitee.io/v2/docs/modules/table.html#reload
