### ISSUE TITLE
单独使用layer没有问题，但是引入layui后报错layer.use is not a function

### ISSUE THREAD

**Issue by 1963926178** [layui/layui#902]
![image](https://user-images.githubusercontent.com/73919903/127836747-3be18d18-bed9-4830-bb2a-a36fab9c8b34.png)

**Comment by nanziok** [comment]
layui.use('layer',function(){})

**Comment by zhangjiuliang** [comment]
兄弟你用的应该是npm安装的layui-vue或其他版本，不是js引入的layui，使用方法有差异，看这个网站就好[layui-vue官网](http://www.layui-vue.com/zh-CN/components/progress)
