### ISSUE TITLE
子模态框给父模态框传值问题

### ISSUE THREAD

**Issue by guozesen832** [layui/layui#910]
在做图片上传的过程中遇到一个问题一直没解决,就在父模态框中用lay.open打开一个子模态框进行图片上传,上传后,后台返回图片的地址到子模态框,再把这地址返回父模态框
一开始我是想直接用$(window.parent.document).find("#ava")获取父页面的元素进行赋值但是传回的值一直为undefine,网上找了多种父页面给子页面传值的方法都没有用.
然后我用第二种方式,在子页面定义一个回调函数callbackdata然后在父页面进行回调,但是callbackdata执行顺序一直在表单提交submitHandler之前导致在获取到图片路径前就会先调一次calbackdata获取到undefined,
有没有大佬给个思路,或者解决办法,卡这里卡很久了

**Comment by bw2015** [comment]
参考 layadmin 中 view.js 的解决方案

**Comment by nanziok** [comment]
例如在父页面写一个function selectUser，子页面使用
parent.layer.close(parent.layer.getFrameIndex(window.name));
window.parent.selectUser(rows);
