### ISSUE TITLE
关于layui表格的一些建议

### ISSUE THREAD

**Issue by 710978670** [layui/layui#96]
贤心您好,
最近接触到layui,觉得使用起来很不错,但是对表格,我有些建议，希望能采纳
1、表格分页栏可以扩展一个工具栏，可以实现一些功能，比如下载列表中的报表文档（csv/excel）等等信息
2、对于一些数值型、时间、map或map转的json类型,的列,可以再cols中配置数值、时间的格式化的类型，列表输出的值可以直接格式化，对于参数类型的，可以通过在cols中配置map或者json对象,然后通过列数据的key,在map中取出value；当然这些都可以通过templet来实现，但是希望插件中可以封装类似的功能
3、希望支持内存分页，查询，排序
4、在你的数据表格Demo中>监听单元格事件>点击签名列,弹出修改对话框,关闭对话框以后,该行被选中的灰色背景并没有被移除,而是一直在那个地方.
5.希望支持单双行背景颜色，鼠标悬浮背景颜色，多行选中背景颜色进行区分

因为就目前我使用过也不多，有可能有些功能已经存在。希望layui越来越好.

**Comment by sentsin** [comment]
非常感谢热心建议，table 会逐步完善。而由于目前个人精力有限，无法顾及太多渠道得 Issues，所以还是希望把上述建议发布到社区：http://fly.layui.com/，社区有收藏功能，我通常在升级版本时，会结合实际情况逐个采纳的
