### ISSUE TITLE
还真是返璞归真啊，文档都没了

### ISSUE THREAD

**Issue by huangdijia** [layui/layui#965]
https://github.com/sentsin/layui/blob/6a610cbe7820e6ccd0ef6d25f64d25b12996b0f1/README.md#L29

**Comment by iprotn** [comment]
### 贤心Gitee文档说明：[关于 layui 在线文档](https://gitee.com/sentsin/layui/wikis/%E5%85%B3%E4%BA%8E%20layui%20%E5%9C%A8%E7%BA%BF%E6%96%87%E6%A1%A3)
###  在线文档：[https://layui.itze.cn/](https://layui.itze.cn/)
###  弹出层独立组件（layer）在线文档：[https://layer.itze.cn/](https://layer.itze.cn/)
### 内含layui在线文档目前版本内容，包括独立组件弹出层（layer）
### 声明
 **已经按照@sentsin 大佬的要求，剔除文档无关内容，以上两个地址仅为layui在线文档保留使用，和layui团队无任何关系，也并非官网！** 

 **以后就当自己使用方便吧，大家也可以来使用，主站也加入了十年之约，最起码近几年能保证不会消失，放心收藏，layui加油！**

**Comment by iprotn** [comment]
> > 打死你！文档在这https://layui.itze.cn/
> 
> 哈哈，只认官方的，能及时更新的那种。

官方的暂时没了，先用着吧，内容和官方关闭之前一致

**Comment by huangdijia** [comment]
作者是不是搞vue去了
