### ISSUE TITLE
laydate一些问题

### ISSUE THREAD

**Issue by csnb-job** [layui/layui#969]
laydate中type为month的时候，
1.点击月份不能直接选择。
2.有bug，选择完之后，再次点击出现一个小弹出层，不知道什么问题查找了半天。
3.提前定义好laydate的位置例如top,left，选择为imporant，但是有时候还是会出现错误定位

**Comment by sentsim** [comment]
你可能用的还是很老的版本，第 1、2 点问题新版本应该都不存在。
至于第 3 点，估计您是 css 强制控制了位置，这个不建议这样做，laydate 会自动计算应该弹出的位置。
