### ISSUE TITLE
Layui最新完整版镜像 建议大家收藏 www.layui.site

### ISSUE THREAD

**Issue by judy92828** [layui/layui#981]
## Layer文档：[https://www.layui.site/doc/modules/layer.html](https://www.layui.site/doc/modules/layer.html)

**Comment by instanceofs** [comment]
已收藏

**Comment by myproductshow** [comment]
https://www.layui.site/extend/index.html第三方组件这个网址的内容目前样式是错乱的

**Comment by linlucasbee** [comment]
感谢

**Comment by Heavy-Falcon** [comment]
大爱！
