### ISSUE TITLE
可否把扩展组件的实例站源码开放下

### ISSUE THREAD

**Issue by CHminggao** [layui/layui#988]
有些扩展组件没有在码云或者github上，之前的项目用了几个扩展组件，文档也没有示例代码也没有，看源码很痛苦……
https://www.layui.site/extend/treeTable/index.html#doc

**Comment by sentsim** [comment]
您访问的这个站是第三方的镜像站点，Layui 最新官方文档站是这个：https://layui.gitee.io/v2
