### ISSUE TITLE
喜欢layui又不想用jqury的同学，终于可以在vue里面愉快的使用layui了

### ISSUE THREAD

**Issue by starao520** [layui/layui#999]
[ems-admin-layui](https://github.com/ems-admin)是我开源的一套前后端完全分离的后台管理系统，后台使用SpringBoot2.5、Mybatis-plus3.4、Mysql8，前端使用的Vue3.0和Layui2.6.8,后期会根据官方进度进行升级，有需要的同学可以去看看

**Comment by qq02463** [comment]
太好了，菜鸡用vue的框架看得头疼
